- meta/src/html.rs
This is a simple fix to make the behavior of SSR the same as Hydrate. I think it's expected to be able to mismatch in different places attributes of Html.
> Fixes #1828, making SSR behavior match the Hydrate behavior.

- leptos_reactive/src/signal_wrappers_read.rs
- leptos_reactive/src/stored_value.rs
Small addition that allows for manual disposing of `StoredValue` and `Signal` types
> Allow disposing of Signal & StoredValue

- integrations/axum/src/lib.rs
Async mode doesn't use generate_response() but should still return a Content-Type header
> Make Async Mode return Content-Type header in Response

- leptos_reactive/src/lib.rs
- leptos_reactive/src/macros.rs
This adds support for using both signals and stored values in the `with!` and `update!` macros, without needing to use `with_value!` and `update_value!`.
(also modified the doctests a bit to match the doctests used on signals)
I'm not that great with traits, so feel free to change up the implementation if you see a better way :)
> feat: support stored values in `with!` and `update!`

- .github/workflows/get-changed-examples-matrix.yml
- .github/workflows/get-example-changed.yml
- .github/workflows/get-examples-matrix.yml
- .github/workflows/get-leptos-changed.yml
- .github/workflows/publish-book.yml
This warning 
```
The following actions uses node12 which is deprecated and will be forced to run
on node16: actions-rs/toolchain@v1. For more info:
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
In other places @3 was being used, so for consitency I have bumped everything up to @4
```
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
```
> Removed warning in build artefacts.

- examples/login_with_token_csr_only/client/src/lib.rs
Update to use `_untracked` for log::debug to resolve client side console error for `examples/login_with_token_csr_only`
> fix: update log debug to use get_untracked for logged in user to resolve client side console error

- leptos_macro/src/component.rs
> fix: `clippy` "needless lifetimes" warning (closes #1825)

- docs/book/src/view/02_dynamic_attributes.md
It took me some time to understand what running twice means for derived signals, I think this clarification can help.
If you don't think it's necessary, that's ok, I was able to figure it out while reading anyways haha.
A lot of lines are modified so that they keep around the same width, but I only added the parenthesis.
> docs: clarify what "once per signal change" means

- leptos_dom/src/html.rs
- leptos_reactive/src/trigger.rs
So I've been using `leptos` for a while, and I stumbled upon one tiny mistake while going through the documentation.
The documentation for [`Trigger::try_notify`](https://github.com/leptos-rs/leptos/blob/e0d15c1a094f193a85cd9304bf86edabbf46a902/leptos_reactive/src/trigger.rs#L32C9-L32C57) and [`Trigger::try_track`](https://github.com/leptos-rs/leptos/blob/e0d15c1a094f193a85cd9304bf86edabbf46a902/leptos_reactive/src/trigger.rs#L50C67-L51C49) states that they **return `None`** if the runtime has been disposed:
> (...) Returns `None` if the runtime has been disposed.
...when, in fact, they **return `false`** in such a case.
To rectify this, changing `None` to `false` could be sufficient, but I thought it might make sense to use the same wording as in …
> fix: documentation in `leptos_reactive::Trigger`

- integrations/actix/src/lib.rs
- integrations/axum/Cargo.toml
- integrations/axum/src/lib.rs
The `extract` functions in the Actix and Axum integrations took me a while to figure out, and the API is okay but not great. There's actually a much simpler way to do the same thing. This PR adds an `extractor` function, which is generic over some extractable `T` type and returns it. This supports tuples, etc. as well.
```rust
#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct Search {
q: String,
}
// Actix
#[server]
pub async fn query_extract() -> Result<Search, ServerFnError> {
use actix_web::web::Query;
use leptos_actix::extractor;
let Query(query) = extractor().await?;
Ok(query)
}
// Axum
#[server]
pub async fn data() -> Result<Search, ServerFnError> {
use axum::extract::Query;
use leptos_axum::extractor;
let Query(query) = extractor().await?;
Ok(query)
}
> feat: add `extractor` functions with better API than `extract`

- docs/book/src/view/09_component_children.md
In 3.9, the [Manipulating children](https://leptos-rs.github.io/leptos/view/09_component_children.html#manipulating-children) section, the `WrapsChildren` example component was missing the argument name. This PR adds the name.
> fix: Add missing argument name to WrapsChildren component in section 3.9 of the book

- docs/book/src/view/08_parent_child.md
In the [Providing a Context](https://leptos-rs.github.io/leptos/view/08_parent_child.html#4-providing-a-context) section 3.8, the example uses shorthand for passing props to child components, however the function signature for the components takes a different prop name. 
This PR resolves that so that it uses the correct names.
> fix: Prop-drilling example in Parent-Child Communication section of the book

- leptos_dom/src/ssr.rs
In some contexts the generated comments leads to invalid HTML/XML.
This quick fix uses `unknown` as placeholder to avoid the problem.
probably there are cleaner solutions, but it would be a first step.
> Fix: use placeholder in comments for empty component names

- leptos_reactive/src/signal.rs
- leptos_reactive/src/stored_value.rs
Implement Default trait for `RwSignal` and `StoredValue` so that optional properties can be implemented, such as:
```rust
#[component]
fn My(#[prop(optional)] value: RwSignal<f32>) -> impl IntoView {
...
}
fn main() {
view! {
<My />
}
}
```
> feat: Implement Default trait for RwSignal and StoredValue

- docs/book/src/deployment.md
- cargo-leptos@0.2.0 changes the file structure under the target folder from `/app/target/server/release/` to `/app/target/release/`. https://github.com/leptos-rs/cargo-leptos/pull/159
- `cargo leptos new` now creates the project with the name `leptos-start` instead of `leptos_start`. So, we need to change the binary filename too.
> docs: update Dockerfile in deployment.md to work with cargo-leptos@0.2.0

- leptos_reactive/src/resource.rs
I'm assuming this is a mistake because the point of `with` is to not clone, and the code compiles just fine with the bound removed.
> Remove `Clone` requirement on `SignalWith` for `Resource`

- router/src/matching/matcher.rs
#1890 fixed the bug
but after that, I've noticed inconsistent router behavior under the following condition:
```jsx
...
<Router>
<Routes>
<Route path="*"            view=|| { "A" } />
<Route path="/"            view=|| { "0" } />
<Route path="/test"        view=|| { "1" } />
<Route path="/test/test"   view=|| { "2" } />
</Routes>
</Router>
...
```
(sorry for the wall of table, but i cant think of any better way to express this)
O: correct
X: incorrect
| URL | View | Correct |
|-|-|-|
| / | `0` | O |
| // | `A` | O |
| ///// | `A` | O |
| /test | `1` | O |
| /test/ | `1` | O |
| /test// | `1` | X (this should be `A`) |
| /test/// | `A` | O |
| //test | `1` | O |
| ///test | `1` | O |
| ////test | `A` | X (this should be `1`) |
| /test/////test | `A` | X (this should be `2`) |
| …
> fix: properly handle trailing `/` in more routes

- leptos_macro/Cargo.toml
- leptos_macro/src/lib.rs
- leptos_macro/src/server.rs
- leptos_macro/tests/server.rs
- leptos_macro/tests/ui.rs
- leptos_macro/tests/ui/server.rs
- leptos_macro/tests/ui/server.stderr
Closes #1621.
- modified `ServerFnArgs.parse` to accept keyword arguments and positional arguments as well
- added default encoding in `server_impl` because the Rust compiler complained if we fed only `endpoint`
- added unit tests.
- I couldn't compile leptos_macro/src/server.rs with `cargo test --features=ssr` in directory `leptos_macro`. So I enclosed it in cfg_if.
- update document
> feat: optional named arguments for #[server] macro (closes #1621)

- leptos/src/await_.rs
This PR adds the ability to use `create_local_resource` instead of `create_resource`. This will run the create resource locally on the system and therefore its result type does not need to be `Seriaziable`.
Closes #1567
> feat: Add local attribute for Await

- router/src/components/router.rs
- router/src/components/routes.rs
Minor change - Over time clippy is refining its default ruleset.
here is the relevant documentation 
https://rust-lang.github.io/rust-clippy/master/index.html#/get_first
> Clippy: use .first() [not .get(0)]

- router/src/components/form.rs
This adds a `replace` property to the form component to control `NavigationOptions` on submit.
Closes #1914
> Add `replace` property to form component

- integrations/actix/src/lib.rs
- integrations/viz/src/lib.rs
- leptos/src/lib.rs
- leptos_dom/src/nonce.rs
- leptos_reactive/src/lib.rs
- router/src/lib.rs
Seen when running 
```
cargo doc
```
There were a couple of disambiguation issues hiding behind the list of minor issues 
scrolling off the page 
So 
[Route] becomes [struct@Route]
and 
[`extract`] becomes [`extract()`].
> chore: cargo doc -- removed lint warnings.

- leptos_reactive/src/resource.rs
- `read` -> `get` as the former is deprecated, [docs](https://docs.rs/leptos/latest/leptos/struct.Resource.html#method.read)
- Add documentation on how to have single and multiple signals as source
P.S: I have not created an issue as I feel this is a simple fix, hope it's fine
> docs: Improve create_resource docs

- leptos_dom/src/lib.rs
- leptos_dom/src/macro_helpers/into_attribute.rs
- Avoids an allocation when possible when using `std::fmt::Argumenets` in `IntoView`.
- Implements `IntoAttribute` for `std::fmt::Arguments`.
> `IntoView` and `IntoAttribute` for `std::fmt::Arguments` improvements

- .github/workflows/run-cargo-make-task.yml
My motivation is to clear warnings in the build artefacts.
Jumping several node version at once has bitten me in the past 
so I favour regular maintenance tasks.
> workflows: bump setup-node to version 4.

- leptos_reactive/src/trigger.rs
Adds a `new` method to `Trigger`.
This PR also implements `Default` for `Trigger` (as was suggested by clippy).
> feat: add `new` method to `Trigger`

- leptos_dom/src/macro_helpers/into_attribute.rs
This PR adds a missing implementation of `IntoAttribute` for `Cow<'static, str>`.
> feat: impl `IntoAttribute` for `Cow<'static, str>`

- docs/book/src/appendix_dx.md
- Update helix configuration for the newest version.
- To be consistent, adding the `server` ignore entry to helix as well.
- Sorting the parameters alphabetically.
> chore: Add server to procMacro for helix as well

- integrations/axum/src/lib.rs
- router/src/components/route.rs
- router/src/components/static_render.rs
@mrvillage I needed to add some `Send` + `Sync` bounds to the static data generation function, which I *think* should be okay, but I'd appreciate it if you could help out with some testing, since I think you probably have a better example of using this than I do, and/or let me know if this is wrong.
There may be a better way of getting it to work with Axum, I'm not sure, but as of now I think it's broken on Axum.
> fix: add `leptos_axum::build_static_routes` (closes #1843)

- router/src/lib.rs
* [suspect docs](https://docs.rs/leptos_router/0.5.2/leptos_router/#feature-flags)
* [feature flags](https://docs.rs/crate/leptos_router/0.5.2/features)
Likely missed when the `stable` flag was deprecated
> fix: router docs feature `stable` to `nightly`

- leptos/Cargo.toml
- leptos_config/Cargo.toml
- leptos_macro/Cargo.toml
all changes are of the form 
```
-typed-builder = "0.16"
-typed-builder-macro = "0.16"
+typed-builder = "0.18"
+typed-builder-macro = "0.18"
```
> chore: typed-builder and typed-builder-macro - bumped version numbers.

- router/Cargo.toml
- router/src/history/params.rs
fixes #1971 through reimplementation.
Comes with the benefit of knocking a crate out of the deps tree.
> fix: `leptos_router::params_map!`

- leptos/src/suspense_component.rs
- leptos/src/transition.rs
- leptos_reactive/src/hydration.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/suspense.rs
Closes #1805, closes #1905.
This one was a poor decision with some odd edge cases. Basically, the value "number of resources the Suspense is currently waiting for" was treated as a simple integer counter, rather than a `Set<Resource>`. This meant that things like reading two resources in the same reactive `move ||` block would be inherently broken, as on of them resolving would trigger the second one to read again, incrementing the Suspense counter again.
I am going to be changing how Suspense works pretty significantly in 0.6, but I'm hopeful that for now, this will manage to fix those edge cases without breaking the API or existing examples.
> fix: treat Suspense as containing a Set of resources, not a counter

- leptos_server/src/action.rs
We discussed deprecating the `create_action` and related functions over time. I went ahead and swapped some of the pure function implementations to use the new constructor. I will need to continue to work through the other types and grep out as much as I can in the internal API.
May be a slow effort with my current work schedule, but progress regardless.
I would appreciate feedback on the docs. I tried to keep original intent while reducing word count for the sake of maintenance. Open to corrections.
> feat: `Action::new` and `Action::server`

- examples/tailwind_axum/src/app.rs
- leptos/src/lib.rs
- leptos_macro/src/lib.rs
- leptos_macro/src/slice.rs
- leptos_macro/tests/slice/red.stderr
re-exports the `leptos_macro::slice!` macro to `leptos::slice!`.
Also changed the implementation a bit to use more idiomatic `syn`/`quote` stuff.
> re-export slice!

- leptos/src/portal.rs
This would close #2010. 
`create_render_effect` runs immediately/synchronously during rendering. `create_effect` doesn't run until the tick after it's created.
This means that if used during hydration, `create_render_effect` runs during the hydration process and `create_effect` runs after hydration.
`<Portal/>` was causing a bug during hydration because its elements were created inside a render effect, which meant they happened during hydration, and when they went to create elements thought they should be looking them up in the existing HTML in the DOM rather than creating them afresh.
This fixes the issue by switching to `create_effect`, so a `<Portal/>` only creates elements after hydration is done and there is no error.
@maccesch This does have the effect of slightly changing execution …
> fix: use `create_effect` for `<Portal/>` to avoid hydration issues (closes #2010)

- docs/book/src/progressive_enhancement/action_form.md
- router/src/components/form.rs
This was brought up in Discord and I noticed there were no examples.
> Docs: `ActionForm` examples for complex arguments

- docs/book/src/router/20_form.md
I believe it is a typo in The document book section [form]( https://leptos-rs.github.io/leptos/router/20_form.html).
The input name attribute should be `q` for `let search = move || query().get("q").cloned().unwrap_or_default();` working.
> fix document book input name query

- integrations/axum/src/lib.rs
- leptos_dom/src/events/typed.rs
- leptos_dom/src/helpers.rs
- leptos_dom/src/hydration.rs
- leptos_dom/src/lib.rs
- leptos_dom/src/macro_helpers/into_attribute.rs
- leptos_dom/src/macro_helpers/into_style.rs
- leptos_dom/src/nonce.rs
- leptos_hot_reload/src/lib.rs
- leptos_reactive/src/hydration.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/selector.rs
- leptos_reactive/src/signal_wrappers_read.rs
- leptos_reactive/src/signal_wrappers_write.rs
- leptos_reactive/src/suspense.rs
- meta/src/body.rs
- meta/src/html.rs
- meta/src/lib.rs
- meta/src/title.rs
- router/src/components/redirect.rs
- router/src/components/route.rs
- router/src/components/router.rs
- router/src/components/static_render.rs
- router/src/history/mod.rs
- router/src/history/params.rs
- router/src/matching/route.rs
- server_fn/src/error.rs
This is a coding standard, I have adopted in my own libraries, and well this is open source, so I want to start using this practice in modules that I use on a regular basis too..
It follows a recent trend in the rust community.
It is a aspiration, rather than an achievable goal - One day someone will try and run my library of an IOT device 
and I will have to answer question on the lines of
What portions of the library can I still use in a "no_std" environment.
So the is a defensive change .. and to drop std::fmt and use core::fmt  where possible 
I hope this helps.
> Minor: stop using std::fmt, instead used core::fmt.

- examples/fetch/src/lib.rs
The docs state that when used in conjunction, `<ErrorBoundary>` should be inside `<Transition>`, not the other way around. This didn't have a functional effect on the fetch example because it happens to use `create_local_resource` which guarantees that the resource will be loaded on the client side. https://docs.rs/leptos/latest/leptos/fn.ErrorBoundary.html#interaction-with-suspense
But I was working on an application that uses `create_resource`, and I happened to be using this example as a model of using `<ErrorBoundary>` and `<Transition>` in conjunction. When server side rendering is a possibility, reversing them seems to cause an issue where the `<ErrorBoundary>` fallback doesn't render properly.
So I thought maybe we should use them in the recommended order in this example.
> Have fetch example conform to docs guidance around using <ErrorBoundary> and <Transition> in conjunction

- leptos/src/lib.rs
- leptos/src/provider.rs
- leptos_reactive/src/context.rs
See issues #1986 and #2038. This is better than the edited docs in #2015.
```rust
#[component]
// each Provider will only provide the value to its children
view! {
<Provider value=1u8>
// correctly gets 1 from context
{use_context::<u8>().unwrap_or(0)}
</Provider>
<Provider value=2u8>
// correctly gets 2 from context
{use_context::<u8>().unwrap_or(0)}
</Provider>
// does not find any u8 in context
{use_context::<u8>().unwrap_or(0)}
}
}
```
> feat: `<Provider/>` component to fix context shadowing (closes #2038)

- leptos_reactive/src/trigger.rs
`Trigger` has its own implementation to optimize on not actually having a value. Unfortunately, its implementation was actually slightly different from signals, which meant that if it had been marked `DirtyMarked` it would never be marked `Clean` again, which meant it would never actually track in future. This caused tricky issues like #1948 and #2048. This PR should close both of those.
> fix: correctly mark `Trigger` as clean when it is re-tracked (closes #1948, #2048)

- examples/README.md
Add the install step to the README.md so the user can follow the readme, without using the [leptos book](https://leptos-rs.github.io/leptos/02_getting_started.html)
> Add instruction to install trunk to examples/README.md

- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
- leptos_macro/tests/ui/component.rs
- leptos_macro/tests/ui/component.stderr
This restructures the component macro so that it always emits a function with the identical name into a `#[doc(hidden)]` module named like `component_module_my_component`, whether the rest of the `#[component]` expands successfully or not.
The goal here is to provide a better rust-analyzer experience when there are syntax errors, when you are typing, etc (see #1781 and #1782, which doesn't really fix it)
If some others could let me know if this actually helps, I'd appreciate it and will fix any CI errors that arise.
> fix: improved rust-analyzer support in `#[component]` macro?

- router/src/components/link.rs
#1953 modified the `aria-current` attribute of the router link component to an invalid value.
As a result, the CSS selector `[aria-current=page]` is no longer working in the latest release `0.5.3`.
> Fix `aria-current` attribute value

- docs/book/src/view/08_parent_child.md
This seems to have been left in as a typo. 
With the `F` present, it gives an error of:
```
error[E0392]: parameter `F` is never used
--> src/main.rs:16:16
|
16 | pub fn ButtonC<F>() -> impl IntoView {
|                ^ unused parameter
|
= help: consider removing `F`, referring to it in a field, or using a marker such as `PhantomData`
= help: if you intended `F` to be a const parameter, use `const F: usize` instead
error[E0282]: type annotations needed
--> src/main.rs:11:10
|
11 |         <ButtonC on:click=move |_| set_toggled.update(|value| *value = !*value)/>
|          ^^^^^^^ cannot infer type of the type parameter `F` declared on the function `ButtonC`
|
help: consider specifying the generic argument
|
11 |         <ButtonC::<F> on:click=move |_| set_toggled.update(|value| *value = …
```
> Fix book chapter 3.9 #3

- docs/book/src/interlude_projecting_children.md
- docs/book/src/testing.md
Fixed two errors in the code examples while studying the documentation. 
1. Missing the variable names in `docs/book/src/interlude_projecting_children.md`.
2. Referencing to a non-existing variable in `docs/book/src/testing.md`.
> docs: minor fixes for some code examples in the book

- examples/hackernews_axum/Cargo.toml
- examples/hackernews_islands_axum/Cargo.toml
- examples/hackernews_js_fetch/Cargo.toml
- examples/session_auth_axum/Cargo.toml
- examples/tailwind_axum/Cargo.toml
- examples/todo_app_sqlite_axum/Cargo.toml
- examples/todo_app_sqlite_csr/Cargo.toml
- examples/todo_app_sqlite_viz/Cargo.toml
- integrations/axum/Cargo.toml
- integrations/viz/Cargo.toml
The http version [1.0](https://docs.rs/http/latest/http/index.html) is now public 
but moving from 0.2.8 is just picking up non breaking changes.
Covering the breaking changes is a complex conversion 
which I want to leave to a fresh issue.
> Chore: Bump http from 0.2.8 to 0.2.11.

- leptos_macro/src/component.rs
- leptos_macro/src/params.rs
- leptos_macro/src/view/client_builder.rs
- leptos_macro/src/view/client_template.rs
- leptos_macro/src/view/component_builder.rs
- leptos_macro/src/view/ide_helper.rs
- leptos_macro/src/view/mod.rs
- leptos_macro/src/view/server_template.rs
- leptos_macro/src/view/slot_helper.rs
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__client_template__custom_event.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__client_template__full_span__custom_event.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__client_template__full_span__simple_counter.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__client_template__simple_counter.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__csr__custom_event.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__csr__full_span__custom_event.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__ssr__custom_event.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__ssr__full_span__custom_event.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__ssr__full_span__simple_counter.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__ssr__simple_counter.snap
improved macro hygiene by using more fully qualified paths. Main thing was swapping trait methods called with `.` for fully qualified trait methods, so that users don't always need to import `leptos::*` / `leptos_router::*` for macros to work.
Didn't bother as much for fully qualified std traits since no one is working in no_std anyways
(minor bit: also reformatted some `quote_spanned!` bits to follow convention (no space before `=>`) and remove redundant variable bindings)
might need to change up some `#[allow(unused_braces)]` if incorrect warnings appear
> Improve macro hygiene

- leptos/Cargo.toml
- leptos_reactive/Cargo.toml
- leptos_reactive/src/spawn.rs
- router/src/history/mod.rs
- router/src/matching/resolve_path.rs
Fixes #2056.
This is a change to the original fix proposed in the issue.  After talking to colleagues working on upstream WASI, the recommendation was to poll the future only _once_, on the basis that if the future were pending at that point, `futures::executor::block_on` would block forever, and it was better to panic with a specific message than to do that.
The caveat here is that `spawn_local` is a very low level function.  My fix works for the case I ran into, which was `create_resource`.  But if `spawn_local` is used elsewhere for a future that is truly long-running and non-blocking (such as a WASI Preview 2 outbound HTTP request) then this will fail.  Hopefully in that case the message will at least point us to the fix that's needed.  I don't think this is an issue as yet, but I …
> Fix WASI builds trying to use JS for `spawn_local`

- examples/tailwind_actix/Cargo.toml
- examples/tailwind_actix/src/app.rs
- examples/tailwind_axum/Cargo.toml
- examples/tailwind_axum/src/app.rs
Make tailwind examples more clear (for newbies) by using an output name other than "tailwind."
I thought that the name "tailwind.css" in "/pkg/tailwind.css" came from the file "style/tailwind.css," but in fact the name comes from the output name specified in Cargo.toml. This small change should help other newbies pick up on what's happening a little quicker.
> Make tailwind examples more clear

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- integrations/viz/src/lib.rs
- router/src/extract_routes.rs
Using Leptos as a static site generator currently has two main steps:
1. generating routes
2. building static routes
The second step allows passing additional context (e.g. global state) via `build_static_routes_with_additional_context` that can then be used in components, but the first step doesn't. This means all components that get evaluated during step 1 will fail to get the additional context, while others that are only evaluated during 2 will be able to use it.
This PR adds support for additional context during step 1
> Support additional context for route generation

- leptos_macro/src/server.rs
We have a `#[warn(missing_docs)]` in our code and server_fns always throws an warning for that. This should fix it. Do let me know if I'm missing something
> Added documentation for server fns

- leptos_dom/Cargo.toml
- leptos_macro/Cargo.toml
- router/Cargo.toml
Regarding a clippy warning seen in a app the uses leptos 
The root cause is the family of leptos modules requiring **BOTH** versions 0.10.5 and 0.11.0 This PR will fix that. ( Also needs a bump to 0.12.0 )
```
warning: multiple versions for dependency `itertools`: 0.10.5, 0.11.0
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#multiple_crate_versions
note: the lint level is defined here
--> src/lib.rs:4:9
|
4 | #![warn(clippy::cargo)]
|         ^^^^^^^^^^^^^
= note: `#[warn(clippy::multiple_crate_versions)]` implied by `#[warn(clippy::cargo)]`
```
> Bumping itertool version number, fixes downstream "Clippy" warning issue.

- leptos_macro/example/src/lib.rs
to reprodce this clippy warning
```bash
cd leptos/leptos_macro/example
cargo clippy
```
warning: the following explicit lifetimes could be elided: 'a
--> src/lib.rs:41:20
|
41 | fn TestMutCallback<'a, F>(mut callback: F, value: &'a str) -> impl IntoView
|                    ^^                              ^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
= note: `#[warn(clippy::needless_lifetimes)]` on by default
help: elide the lifetimes
|
41 - fn TestMutCallback<'a, F>(mut callback: F, value: &'a str) -> impl IntoView
41 + fn TestMutCallback<F>(mut callback: F, value: &str) -> impl IntoView
|
warning: `example` (lib) generated 1 warning (run `cargo clippy --fix --lib -p example` to apply 1 suggestion)
> 'a lifetime are not linking input params to the output. Should be replaced by static

- leptos_macro/src/lib.rs
There's a compile-time trade-off here, as this requires cloning the `TokenStream` another time so makes every `#[component]` macro slightly slower in exchange for correctly passing along errors when the function signature is broken.
> fix: emit original token stream when there are syntax errors in `#[component]` or `#[island]` function signature (closes #2133)

- integrations/axum/src/lib.rs
- leptos_dom/src/macro_helpers/into_attribute.rs
- leptos_dom/src/nonce.rs
This change should both remove repetition for implementing `IntoAttribute` for `Option`s and help futureproof things by making sure any option of an intoattribute will always also be intoattribute.
> Make IntoAttribute more flexible for Options

- router/Cargo.toml
- router/src/components/router.rs
- router/src/components/routes.rs
- router/src/matching/mod.rs
I had another go #1806 and it turned out to be easier than I previously thought to solve naively. But I'm not sure this is an ideal solution, maybe the IDs shouldn't be UUIDs, or maybe the caches should be held by the objects directly.
I'm also finding it hard to add a unit/integration test, so I would welcome a suggestion on this as well.
> Namespace caches and branches with new router IDs

- examples/tailwind_actix/src/main.rs
The output.css file the actix service in the example references was removed here: https://github.com/leptos-rs/leptos/commit/2798dc455fc44118e0e1f1dd34c169c45184ff83
This was causing confusion for new people looking at the example: https://discord.com/channels/1031524867910148188/1192511724570546197/1192511724570546197
This PR simply removes the unused output.css service/endpoint from the actix tailwind example. The example works without it.
> Cleanup some dead code in actix tailwind example

- router/src/history/mod.rs
- router/src/history/state.rs
I am pulling the "State" field in a similar manner to the other location fields within `BrowserIntegration::current()`. I also changed the State serialization for `None` from `UNDEFINED` to `NULL` as the latter is the default in browsers and should be more consistent. I am not sure what the reason was to originally use `undefined` and `State(None)`.
> router: Fix router forgetting about state (fixes #2164)

- leptos_dom/src/lib.rs
Removes a clone when using a `Cow<'static, str>` in a view.
**:warning: Contains breaking change**
`Cow<'_, str>` no longer implements `IntoView`, now only `Cow<'static, str>` does.
The reason being: `Cow<'_, str>` requires a clone when converting to a view, since we don't know if the str is static.
> fix!: remove clone in `Cow<'static, str>` `IntoView` impl

- leptos_dom/src/ssr.rs
This caused me some trouble recently. Just thought it may be helpful
> docs: `View::render_to_string` panic

- router/src/components/static_render.rs
This removes the `.static` from file names for static routes. Some cleanup methods no longer made any sense and were removed, too. With this change, the build output from static routes can be served as a static website without any file renaming (see discussion in #1594).
Additional context is provided for the static_params closures.
> Make static rendered routes servable and provide context to static_params

- examples/ssr_modes_axum/Cargo.toml
- examples/tailwind_axum/Cargo.toml
- integrations/axum/Cargo.toml
- `leptos_axum` default feature:
- remove `tokio/full`, `axum/macros`
- add `tokio/fs`, `tokio/sync`
- example `leptos-tailwind-axum`:
- enable `tokio`'s `rt-multi-thread` and `macros` features
- example `ssr_modes_axum`:
- enable `tokio`'s `rt-multi-thread` and `macros` features
> chore: minimize features activated with `leptos_axum`'s default feature (#1846)

- examples/server_fns_axum/src/app.rs
- server_fn_macro/src/lib.rs
In which we create a custom encoding for TOML server functions, because -- why not?
> feat: add support for custom encoding to `#[server]` macro

- leptos_macro/src/lib.rs
- leptos_reactive/src/memo.rs
- leptos_reactive/src/resource.rs
`.refetch()` inadvertently took a tracked read on the source memo, which meant that if you refetched inside an effect, it would refetch again if the source changed, which is probably not intended.
> fix: `.refetch()` should not include any tracked reads

- server_fn_macro/src/lib.rs
Previously `Result<T, leptos::ServerFnError>` etc. were allowed -- this should restore that ability.
> fix: allow paths to `ServerFnError` type

- README.md
I removed the earlier comparisons from the README, as I was getting the feeling they were out of date, and I don't like the feeling of "competition brain" between frameworks; these have been in there since 0.0.x, but Leptos is much more established now and I didn't feel the need to differentiate as strongly. @rakshith-ravi pointed out that these are still helpful so I'll add them back, updated/edited. Open to feedback on any details here.
> Update README.md framework comparisons

- rustfmt.toml
See [leptosfmt](https://github.com/bram209/leptosfmt?tab=readme-ov-file#using-with-rust-analyzer) for why this may be needed.
TLDR: when rustfmt is hooked by leptosfmt, you need to specify an edition explicitly.
> chore: define `edtion = "2021"` in `rustfmt.toml`

- leptos_reactive/src/runtime.rs
- meta/src/lib.rs
- server_fn/src/error.rs
Having the tag on `ServerFnError` types here caused a runtime panic during SSR if a resource had an initial `Err` value:
```
could not serialize Resource: Serialize(Error("cannot serialize tagged newtype variant ServerFnError::ServerError containing a string", line: 0, column: 0))
```
> fix: serialization error during SSR on ServerFnError

- examples/counter_isomorphic/src/counters.rs
This warning is seen in the browsers console window.
```
counter_isomorphic.js:1068 At src/counters.rs:138:17, you are reading a resource in `hydrate` mode outside a Suspense or Transition. This can cause hydration mismatch errors and loses out on a significant performance optimization. To fix this issue, you can either:
1. Wrap the place where you read the resource in a Suspense or Transition/ component, or
2. Switch to using create_local_resource(), which will wait to load the resource until the app is hydrated on the client side. (This will have worse performance in most cases.)
```
Two derived signals "value" and "error_msg" need to be wrapped in a Suspense block.
"value" falls back to just the initial text.
"error" uses the default fallback.
> example/counter_isomorphic Removed console warning.

- router/src/lib.rs
- server_fn_macro/src/lib.rs
When I was creating a PR just now I wanted to use 
`cargo fmt`
to check my own work.  That only works if HEAD is blemish free.
So this a just a minor bit of housekeeping.
> Chore: Minor, ran ```cargo fmt```

- examples/hackernews/src/routes/stories.rs
This warning appears in the browser's console log.
```
hackernews.js:933 At src/routes/stories.rs:39:17, you are reading a resource in `hydrate` mode outside a <Suspense/> or <Transition/>. This can cause hydration mismatch errors and loses out on a significant performance optimization. To fix this issue, you can either:
1. Wrap the place where you read the resource in a <Suspense/> or <Transition/> component, or
2. Switch to using create_local_resource(), which will wait to load the resource until the app is hydrated on the client side. (This will have worse performance in most cases.)
```
> examples/hackernews: Add a "Suspense" wrapper.

- integrations/axum/src/lib.rs
Because of the awkward setup of spawning into a pinned thread, the Axum integration tries to send its response through a channel (due to the weird Send/Sync workaround currently in place) and unwraps awaiting the receiver
https://github.com/leptos-rs/leptos/blob/0ff1e279a2774730ab01f28d2c794217de35a19d/integrations/axum/src/lib.rs#L332
Panicking here (or anywhere in these handlers) is a bad idea, and can cause difficult-to-reproduce issues.
I'm wondering if replacing all these with something like this might be a good idea.
> fix: error rather than panicking if unable to send response in Axum integration

- router/src/components/form.rs
This commit simply fixes a typo which causes a broken link in the docs.
Thanks for this awesome framework!
> docs: fix broken link in leptos_router

- router/src/history/params.rs
- router/src/history/url.rs
- router/tests/matcher.rs
In my application I have some routes with parameters that can be user defined and often include spaces. This means that there usually is a %20 instead of a space in the parameter which is unexpected from a dev perspective. This makes sure that when building the parameter map we percent decode the parameter.
This breaks a doc test and I have a proposed fix for it since it now requires the "ssr" feature to work. The test now only runs when the ssr feature is enabled.
> Percent Decode Url Parameters

- integrations/axum/src/lib.rs
Note that this is a minimal implementation and will __not__ allow the
user to `expect_state` if they have external calls to rendering their
app (i.e. using `render_app_to_*` directly).
Additional work should be taken up to outline these changes through documentation.
Unfortunately, my personal work takes up most of my time right now.
> feat(axum): provide state to server fn context

- examples/directives/src/lib.rs
- leptos_macro/src/view/mod.rs
fixes #2248 
added to the directive examples as well.
> fix: make directive `.into()` calls consistent

- integrations/axum/Cargo.toml
- server_fn/Cargo.toml
- server_fn/src/lib.rs
- server_fn/src/middleware/mod.rs
- server_fn/src/request/mod.rs
- server_fn/src/response/mod.rs
- server_fn_macro/src/lib.rs
This is required to run an axum leptos server in wasm post 0.6.0. Prior 0.6 server_fn didn't rely on axum and now that it does it needs a no-default version because the default axum is not wasm compatible because it brings in tokio. 
leptos_axum doesn't require server_fn to have axum default features so I set it to rely on the new no-default-feature version of server_fn. 
I don't think server_fn requires axum to have default features at all, so instead of adding a no-default feature flag we could just set no-default feature for axum to be the default feature set of server_fn.
This fixes
https://github.com/leptos-community/deployment-deno/pull/2
> Create an axum-no-default feature for server_fn and sets leptos_axum to rely on it instead.

- .github/workflows/get-changed-examples-matrix.yml
- .github/workflows/get-example-changed.yml
- examples/Makefile.toml
- examples/cargo-make/scripts/web-report.sh
- examples/hackernews_islands_axum/Makefile.toml
Closes #2293 
- Running `cargo make test-report` now shows leptos crates that are not configured to build with `cargo-leptos`
- Add `ci` leptos configuration for **hackernews_islands_axum** example
- **hackernews_js_fetch** is intentionally not configured to build with `cargo-leptos`. It uses a custom build.
> ci(examples): configure leptos examples to build with cargo-leptos when possible

- .github/workflows/run-cargo-make-task.yml
I think the solution is to bump the version numbers of two actions.
```
CI (leptos_config) / Run ci (nightly-2024-01-29)
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20: actions-rs/toolchain@v1, davidB/rust-cargo-make@v1, jetli/trunk-action@v0.4.0, pnpm/action-setup@v2, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
> I have been looking the "github actions" build warnings.

- meta/src/lib.rs
Otherwise user gets:
```
use_head() is being called without a MetaContext being provided. We'll automatically create and provide one, but if this is being called in a child route it may cause bugs. To be safe, you should provide_meta_context() somewhere in the root of the app.
```
> fix(meta): provide meta context missing in example

- server_fn_macro/src/lib.rs
In most cases when you return `Result<..., ServerFnError<E>>` this worked but when you tried `Result<..., leptos::ServerFnError<E>>` then it didn't.
> Error type detection only worked without type path

- integrations/utils/src/lib.rs
> feat: use cdn url for static assets (#2281)

- leptos/src/transition.rs
If a Transition is created in hydrate mode, but after hydration, it should be treated the same way a CSR transition is.
> fix: Transition in hydrate mode that isn't initially created (closes #2279)

- router/src/components/form.rs
Elsewhere, when we hit an error, we both log it as an error and also set the `value` of the action to reflect the error. When converting form fields to the `ServerFn` type, we were only setting the `value`. This made it seem like the `ActionForm` was failing silently if you weren't reading the `action`, and it's super easy to get tripped up by this. This just adds a log.
cc: @benwis
> docs: log error on failing to convert form to ServerFn type, in addition to setting action value

- router/src/components/form.rs
- router/src/components/router.rs
- router/src/hooks.rs
- server_fn/src/redirect.rs
Fixes #2269
In client-side navigation we now handle redirects returned from server functions by resolving the location against the current origin as a base. The base is only relevant if the location doesn't already include an origin. This fixes cross-origin redirects.
Note: in order to handle redirects in the same way as the browser would handle them, we need to use the server function's URL (typically `<origin>/api/something`) as a base. I leave this as a TODO for a future leptos version, because it probably requires changing the signature of the `server_fn` redirect hook.
In order to not be affected by a future breaking change, users should already start making sure that their redirect locations either include an origin or at least start with a single slash (e.g. `Location: /foo`).
> fix: handle cross-origin redirects in server function redirect hook

- examples/tailwind_csr/src/app.rs
Fix for #2327 
Updated `href` path in `Stylesheet` tag to `output.css`
> Fixed href path in tailwind_csr example

- leptos_reactive/src/memo.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/tests/memo.rs
Currently the memo function:
- Only receives a reference to the previous value when running
- Is required to return an owned value, even if it didn't change
This means that:
- The returned type needs to be allocated and copied one time per source signal change, something that may be very common for slices
This PR implements a Proof Of Concept proposing a new, more primitive, "raw memo", that allows the memo function to receive the previous value as owned, allowing it to be re-used by the memo, like effects (in fact, part of the implementation was taken from there).
"Normal" memos were changed to be implemented by using the raw memo, so there's no need to create a new reactive node. It should be backwards compatible. I haven't checked if there's any performance / binary size impact …
> feat: Add owning memos to allow memos that re-use the previous value

- leptos_macro/src/lib.rs
- server_fn_macro/src/lib.rs
This PR adds an optional `impl_from` named  argument for `server_fn` proc macro.
This argument defaults to `true` and enables (or disables) the impl of `From` trait for server function argument type.
In cases when the server function has more than one argument, the `impl_from` has no effect on the trait impl generation, as it has been already disabled by function arguments number check.
The related issue has been discussed here: https://discord.com/channels/1031524867910148188/1203001939089035295
TL;DR: orphan rules disable (in some cases) the implementation of `From` trait for conversion between the only server function argument and server function argument type. 
The minimal example of the issue lives here: https://github.com/videobitva/test_server_fn
> feat: add `impl_from` argument to `#[server]` proc_macro

- integrations/actix/src/lib.rs
- leptos_macro/src/lib.rs
- leptos_reactive/src/context.rs
- leptos_reactive/src/oco.rs
- leptos_server/src/action.rs
- server_fn/src/lib.rs
Potentially fixes #859
The relative paths for some doc links comes inspired from what tokio does for its workspace links. See [here](https://docs.rs/tokio-macros/1.6.0/src/tokio_macros/lib.rs.html#28) for an example.
> Fix Broken Doc links and Deprecate `FromUtf8Error` in `oco.rs`

- leptos/Cargo.toml
- leptos_macro/src/lib.rs
- leptos_reactive/src/oco.rs
#2318 adds a deprecation note on an unused error enum. Unfortunately adding deprecation warnings breaks CI that fails on clippy warnings, including our own, so has caused CI on all subsequent PRs to break.
> chore(ci): fix failing CI by removing deprecation note

- examples/ssr_modes/src/app.rs
- examples/ssr_modes_axum/src/app.rs
- integrations/actix/tests/extract_routes.rs
- router/src/components/route.rs
- router/src/components/router.rs
- router/src/components/routes.rs
- router/src/extract_routes.rs
- router/src/extract_routes/test_extract_routes.rs
- router/src/matching/matcher.rs
- router/src/matching/resolve_path.rs
- router/src/matching/route.rs
- router/tests/join_paths.rs
- router/tests/matcher.rs
- router/tests/trailing_slashes.rs
Fixes regression in #2172. The problem was that it would count 1 path segment in root path ("/") instead of zero. Just moved root path special case to segment extractor function.
Router example tests now pass, also made sure router tests pass (at least with "ssr" feature). Might have missed smth else.
> Trailing slashes (#2154) take 2

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- router/src/components/route.rs
> feat: add method to RouteContext (#1808)

- router/src/components/router.rs
> fix: do not strip query in redirect hook when using client-side navigation

- leptos_macro/src/component.rs
`#[wasm_bingen]` expect to find `wasm_bindgen` as a root module, this can cause an error when compiling island if `wams_bindgen` is not a dependencie of the project.
This PR add `#[wasm_bindgen(wasm_bindgen = leptos::wasm_bingen)]` to tell the macro where to find the module.
close #2312
> Specify path to wasm bindgen in island macro

- examples/cargo-make/playwright-trunk-test.toml
- examples/error_boundary/Makefile.toml
- integrations/utils/src/lib.rs
`options` is already a reference so it was passing a double reference. Looks like this was inadvertently added in the last commit in PR https://github.com/leptos-rs/leptos/pull/2373 while other CI failures were happening so it was missed.
The error_boundary example has been leaving the server running and eventually failing due to timing out. This PR makes the start task run in parallel with the playwright task instead of waiting forever on the server start task to exit it uses a dumb two minute sleep timer to ensure the server has compiled and started. This could probably be improved but might risk being too complex for bash scripts so I left it for now.
> fix(ci): "needless borrow" error and example never exiting

- leptos_reactive/src/memo.rs
Removes trait bound `PartialEq` from `create_owning_memo` which is not needed. Closes #2388.
> Unnecessary trait bound `PartialEq` removed from `create_owning_memo`

- integrations/utils/src/lib.rs
- leptos_config/src/lib.rs
Just some quality of life stuff for hashing
> Rename env var and tweak hashing to align with cargo leptos

- examples/todomvc/src/lib.rs
This is just a minor point seen while copying code snippets from the examples directory
Here is a snippet from this  clippy rule [new_without_default](https://rust-lang.github.io/rust-clippy/v0.0.212/index.html)
struct Foo(Bar);
impl Foo {
fn new() -> Self {
Foo(Bar::new())
}
}
Instead, use:
struct Foo(Bar);
impl Default for Foo {
fn default() -> Self {
Foo(Bar::new())
}
}
both new() and default() are not needed - when just default() will suffice.
> Minor: examples/todomvc -   Rename Todos::new()  as  Todos::default().

- server_fn/Cargo.toml
- server_fn/src/codec/mod.rs
- server_fn/src/codec/msgpack.rs
This adds [MessagePack](https://msgpack.org/) codec support.
To quote MessagePack, "it's like JSON but fast and small". I was wanting to make a param payload that included a decently-sized byte array inline, and JSON is pretty inefficient at that, so I added MessagePack support.
The CI hasn't finished running on my machine but I decided to go ahead and submit it anyways because the change is so isolated.
> Add MessagePack codec

- leptos_reactive/src/hydration.rs
On an experimental islands site I upgraded today, these printlns run >1000 times on a single page load. I believe they're just for development, but also happy to change to tracing if desired
> remove printlns that run many times

- leptos_macro/src/slot.rs
- leptos_macro/src/view/slot_helper.rs
Saw somebody in the Discord server ask for the ability to do
```rs
#[slot]
struct Slot {
#[prop(attrs)]
attributes: Vec<(&'static str, Attribute)>
}
```
Which currently is not implemented, so I just extended the existing options and slapped in the impls and methods in `leptos_macro/slot.rs` and `leptos_macro/slot_helper.rs`
> feat: allow #[prop(attrs)] on slots

- leptos_dom/src/events.rs
Delegated event listeners do not support adding more than one event listener of the same type. This can cause confusion if two listeners are added, as one is silently dropped.
Here I just assert that the value does not exist yet, which was what we decided to go with internally (it seems good practice to avoid double listeners, if possible).
Alternatives:
- Switch to a warning.
- Combine the two event listeners.
> fix: prevent setting the same event listener twice

- cargo-make/lint.toml
- leptos_dom/src/logging.rs
- router/src/components/static_render.rs
> chore: Disallow prints to stdout

- .github/workflows/run-cargo-make-task.yml
- examples/counter_isomorphic/Cargo.toml
- examples/counter_without_macros/Cargo.toml
- examples/counters_stable/Cargo.toml
- examples/suspense_tests/Cargo.toml
- leptos/tests/ssr.rs
Resolves #2427
Install the latest version of `wasm-bindgen` and `cargo-leptos` as part of the CI environment setup.
> fix(ci): leptos examples fail with bindgen schema error

- examples/session_auth_axum/src/auth.rs
The current example for `session_auth_axum` has a serializable `User` struct which contains the user's hashed password:  
https://github.com/leptos-rs/leptos/blob/fda4dba2370fdb4f5f81961bdeb7ca139d2e612d/examples/session_auth_axum/src/auth.rs#L5C1-L11C2
This change separates the password hash into a new, non-serializable struct to prevent it from being returned to the client. Existing auth logic is modified to use new versions of `User::get` and `User::get_from_username` which return `(User, UserPasshash)` tuples.
> For the session_auth_axum example, move the passhash into a separate non-serializable struct.

- .github/workflows/get-examples-matrix.yml
- .github/workflows/run-cargo-make-task.yml
- leptos/tests/ssr.rs
Resolve node warnings from the following actions:
- mbround18/install-jq@v1
- actions-rs/toolchain@v1
- jetli/trunk-action@v0.4.0
- actions/cache@v3
> chore(ci): upgrade actions to node 20

- .github/workflows/get-example-changed.yml
- .github/workflows/get-leptos-changed.yml
tj-actions/changed-files@43 is already used elsewhere in the codebase.
This just makes things uniform.
> Chore(ci) bumping tj-actions/changed-files to version 43.

- .github/workflows/ci-semver.yml
- leptos/tests/ssr.rs
Resolves #2229
See the semver output [here](https://github.com/leptos-rs/leptos/actions/runs/8395834544/job/22995978008).
> test(ci): check semver

- leptos_reactive/src/resource.rs
This PR fixes a loss in parent span context when fetching resources in SSR. 
Most notably, calling `server_fn` in a resource during SSR currently results in a break in span context, and server_fn  span runs as a 'sibling' instead of entering as a child.
With this fix the `server_fn` span will correctly continue as a child of it's caller.
> Persist parent span context within resource fetchers

- leptos_macro/src/component.rs
- leptos_reactive/src/callback.rs
- leptos_reactive/src/slice.rs
- leptos_reactive/tests/memo.rs
- router/src/components/routes.rs
- router/src/extract_routes/test_extract_routes.rs
I Manually reviewed the changes. All look like reasonable nudges.
A summary :-
In one place removed a redundant call to .clone().
In two places, now using clone_from() which clippy says **MAY** be an optimisation.
> Minor: Ran cargo clippy --fix

- leptos_dom/src/helpers.rs
The current location hash implementation will replace all `#` chars in the fragment, which shouldn't be the case.
While, according to spec, `#` is not allowed in the fragment portion of the URL, browsers tend to be lenient towards enforcing this. Opening a URL in your browser (be it Chrome or Firefox) with `#` in the fragment will get accepted and returned in your location hash.
Consider [https://github.com/leptos-rs/leptos/#test#bar](https://github.com/leptos-rs/leptos/#test#bar). Your location hash will return (in Javascript) `#test#bar`.
The current implementation in Leptos will return `testbar` while the new implementation will return `test#bar`, which fits the docs better of the function:
```
/// Current [`window.location.hash`](https://developer.mozilla.org/en-US/docs/Web/API/Window/ …
```
> Fix: Small fix for location hash/fragment

- integrations/utils/src/lib.rs
This PR implements runtime support for CDN_PKG_PATH, preferring it when available.
Beforehand, only build time would be read.
In my case, my cdn path is categorised as a sensitive key, therefore only available at runtime later than the build stage.
> Allow CDN_PKG_PATH at runtime.

- integrations/axum/src/lib.rs
It's not clear what's causing `ResponseOptions` to get removed from context but it causes occasional panics. This removes the panics and starts providing some debug info to track the issue down further.
> Remove panic for axum ResponseOptions

- leptos_config/Cargo.toml
- leptos_config/src/lib.rs
- leptos_config/src/tests.rs
- leptos_config/tests/config.rs
Closes #2429 
This is my first PR on this project and it turned out a bit bigger than expected. So I am not sure about some of the decisions I made.
- Removed `separator("_")` from the Environment source setup, because this is intended for nested structures.
- Added  `convert_case(Case::Kebab)` to the Environment source setup to match the casing serde expects.
- Removed `"[leptos-options]"` from toml string to let the settings be parsed as root level, otherwise the settings from the file and the ones set by the environment variables would be considered in different structures, therefore not affecting each other. Because of this `get_config_from_str()` now returns a `LeptosOptions` object instead of a `ConfFile`.
The test cases gave me some troubles as I had some inconsistent results. I …
> Fix: Environment variables do not overwrite Config.toml options

- .github/workflows/ci-semver.yml
This resolves #2470.
- Allow the **CI semver** workflow to be triggered manually
- _This provides the option of trying again later_
- Do not trigger the **CI semver** on `push`
- The blame for the errors seem to be external to the `leptos` code. Something changed around 03/24/2024 that now causes even previously passing commits to fail.
> ci: disable semver checks

- server_fn_macro/Cargo.toml
Hi! While scraping crates.io I've found `server_fn_macro` to be missing the `repository` field. This fixes it.
> Add repository field to server_fn_macro

- leptos_hot_reload/src/lib.rs
This will close #2421, once it is merged and released and a new version of cargo-leptos is released that includes it.
It does not necessarily make hot-reloading *work* correctly for these empty `view! {}` cases, because there's nothing "in" the DOM to be replaced by a new view. (It might be possible to change this.) But it at least allows the process to continue working correctly rather than bailing out with an error.
> fix: correctly handle empty `view! {}` in hot-reloading code (closes #2421)

- examples/error_boundary/Cargo.toml
- examples/error_boundary/src/lib.rs
> ci(examples/error-boundary): use stable syntax

- examples/counter/src/lib.rs
- examples/counters/src/lib.rs
- examples/hackernews_axum/src/error_template.rs
- examples/hackernews_islands_axum/src/error_template.rs
- examples/hackernews_islands_axum/src/routes/story.rs
- examples/hackernews_js_fetch/src/error_template.rs
- examples/hackernews_js_fetch/src/routes/story.rs
- examples/js-framework-benchmark/src/lib.rs
- examples/parent_child/src/lib.rs
- examples/portal/src/lib.rs
- examples/server_fns_axum/src/app.rs
- examples/slots/src/lib.rs
- examples/sso_auth_axum/src/lib.rs
- examples/tailwind_axum/src/app.rs
- examples/timer/src/lib.rs
- examples/todomvc/src/lib.rs
- leptos_dom/src/lib.rs
Looking back over the PRs to move the examples to stable syntax, and reading them more closely than I did when reviewing initially, I realized that people might not realize that you can use signals directly in the view on stable just as you can on nightly. In other words, you do not need to use 
```rust
view! { <p>{move || value.get()}</p> }
```
but can just use
```rust
view! { <p>{value}</p> }
```
I updated a number of examples here, and also implemented `IntoView` on `Resource` directly, which was just an oversight.
If people notice errant documentation on this feel free to make a PR to correct it.
> Simplify stable syntax in examples

- leptos_reactive/Cargo.toml
- meta/src/body.rs
Update version to spin v3, hoping to coordinate this with an update to leptos-spin
> Update spin_sdk to spin v3

- leptos/src/error_boundary.rs
This might seem simple, but the nuances of types and traits confuse many people learning the language.
> Add beginner tip to ErrorBoundary

- leptos_dom/src/lib.rs
- leptos_dom/src/macro_helpers/into_attribute.rs
This makes passing a `TextProp` directly into an attribute behave as one would expect.
> fix: make TextProp's IntoView and IntoAttribute impls reactive

- leptos_macro/src/component.rs
- leptos_macro/src/view/component_builder.rs
Solves https://github.com/leptos-rs/leptos/issues/2403
In the following code `Bar` will not inherit attributes from `Foo` when it spreads its attributes
```rs
fn main() {
let (count, set_count) = create_signal(0);
mount_to_body(move || {
view! {
<Foo
attr:hello=move || count.get().to_string()
/>
<button on:click=move|_| { set_count.update(|count| *count += 1) }>"+ count"</button>
}
});
}
#[component]
fn Foo(#[prop(attrs)] attrs: Vec<(&'static str, Attribute)>) -> impl IntoView {
view! {
<Bar {..attrs} />
}
}
#[component]
fn Bar(#[prop(attrs)] attrs: Vec<(&'static str, Attribute)>) -> impl IntoView {
view! {
<div {..attrs}>"hello world"</div>
}
}
```
This PR allows for this functionality
> feat: spread component attrs

- leptos_macro/src/lib.rs
the removed type parameter is redundant to the 'bad' example, and is confusing with it being one of the 'valid' options
> docs: remove unnecessary type parameter and trait bound in component macro 'bad' example

- leptos_macro/src/view/client_template.rs
- leptos_macro/src/view/mod.rs
Adds array syntax to the `fancy class name` syntax in the `view` macro for multiple classes to be controlled by the same `class` attribute.
e.g.
```rust
#[component]
fn App() -> impl IntoView {
let (classes, set_classes) = create_signal(true);
view! {
<div
class=(["class-1", "class-2"], classes)
>
<button
on:click=move |_| set_classes(!classes)
>
Toggle
</button>
</div>
}
}
```
Compared to the current style which requires creating a new `class` attribute for each class.
e.g.
```rust
#[component]
fn App() -> impl IntoView {
let (classes, set_classes) = create_signal(true);
view! {
<div
class=("class-1", classes)
class=("class-2", classes)
>
<button
on:click=move |_| set_classes(!classes)
>
Toggle
</button>
</div>
}
}
``` 
This can be especially useful when using styling systems like …
> Adds ability to use multiple classes in view macro using array syntax.

- leptos/Cargo.toml
The currently referenced `leptos-spin-macro` crate depends on `spin-sdk` v2, which can cause conflicts for users wanting to run Leptos on Spin using `spin-sdk` v3.
This PR updates the reference.  `leptos-spin-macro` 0.2 does not depend on the Spin SDK so should avoid any potential conflicts.
> Update leptos-spin-macro reference

- leptos_dom/src/node_ref.rs
This is a response to #2414
In production #[repr(transparent)] is use to ensure a compact representation in memory. 
In developement the memory is slightly expanded.
Things I am thinking about 
A) I have introduced a maintence hazard... the documentation block for NodeRef is repeated twice 
So any future PRs will have to make sure things are kept in sync.
I would love to avoid that...
B) I may have been over eager.. ( adding  #[track_caller ] in too many places. ) 
impl<T: ElementDescriptor> Clone for NodeRef<T> {
#[track_caller]
fn clone(&self) -> Self {
*self
}
> Debug NodeRef Warning (#2414)

- server_fn/server_fn_macro_default/src/lib.rs
- server_fn_macro/src/lib.rs
Adds `input_derive` parameter for customizing the derives on the server functions input struct.
> feat: add `input_derive` parameter to `#[server]` macro (closes #2544)

- leptos_macro/src/component.rs
The `#[component]` macro used to output an empty rustdoc comment (i.e `/// `) when a component had no documentation and no props. This triggers the `empty_docs` clippy warning which is new, and on by default, in Rust 1.78. This change avoids outputting that empty comment in that particular case.
fixes: #2571
> Fix `empty_docs` warnings in `#[component]` macro

- leptos_reactive/src/runtime.rs
If the value inside a `StoredValue` implements the drop trait, and that drop causes another read, update or dispose on another StoredValue, we'd get a cryptic panic with `already mutably borrowed: BorrowError`. 
I encountered this issue with a `StoredValue<Disposer>` with the disposer type returned by `as_child_of_current_owner()`. Because the Disposer cleans up a reactive sub-scope on Drop, it will try to mutably borrow `Runtime::stored_values` while it is still mutably borrowed by the function that drops it.
> fix: StoredValue and Resource panic during cleanup

- leptos_server/src/multi_action.rs
Noticed this small typo when digging into some of the examples :)
Thank you for all that you are doing!
> fix: grammar typo for MultiActon doc comment

- leptos_macro/src/component.rs
- leptos_macro/tests/component.rs
Fix #2274 (for real)
Currently the `Ident`s generated are just in the form `__ImplTrait0`, `__ImplTrait1`, etc. Maybe could base it off of the argument names, to improve error messages if there are bugs.
Book needs to be updated to remove this line:
https://github.com/leptos-rs/book/blob/35c380ffc8f7d2e50ef21db97943138b3dba2728/src/view/03_components.md?plain=1#L233
> feat: `#[component]` now handles `impl Trait` by converting to generic type params, fix #2274

- router/src/history/params.rs
- router/src/history/url.rs
- router/src/matching/matcher.rs
`encode_uri` does not encode URL critical characters like `&` and `+`, for that `encode_uri_component` must be used.
This also revelaed some issues with too much unescaping in several cases. Fixes #2602
> fix: URL encoding issue (closes #2602)

- leptos/src/for_loop.rs
This code block is added twice to the example.
> docs: remove duplicated code block in example of For

- leptos_reactive/src/resource.rs
With this change, the following code:
```
...
Some(existing_resource) => {
let signal_alive = existing_resource.try_with(|r| {});
match signal_alive {
Some(()) => *existing_resource,
None => {
let r = self.create_resource(&id);
self.resource_cache.insert(id, r);
r
},
}
}
...
```
can be used to check whether the cached resource is still usable (in an implementation of resource cache as described in https://github.com/leptos-rs/leptos/discussions/1162).
> fix: try_with should not panic on disposed resources (closes #2620)

- tachys/src/html/attribute/mod.rs
Exposes the PhantomData field to allow the creation of Attr instances in external libraries.
> feat: Attr exposes PhantomData field

- leptos/src/children.rs
As discussed in https://github.com/leptos-rs/leptos/discussions/2640, the `ToChildren` trait is useful to consumers who want to use the builder syntax. However, because it is currently annotated with `#[docs(hidden)]`, it's not visible in docs and also not included in Jetbrains's auto-complete.
Add a doc comment for the `ToChildren` trait, including doc tests that demonstrate how to use the trait and how it compares to directly creating children.
> docs: Add docs for `ToChildren`

- examples/action-form-error-handling/src/main.rs
- examples/counter_isomorphic/src/main.rs
- examples/errors_axum/src/main.rs
- examples/hackernews/src/main.rs
- examples/hackernews_axum/src/main.rs
- examples/hackernews_islands_axum/src/main.rs
- examples/islands/src/main.rs
- examples/server_fns_axum/src/main.rs
- examples/ssr_modes/src/main.rs
- examples/ssr_modes_axum/src/main.rs
- examples/suspense_tests/src/main.rs
- examples/tailwind_actix/src/main.rs
- examples/tailwind_axum/src/main.rs
- examples/todo_app_sqlite/src/main.rs
- examples/todo_app_sqlite_axum/src/main.rs
- examples/todo_app_sqlite_csr/src/main.rs
- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- leptos_config/src/lib.rs
- leptos_config/tests/config.rs
- projects/meilisearch-searchbar/src/main.rs
- projects/nginx-mpmc/app-1/src/main.rs
- projects/nginx-mpmc/app-2/src/main.rs
- projects/openapi-openai-api-swagger-ui/src/main.rs
- projects/ory-kratos/server/src/main.rs
- projects/session_auth_axum/src/main.rs
- projects/sitemap_axum/src/main.rs
- projects/sso_auth_axum/src/main.rs
I noticed get_configuration() in leptos_config doesn't need to be async, and I have an integration where that makes things a bit easier
> Make get_configuration sync

- leptos_reactive/src/node.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/tests/cleanup.rs
- leptos_reactive/tests/memo.rs
Hi there!
This one popped up for us as a `BorrowMut` error on the `on_cleanups` secondary map, here's what I think was going on:
- `dispose_node` was removing nodeA from the reactive graph, but not running the cleanups.
- The slot in the `slotmap` was reused by nodeB, and nodeB used `on_cleanup`.
- The old cleanups were still there, so, when inserting the new cleanup, the old ones were dropped since the slot is the same but has a higher version.
- The old cleanups contained `Drop` impls that triggered some work, which were triggered [inside `slotmap`](https://github.com/orlp/slotmap/blob/c905b6ced490551476cb7c37778eb8128bdea7ba/src/sparse_secondary.rs#L291).
- If any of the triggered work used `on_cleanup`, we recurse and panic.
With this patch I tried to simplify and make it more obvious …
> fix: ensure everything is disposed of consistently

- server_fn/src/codec/json.rs
- server_fn/src/codec/mod.rs
This PR handles serialization and deserialization for custom types with streaming server functions (https://github.com/leptos-rs/leptos/issues/1284)
It adds a new `StreamingJson` encoding which serializes each item in the stream with `serde_json`. The implementation is a fairly straight forward combination of the streaming bytes and json codecs with two exceptions:
1) The content type is the default streaming type instead of JSON because if the chunks are read as merged chunks they cannot be parsed as valid json
2) When using a custom stream type with `StreamingJson`, this PR requires the bound `Stream<Item=T>` in order to make the `T` type used in the trait implementation. We don't use the bound, but it makes the `T` type constrained. Alternatively, I could add an unused generic to …
> Server function streaming with serializable types

- router/src/components/router.rs
- router/src/history/url.rs
Resolves the need for both #2602 and the following to work:
```
#[component]
view! {
<Router>
<nav>
<a href="/file/demo">This link matches</a><br/>
<a href="/file/demo%2Ftest">"This link doesn't match"</a>
</nav>
<main>
<Routes>
<Route path="/" view=|| view!{ <h1>Home</h1> }/>
<Route path="/file/:id" view=|| view!{<h1>File match!</h1>}/>
<Route path="/*any" view=|| view! { <h1>Any</h1> }/>
</Routes>
</main>
</Router>
}
}
```
> fix: do not unescape / and other route characters when following a link

- examples/cargo-make/cargo-leptos-compress.toml
- examples/hackernews_islands_axum/Cargo.toml
- examples/hackernews_islands_axum/Makefile.toml
- examples/hackernews_islands_axum/README.md
- examples/hackernews_islands_axum/build-front.sh
- examples/hackernews_islands_axum/src/fallback.rs
- examples/hackernews_islands_axum/src/main.rs
One of the things I love about leptos is how easy it is to ship a small frontend. 
Leptos provides islands that reduce the amount of total HTML generated and it's build tool minifies CSS with `lightningcss`, soon will be minifying javascript with `swc`, and it can even precompress these static assets. That last of which I think may be the most important because web assembly compress fairly well and it allows the user to ship their entire app as 1 static binary (with musl). 
Since precompression was added as a feature in `cargo-leptos` I haven't seen it mentioned a whole lot so I wanted to help people see how to use it. I have also seen a couple question about setting up compression in general so I added that too.
I've updated the `hackernews_islands_axum` example to serve all static …
> feat: Add Compression to Hacker News w/ Islands Example

- leptos_hot_reload/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_macro/src/view/component_builder.rs
This PR adds a new `let()` syntax to components, while also keeping `let:` alive for backwards compatibility.
Example usage:
```rust
view! {
<For
each=move || data.get()
key=|n| *n
// stores the item in each row in a variable named `data`
let(data)
>
<p>{data}</p>
</For>
}
```
This also allows for destructuring of tuples and structs, as it's just directly embedded in the children function's arguments.
```rust
view! {
<For
each=move || data.get()
key=|n| *n
// stores the item in each row in a variable named `data`
let((tup1, tup2)) // note the extra parentheses for destructuring
>
<p>{tup1} {tup2}</p>
</For>
}
```
I haven't gone through all the examples and changed the usage as I wasn't sure what you wanted to present as the default. Would you like me to do that?
> Destructuring `let` (0.7)

- leptos/src/callback.rs
I suppose it's an oversight rather than an intentional change compared to v0.6?
> fix: impl `Copy` for `Callback`

- tachys/src/mathml/mod.rs
Although this attribute seems to be missing in the attribute table on [Mozilla Docs for that tag](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mo) ,
it does appear in the compatibility [table lower down](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mo#browser_compatibility).
This attribute is also frequently used by [temml](https://temml.org/), a common generator for MathML content.
**WARNING: I haven't set up a dev or test env**, and hoping this this can be picked up by somebody else as a quick fix if what I did was incorrect.
Mainly doing this to raise awareness of the issue.
> Add missing 'form' attribute for <mo> MathML element

- integrations/actix/Cargo.toml
- integrations/axum/Cargo.toml
- integrations/utils/Cargo.toml
- leptos/Cargo.toml
- leptos_config/Cargo.toml
- leptos_dom/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_reactive/Cargo.toml
- leptos_server/Cargo.toml
- meta/Cargo.toml
- router/Cargo.toml
- server_fn/Cargo.toml
- server_fn_macro/Cargo.toml
Need to make sure the CI passes for this but it should allow for links within the docs rs source code.
This was mentioned in discord a while back and I am just getting around to it.
Tried to get all of the major crates as putting this config in the workspace did not seem to work.
> docs: generate link to definition

- integrations/actix/src/lib.rs
- leptos_macro/src/lib.rs
- leptos_reactive/src/hydration.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/signal.rs
- meta/src/lib.rs
- router/src/components/router.rs
While running checks described in [CONTRIBUTING.md](https://github.com/leptos-rs/leptos/blob/main/CONTRIBUTING.md) I've noticed quite some warnings. Some of them reference to obsolete features, some of them origin in misspelling of attributes. Current PR addressed these issues
> Fixed several warnings in check pipeline

- integrations/axum/src/lib.rs
Hi im trying out leptos for SSR template rendering and saw in the new version LeptosOptions was no longer needed for routes generation.
Maybe this line should be removed o maybe it was left there on purpose 😄 and this should just be closed
> leptos 0.7: remove FromRef LeptosOptions in `LeptosRoutes` axum integration

- leptos_dom/src/macro_helpers/into_style.rs
The static lifetime is unnecessary for this argument. It isn't used within the function and only adds an unwarranted constraint. This prevents passing the argument as a regular string.
```rust
let style = Style::Value("foo".into());
// Ok
style.as_value_string("bar");
// Compilation error: borrowed value does not live long enough
let bar = "bar".to_string();
style.as_value_string(&bar); 
```
`as_value_string` signature
```rust
impl Style {
/// Converts the style to its HTML value at that moment so it can be rendered on the server.
pub fn as_value_string(
&self,
style_name: &'static str,
) -> Option<Oco<'static, str>> {
...
}
}
```
> Remove unnecessary 'static lifetime from argument in Style::as_value_string()

- leptos_macro/src/lib.rs
I was having this warning with clippy, im just copying this #1852
> `leptos 0.7` Add allow needless_lifetimes to components macro

- leptos_macro/src/view/client_builder.rs
- leptos_macro/src/view/component_builder.rs
- leptos_macro/src/view/server_template.rs
- leptos_macro/src/view/slot_helper.rs
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__client_template__full_span__counter_component.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__csr__full_span__counter_component.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__csr__full_span__simple_counter.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__ssr__full_span__counter_component.snap
Fixes #2527: DX regressions introduced by Rust Analyzer [2024-03-18 (v0.3.1885)](https://github.com/rust-lang/rust-analyzer/releases/tag/2024-03-18). Specifically:
- **Hover over items used inside view! macro** - fixed in this PR
- **Component's syntax highlighting** - fixed in r-a in recent updates
- **Go to definition** - fixed in r-a in recent updates
Related discussion on Rust Analyzer's Zulip: [t-compiler/rust-analyzer > Leptos macros](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/.E2.9C.94.20Leptos.20macros)
> fix: move lint rules outside of quote_spanned

- Cargo.toml
- router/Cargo.toml
- router/src/lib.rs
Seems like this is currently missing from the public API on v0.7.
I chose to re-export it through `leptos_router`, I am assuming it doesn't
have use outside of that crate. Please let me know if it is preferred to be
through the base `leptos` crate instead.
This macro was mentioned in the release docs for 0.7-beta
> fix: add `leptos_router_macro::path` to public api [`0.7`]

- leptos_reactive/src/memo.rs
- leptos_reactive/src/signal.rs
- leptos_reactive/src/signal_wrappers_read.rs
- server_fn_macro/src/lib.rs
The bulk of the changes, just add/subtrract two spaces as in 
```
-///   - [`.with_untracked()`](#impl-SignalWithUntracked<T>-for-Memo<T>) allows you to access the signal’s
+/// - [`.with_untracked()`](#impl-SignalWithUntracked<T>-for-Memo<T>) allows you to access the signal’s
```
A small number of changes come from running cargo fmt.
> Mnior: As of rust1.80: cargo clippy now reports doc indentation issues.

- reactive_graph/src/effect/effect.rs
- reactive_graph/tests/watch.rs
This PR provides a deprecated `watch` function, similar to `create_effect`. This should ease migration.
In order for `watch` to maintain the same signature as 0.6, `Effect` must be at least `Clone`. I provided both `Clone` _and_ `Copy`. Since the underlying type is always `Copy`, I think it makes sense to allow easy ergonomic access to `Effect::stop`, even if this may result in `stop` being called more than once. As noted [in this message](https://discord.com/channels/1031524867910148188/1263897766929764363/1269441434222592000), multiple calls to `stop` aren't a correctness problem; they're simply redundant.
I also provided a single test to ensure it runs properly. Since `watch` is a very light wrapper around `Effect::watch`, this can be argued to be redundant.
> Provide deprecated `watch` function

- tachys/src/reactive_graph/inner_html.rs
- tachys/src/reactive_graph/mod.rs
Fixed an issue where `data-count` and `inner_html` were not updated when count was updated. (Refer to https://github.com/leptos-rs/leptos/commit/309a3d504a7ad8e67a7649478bb6dd841d8fe2b0)
```rust
#[component]
pub fn Count() -> impl IntoView {
let count = RwSignal::new(1);
let on_click = move |_| {
count.update(|c| *c += 1);
};
view! {
<div>
<button on:click=on_click>"+ 1"</button>
{
move || {
if count.get() != 0 {
Either::Left(view!{<CountData data=count/>})
} else {
Either::Right(())
}
}
}
</div>
}
}
#[component]
pub fn CountData(#[prop(into)] data: MaybeSignal<i32>) -> impl IntoView {
view! {
<div data-count=move || data.get() inner_html=move || data.get().to_string()>
</div>
}
}
```
> fix: correctly rebuild reactive attributes to avoid stale signals

- tachys/src/reactive_graph/node_ref.rs
This PR provides a deprecated `create_node_ref` function as a part of #2771.
> Provide deprecated create_node_ref

- tachys/src/html/attribute/key.rs
- tachys/src/html/element/elements.rs
Addresses #2766.
This rounds out all attributes for `img` and `video` as defined [here for `img`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attributes) and [here for `video`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attributes).
> Complete `img` and `video` attributes set

- leptos/Cargo.toml
- reactive_graph/Cargo.toml
- tachys/Cargo.toml
This is a small thing, but I find without constant small PRs keeping the list of things reported by "cargo outdated" small ....
Well the thing blows up into a UGLY spaghetti monster which is impossible to unpick 
On this branch here is output of "cargo outdated"
On the target list for the next PR hmmm..   ahash, log, iter-tools, libc, bitflags , cfg-if
```
any_spawner
================
Name           Project  Compat  Latest   Kind    Platform
----           -------  ------  ------   ----    --------
gio-sys        0.19.8   ---     0.20.0   Normal  ---
glib           0.19.9   ---     0.20.0   Normal  ---
glib-macros    0.19.9   ---     0.20.0   Normal  ---
glib-sys       0.19.8   ---     0.20.0   Normal  ---
gobject-sys    0.19.8   ---     0.20.0   Normal  ---
proc-macro2    1.0.86   --- …
```
> Chore: cargo outdated, bump rustc-hash to version 2.0.0, no additional fixups

- .github/workflows/ci-semver.yml
Now that 0.7 is merged into the main branch, `cargo-semver-checks` is helpfully pointing out that everything is a breaking change relative to 0.6. This will just temporarily disable it until final release.
> chore(ci): temporarily disable semver checks

- reactive_graph/src/owner/stored_value.rs
`StoredValue::is_disposed` should return true when it has been removed from the arena.
> fix: correctly report whether a stored_value is disposed

- server_fn/src/codec/url.rs
`serde-qs` ["strict mode"](https://docs.rs/serde_qs/latest/serde_qs/struct.Config.html), which is enabled by default, doesn't accept URL-encoded `[` and `]` as part of field names, which the browser sends automatically. Disabling strict mode when deserializing allows complex structs to work when sent directly from the browser. `serde-qs` docs note that "Strict mode is more accurate for cases where it a field may contain square brackets" so there is a potential trade-off, but I am not sure exactly the cases in which this would apply.
> fix: support complex struct form submits without JS (closes #2790)

- router/src/link.rs
This started with the fix to setting of `aria-current="page"` for `href` that ends with a single trailing slash, such as `<A href="/item/">`, during navigation to it, and further testing found additional problems with the initial algorithm which was introduced in #1656 (which was a much appreciated starting point).  Work was done to refactor the `std::iter::zip` call into its own function and extended it to support the initial desired use-case, along with multi-level matching, and includes a decent number of test cases with a fairly exhaustive set of href/location combination (which lead to the discovery of the issue with multi-level matching).  There are some edge-case tests also, though given the nature of that less common interpretation I have not include the ability to allow the …
> fix: a more robust `aria-current="page"` algorithm for `A`

- examples/ssr_modes_axum/src/app.rs
- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
Include the note about blocking resource for both the actix and axum, and expanded the wording on the axum version.
Note that I did add a `FIXME` note to `leptos_axum::redirect` because I don't know how should this be properly addressed in the documentation (or the code for that matter).
I am open to suggestion to better wording, etc.
> doc: more details on how redirect works (#2789)

- Cargo.toml
```
warning: current MSRV (Minimum Supported Rust Version) is `1.75.0` but this item is stable since `1.76.0`
--> tachys/src/view/keyed.rs:574:14
|
574 |             .inspect(|(set_index, _)| set_index(*to));
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#incompatible_msrv
= note: `#[warn(clippy::incompatible_msrv)]` on by default
```
> fix: increase MSRV to 1.76

- reactive_graph/src/owner/stored_value.rs
- reactive_graph/src/signal/guards.rs
Includes examples for major `StoredValue` methods as well as a few proofreads and catches for spelling mistakes.
Please feel free to add any critiques.
> docs: `StoredValue` methods and examples for 0.7

- reactive_graph/src/computed.rs
- reactive_graph/src/effect.rs
- reactive_graph/src/signal.rs
Contributes to #2771. Adds:
- `create_owning_memo`
- `create_selector`
- `create_selector_with_fn`
- `create_render_effect`
- `create_trigger`
> feat: provide several deprecated functions

- reactive_graph/src/owner/stored_value.rs
I am not entirely familiar with `#[track_caller]`. But, I believe it is only inherited through traits in cases where the trait method is marked as such. [see here](https://rustc-dev-guide.rust-lang.org/backend/implicit-caller-location.html#traits).
I followed the same bounds as `StoredValue::new_with_storage`, please correct me if that is wrong
> feat: `StoredValue::default` implementation

- meta/src/lib.rs
- tachys/src/html/element/mod.rs
- tachys/src/view/mod.rs
- tachys/src/view/primitives.rs
- tachys/src/view/strings.rs
951f4a73eef8df1e444f446a9ff3bf8b383a51b3 was misguided, as temporarily unmounting a parent (as in the case of Suspense) should not unmount its children from that parent.
Rather than providing a default implementation for all container types, etc., it is much smarter simply to fix #2832 in a better way: a `Drop` implementation on `RegisteredMetaTagState` that unmounts the meta tags from the head, as they should be.
> Fix nested routing/related issues

- router/src/lib.rs
- router_macro/src/lib.rs
Provides documentation for `leptos_router_macro::path!` and a small example.
> docs: `leptos_router_macro::path`

- leptos_macro/src/view/component_builder.rs
- leptos_macro/src/view/mod.rs
- leptos_macro/src/view/slot_helper.rs
These changes hope to improve (I wish I could say fix, but I'm not entirely sure yet) the recent issues that the `view!` and `#[component]` macros had with providing incorrect / extra information through Rust-Analyzer.
In many instances, the procedural macros are spanning tokens with their own span redundantly, while also including lint attributes and unrelated tokens within their spanned interpolation.
I am **far** from an expert on procedural macros and token spans, while this seems to fix the issues on my editor, I just don't know enough to say if it actually fixes everything. From what I can tell, no diagnostic information is lost from these changes.
Additionally, I have no idea how to write a test for this. I am open to doing additional work to research and write tests if needed.
> fix: Rust-Analyzer hover information / redundant spans

- leptos_macro/src/view/client_builder.rs
- leptos_macro/src/view/component_builder.rs
- leptos_macro/src/view/mod.rs
- leptos_macro/src/view/server_template.rs
- leptos_macro/src/view/slot_helper.rs
These changes hope to achieve the same result as #2836 but for the current stable version.
Everything stated in that PR is also applicable here. This works on my machine but other people may need to chime in and say if anything doesn't look correct
All images taken using `rust-analyzer@2024-08-12`
Notice `on:click`
Correct hover information is provided for each individual section of `on:event` handlers as well.
> [0.6] fix: Rust-Analyzer hover information / redundant spans

- tachys/Cargo.toml
Closes [#2854](https://github.com/leptos-rs/leptos/issues/2854)
> Make any_spawner optional and dependent on the reactive_graph feature

- leptos_server/Cargo.toml
This shouldn't affect anything in Leptos at all. Just updateing so leptos-use has the same version
> updated codee version

- examples/server_fns_axum/Cargo.toml
- examples/server_fns_axum/src/app.rs
- server_fn/Cargo.toml
- server_fn/src/codec/mod.rs
- server_fn/src/codec/postcard.rs
According to the ser/de benchmarks on https://github.com/djkoloski/rust_serialization_benchmark, postcard should be almost as fast as rkyv, while being compatible with serde, which is very convenient.
Postcard also has a significantly smaller serialized size compared to rkyv.
I've implemented the codec in server_fn and it seems to be working well.
> Add support for postcard codec in server_fn

- tachys/src/html/element/elements.rs
I noticed some missing attributes on the `<source>` element, so I just added the ones listed on the [reference page on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source#srcset).
> Added attributes to <source> element

- tachys/src/html/element/mod.rs
Deriving `Clone` or `Copy` on `HtmlElement` is kind of useless because pretty much everytime you use HtmlElement the `Rndr` is `Dom`, which is not `Clone` or `Copy`. Because it is behind a `PhantomData` implementing `Clone` and `Copy` by hand makes it possible to use.
> implement Copy and Clone for HtmlElement without needing Rndr to be Clone/Copy

- leptos/Cargo.toml
- leptos/src/hydration/mod.rs
- meta/src/stylesheet.rs
This adds a `<HashedStylesheet />` component for inserting the `cargo-leptos` CSS hashed style sheet, and modifies `<HydrationScripts />` to insert the JS and CSS hashes into the file names.
> Add hash files support to 0.7

- Cargo.toml
- any_error/Cargo.toml
- hydration_context/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_server/src/resource.rs
- leptos_server/src/shared.rs
- meta/Cargo.toml
- next_tuple/Cargo.toml
- reactive_graph/Cargo.toml
- reactive_graph/src/owner/stored_value.rs
- reactive_stores/Cargo.toml
- reactive_stores_macro/Cargo.toml
- router/Cargo.toml
- router_macro/Cargo.toml
- tachys/Cargo.toml
In full hydration mode, you need to serialize all resources so they can be deserialized in the client. In partial hydration/islands mode, you only need to serialize a Resource if it was created in an island, because a Resource will either be:
1) created in an island, and therefore need its data when the island is being hydrated
2) created in a non-island, and therefore rendered to HTML on the server but without needing hydration, or
3) created in a non-island, and passed to an island -- but it will be passed either as props (and therefore serialized with props) or pass as part of the children (and therefore serialized as HTML)
This brings 0.7 in line with 0.6 by preventing the serialization of resources created outside islands, when you are in islands mode.
> fix: only serialize Resources if we're in a part of the tree that needs hydration

- leptos_macro/src/view/mod.rs
This automatically transforms any set of > 16 children into multiple tuples of max 16 items, which should avoid any problems due to the fact that rendering and routing traits are only implemented on tuples of up to some N (16, 26, whatever), at least when you are using the view macro.
> fix: automatically break children into tuples of a size the trait system can handle (closes #2863)

- hydration_context/src/ssr.rs
- leptos_server/Cargo.toml
- leptos_server/src/local_resource.rs
- reactive_graph/src/computed/async_derived/arc_async_derived.rs
- reactive_graph/src/computed/async_derived/async_derived.rs
- reactive_graph/src/signal/guards.rs
See #2920. This was an interesting bug. 
Basically, each resource and each Suspense/Transition gets a unique ID, which is created just by incrementing a counter in the shared context.
However, there is an issue when you have code that runs on the server (incrementing that counter) but not on the client (where it doesn't increment the counter). In this case, it caused the server-only Transition used by ProtectedParentRoute to take the ID 1, so it went 0 (resource), 1 (Transition), 2 (resource), while the client did not run the ProtectedParentRoute because it was not an island, so it went 0 (resource), 1 (resource). It did not find a serialized resource for 1, so loaded the resource again, but it thought the value hadn't loaded yet, so attempted to hydrate as if it was not there, hence the …
> fix: ensure stability of hydration IDs on client and server, when using partial hydration (closes #2920)

- leptos/src/hydration/hydration_script.js
- leptos/src/hydration/island_script.js
- leptos/src/hydration/mod.rs
- meta/src/stylesheet.rs
This enables setting a root for a url, especially relating to generated .wasm, .js, and .css files.
This allows using a CDN for static assets by virtue of being able to pass in an https:// root.
```rust
pub fn shell(options: LeptosOptions) -> impl IntoView {
let root = std::env::var("CDN_PATH").unwrap();
view! {
<!DOCTYPE html>
<html lang="en">
<head>
<HydrationScripts options=options.clone() root=root.clone() islands=true/>
<HashedStylesheet options=options root=root />
</head>
<body>
<App/>
</body>
</html>
}
}
```
> Enable CDN support for assets

- leptos_macro/Cargo.toml
- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
- leptos_macro/src/view/client_builder.rs
- leptos_macro/src/view/client_template.rs
- leptos_macro/src/view/ide_helper.rs
- leptos_macro/src/view/mod.rs
- leptos_macro/src/view/server_template.rs
- leptos_macro/src/view/slot_helper.rs
`proc-macro-error` is unmaintained according to https://github.com/rustsec/advisory-db/pull/2057, and one of my CI checks failed on this.
I attempted to fix the tests, but they're failing on `leptos_0.6`, and since 0.7 isn't too far away 🤞 I didn't think it's too important to spend effort here.
> leptos 0.6: Switch to `proc-macro-error2` to address unmaintained security advisory.

- leptos_macro/Cargo.toml
- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
- leptos_macro/src/view/mod.rs
- leptos_macro/src/view/slot_helper.rs
`proc-macro-error` is unmaintained according to https://github.com/rustsec/advisory-db/pull/2057, and one of my CI checks failed on this.
> leptos 0.7: Switch to `proc-macro-error2` to address unmaintained security advisory.

- reactive_graph/src/computed/async_derived/arc_async_derived.rs
- reactive_graph/src/computed/async_derived/inner.rs
This restores an existing 0.6 feature, which is that resources are versioned to prevent race conditions between async work that resolves at different times.
It follows a simple rule: Each time the `async` block is run, it receives a unique version number. If the version number is no longer the highest version number, it does not set a new value or turn `loading` to `false`, nor does it notify subscribers.
This means that if you fire the same resource 5 times in quick succession, it will still be `loading` until the last one resolves, and the value set will be the value of the 5th call, even if (for example) these are HTTP requests, and the 3rd one *happens* to be so slow that it returns after the 5th.
Not a new feature, just bringing it up to snuff with 0.6 and hopefully implemented …
> feat: version Resources to avoid race conditions

- .github/workflows/get-leptos-changed.yml
- tachys/src/reactive_graph/class.rs
- tachys/src/reactive_graph/mod.rs
- tachys/src/reactive_graph/style.rs
- tachys/src/reactive_graph/suspense.rs
Still needs cancellation implementation.
> fix: do not retrigger parent effect when Suspend's resources resolve (closes #2956)

- reactive_graph/src/signal/subscriber_traits.rs
Currently when `unwrap_signal!` is called inside `ToAnySource::to_any_source` the message is:
```
thread 'tokio-runtime-worker' panicked at C:\Users\bapti\.cargo\registry\src\index.crates.io-6f17d22bba15001f\reactive_graph-0.1.0-beta5\src\signal\subscriber_traits.rs:108:29:
At C:\Users\bapti\.cargo\registry\src\index.crates.io-6f17d22bba15001f\reactive_graph-0.1.0-beta5\src\signal\subscriber_traits.rs:108:29, you tried to access a reactive value which was defined at C:\Users\bapti\Documents\Code\Rust\hex-chess\leptos_i18n\leptos_i18n\src\context.rs:121:25, but it has already been disposed.
```
the "At {location}, you tried ..." location is not very helpfull, adding `#[track_caller]` to the function provide a better hint to where the bug is.
> Added `#[track_caller]`  to `to_any_source`

- router/src/matching/horizontal/param_segments.rs
- router/src/matching/horizontal/static_segment.rs
Adds documentation to the router path segments. Open to feedback if this is the correct way to structure the examples.
I am not super familiar with 0.7 yet, so please let me know if I am missing the mark anywhere
> doc: `router::{Wildcard, Static, Param}Segment`

- leptos_macro/src/component.rs
> fix: allow component to use span prop when tracing feature is enabled

- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
I think this is kind of a ridiculous solution, but unfortunately most of the useful methods on `Span` are nightly-only, and it is otherwise pretty hard to distinguish between proc-macro invocations.
We *can't* do the same thing here that we do with server fn macros and use a compile-time hash of the file, line number, etc. because `wasm-bindgen` requires a literal and won't accept this expanded macro.
> fix: stable hashes across different client and server builds for islands (closes #2978)

- router/src/matching/mod.rs
`PartialPathMatch` has only one use, be used with `PossibleRouteMatch::test`, where everything is used around the `'a` lifetime, but `remaining` and `matched` being private you need to use the accessors, but they are `fn(&self) -> &str`, so the lifetime is not tied to `'a` but tied to the struct iself. This makes `*Segment::test` unsable in a public API as the result can't be used.
This PR only change the lifetime of the returned str of the accessors to match the `'a` lifetime.
> fixed lifetimes for `PartialPathMatch`

- examples/js-framework-benchmark/src/lib.rs
- leptos_macro/src/lib.rs
- leptos_macro/src/view/component_builder.rs
- leptos_macro/src/view/mod.rs
- leptos_macro/src/view/slot_helper.rs
- tachys/src/html/mod.rs
- tachys/src/renderer/dom.rs
- tachys/src/renderer/mock_dom.rs
- tachys/src/renderer/mod.rs
- tachys/src/renderer/sledgehammer.rs
One of the main architectural shifts between Leptos 0.1-0.6 and 0.7 is the shift from a type-erased `View` enum to a fully-typed view tree. This enables the compiler to generate much more efficient code, because it knows (for example) that `move || something.get().to_string()` can *only ever* generate `String` text nodes, and never any other kind of view: so it does not need to emit code to handle swapping one branch of the old `View` enum for another. This has led to significant binary-size reductions on the order of 20-30% in many example applications.
On the other hand, creating deeply-nested generic types seems to have catastrophic effects on compile times. In particular, representing a big tree of static HTML with many nested components as a tree of `HtmlElement<El, Attributes, …
> Optimize inert HTML elements

- router/src/static_routes.rs
I'm not sure if this was intended behaviour but I was trying to use leptos as Static site generator, so main with something like
```rust
#[tokio::main]
async fn main() {
let conf = get_configuration(None).unwrap();
let addr = conf.leptos_options.site_addr;
let leptos_options = conf.leptos_options;
let (_, static_routes) = generate_route_list_with_ssg({
let leptos_options = leptos_options.clone();
move || shell(leptos_options.clone())
});
static_routes.generate(&leptos_options).await;
}
```
this didn't worked but if I added a `tokio::sleep` for a few seconds before exiting it worked, which is not how I think should be the default behaviour.
I noticed the oneshot send was being called before writer was called and so it was not being awaited in sync, this moves tx.send after writer. Now …
> StaticRouteGenerator's generate wait for initial fs write

- tachys/src/html/element/custom.rs
- tachys/src/html/element/elements.rs
- tachys/src/html/element/mod.rs
- tachys/src/mathml/mod.rs
- tachys/src/svg/mod.rs
- tachys/src/view/add_attr.rs
- tachys/src/view/mod.rs
This branch included some work intended to begin addressing #2971, which was fixed separately by the work in #2989. 
`BoxedView<T>` may be useful in some cases anyway, and the removal of unused debugging fields is probably useful as well.
> Changes related to stack overflows

- benchmarks/Cargo.toml
- benchmarks/src/ssr.rs
- benchmarks/src/todomvc/tera.rs
- examples/counter_isomorphic/Cargo.toml
- examples/counter_isomorphic/src/counters.rs
- examples/hackernews_islands_axum/Cargo.toml
- examples/ssr_modes/Cargo.toml
- examples/ssr_modes/src/app.rs
- examples/ssr_modes_axum/Cargo.toml
- examples/ssr_modes_axum/src/app.rs
> MSRV Bump to 1.80.0, drop crate lazy_static and use std::sync::LazyLock.

- either_of/src/lib.rs
While porting some code from 0.6 to 0.7 beta I had a few occurences of this pattern:
```rust
match error {
Some(error) => {
view! {
// view with custom component A
}
}
None => {
view! {
// view with custom component B
}
}
}
```
which in 0.7.0 returns an error due to the type mismatch.
I know it can be resolved by adding `.into_any()` to erase the types, but sometimes you want to keep the types so I figured why not add a macro to help with the creation of the Either types.
For now only up to `EitherOf6` is implemented, adding more is trivial.
I've also changed some usages in the leptos crate, but they are not necessary
> feat: add either macro

- reactive_stores/src/arc_field.rs
- reactive_stores/src/field.rs
- reactive_stores/src/iter.rs
- reactive_stores/src/keyed.rs
- reactive_stores/src/lib.rs
- reactive_stores/src/patch.rs
- reactive_stores/src/store_field.rs
- reactive_stores/src/subfield.rs
The current implementation has some issues when trying to manage 
a) triggering parents when a child changes, and
b) triggering children when a parent changes, without
c) triggering siblings (because child changed > triggers parent > triggers all other children)
Separating this out into two separate sets of triggers, one for "notify me and my parents" and one for "notify me and my children," seems to get the test cases into the correct shape. (Demo app also continues to work fine.)
> Fix stores

- reactive_stores_macro/Cargo.toml
- reactive_stores_macro/src/lib.rs
- router_macro/Cargo.toml
- router_macro/src/lib.rs
I ran cargo-audit on a project of mine that uses Leptos and got a warning that Leptos is using an unmaintained library: `proc-macro-error`. This PR replaces it with `proc-macro-error2`, a drop-in replacement. Interestingly, `leptos-macro` is already using the newer library.
> Replace proc-macro-error with proc-macro-error2

- reactive_graph/src/computed/arc_memo.rs
- reactive_graph/src/computed/memo.rs
This MR removes certain `PartialEq` bounds which are not required when creating a new Memo
> remove unnecessary `PartialEq` trait bounds

- leptos_dom/src/lib.rs
- oco/src/lib.rs
0.7 will be much harder to work with Rc, so this adds the Arc support in 0.6 to make it possible to transition away from Rc before taking the already-large step to 0.7.
> Implement `IntoView` for `Arc<str>`

- router/src/hooks.rs
- router/src/params.rs
> make ParamsMap have multiple values per key

- leptos_macro/src/view/mod.rs
- tachys/src/html/attribute/value.rs
- tachys/src/html/element/mod.rs
- tachys/src/lib.rs
- tachys/src/view/mod.rs
One of the nice things about 0.6 was that you could implement `IntoView` on arbitrary types pretty easily, by just declaring how they created a type-erased `View`. 0.7 makes this harder by requiring additional method boilerplate. This PR restores a similar functionality by allowing you to implement an `IntoRender` trait on arbitrary types that consists of a single method converting them into an output type, which can either be explicitly named or `AnyView`.
`IntoRender` is blanket implemented for any type that already implements `Render`.
The `view` macro will automatically insert `.into_render()` on all blocks (`{ ... }`) that are in the view. This is because, elements, components, and text nodes already have defined behaviors that we know don't need custom implementations; the only way …
> feat: add `IntoRender` for rendering custom data

- reactive_graph/tests/cleanup.rs
This adds the regression tests for disposal that were added in #2639, porting them over from `leptos_reactive` 0.6 to `reactive_graph`. Unless I'm mistaken and have missed running some test combo that CI will catch, these are already passing, which is encouraging.
> chore: re-add regression tests from #2639

- examples/router/src/lib.rs
- leptos/Cargo.toml
- leptos/src/await_.rs
- leptos/src/provider.rs
- leptos/tests/ssr.rs
- leptos_macro/Cargo.toml
- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
- leptos_macro/tests/ui.rs
- router/src/components.rs
- tachys/src/html/attribute/any_attribute.rs
- tachys/src/view/any_view.rs
Related to #2902. There is a genuine trade-off between compile time and WASM binary size: there seems to be some exponential compile time growth (and occasional recursion limits!) as we build a larger and larger statically-typed view tree, but it does allow the compiler to eliminate unused code much more effectively.
**`hackernews`**
`cargo build --timings --features=ssr`: 19.67s (main) => 6.65s (branch)
WASM size: 544kb (main) => 583kb (branch)
**`todo_app_sqlite_axum`**
`cargo build --timings --features=ssr`: 5.74s (main) => 2.62s (branch)
WASM size: 535kb (main) => 566kb (branch)
> test: does erasing types of components improve compile times?

- leptos/Cargo.toml
We regularly need to update `cargo-leptos` to match `wasm-bindgen` version updates, as they declare their format incompatible between patch releases.
Unfortunately they also made breaking changes to `wasm-bindgen-cli-support` in 0.2.94 such that `cargo-leptos` no longer compiles, which means it will take us longer to update `cargo-leptos` than usual.
This means all our examples won't compile (because they pull in 0.2.94), and user code won't unless they pin to `=0.2.93`. For now, I'm going to try pinning to `=0.2.93` in `leptos` itself in the hope this will resolve that.
I opened an issue on `wasm-bindgen` but I don't anticipate particularly swift action there. I suspect we'll just need to deopt what cargo-leptos does there a bit and make a new release. …
> chore: pin wasm-bindgen to 0.2.93 (does this fix example builds?)

- integrations/axum/Cargo.toml
- integrations/axum/src/lib.rs
- router/Cargo.toml
In the process of preparing for 0.7 (atleast for leptos_axum), some dependencies were added but unnecessary as axum re-exports them.
> remove unused dependencies leptos_axum and leptos_router

- leptos_macro/src/params.rs
Hello!
Just encountered this bug and decided to quickly fix it. Currently it fails if you define your own `Result` alias without second generic.
- Should I also create a backport PR for branch with stable release?
- Should I bump version somewhere?
> Use full path to Result in Params derive

- reactive_graph/src/serde.rs
- reactive_graph/src/signal/guards.rs
- reactive_graph/src/traits.rs
- reactive_graph/src/wrappers.rs
- tachys/src/reactive_graph/node_ref.rs
#3031 continuation, allow overriding the auto implemented `Read::try_read` implementation from the `ReadUntracked` trait. 
Doing so in this way means the normal `Track` trait can be used, and the double-clone fix propagates automatically to `MaybeSignal`, `MaybeProp` and any user created trait derivations involving the `Signal` wrapper.
> Use the `Track` trait for the `Signal` wrapper.

- leptos_macro/src/lib.rs
See #1966 for original PR on older version.
This was held off as a breaking change. The breaking change is now acceptable prior to 0.7 release
> fix: remove unused `Params` attribute `params`

- integrations/axum/src/lib.rs
I'm not sure if this is the right branch to merge, but this applies to Leptos `v0.6.15` and not the latest `main` branch for `v0.7-...`.
When using a custom leptos route handler (`render_route_with_context`), I noticed that traces where not being propagated if using `SsrMode::Async`. The other `SsrMode`s work correctly.
My handler:
```rust
#[tracing::instrument(skip_all)]
async fn leptos_routes_handler_protected(
auth_session: AuthSession,
read_session: ReadSession,
State(app_state): State<AppState>,
request: Request<Body>,
) -> axum::response::Response {
let handler = leptos_axum::render_route_with_context(
app_state.leptos_options.clone(),
app_state.routes.clone(),
move || {
provide_context(auth_session.clone());
provide_context(read_session.clone());
provide_context(app_state.clone()); …
```
> Add missing tracing span when using `render_route_with_context` for `SsrMode::Async` on Leptos 0.6.15

- leptos/Cargo.toml
- tachys/Cargo.toml
- tachys/src/reactive_graph/bind.rs
This add support for directly using `Store` fields with the new two-way `bind:` for elements.
Needed only to `impl IntoSplitSignal` for `Subfield`, also added a impl for `KeyedSubfield` but don't know the utility yet.
Tested with `Subfield`
```rust
use reactive_stores::{Field, Patch, Store};
use serde::{Deserialize, Serialize};
#[derive(Debug, Store, Patch, Serialize, Deserialize, Clone)]
struct User {
name: String,
email: String,
}
let user = Store::new(User {
name: "John Doe".to_string(),
email: "john.doe@example.com".to_string(),
});
view! {
<input type="text" bind:value=user.name() />
<span>{move || user.name().get()}</span>
}
```
I had to add `reactive_stores` as a feature of `tachys` in the leptos Cargo.toml, not sure if that's a good approach, as leptos crate doesn't depend on the …
> feat: add two-way data binding support for stores

- examples/router/index.html
- examples/router/src/lib.rs
- examples/router/style.css
- router/src/components.rs
- router/src/flat_router.rs
- router/src/hooks.rs
- router/src/lib.rs
- router/src/location/history.rs
- router/src/location/mod.rs
- router/src/matching/mod.rs
- router/src/nested_router.rs
The current router includes `AnimatedRoutes` and `AnimatedOutlet` components, which allow for animating route transitions. These were quite tricky to implement on my part, buggy in hard-to-resolve ways (#1754, #2058), and don't work as well with the new model in 0.7 because they relied on cloning the view and keeping two copies of it around in memory during the transition.
This is very similar to how the native View Transition API works. This API has stabilized fairly view and is being adopted by a number of frameworks. It [can be polyfilled](https://github.com/demarketed/view-transitions-polyfill) to support browsers that do not support it themselves. Using a feature that has browser support allows us to have faster compile times, smaller WASM binary sizes, and reduces the overall …
> (wip) feat: use View Transition API for router animations

- examples/hackernews/src/routes/nav.rs
- examples/hackernews/src/routes/stories.rs
- examples/hackernews/src/routes/story.rs
- examples/hackernews/src/routes/users.rs
- router/src/flat_router.rs
- router/src/matching/choose_view.rs
- router/src/matching/mod.rs
- router/src/matching/nested/mod.rs
- router/src/matching/nested/tuples.rs
- router/src/static_routes.rs
This erases view types throughout the router by using `AnyView`.
It was initially an experiment with compile times, but also happens to fix #3093 so that's good. As with other issues with statically typed view trees, that is (generally speaking) caused by reducing the "depth" and/or "breadth" of the type for any given type. The example in #3093 has a few dozen pages, each of which was (previously) represented as returning some type `A` (`B`, `C`, etc). Snipping each of these concrete types out so that they become `AnyView` instead reduces the "depth" of the type tree significantly.
There is some cost in terms of binary size (and a minor runtime cost) to doing this. However, automatically doing it for routes makes a reasonable amount of sense.
The binary size cost for `AnyView` in general …
> Use type erasure in router 

- router/src/components/router.rs
simple change here to make history updates atomic. 
this is especially useful when doing navigation based on state. e.g.:
```
let hash_memo = use_location().hash;
let state_signal = use_location().state;
let location_signal = create_memo(move |_| {
let hash = hash_memo.get();
let state = state_signal.get()
let path = todo!(); // some processing
(path)
});
```
making the nav updates atomic ensures that this memo doesn't get updated twice for a single navigation event
> batch navigation updates

- examples/tailwind_actix/end2end/tests/example.spec.ts
- examples/tailwind_actix/src/app.rs
- examples/tailwind_actix/tailwind.config.js
- examples/tailwind_axum/end2end/tests/example.spec.ts
- examples/tailwind_axum/src/app.rs
- examples/tailwind_axum/tailwind.config.js
- examples/tailwind_csr/end2end/tests/example.spec.ts
- examples/tailwind_csr/src/app.rs
- examples/tailwind_csr/tailwind.config.js
The previous tailwind config did not catch classes that are set dynamically, e.g.
```
use leptos::*;
fn main() {
mount_to_body(|| {
view! { <p
class:text-orange-600=true
>"This text should be orange"</p> }
})
}
```
would not add `text-orange-600`.
The tailwind config now uses the `content.transform` property to [transform](https://tailwindcss.com/docs/content-configuration#transforming-source-files) the leptos code enough for tailwind to extract all classes. Furthermore, there is now a button in all tailwind examples with a dynamic class.
Fixes https://github.com/leptos-rs/leptos/issues/2890
> improve tailwind config to also catch dynamic classes

- hydration_context/src/lib.rs
- hydration_context/src/ssr.rs
My usecase was needing to test behaviour of resources when hydrating, these changes allowed me to create a mock hydrate context downstream and use on non-wasm targets.
> Expose innards of SerializedDataId and SsrSharedContext to allow creating custom hydration contexts

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- server_fn/src/lib.rs
@benwis I had a slightly different idea on how to implement this, without any type signature changes, by simply creating a separate "excluded route" category in the generated route list, and then checking against that. Could you test it out for me?
> fix: exclude excluded server fn paths instead of unregistering them (closes #3150, #3175)

- leptos/Cargo.toml
Leptos can't be installed alongside another crate that uses a newer `wasm-bindgen` version. For example:
```
error: failed to select a version for `wasm-bindgen`.
... required by package `web-sys v0.3.72`
... which satisfies dependency `web-sys = "^0.3.72"` of package `crate-c v0.0.1`
... which satisfies dependency `crate-c` of package `crate-b v0.0.1`
versions that meet the requirements `^0.2.95` are: 0.2.95
all possible versions conflict with previously selected packages.
previously selected package `wasm-bindgen v0.2.93`
... which satisfies dependency `wasm-bindgen = "=0.2.93"` of package `leptos v0.7.0-rc0`
... which satisfies dependency `leptos = "^0.7.0-rc0"` (locked to 0.7.0-rc0) of package `crate-a v0.0.1`
failed to select a version for `wasm-bindgen` which could resolve this …
```
> Unpin `wasm-bindgen` to improve compatibility with other crates

- leptos/Cargo.toml
Hi folks! Creating this PR to add the `futures-executor` feature to any_spawner, which is needed for leptos-wasi integrations [(example)](https://github.com/ogghead/leptos-wasi-test/blob/main/src/server.rs#L17) to call `Executor::init_local_custom_executor` without pulling that crate in directly. This allows using `leptos::task::Executor` for the same
> Add futures-executor feature for any_spawner

- .github/workflows/run-cargo-make-task.yml
Related: https://github.com/leptos-rs/leptos/pull/3204
Credit: https://github.com/actions/runner-images/issues/10386#issuecomment-2271613335
> fix: make free space for ci workflows before running them

- integrations/utils/src/lib.rs
Same as #3219 but for Leptos 0.6
Feel free to close if you don't want to bother backporting this. I just was using it so thought I'd share. I do plan on upgrading to 0.7 when I can.
> Fix deprecated parameters js warning (0.6)

- integrations/axum/src/lib.rs
The method `build_static_routes` is no longer used or needed.
> remove obsolete build_static_routes

- leptos/src/hydration/hydration_script.js
Fixes the browser js console warning when running Leptos apps: 
> using deprecated parameters for the initialization function; pass a single object instead
I figured it out by following the link in the wasm-bindgen changelog entry:
> Deprecated parameters to default (init) and initSync in favor of an object. https://github.com/rustwasm/wasm-bindgen/pull/3995
Which told me it was our calling of the default function that was changed/deprecated, and I looked at the changed examples to see how it should be now be called with an object like `{module_or_path: path}` here: 
https://github.com/daxpedda/wasm-bindgen/blob/152dcf22f241d0245cccd97e5d1bd3286ebc5514/examples/websockets/index.js#L4
I tested it with the hackernews_axum example and the warning no longer showed up with this change.
> Fix deprecated parameters js warning

- router/src/static_routes.rs
As far as I can tell, both #3224 and #3226 are really the same problem, caused by the fact that the static path expansion algorithm was accidentally expanding `(StaticSegment(""), StaticSegment("post"), ParamSegment("slug"), StaticSegment("/"))` into routes like `//post/1/` instead of `/post/1/`.
> Fix static routing example

- projects/sso_auth_axum/migrations/20231217000000_create_tables.sql
- projects/sso_auth_axum/src/lib.rs
- projects/sso_auth_axum/src/main.rs
I noticed that the example was not working because the migration could not run:
```
sqlite> CREATE TABLE IF NOT EXISTS google_tokens (
(x1...>   id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
(x1...>   user_id INTEGER NOT NULL UNIQUE,
(x1...>   access_secret TEXT NOT NULL,
(x1...>   refresh_secret TEXT NOT NULL,
(x1...>   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
(x1...>   FOREIGN KEY (user_id) REFERENCES users(id) CONFLICT REPLACE
(x1...> );
Parse error: near "CONFLICT": syntax error
AMP,   FOREIGN KEY (user_id) REFERENCES users(id) CONFLICT REPLACE );
error here ---^
sqlite> 
```
Moving that conflict resolution to the insert query seems to work fine.
> fix: migration syntax and insert query

- examples/suspense_tests/e2e/features/check_aria_current.feature
- examples/suspense_tests/e2e/tests/fixtures/check.rs
- examples/suspense_tests/e2e/tests/fixtures/find.rs
- examples/suspense_tests/e2e/tests/fixtures/world/check_steps.rs
This provide the basic fixtures to check for `aria-current` for links, plus a basic test case to show that it works - can easily be modified to use non-highlighted link to trigger text failure.
This may be merged separately via this pull request or be part of the bigger pull request that includes the fix plus tests.  Navigating around `suspense_test` will demonstrate the particular issue as reported in #3196 so this was as good place as any to set this up.
> test: fixtures for testing aria-current

- examples/suspense_tests/e2e/features/check_aria_current.feature
- examples/suspense_tests/e2e/tests/fixtures/check.rs
- examples/suspense_tests/e2e/tests/fixtures/world/check_steps.rs
- router/src/matching/mod.rs
End-to-end tests for #3213.
Edit: Not sure why the autofix.ci decided to kick in here but that CI setup probably should be done with the original pull request that introduce this to have a clean slate for this pull request to apply to.
> test: aria-current end-to-end tests (#3213)

- tachys/src/html/element/custom.rs
- tachys/src/html/element/elements.rs
- tachys/src/html/element/mod.rs
- tachys/src/hydration.rs
- tachys/src/mathml/mod.rs
- tachys/src/svg/mod.rs
- tachys/src/view/primitives.rs
- tachys/src/view/strings.rs
Error messages in the case of hydration problems are currently very unhelpful in 0.7, as I had not yet done anything to make them more useful. For example, if the renderer was expected to find an element and found something else instead, you just got an `.unwrap()` inside `HtmlElement::hydrate()`.
This adds some debugging machinery that attempts to do the following:
1. Provide a useful error message.
2. List the location of the `view!` or element that is currently being hydrated, to help narrow down problems.
3. Logs out the unexpected node as part of the error message in the JS console. Most browser devtools allow you to right-click and go to where that node is used in the page, which means you can navigate directly to wherever in your application the unexpected node was found.
> docs: adds more helpful text for hydration errors (closes #3267)

- Cargo.lock
- Cargo.toml
- any_spawner/Cargo.toml
- leptos/src/lib.rs
This PR proposes a couple options (not mutually exclusive) for how to version new any_spawner functionality in downstream crates:
1. Create an rc2 version of any_spawner to align with leptos crate versions -- [leptos_wasi](https://github.com/leptos-rs/leptos_wasi) (and potentially others) rely on this crate and currently must use a locked git revision, [this comment has more details](https://github.com/leptos-rs/leptos_wasi/pull/9#issuecomment-2495546644)
2. Reexport CustomExecutor from any_spawner in Leptos -- this allows using the Executor and CustomExecutor directly from Leptos and eliminating any_spawner dependency in downstream crates
> Version any_spawner alongside other crates, reexport CustomExecutor

- leptos_macro/src/lib.rs
I stumbled over the help message of the `island` macro using `component` instead of `island`.
> Fix help message for island macro

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
The problem turned out to be specific to 0.7 Actix, which I did not expect.
This solution is what was proposed by @gbj in #3298, although I did not make the new code part of `extend_response` because `extend_response` is also [called in `handle_static_route`](https://github.com/leptos-rs/leptos/blob/d665dd4b89151e5d797df3db5cd2260cbe1e8fae/integrations/actix/src/lib.rs#L1285), and I don't think it needs this (maybe I'm wrong?).
I believe a better solution would actually be to match the Axum behavior, that uses [`http::HeaderMap::extend`](https://github.com/hyperium/http/blob/5a1a5e8ee54fc2e2f274faf318d9a8b1129c386a/src/header/map.rs#L2081): For merging map A with map B, if map B contains a key that is present in A, all values with such key in A are removed and all values with that key in …
> fix: prevent multiple location headers on redirect (#3298)

- Cargo.lock
- server_fn_macro/src/lib.rs
Actix pins requests and responses to a single thread, allowing it to use a number of `!Send` types in its ecosystem. You need to be able to hold these across `.await` points.
Leptos server functions and resources want server functions to be `Send`.
The `#[server]` macro currently includes a workaround for Actix that automatically wraps a server fn body in `SendWrapper` in the trait implementation. However, it didn't do this in the dummy function body, with the result that this didn't actually work—it would work in the trait implementation but not the dummy function. (The dummy function only needs to exist for better rust-analyzer support.)
Test case:
```rust
#[server]
pub async fn list_post_metadata() -> Result<Vec<PostMetadata>, ServerFnError> {
// really these would be some Actix …
```
> fix: correctly support `!Send` Actix APIs in server functions

- reactive_graph/src/owner/arena.rs
- reactive_graph/src/wrappers.rs
Noticed the typo while following along with the book, and then got a rustdoc warning for the `ArenaItem` link. Figured that I might as well fix that too.
> Fix a doc typo and one broken intra-doc link

- server_fn/src/request/actix.rs
implement multipart for actix to address issues on this discussion #3358 
tested on my machine and it worked
```
Index: 0, Header: {"content-disposition": "form-data; name=\"images[]\"; filename=\"Typescript Enum.png\"", "content-type": "image/png"}, Name: "images[]"      
Index: 1, Header: {"content-disposition": "form-data; name=\"animal_name\""}, Name: "animal_name"
Index: 2, Header: {"content-disposition": "form-data; name=\"animal_status\""}, Name: "animal_status"
Index: 3, Header: {"content-disposition": "form-data; name=\"animal_type\""}, Name: "animal_type"
Index: 4, Header: {"content-disposition": "form-data; name=\"description\""}, Name: "description"
Index: 5, Header: {"content-disposition": "form-data; name=\"expected\""}, Name: "expected"
```
> feat : implemented actix multipart

- leptos/src/children.rs
TypedChildrenFn wraps `Arc<dyn Fn() -> View<T> + Send + Sync>`, but not derived with `Clone`, I think it is logical for a type based on `Arc`, and type `ViewFn` derived with Clone as well.
> TypedChildrenFn impl Clone trait

- reactive_stores/src/patch.rs
As part of [a larger discussion ](https://github.com/leptos-rs/leptos/discussions/3345) r.e. implementing `PatchField` for non-primative types, I noticed that the primative type `usize` is missing from the primative types that _do_ implement `PatchField`.
This PR is a one line change (made via GitHub, i.e. untested) that adds it to the list.
> fix: Implement PatchField for `usize`

- reactive_graph/src/owner/arc_stored_value.rs
- reactive_graph/src/owner/arena_item.rs
- reactive_graph/src/owner/storage.rs
- reactive_graph/src/owner/stored_value.rs
- reactive_graph/src/signal.rs
- reactive_graph/src/signal/arc_read.rs
- reactive_graph/src/signal/arc_rw.rs
- reactive_graph/src/signal/arc_write.rs
- reactive_graph/src/signal/read.rs
- reactive_graph/src/signal/rw.rs
- reactive_graph/src/signal/write.rs
- reactive_graph/src/traits.rs
- reactive_graph/tests/signal.rs
This implements `into_inner` the way it is implemented for `Arc`s. This fixes #3068 .
However, with the non-arc signals, the behaviour can be rather unintuitive. For example, the following does not succeed.
Why?
Because there's still the original `RwSignal` that was created inside the `signal` function. (`RwSignal::new(value).split()` creates 3 signals)
```rust
#[test]
fn into_inner_non_arc_signal() {
let owner = Owner::new();
owner.set();
let (a, b) = signal(2);
assert_eq!(a.get(), 2);
b.dispose(); // strong count is now 2
assert_eq!(a.into_inner(), Some(2)); // fails
}
```
I'm happy to document this, or to attempt a fix, or to remove the trait for normal signals.
> Implement signal.into_inner()

- tachys/src/reactive_graph/bind.rs
Adds `IntoSplitSignal` for `Field`. This allows us to use `bind:value=field` instead of `bind:value=(field, field)`.
Copying some similar trait bounds, so please take a look and see if they make sense.
Fixes https://github.com/leptos-rs/leptos/issues/3362
> Implement IntoSplitSignal for Field.

- leptos/src/for_loop.rs
I thought it would be a boon for DX to showcase the `let` syntax for the `<For>` component. 
I knew there were some improvements, but I erroneously tried the legacy `let:item` style to destructure my struct and had to go looking for docs. It was kind of hard to find so I thought I'd try to contribute :sweat_smile: Please, edit and adjust to your liking. 
I think this should close #3059 
See cousin PR for the book.
> docs: showcase let syntax in for_loop

- reactive_stores/src/keyed.rs
#3170 fixed the tracking of parent fields in children (and vice versa), including in keyed subfields (see #3169), but didn't correctly apply that change in the case of the `IntoIter` implementation (see #3401). This applies that same tracking mechanism there.
> fix: correctly track updates to keyed fields in keyed iterator (closes #3401)

- integrations/axum/src/lib.rs
The `file_and_error_handler` provided by leptos_axum does not provide the app's custom state in the context. This means that when the fallback handler tries to render the app, the app will not be able to access the custom state (and will panic if it uses `expect_context`).
The handler defined by `file_and_error_handler` has access to the custom state from Axum, so we can pass the custom state from Axum into the Leptos handler using the `additional_context` parameter of `handle_response_inner`.
I think this might technically be a semver breaking change because we're adding constraints to the `S` type parameter. However, I think it should be fine because any custom state used with this method would need to satisfy these constraints to be used in the first place (e.g., in the [LeptosRoutes …
> Provide custom state in `file_and_error_handler`

- leptos_macro/src/component.rs
- leptos_macro/tests/component.rs
- leptos_macro/tests/ui/component.rs
- leptos_macro/tests/ui/component.stderr
- leptos_macro/tests/ui/component_absolute.stderr
- server_fn/src/codec/json.rs
- server_fn/src/codec/stream.rs
Allows props to be destructured in the component definition e.g.
```rust
#[prop(name = "data")] UserInfo { email, user_id }: UserInfo,
```
for that to work a `name` attribute was introduced which is used to define the name of the prop in the generated builder.
> feat: allow to destructure props

- integrations/axum/src/lib.rs
[This feature no longer exists](https://github.com/leptos-rs/leptos/blob/7a5b27ad2081dbc751c21291ce2702a0e3915da6/integrations/axum/Cargo.toml#L36).
> docs: remove `islands` mention from `leptos_axum`

- reactive_graph/src/signal/guards.rs
I stumbled upon a bug while working on https://github.com/Synphonyte/leptos-struct-table.
Specifically these lines: https://github.com/Synphonyte/leptos-struct-table/blob/leptos-0.7/src/components/table_content.rs#L276-L279
```rust
if let Some(mut rows) = rows.try_write_value() {
rows.set_sorting(&sorting);
clear(false);
};
```
The `rows` is `StoredValue`.
The problem is `try_write_value()` works down to `UntrackedWriteGuard::try_new()`, which calls `ArcRwLockWriteGuardian::take`, which panics if it's impossible to get a write lock. But `try_write_value()` mustn't panic, it must return `None` instead.
Hence the fix.
> fix failure on try_new() methods which should not fail

- leptos/Cargo.toml
I suppose enabling `rkyv` feature on `leptos` crate should enable it on all dependencies. 
Otherwise `Resource::new_rkyv()` is not accessible without extra dependency juggling i.e. explicitly bringign in `leptos_server` with `rkyv` feature enabled.
> Rkyv feature should propagate properly

- router/src/components.rs
This change allows users to clone RouteChildren and call .into_inner() on it to get an owned version of \<Children\>, and then pass on the original RouteChildren to an underlying Routes, or ParentRoute component. This helps users snapshot all possible routes in an application.
> Derive clone for RouteChildren

- tachys/src/view/static_types.rs
> Implement AddAnyAttr trait for Static<V>

- leptos_dom/src/logging.rs
This unifies the code path by using the `cfg!` macro instead of `#[cfg]` attribute. The alternative will *move* arguments passed to the debug_warn! macro only when compiling without debug_assertions. This version will instead always use additional format arguments by reference.
A minimal test code the shows the avoided bug:
```rust
let foo = "foo".to_string(); // A value that is not copy
leptos::logging::debug_warn!("Message: {}", foo); // foo is passed as an additional argument
let _ = foo.len(); // A usage after logging
```
The above will complain about `foo` being moved in the unpatched code only when compiling with `not(debug_assertions)`, since in that case the macro expands to a tuple of the arguments which counts as a usage and moves `foo` (into the void, but still).
Further …
> Fix: values being moved with the debug_warn! macro when compiling with not(debug_assertions)

- leptos_dom/src/helpers.rs
Make it clear what is called outside the ownership tree to prevent other people from having the same issue I had with #3437.
> docs: warn about callbacks outside the ownership tree

- reactive_stores/src/lib.rs
- reactive_stores_macro/src/lib.rs
Adds a new `#[patch(|this, new| ...)]` derive helper for `Patch` that allows specifying an arbitrary patch.
> Add support for custom patch

- either_of/src/lib.rs
This is an idea that came out of [this](https://github.com/leptos-rs/leptos/issues/3378) feature request.
It adds an `EitherOr` trait providing a `either_or` method which can be used to "map" over `bool`, `Option` and `Result` types in a similar manner as e.g. [Option.map_or_else](https://doc.rust-lang.org/std/option/enum.Option.html#method.map_or_else).
With this there is yet another way to remove the need for `to_any` or to manually specify the Either::Left/Right:
e.g. 
```rust
if let Some(key) = phantom_wallet_adapter.get().public_key() {
view!{ ... }.into_any()
} else {
view!{ ... }.into_any()
}
```
could be then written as
```rust
phantom_wallet_adapter.get().public_key().either_or(|key| view!{ ... }, |_| view!{ ... });
```
> feat: either_or combinator

- leptos/src/callback.rs
PR aims to make the Callback types more consistent with the other stored types in leptos.
* Adds `try_run` to callable which (in line with other stored types) will return `None` if the callback had been disposed.
* Adds `impl Dispose` for both `Callback` and `UnsyncCallback`
Small detail regarding implementation:
The impl of `Callable::run` for `UnsyncCallback` and `Callback` was inconsistent. One used `try_with_value` with expect while the other was using `with_value`.
I chose to make them consistent and use `with_value` in both impls. I'm unsure if I chose the right option, perhaps try_with_value was preferable.
> impl Dispose for Callback types and add try_run to the Callable trait

- router/src/matching/horizontal/mod.rs
- router/src/matching/horizontal/param_segments.rs
- router/src/matching/horizontal/static_segment.rs
- router/src/matching/horizontal/tuples.rs
- router/src/matching/nested/mod.rs
This allows a pattern like this:
```rust
enum Page {
Home { f1: u8 },
Account(u8),
}
impl Page {
fn to_route(&self) -> Arc<dyn PossibleRouteMatch + Send + Sync> {
match self {
Self::Home { f1 } => {
Arc::new((StaticSegment("home"), ParamSegment("f1")))
}
Self::Account(acc) => {
Arc::new((StaticSegment("accounts"), ParamSegment("f1")))
}
}
}
}
```
> feat(breaking): allow make `PossibleRouteMatch` dyn-safe

- Cargo.lock
- leptos_macro/src/lazy.rs
- leptos_macro/src/lib.rs
- router_macro/Cargo.toml
- router_macro/src/lib.rs
For context and an example, see [my fork of `wasm-split-prototype`](https://github.com/gbj/wasm-split-prototype/blob/main/crates/example/src/lib.rs).
> feat: `#[lazy]` macros to support lazy loading and code splitting

- Cargo.lock
- reactive_stores/Cargo.toml
- reactive_stores/src/lib.rs
After building with Stores I found there we places the docs could be enhanced.  I took a stab at documenting the things that tripped me up. I also included some docs for the new support for Box.  Added docs on shadow traits, Option, Enum, Vec, and Box usage with Store.
I'm not sure if you have a particular way you want docs done, or even want this sort of detail.  I also realize you might want the docs in the Leptos Book - but I figured I'd start here and then get guidance from the maintainers.
> Enhanced docs for reactive_stores

- Cargo.lock
- leptos_server/Cargo.toml
This change happens on the back of https://github.com/leptos-rs/leptos/issues/3467
I've tried this locally, rkyv serialisation seems to work now. Leptos codebase compiles, but re-exports may break something else I am not aware of.
> issue-3467 - bumping codee version to support rkyv 8

- Cargo.lock
- leptos_macro/src/view/component_builder.rs
- tachys/Cargo.toml
- tachys/src/html/attribute/any_attribute.rs
- tachys/src/html/attribute/custom.rs
- tachys/src/html/attribute/maybe_next_attr_erasure_macros.rs
- tachys/src/html/attribute/mod.rs
- tachys/src/html/attribute/panic_on_clone_attribute.rs
- tachys/src/html/class.rs
- tachys/src/html/directive.rs
- tachys/src/html/element/custom.rs
- tachys/src/html/element/elements.rs
- tachys/src/html/element/inner_html.rs
- tachys/src/html/element/mod.rs
- tachys/src/html/event.rs
- tachys/src/html/node_ref.rs
- tachys/src/html/property.rs
- tachys/src/html/style.rs
- tachys/src/lib.rs
- tachys/src/mathml/mod.rs
- tachys/src/reactive_graph/bind.rs
- tachys/src/svg/mod.rs
- tachys/src/view/any_view.rs
cc #3156 #3458 #3460 #3461 #3476
TLDR: this PR enables `AddAnyAttr` on `AnyView` when the`--cfg erase_components` feature flag is enabled. Made possible by further type erasing tuples of attrs types to `Vec<AnyAttribute>` before they even became tuples preventing generation of an exponential number of types. `--cfg erase_components` is now feature complete and provides up to 1.5-3x faster compilation speed. Yay!
Unfortunately this means the issues surrounding `AddAnyAttr` and `AnyView` without type erasure are most likely not an issue with rust or the compiler, but too many unique attribute tuple types, monorphisation and codegen, but importantly this missing feature is actually what is making stable leptos compile, by trimming the potential for futher attr types at each `AnyView` …
> AddAnyAttr working with erase_components

- leptos/src/text_prop.rs
- reactive_stores/src/lib.rs
I noticed that I can't pass `TextProp`s directly to HTML elements as attributes. This seems like something it should be able to do, so I made `TextProp` impl `IntoAttributeValue`.
> impl IntoAttributeValue for TextProp

- reactive_graph/src/computed.rs
- reactive_graph/src/computed/arc_memo.rs
- reactive_graph/src/computed/inner.rs
- reactive_graph/src/computed/memo.rs
- reactive_graph/src/wrappers.rs
- reactive_graph/tests/memo.rs
For the issues with memos, I figured that it should be possible to run the change tracking logic *without* requiring a lock on the value itself. The lock on the value should only be necessary when one is actually updating the value.
Fix https://github.com/leptos-rs/leptos/issues/3252
I am not sure if this is a particularly good approach, but I figured it's better than having a potential bug.
> Fix memo recomputation

- leptos_macro/src/lib.rs
In theory this is a breaking change, because it emits an error where previously it emitted no error. However, it emits an error if there is a syntax error in a component, rather than simply emitting an empty token stream with no error. i.e., if this causes a new compile error your code was already broken.
> fix: emit syntax errors in components rather than swallowing them (closes #3535)

- tachys/src/view/either.rs
This implementation allows to define `HtmlElement<Tag, (Either<FooAttribute, BarAttribute>,), Children>` as the output of a fully-typed reusable component.
The current workaround of having to write `Either<HtmlElement<Tag, FooAttribute, Children>, HtmlElement<Tag, BarAttribute, Children>>`, besides being more verbose, also lacks an implementation of `ElementExt`.
> Implement `Attribute` for `Either<A, B>`

- tachys/src/view/either.rs
As mentioned in https://github.com/leptos-rs/leptos/issues/3556#issuecomment-2646165698 by @luxalpa, the changes I introduced in #3556 broke the `--cfg=erase_components` mode.
> Handle `erase_components` on `Either<A, B>`

- reactive_stores_macro/src/lib.rs
The error message did not correspond to the actual signature
> fix(reactive_stores_macro): `store` attribute signature error message

- leptos/src/attribute_interceptor.rs
- leptos/src/error_boundary.rs
- leptos/src/into_view.rs
- leptos/src/suspense_component.rs
- leptos_server/src/lib.rs
- meta/src/body.rs
- meta/src/html.rs
- meta/src/lib.rs
- meta/src/title.rs
- router/src/flat_router.rs
- router/src/nested_router.rs
- tachys/src/html/element/mod.rs
- tachys/src/html/islands.rs
- tachys/src/html/mod.rs
- tachys/src/oco.rs
- tachys/src/reactive_graph/mod.rs
- tachys/src/reactive_graph/owned.rs
- tachys/src/reactive_graph/suspense.rs
- tachys/src/view/any_view.rs
- tachys/src/view/either.rs
- tachys/src/view/error_boundary.rs
- tachys/src/view/iterators.rs
- tachys/src/view/keyed.rs
- tachys/src/view/mod.rs
- tachys/src/view/primitives.rs
- tachys/src/view/static_types.rs
- tachys/src/view/strings.rs
- tachys/src/view/template.rs
- tachys/src/view/tuples.rs
As discussed [here](https://github.com/leptos-rs/leptos/pull/3562#issuecomment-2646745564) this allows removing the static requirement from `IntoAny` to prevent compile errors on switching to erased mode.
> RenderHtml::into_owned

- reactive_graph/src/effect/render_effect.rs
- reactive_graph/src/owner.rs
- tachys/src/html/element/mod.rs
- tachys/src/reactive_graph/mod.rs
~Some free binary size optimisations after https://github.com/leptos-rs/leptos/pull/3553 (reduces impact from 8% to 4% on hackernews example)~
~Testing hackernews with `cargo +stable leptos build --release` then looking at `target/pkg/$name.wasm`:~
~Before https://github.com/leptos-rs/leptos/pull/3553: 577210~
~After [#3553 anyattr change](https://github.com/leptos-rs/leptos/pull/3553): 624529~
~This PR: 602081 599795~
Updated, some random optimisations I stumbled on whilst trying to reduce binary impact of https://github.com/leptos-rs/leptos/pull/3553
Testing hackernews with `cargo +stable leptos build --release` then looking at `target/pkg/$name.wasm`:~
Baseline: 597734
This PR: 589089
> Binary size wins

- tachys/src/html/element/elements.rs
https://html.spec.whatwg.org/#the-fieldset-element
> Add missing `<fieldset>` attributes

- leptos_macro/src/component.rs
- leptos_macro/tests/component.rs
> Allows non static lifetimes in component macro

- projects/bevy3d_ui/Cargo.toml
- projects/bevy3d_ui/src/main.rs
- projects/bevy3d_ui/src/routes/demo1.rs
- projects/bevy3d_ui/src/routes/mod.rs
I want to keep the bevy reference design up to date ... 
This is the first PR of 2. 
PR2 Will follow the bevy migration guide ( from 0.14 to 0.16 )
> projects/bevy3d_ui Migrate to leptos 0.7.7

- Cargo.lock
- leptos_config/Cargo.toml
Next PR in a series of housekeeping issues.
> Minor: leptos_config - Bump the "config" crate to version 0.15.8

- Cargo.lock
- Cargo.toml
- leptos_macro/Cargo.toml
- reactive_stores/Cargo.toml
- tachys/Cargo.toml
The crate is used by "leptos_macro","reactive_stores" and "tachys"
So the definition of itertools can be centralized up into the root workspace
PS 
Dependabot report 16 vunerabilities .. as a way to resolve this 
I am chippy away at the list provided by "cargo outdated" .. as a way to reasons with  those "potential" vunerabilities
> Minor: Bump itertools to "0.14.0"

- Cargo.lock
- leptos_macro/Cargo.toml
- reactive_stores_macro/Cargo.toml
Just doing a minor periodic spring clean
I want to keep the output of "cargo outdated" to a small set
> Minor: Bumped version of convert_case to 0.7

- Cargo.lock
- Cargo.toml
- any_spawner/Cargo.toml
- benchmarks/Cargo.toml
- hydration_context/Cargo.toml
- leptos/Cargo.toml
- leptos_dom/Cargo.toml
- leptos_server/Cargo.toml
- meta/Cargo.toml
- router/Cargo.toml
- server_fn/Cargo.toml
- server_fn_macro/src/lib.rs
- tachys/Cargo.toml
"This synchronizes the version number amongst all sub-projects. [Where the definition is "optional" manual adjustment is still required]"
Please forgive my paranoia
Upstream from here in my app I recently had some issues where a major change to the wasmbindgen crate was  being hidden in a "minor update".
With this PR, in all these core sub crates ( and more ), the version number is now in lock step.
leptos/Cargo.toml
leptos_dom/Cargo.toml
leptos_server/Cargo.toml
This is a defensive patch as any bugs due to differing version number brings up are a pain to resolve.
> Minor: "wasm-bindgen" - Moved the crate definition up to the root workspace

- .cargo/config.toml
- Cargo.lock
- leptos/Cargo.toml
This warning 
"warning: Feature js of package getrandom has been obsolete in version 0.3.1"
Now using the feature "wasm_js"
Just a small maintence nudge
> Remove getrandom

- integrations/actix/Cargo.toml
- integrations/axum/Cargo.toml
- leptos_config/Cargo.toml
- reactive_graph/Cargo.toml
- reactive_stores/Cargo.toml
- tachys/Cargo.toml
I should explain my motivation
Dependabot is reporting lots of warnings related to the mio crate 
When I run "cargo why mio"
There is a complex sprawling dependency list and one of the entry points for mio is tokio
The dependabot issue will not be fixed in a single issue... It seems to only valid repoonse is to keep tokio and 
some other crates on a tight update scedule.
> Minor: Bump tokio to 1.43.

- projects/bevy3d_ui/Cargo.toml
- projects/bevy3d_ui/src/demos/bevydemo1/eventqueue/plugin.rs
- projects/bevy3d_ui/src/demos/bevydemo1/scene.rs
- projects/bevy3d_ui/src/routes/demo1.rs
The bugfix is related to access to a signal
"
bevy3d_ui-b20a0a6a298e7144.js:2637 At src/routes/demo1.rs:24:23, you access a reactive_graph::signal::read::ReadSignal<bevy3d_ui::demos::bevydemo1::scene::Scene> (defined at src/routes/demo1.rs:19:39) outside a reactive tracking context. This might mean your app is not responding to changes in signal values in the way you expect. "
The solution is to use .get_untracked() inside an "effect" block.
Lots of small clippy fixes.
Also here are the crates that have been bumped
-wasm-bindgen = "0.2.92"
-wasm-bindgen-test = "0.3.42"
-web-sys = "0.3.69"
+wasm-bindgen = "0.2.100"
+wasm-bindgen-test = "0.3.50"
+web-sys = "0.3.77"
> projects/bevy3d_ui: Bevy - Bugfix, clippy and crate bump

- reactive_stores/src/option.rs
This PR adds a method called "transpose" to the OptionStoreExt which converts a subfield with an option into an option of a subfield. 
I found it useful in pattern matching while we want to keep the reactivity of the subfield.
> Add transpose to the OptionStoreExt

- README.md
I don't look at the landing page often ... but this goofy mistake made me chuckle.
> Minor: drop create_signal form the landing page.

- Cargo.toml
- integrations/actix/Cargo.toml
- leptos_server/Cargo.toml
- oco/Cargo.toml
- server_fn/Cargo.toml
serde_json is common to
integrations/actix
leptos/server
oco
server_fn
This is a defensive PR - Putting the crate definition into the root workspcace makes it less likely to get difficult to trace version slip bugs.
This does not help where sede_json is optional so care manual review is required.
> Put serde_json in the root workspace

- tachys/src/html/style.rs
- tachys/src/reactive_graph/style.rs
I don't know that I've tested every permutation of these trait implementations, but have tested the following, for example.
```rust
#[component]
fn HomePage() -> impl IntoView {
let count = RwSignal::new(0);
view! {
<button
on:click=move |_| *count.write() += 1
style:font-weight=move || (count.get() % 2 == 0).then_some("bold")
style:padding-top=move || format!("{}px", count.get())
style:text-decoration="underline"
style="color: red"
>
"Click"
</button>
}
}
```
> feat: support `Option<_>` in `style:` (closes #3568)

- Cargo.lock
- leptos_macro/src/view/component_builder.rs
- leptos_macro/src/view/mod.rs
- reactive_graph/src/computed/inner.rs
- router/Cargo.toml
- router/src/components.rs
- router/src/matching/any_choose_view.rs
- router/src/matching/choose_view.rs
- router/src/matching/mod.rs
- router/src/matching/nested/any_nested_match.rs
- router/src/matching/nested/any_nested_route.rs
- router/src/matching/nested/mod.rs
- router/src/matching/nested/tuples.rs
- tachys/Cargo.toml
- tachys/src/erased.rs
- tachys/src/html/attribute/any_attribute.rs
- tachys/src/lib.rs
- tachys/src/view/any_view.rs
- tachys/src/view/fragment.rs
- tachys/src/view/iterators.rs
- tachys/src/view/static_types.rs
There's a few things in here (sorry!), to sum up: 
- Routing is erased, most importantly this should (probably) solve any remaining compile errors in rust debug/dev builds
- The `view!{}` macro now erases thoroughly
- A few more hot codegen optimisations of existing logic in traits
- erased containers define their `fn()` functions with concrete `fn foo` declarations rather than closures, TIL this is more codegen efficient
- The [erased](https://docs.rs/erased/latest/erased/) crate is used as a replacement for `Box<dyn Any>` in erased containers, which is more efficient and (I think) avoids a massive `dyn Any` vtable
- `IntoFragment` contains `StaticVec` instead of a `Vec`
This shouldn't have any breaking changes.
> Erased routing, codegen opts

- leptos_server/src/local_resource.rs
- leptos_server/src/once_resource.rs
Adds the `map` and `and_then` functions found on `Resource` to `OnceResource` and `LocalResource`. Fixes #3646
> feat: map and and_then for resource variants

- examples/server_fns_axum/Cargo.toml
crates updated :- 
tower-http
tower
thiserror
strum
notify
server_fn_axum is a great resource, so I want to keep the dependencies upto date.
I want to isolate the axum changes in a PR I am currenlty writing ...
> Minor: examples/server_fns_axum - Bumped various packages (not axum).

- .github/workflows/ci-changed-examples.yml
- .github/workflows/ci-examples.yml
- .github/workflows/ci.yml
- .github/workflows/get-changed-examples-matrix.yml
- .github/workflows/get-examples-matrix.yml
- .github/workflows/get-leptos-matrix.yml
- .github/workflows/run-cargo-make-task.yml
- examples/fetch/src/lib.rs
- examples/js-framework-benchmark/src/lib.rs
- examples/router/src/lib.rs
- examples/spread/rust-toolchain.toml
- examples/suspense_tests/src/instrumented.rs
- integrations/axum/src/lib.rs
- leptos/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
- leptos_macro/src/view/component_builder.rs
- leptos_macro/src/view/mod.rs
- leptos_macro/src/view/slot_helper.rs
- leptos_macro/tests/ui.rs
- tachys/src/html/attribute/mod.rs
- tachys/src/html/element/mod.rs
- tachys/src/lib.rs
- tachys/src/view/either.rs
- tachys/src/view/iterators.rs
Add erase components as part of the test matrix, seems to work first try, although I am slightly surprised by that!
> Erased mode in CI

- any_error/src/lib.rs
- reactive_graph/src/owner.rs
- reactive_graph/src/transition.rs
all changes are of the form
```rust
-        ERROR_HOOK.with_borrow_mut(|this| mem::replace(this, Some(hook))),
+        ERROR_HOOK.with_borrow_mut(|this| Option::replace(this, hook)),
```
In this example there is no need to wrap "hook" as "Some(hook)".
> Minor: clippy - Replace mem::replace with Option::replace

- tachys/src/reactive_graph/bind.rs
- tachys/src/reactive_graph/inner_html.rs
- tachys/src/reactive_graph/mod.rs
- tachys/src/reactive_graph/property.rs
- tachys/src/reactive_graph/style.rs
This PR implements these traits:
- `IntoStyle`
- `IntoStyleValue`
- `IntoProperty`
- `Render`
- `RenderHtml`
- `AttributeValue`
- `InnerHtmlValue`
for these store fields:
- `Store`
- `ArcStore`
- `Field`
- `ArcField`
- `SubField`
- `AtKeyed`
- `KeyedSubField`
- `DerefedField`
- `AtIndex`
It also implements `IntoSplitSignal` for these traits:
- `AtKeyed`
- `AtIndex`
- `DerefedField`
I created a new macro rule that was flexible enough to handle the signals, so I replaced the previous macro with this new one for all signals.
I didn't implement `IntoClass` because it also had an implementation for `(&'static str, $sig<bool, S>)`, which my new macro wasn't flexible enough to handle. However, I thought that if you create something like `IntoStyleValue` for `IntoClass`, it can have a unified …
> Implement several into traits for store fields (0.8)

- leptos_server/src/local_resource.rs
`LocalResource`'s, unlike `Resource` cannot currently be used outside `Suspense`. 
This allows `.get()` and friends to be used outside `Suspense`, this doesn't affect `.await`, which would still panic, these would now all just return `None` on the server.
> Allow LocalResource sync methods to be used outside Suspense

- integrations/axum/src/lib.rs
This is more consistent with the other Axum integration functions, which are also generic. This also allows passing a closure.
The reason I made this PR is that I'm trying to create a private library that wraps the Leptos Axum integration, but the function pointer is giving me a lot of trouble.
> refactor: make `shell` parameter in `file_and_error_handler*` generic

- leptos/src/children.rs
- leptos_macro/src/view/component_builder.rs
- leptos_macro/src/view/slot_helper.rs
- leptos_server/src/local_resource.rs
This optimisation improves thaw demo compile time in erased mode by 25% and non-erased mode by 10%, and shouldn't be a breaking change. Albeit this is probably a larger improvement than for the average project. For thaw, this optimises ~2500 unique string nodes.
It seems the unique closures for each component's children prop, when passing to `ToChildren::to_children(move || #children)` is a significant bottleneck for the compiler. 
We can identify strings inside the `view!{}` macro, so we can provide an optimised path that doesn't add the closure. 
It does bring up the idea of replacing all `FnOnce()` children types with this, assuming `AnyView` could be made `Clone`, but I don't see how this would be possible without a massive breaking change, so I'm not looking into it.
> view!{} macro optimisation: don't wrap string types in closures when passing to ToChildren

- examples/suspense_tests/e2e/features/check_instrumented_issue_3719.feature
- examples/suspense_tests/e2e/tests/app_suite.rs
- examples/suspense_tests/src/instrumented.rs
Also as reported in #3719, which has an actual minimum example.
To provided additional detail that I missed there (even though I mentioned this briefly in #3699), these tests in this pull request should have flagged #3502 which the cdee2a9476109b10f5d8da268684bd1257c6ce9b being the first source of the regression, and that this following patch is as close to the source of the issue as I can find:
```patch
diff --git a/router/src/nested_router.rs b/router/src/nested_router.rs
index 27269b3c..3fa6ed0e 100644
--- a/router/src/nested_router.rs
+++ b/router/src/nested_router.rs
@@ -655,8 +655,8 @@ where
ScopedFuture::new(view.choose()),
);
let view = view.await;
-                                    let view =
-                                        MatchedRoute(matched.0.get(), view);
+ …
```
> test: regression from #3502

- examples/tailwind_actix/style/tailwind.css
- examples/tailwind_axum/style/tailwind.css
See https://github.com/leptos-rs/leptos/issues/3688
Note that example_csr still holds style.css of tailwind v3, which still seems to works using trunk instead of cargo-leptos.
> docs: update example tailwind input css to v4

- projects/ory-kratos/app/src/auth/login.rs
- projects/ory-kratos/app/src/auth/recovery.rs
- projects/ory-kratos/app/src/auth/registration.rs
- projects/ory-kratos/app/src/auth/settings.rs
- projects/ory-kratos/app/src/auth/verification.rs
- reactive_stores/src/lib.rs
- server_fn_macro/src/lib.rs
This PR refactors the server function macro implementation into a struct that can be parsed and converted to tokens. The struct has more modular methods for derived values like the protocol based on the default configuration and the parsed arguments. This should make it both easier to maintain in the long run and easier to modify for Dioxus. I did make some fields of the server function arguments and body public to make them easier to read and modify externally. This introduces some additional semvar requirements. I have marked the newly public structs as non exhaustive so we can add fields in minor releases. Let me know if you would rather expose getters and setters or if the API surface is too broad
There are two small potentially breaking changes in this PR:
1) Some arguments like …
> More flexible server fn macro api

- .github/workflows/ci-semver.yml
JSON document v40 is not supported in cargo semver. For most compatibility, advised to use the latest stable:
> It's also possible that support for some nightly versions may be dropped even while older stable versions are still supported. This usually happens when a rustdoc format gets superseded by a newer version before becoming part of any stable Rust. In that case, we may drop support for that format to conserve maintenance bandwidth and speed up compile times. For example, cargo-semver-checks v0.24 [supported](https://github.com/obi1kenobi/cargo-semver-checks/blob/93baddc2a65a5055117ca670fe156dc761403fa5/Cargo.toml#L18) rustdoc formats v24, v26, and v27, but did not support the nightly-only v25 format.
> fix(CI): switch to stable in semver for most compatibility

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
This provides much better compatibility with server functions using custom errors while still working as before with server functions using `ServerFnError`.
This can be verified with the `server_fns_axum` which uses the `extract()` function and a `ServerFnError` without needing to be edited in any way, and I've also tested it against my own server functions that use a custom error and that also works as expected with the `?` operator.
Resolves #3745
> feat: switch `extract()` helper to use `ServerFnErrorErr` (closes #3745)

- reactive_graph/src/effect/effect.rs
`deps` and `callback` were argument names used in the deprecated `watch` function
> docs(`Effect::watch`): refer to `dependency_fn` and `handler` args

- .github/workflows/run-cargo-make-task.yml
We don't (and shouldn't) test against incremental builds and we don't build tool dependencies (we are using binaries). 
Caching layer causes issues here:
https://github.com/leptos-rs/leptos/actions/runs/14016515233/job/39243094896
https://github.com/leptos-rs/leptos/actions/runs/14016422234/job/39243222969
> fix(CI): remove caching

- examples/server_fns_axum/src/app.rs
- leptos/src/form.rs
- reactive_graph/src/actions/action.rs
- reactive_graph/src/send_wrapper_ext.rs
A better fix for #3746 and addresses @benwis's comment [here](https://github.com/leptos-rs/leptos/pull/3749#issuecomment-2743413942). There's a bit of API leakage but because `MaybeSendWrapperOption<T>` (should maybe rename this?) implements Deref/DerefMut to `Option<T>` it is usually pretty easy to work with it.
The same thing can be done for other primitives that are built in similar ways.
> Reduce use local signals for `Action::new_local` and similar primitives

- leptos_server/src/lib.rs
Prevents having to keep `codee` and `leptos` in sync because `codee` has a different versioning scheme. Used in common case of changing encoding for resources, so makes sense to be exported.
> Re-export the codee crate

- server_fn/src/codec/cbor.rs
- server_fn/src/codec/json.rs
- server_fn/src/codec/mod.rs
- server_fn/src/codec/msgpack.rs
- server_fn/src/codec/multipart.rs
- server_fn/src/codec/patch.rs
- server_fn/src/codec/postcard.rs
- server_fn/src/codec/put.rs
- server_fn/src/codec/rkyv.rs
- server_fn/src/codec/serde_lite.rs
- server_fn/src/codec/stream.rs
- server_fn/src/codec/url.rs
- server_fn/src/error.rs
- server_fn/src/request/browser.rs
- server_fn/src/request/mod.rs
- server_fn/src/request/reqwest.rs
Adds `PATCH`, `PUT`, `DELETE`, and limited `HEAD` method support for `#[server]` functions. Includes a note about potential browser support issues when JS/WASM is not enabled. Useful when defining REST apis via `#[server]` functions.
See #3733 for previous discussion on this topic.
> feat: add support for more HTTP methods in server fn codecs

- reactive_stores_macro/src/lib.rs
Improves error messages by pointing to the actual location that the signal was accessed.
> Add track_caller to store field methods

- integrations/axum/src/lib.rs
At present, the Axum integration `file_and_error_handler` sets a 404 if it renders the fallback route. This PR changes this behavior to only set the status code to 404 (Not Found) if the status code is currently 200 (Ok), which is the default. It will be 200 unless you have overwritten it in the `fallback` of your `Router`, in which case we'll preserve that status code. 
This is especially important because it allows you to use `<Redirect/>` in the `fallback` and preserve the 302 redirect code, which is necessary for correct behavior.
> fix: allow custom status codes or redirects for route fallbacks

- Cargo.lock
- Cargo.toml
- leptos/src/lib.rs
- leptos_macro/Cargo.toml
- server_fn/Cargo.toml
- server_fn/src/error.rs
- server_fn/tests/invalid/aliased_return_full.rs
- server_fn/tests/invalid/aliased_return_full.stderr
- server_fn/tests/invalid/aliased_return_none.rs
- server_fn/tests/invalid/aliased_return_none.stderr
- server_fn/tests/invalid/aliased_return_part.rs
- server_fn/tests/invalid/aliased_return_part.stderr
- server_fn/tests/invalid/empty_return.rs
- server_fn/tests/invalid/empty_return.stderr
- server_fn/tests/invalid/no_return.rs
- server_fn/tests/invalid/no_return.stderr
- server_fn/tests/invalid/not_async.rs
- server_fn/tests/invalid/not_async.stderr
- server_fn/tests/invalid/not_result.rs
- server_fn/tests/invalid/not_result.stderr
- server_fn/tests/server_macro.rs
- server_fn/tests/valid/aliased_return_full.rs
- server_fn/tests/valid/aliased_return_none.rs
- server_fn/tests/valid/aliased_return_part.rs
- server_fn/tests/valid/custom_error_aliased_return_full.rs
- server_fn/tests/valid/custom_error_aliased_return_none.rs
- server_fn/tests/valid/custom_error_aliased_return_part.rs
- server_fn_macro/src/lib.rs
Add support for aliased result types to the `server_fn` macro. 
```rust
use leptos::prelude::*;
type AliasedResult = Result<String, ServerFnError>;
#[server]
pub async fn full_alias_result() -> AliasedResult {
Ok("full".to_string())
}
```
Partial aliases can also be used. 
```rust
use leptos::prelude::*;
type PartialResult<T> = Result<T, ServerFnError>;
#[server]
pub async fn partial_alias_result() -> PartialResult<String> {
Ok("partial".to_string())
}
```
This also supports custom error types added in `0.8.0-alpha`. 
- Enhanced error messages for better clarity when server functions do not meet the expected return type requirements.
- Added `trybuild` tests to ensure behaviour is not broken in future releases.
- Add `ServerFnErrorErr` and `FromServerFnError` to prelude.
> feat: support aliased `Result` return types for `server_fn`

- examples/js-framework-benchmark/src/lib.rs
- reactive_graph/src/computed/selector.rs
It's a breaking change, and it avoids two possible `clone`:
* the function call
* the inner lookup
It may use `K: AsRef<T>`, but I don't think it's neccessary, and put this into v0.8 is good enough?
> pass key reference to `Selector::selected`

- Cargo.lock
- leptos/Cargo.toml
Restores `getrandom` dependency to avoid compilation error when compiling for WASM with the `nonce` feature.
> Revert "Remove getrandom (#3589)"

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
Currently, `additional_context()` is called after we provide other server context (like the request `Parts` in Axum) for ordinary routes, but before the other context for server functions. That's just an oversight; correcting it allows you to access the request data in your `additional_context` function, which can be useful!
> fix: call `additional_context` after providing other server context in all cases

- tachys/src/view/keyed.rs
#3844 notes a panic when the combination of `Suspense`, a `LocalResource`, and a `For` (with no HTML element parent) leads to the need to rebuild a `For` that's not currently mounted to the DOM. Currently, the renderer panics. But this is completely unnecessary: because `mount()` simply mounts all the elements in their current order, it's perfectly possible to handle adding and moving items in the list by simply adding and moving the items in the list *without* moving them in the DOM: they will be mounted in the correct order when remounted.
I can't imagine a case in which this would break existing code, because existing code would currently panic if `parent` was `None`, whereas now it will update the internal list but not modify the DOM.
> fix: don't try to move keyed elements within the DOM if they're not yet mounted (closes #3844)

- leptos_macro/src/lib.rs
Latest nightly `2025-04-15` removes the [`.source_file()`](https://doc.rust-lang.org/proc_macro/struct.Span.html#method.source_file) method on `proc_macro::Span` (used in our hot-reloading code) and [splits it into `.file()` and `local_file()`](https://github.com/rust-lang/rust/issues/54725#issuecomment-2796806678). 
The bad news: this means leptos nightly no longer compiles on latest nightly.
The good news: this is a step toward stabilization for other parts of the API, which is *great*.
I've made the decision to just change to the newer method name, and require nightly users to use latest nightly.
> chore(nightly): update proc-macro span file name method name

- Cargo.lock
- reactive_stores/Cargo.toml
- reactive_stores/src/lib.rs
- reactive_stores_macro/src/lib.rs
This PR improves the `reactive_stores` `KeyMap` implementation by using concurrent `DashMap` on non-wasm and lock-free std `HashMap` on wasm. This also solves two Clippy errors, one mentioned earlier and the other was enum large stack usage.
> fix: reactive_graph keymap impl and clippy warnings

- leptos/src/error_boundary.rs
- leptos/src/suspense_component.rs
- leptos/src/transition.rs
- tachys/src/ssr/mod.rs
- tachys/src/view/error_boundary.rs
This PR should address issues #3850 (clearing the previous error when rebuilding a node from `Err(_)` to `Err(_)`) and #3851 (`ErrorBoundary` with child `Suspense` that contains a value that starts in the `Err(_)` state).
@sabify if you distilled those MREs from a larger or more complex example, please feel free to let me know if there are additional, unaddressed issues! 
The fix for #3851 in particular is a behavior change: it effectively turns any `<ErrorBoundary/>` that contains a `<Suspense/>` in its children into a `<Suspense/>` itself, so that it can wait for the children to load in order to know whether it needs to render its error fallback. It seems to work but I imagine there are also edge cases here that I have not foreseen.
> Error boundary fixes

- leptos_macro/src/component.rs
Removed lint(allow) attributes from adding to component function and added it to user logic.
Fix for #3771
> Forward lint attributes used with #[component] macro

- tachys/src/html/event.rs
`ClipboardEvent` has been stabilized in `web-sys` for a while now, and is widely available according to MDN, so this PR uses `ClipboardEvent` for the appropriate events (`copy`, `cut`, `paste`).
- `web-sys` changelog: https://github.com/rustwasm/wasm-bindgen/blob/c35cc9369d5e0dc418986f7811a0dd702fb33ef9/CHANGELOG.md#changed-7
(Note that the version number in the changelog refers to `wasm-bindgen` instead of `web-sys`, but `ClipboardEvent` is indeed stabilized in the version of `web-sys` that `tachys` uses)
- MDN page: https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent
> fix: Use stabilized ClipboardEvent

- server_fn/src/codec/stream.rs
\+ easing an unnecessary trait bound over some `TextStream` methods.
Related: https://github.com/leptos-rs/leptos/pull/3811#issuecomment-2817878129
> feat: enhancing `ByteStream` error handling

- examples/server_fns_axum/src/app.rs
- server_fn/src/client.rs
- server_fn/src/error.rs
- server_fn/src/lib.rs
- server_fn/src/request/actix.rs
- server_fn/src/request/axum.rs
- server_fn/src/request/generic.rs
- server_fn/src/request/mod.rs
With the current implementation, you are not able to send errors over WebSockets and you will be trapped into an infinite loop. This PR solves it and you can properly send stream data over WebSocket. As an effect, there is no longer a requirement to have `Display` bound on the `FromServerFnError` trait as we are no longer using it.
Supersedes: #3847
PR origin: #3656
>  fix: send/receive websocket data

- examples/hackernews_islands_axum/src/fallback.rs
- examples/hackernews_islands_axum/src/routes/stories.rs
Avoid calling category() twice on the story type.
> fix(examples): incorrect routes in hackernews example (closes #3892)

- examples/islands_router/Cargo.toml
- leptos/Cargo.toml
- leptos/src/hydration/islands_routing.js
- leptos/src/hydration/mod.rs
- leptos_macro/src/component.rs
- router/src/flat_router.rs
- tachys/Cargo.toml
- tachys/src/hydration.rs
- tachys/src/view/any_view.rs
- tachys/src/view/either.rs
- tachys/src/view/keyed.rs
Looking at #3896 raised a few overlapping issues with out-of-order rendering, type-erasure, and island hydration when using the new/semi-experimental islands-routing feature. The commits in this PR return it to a working state, in and out of `erase_components` mode.
> Fix some island-routing issues

- reactive_graph/src/owner/context.rs
This short changeset merely fixes a few panic messages of copied–and–adjusted documentation code examples.
> fix(docs): correct panic message in copied example code

- examples/stores/README.md
- reactive_stores/src/lib.rs
Fix some typos in the reactive store docs, and give a more specific description in the reactive store's example README.md
> Fix some typos in the documentation/examples for reactive store.

- reactive_stores/src/lib.rs
Minor fix for better copy-paste when reading through the docs :)
> Remove unnecessary "crate::" prefix in a documentation example.

- router/src/ssr_mode.rs
Closes #3963 by substituting the correct [module level](https://docs.rs/leptos_router/0.8.2/leptos_router/enum.SsrMode.html) doc comment for the erroneous variant doc comment of [`PartiallyBlocked`](https://docs.rs/leptos_router/0.8.2/leptos_router/enum.SsrMode.html#variant.PartiallyBlocked) (being a duplicate of the [`InOrder`](https://docs.rs/leptos_router/0.8.2/leptos_router/enum.SsrMode.html#variant.InOrder) variant).
> fix: correct doc comment for `SsrMode::PartiallyBlocked` (closes #3963)

- router/src/matching/horizontal/mod.rs
- router/src/matching/horizontal/static_segment.rs
- router/src/matching/mod.rs
Fixes matching the path containing a smooshed static segments. 
`/barbaz` will no longer match `path!("/bar/baz")`
> fix: smooshed static segments no longer matches the path #3968

- leptos_macro/src/component.rs
> fix: forward missing lint attributes passed to `#[component]` macro

- tachys/src/html/class.rs
- tachys/src/html/element/inner_html.rs
- tachys/src/reactive_graph/class.rs
- tachys/src/view/strings.rs
Getting cute with little optimizations can lead to weird little bugs.
See further discussion in #3983.
> fix: don't use `Arc::ptr_eq` for string comparison (closes #3983)

- reactive_graph/src/owner.rs
- reactive_graph/src/owner/context.rs
- router/src/nested_router.rs
@benwis provided me another reproduction similar to the issue #3042, which I simplified to this:
```rust
#[component]
view! {
<Router>
<main>
<Routes fallback=|| "Not found">
<ParentRoute path=StaticSegment("") view=|| view! {
<Provider value=42i32>
<Outlet/>
</Provider>
}>
<Route path=StaticSegment("") view=HomePage/>
</ParentRoute>
</Routes>
</main>
</Router>
}
}
#[component]
fn HomePage() -> impl IntoView {
let value = use_context::<i32>();
view! {
<p>{format!("{value:?}")}</p>
}
}
```
The issue here is that currently an `Outlet` is slotted into the ownership tree as the child of its parent's `view`, not in the location where the `Outlet` itself is consumed. This is important to the way `Outlet` itself works, because it uses context to determine which …
> Fix context issues with nesting routing

- tachys/src/html/attribute/value.rs
Similar idea as https://github.com/leptos-rs/leptos/pull/3420
This makes it easier to deal with rarely changing `&'static str`
> Implement AttributeValue for Cow<'_, str>

- tachys/src/reactive_graph/mod.rs
- tachys/src/view/template.rs
Uncovered during a crater run for `-Znext-solver` in https://github.com/rust-lang/rust/pull/133502.
These where-clauses cause `tachys` to fail with an overflow error when compiling with the next-generation trait solver right now: https://github.com/rust-lang/trait-system-refactor-initiative/issues/89. We're still unsure whether we actually have to break this when stabilizing the new solver, so it may not be an issue in the end. This breakage is a really subtle issue and quite unfortunate.
Luckily, this PR should be neutral or even desirable by itself, so I think it's fine to merge it regardless of whether it'll be actually necessary to avoid future breakage.
In case this looks good to you, it would be awesome if you could release this change as a point-release for version 0.2 and maybe …
> remove unnecessary where-clauses

- Cargo.lock
- projects/session_auth_axum/Cargo.toml
- projects/session_auth_axum/src/auth.rs
- projects/session_auth_axum/src/main.rs
- projects/session_auth_axum/src/todo.rs
There's a bunch of ceremony in the current version of the example that is no longer necessary in the present version of the framework: specifically the custom handlers are not needed.
> Update `session_auth_axum` example

- reactive_graph/src/diagnostics.rs
(Very easy to fix but I'm pretty sure this is a semver-breaking change, as `SpecialNonReactiveZoneGuard` was previously a unit struct that could be constructed by a user arbitrarily.)
Edit to add: That said, simply constructing and then dropping one of these before would itself be incorrect, so I think making this change is fine; only very strange and broken code could break.
> fix: allow nested untracked reads without false positives (closes #4032)

- reactive_graph/src/computed/async_derived/arc_async_derived.rs
- reactive_graph/src/computed/async_derived/mod.rs
Resources are not supposed to track anything inside the `async` block: rather, anything you need to track is tracked in the first argument. This allows us to only track the first argument on the client, and not run the `async` block again until something in the first argument has changed.
However, #4060 shows that when you read from another resource via `.await`, and that first resource is not actually ready, it was actually getting tracked and causing the second (dependent) resource to re-run when the first resource completed, which is not correct.
This corrects that behavior, fixing the problem in #4060.
I think this falls into the awkward category in which it 1) fixes a bug, 2) doesn't change the type/won't break compilation of existing code, but 3) could hypothetically break …
> fix: do not track anything inside the `async` block of a `Resource` (closes #4060)

- reactive_graph/src/computed/async_derived/arc_async_derived.rs
- reactive_graph/src/owner.rs
- reactive_graph/src/owner/context.rs
Kind of a good news/bad news situation here.
This seems to fix the memory leak reported [here](https://github.com/leptos-rs/leptos/pull/4015#issuecomment-2957748006), by only storing `WeakOwner` rather than a regular `Owner` when joining two context tree together.
On the other hand, it reintroduces the panic described in #3729. Which suggests to me that the problem was being "solved" by accidentally leaking the `Owner` by storing it in a cyclical data structure. Now, it's getting disposed properly again which means those panics are occurring again.
This will require a bit more investigation on my part to fix #3729 properly. (For now, I'm going to bed.)
> fix: memory leak introduced by #4015

- reactive_stores/src/store_field.rs
- reactive_stores/src/subfield.rs
Fixes the following:
- `StoreField::triggers_for_path`: Too small vec capacity calculation potentially causing reallocations
- `StoreField::triggers_for_path`: Duplicate trigger when path is empty
- `Subfield::track_field`: Duplicate track on `this` trigger
Also rewrites `Subfield::track_field` to skip 1 `get_trigger`
> Bugfixes to `reactive_stores`

- Cargo.lock
- Cargo.toml
- examples/counter_isomorphic/Cargo.toml
- examples/server_fns_axum/Cargo.toml
- examples/server_fns_axum/src/app.rs
- hydration_context/Cargo.toml
- hydration_context/src/hydrate.rs
- integrations/actix/Cargo.toml
- integrations/actix/src/lib.rs
- integrations/axum/Cargo.toml
- integrations/axum/src/lib.rs
- meta/Cargo.toml
- meta/src/lib.rs
- projects/ory-kratos/e2e/Cargo.toml
- projects/ory-kratos/e2e/tests/app_suite.rs
- router/Cargo.toml
- server_fn/Cargo.toml
- server_fn/src/lib.rs
- server_fn/src/request/reqwest.rs
- tachys/Cargo.toml
- tachys/src/renderer/dom.rs
As of rust_version 1.80.0 there are now equivalent options in std.
Async and sync changes are as follows.
-use once_cell::sync::Lazy;
+use std::sync::LazyLock;
-use once_cell::sync::Lazy;
+use std::sync::LazyLock;
> Removed crate once_cell

- router/src/components.rs
https://github.com/leptos-rs/leptos/pull/4035 and https://github.com/leptos-rs/leptos/pull/4074 were conflicting
> Fix compilation because of concurrent conflicting change

- tachys/src/svg/mod.rs
#4099 introduced caching for inert elements, changing the API for [`dom::Dom::create_element_from_html`](https://github.com/leptos-rs/leptos/blob/30b0a579cad0765e9cc5c62739785cb155fe6154/tachys/src/renderer/dom.rs#L495). This updates `svg::InertElement` (added in #4085) to match the new API.
> [fix] Update `svg::InertElement` for `dom` cache.

- server_fn/src/request/browser.rs
The `MultipartData` struct (used as an argument for server functions of `input = MultipartFormData`) allows access to a `BrowserFormData` on the client. However, there is not much useful that can be done with it at this time.
As @gbj suggested, this adds a `take` method that transforms the `BrowserFormData` into a regular `FormData` from `web_sys`. From there it is possible to retrieve data about the form fields and whatnot.
In my project, it would be very helpful if MultipartFormData server functions behaved more like the default ones: where the parameters define the expected request body and the contents can be assembled into a struct automatically by using `ServerFn::from_event` and `ServerFn::from_form_data` (I supposed there would need to be some mechanism to limit allowed file sizes …
> feat: add method `take` for BrowserFormData

- reactive_graph/src/owner.rs
- reactive_graph/src/owner/context.rs
This API was introduced in #4015, but was pretty much a hack to fix #3042 and similar issues, which are fixed in a more principled way by #4091, which no longer used these APIs. Removing them removes the overhead cost of their existence.
> chore: remove now-unused `join_contexts` API

- leptos_macro/src/view/mod.rs
Fixes a bug that wraps top level `<svg>` elements in a `<g>` tag, invalidating the DOM subtree and causing them not to render.
> Use inert_element for top level <svg> elements.

- examples/regression/e2e/features/issue_4088.feature
- examples/regression/e2e/features/pr_4015.feature
- examples/regression/e2e/features/pr_4091.feature
- examples/regression/e2e/tests/fixtures/check.rs
- examples/regression/e2e/tests/fixtures/find.rs
- examples/regression/e2e/tests/fixtures/world/check_steps.rs
- examples/regression/src/app.rs
- examples/regression/src/issue_4088.rs
- examples/regression/src/lib.rs
- examples/regression/src/pr_4015.rs
- examples/regression/src/pr_4091.rs
- leptos/src/into_view.rs
- meta/src/lib.rs
- meta/src/title.rs
- router/src/nested_router.rs
- tachys/src/view/any_view.rs
- tachys/src/view/tuples.rs
This should fix the ownership/cleanup issue identified in #4114, fixing the failing test in `examples/regression`.
Todo
> Clean up nested routing ownership and add regression tests

- reactive_stores_macro/src/lib.rs
Fixes the case when struct had a generic arguments by adding missing generic arguments into the generated trait and the said trait implementation.
> Fixes #4136: Compile time errors while deriving store

- .github/workflows/autofix.yml
- .github/workflows/run-cargo-make-task.yml
- Cargo.toml
- benchmarks/Cargo.toml
- examples/counter_isomorphic/Cargo.toml
- examples/ssr_modes/Cargo.toml
- examples/ssr_modes_axum/Cargo.toml
- leptos/src/into_view.rs
- leptos_hot_reload/src/patch.js
- leptos_macro/src/lib.rs
- reactive_stores/src/lib.rs
- server_fn/tests/invalid/empty_return.stderr
- server_fn/tests/invalid/not_result.stderr
This PR makes a few related changes:
- Updates MSRV to 1.88 from 1.80, which allows us to use (stable) proc macro spans
- Updates the `nightly` compiler version used in CI to something more recent (2025-07-16 instead of 2025-04-16)
- Adds support for `cargo leptos watch --hot-reload` in stable Rust (enabled by the 1.88 update)
The same version bump will allow fixing #4157 on stable consistently with nightly as well, when lazy-loading/code-splitting is added.
There's some disagreement about whether an MSRV increase is a semver-breaking change. From my perspective, requiring a bump from 0.8 to 0.9 for a change like this would be a lot of unnecessary churn. Historically, we did not include an MSRV at all; I think adding it explicitly is a nice convenience, but I'm not willing to treat it as …
> Version updates + stable hot-reloading

- leptos_hot_reload/src/node.rs
- leptos_hot_reload/src/patch.js
- tachys/src/view/any_view.rs
This PR fixes three bugs in hot-reload functionality ( two of which were mentioned in #3191 ).
1) unquoted text wasn't parsed into LNode which led to wrong indexing of children in patch.js
2) components without DOM ( e.g. metatags ) also broke indexing
3) changes to views with fragment components led to updating elements inside these fragments
- Now unquoted text parses into the same LNode::Text variant as Node::Text does. I searched for differences in handling RawText and Text variants, but didn't find any.
- DOM-less components now inserts  comment into html, instead of . I also didn't find code that relies on that behaviour.
Here is the code that I tested changes on:
```rust
use leptos::prelude::*;
use leptos_meta::{provide_meta_context, MetaTags, Title};
use leptos_router::{ …
```
> fix: three hot-reloading bugs ( closes #3191 )

- leptos_dom/src/logging.rs
This PR adds debug-only macros and methods for `log` and `error` levels, aligning with the existing warning level implementation. I guess the debug-only methods contain duplicated code, but I’ve kept them as-is to match the existing pattern. Additionally, I noticed that `console_error` is defined inline, while the other two methods are not. I left this unchanged to avoid potential impacts on compile times. Let me know if any changes are needed.
> feat: add `debug_log!`, `debug_error!`, `console_debug_log` and `console_debug_error` 

- leptos_hot_reload/src/diff.rs
- leptos_hot_reload/src/patch.js
This PR implements Myers diff algorithm for `diff_children` method. This fixes two bugs and one small issue:
- inserting multiple tags at once results in incorrect ordering of elements
- being unable to insert new tags in fragments
- the previous algorithm produces unnecessary patches when inserting new child between two tags
Now patches apply immediately instead of after processing every patch for a view, and actualChildren is rebuilt before each patch. These changes were needed for the new algorithm, because it relies on indexes that reference newly added elements.
I tested it mostly on simple cases, so it could break some edge cases with deeply nested elements or combination of fragments and components. If that happens, I will fix them in the future.
Here is the code that you can test …
> fix(hot-reload): implement Myers diffing algorithm

- leptos_hot_reload/src/lib.rs
- leptos_hot_reload/src/patch.js
This PR fixes four bugs:
- hot-reload stops updating view macro map when number of view macro in a file mismatch with previous state of a file
- fragment couldn't be replaced with a single tag
```rust
view! {
<p>"Text 1"</p>
<p>"Text 1"</p>
<p>"Text 1"</p>
}
```
```rust
view! {
<p>"Text 1"</p>
}
```
- unable to fully clear fragment view 
```rust
view! {
<p>"Text 1"</p>
<p>"Text 1"</p>
<p>"Text 1"</p>
}
```
```rust
view! {
}
```
- unable to append children to an empty tag
```rust
view! {
<div></div>
}
```
```rust
view! {
<div>
<p>"Text"</p>
</div>
}
```
> fix(hot-reload): hot-reload stops working when number of views changes in a file + small fixes

- Cargo.lock
- Cargo.toml
- oco/Cargo.toml
In a way this is a field report from a leptos app.
There are duplicate crates derived solely from within the eco-system of leptos crates.
I have traced down why thiserror is still duplicated even though there has been a recent efforts to unify things by referencing a single crate definitions in the root workspace.
The recent changes do not appear in the published version of oco_ref and so the ecosystem at
large is still relying on stale versions ( crates.io reports oco_ref is about a year old. )
In short, bump oco_ref.
> Preparing to publish oco_ref 0.2.1

- Cargo.toml
- integrations/actix/Cargo.toml
- integrations/axum/Cargo.toml
- integrations/utils/Cargo.toml
- leptos/Cargo.toml
- leptos_config/Cargo.toml
- leptos_dom/Cargo.toml
- leptos_hot_reload/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_server/Cargo.toml
- meta/Cargo.toml
- router/Cargo.toml
- router_macro/Cargo.toml
- scripts/bump.sh
- server_fn/Cargo.toml
- server_fn/server_fn_macro_default/Cargo.toml
- server_fn_macro/Cargo.toml
This PR introduces two changes:
- Decouple versioning of members from the workspace. If there are no changes to a member, there shouldn't be a version bump and a release.
- To tackle the difficulty of tracking changes in the members, I wrote and added a `bump.sh` script that tracks the changes from the last release tag and provides a simple interface to update member versions. The changes will be applied to both the workspace and the crate's `Cargo.toml`.
Here is the usage:
```bash
$ ./scripts/bump.sh
Changes detected in reactive_graph (/Users/sabify/dev/leptos/reactive_graph)
1) patch
2) minor
3) major
Select version bump for reactive_graph: 1
Upgrading reactive_graph from 0.2.3 to 0.2.4
Updating workspace's dependency from 0.2.3 to 0.2.4
reactive_graph bumped to patch
```
> Enhancing members’ versioning

- tachys/src/html/element/elements.rs
When trying to use the `name` attribute of the `<details>` element I noticed it was missing. This is a relatively new attribute that is younger than Leptos so it was probably just never added. Basically if you have a group of `<details>`s that share a name then the browser handles only displaying one at a time. I would like to use this in my component library.
[According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/details#browser_compatibility) it is fully supported by all browsers, since September 2024.
I think it makes sense to add it.
> Add name attribute to details element

- leptos_dom/src/helpers.rs
Referring to discussion #4200, this allows easier branching based on server/client that is not based on cargo features. This is usefull for cases where all the code can compile for both environments, but there is no point in doing the extra work on the server/client.
> make is_server and is_browser public

- scripts/bump.sh
Related: #4172 
The script now detects if any changes were made to a member from a commit release up to the latest tag.
@gbj, if you are going to release and publish a member crate without releasing a tag, please push a commit in the following format to keep track of the changes: `<member-name>-v<member-version>`. For example, `oco_ref-v0.2.1`.
Please keep in mind to use the member package name defined in the `Cargo.toml`, not the directory name.
Here is the logic:
- If there is a **release commit** newer than the latest tag for the member crate, check if there are any changes made to it from the **release commit** and request a bump.
- Otherwise, use the **latest tag** and check if there are any changes made to the member crate and request a bump.
> feat: improving the bump script

- tachys/src/oco.rs
Since `Cow<'static, str>` implements `IntoProperty`, I don't see why `Oco<'static, str>` wouldn't. This makes it easier to use a `TextProp` as a property, for instance.
I wondered whether I should put this in `tachys/src/oco.rs` alongside its other implementations of `IntoClass` and `IntoStyle` or in `tachys/src/html/property.rs` alongside the `IntoProperty` implementations of `Cow` and friends...
> feat: implement IntoProperty for Oco

- leptos/src/hydration/mod.rs
- leptos/src/hydration/reload_script.js
- leptos_config/src/lib.rs
The current behavior is to always try to connect to the live reload endpoint via `ws://`, but I think that's not very smart since, if the website is being served via HTTPS, the browser will actively prevent `ws://` connections. Thus defaulting to `wss://` in those situations seems reasonable, as there is not really another option (unless the browser is configured to allow `ws://` from `https://` somehow...).
Thus I introduce a new option for LEPTOS_RELOAD_WS_PROTOCOL: `auto`. That will make it so that the actual protocol to be used from the client will be determined by the protocol used to access the originating website: if the website was accessed via `https://`, then the live reload protocol is `wss://`. Otherwise it is `ws://`.
This was the only option on #1548, but #1613 removed it in …
> feat: add default "auto" live reload protocol option

- leptos_server/Cargo.toml
- leptos_server/src/once_resource.rs
- leptos_server/src/resource.rs
- leptos_server/src/shared.rs
This should allow feature-gated methods like `Resource::new_rkyv()` and so on to appear correctly on docs.rs.
> docs: correctly document additional serialization features for `leptos_server`

- leptos/src/animated_show.rs
- leptos/src/hydration/mod.rs
- leptos/src/hydration/reload_script.js
- leptos/src/show.rs
- leptos_config/src/lib.rs
Reverts #4236, which doesn't compile with `nightly`, and reverts #4224, which caused breaking changes to be published in a patch release, so that I can republish `leptos_config` and `leptos` and resolve #4254.
> Revert recent broken changes

- leptos/src/hydration/reload_script.js
Non-breaking version of #4224, as suggested by @gbj.
This builds on top of #4255.
I would like to make another PR reintroducing the `auto` option for an eventual 0.9 release, as I think it's a more elegant solution.
> fix: use wss for live reload if on https

- reactive_graph/src/actions/action.rs
- reactive_graph/src/computed/async_derived/mod.rs
- tachys/src/html/event.rs
Migrating code from 0.6, it's a common painpoint that context doesn't work in `Action`s or event listeners.
I took a look into this today and it was actually pretty easy to support unless there are some downsides I'm missing!
With this PR, the following works:
```rust
#[derive(Debug, Clone)]
struct Ctx;
provide_context(Ctx);
let a = Action::new(move |_arg: &()| {
expect_context::<Ctx>();
async move {
expect_context::<Ctx>();
}
});
let a_local = Action::new_local(move |_arg: &()| {
expect_context::<Ctx>();
async move {
expect_context::<Ctx>();
}
});
Effect::new(move || {
spawn_local(async move {
a.dispatch(());
a_local.dispatch(());
});
});
view! {
<button
on:click={move |_| {
expect_context::<Ctx>();
}}
>
"Click me"
</button>
};
```
> Preserve owner in Actions and event listeners

- reactive_graph/src/wrappers.rs
Some extra conversion impls for signal types to `ArcSignal` that seem to have just been missed.
> impl From<RwSignal/ReadSignal/Memo> for ArcSignal

- tachys/src/ssr/mod.rs
Note to self: the current implementation was supposed to poll all pending out-of-order chunks round-robin, but instead only polled whichever one of them happened to be *first* in the queue: so if you had two chunks, 1 second and 2 second, you would
1) poll 1-second, find it pending, put it back on the back of the queue
2) wake up after 1 second was ready
3) poll 2-second, find it pending, add it to to back of the queue -- but not then also poll 1-second
4) wake up after 2 second was ready
5) poll 1-second, then poll 2-second, both ready, both flush
This fixes step 3 so that it will poll all pending out-of-order chunks every time, flushing any that are ready to the sync buffer and putting the rest back into the queue.
> fix: correctly poll all out-of-order streaming chunks (closes #4326)
