leptos-rs/leptos

- leptos_dom/Cargo.toml
wee_alloc has a security advisory ([RUSTSEC-2022-0054](https://rustsec.org/advisories/RUSTSEC-2022-0054)). It looks like you recently removed it from the examples, this just finishes the job by removing it from the leptos_dom cargo.toml since it's not actually in use.
> Remove wee_alloc dependency

- examples/hackernews/hackernews-app/src/lib.rs
- examples/hackernews/hackernews-app/src/stories.rs
- examples/hackernews/hackernews-app/src/story.rs
- examples/hackernews/hackernews-app/src/users.rs
- examples/router/src/lib.rs
- leptos_dom/Cargo.toml
- leptos_reactive/src/scope.rs
- leptos_reactive/src/signal.rs
- router/src/components/routes.rs
I'm still trying to figure out what makes the most sense for a loader API. For now, I'm removing the loaders from the examples and using resources directly instead so that nobody's surprised if/when the loader API changes.
> Remove loaders from examples

- examples/hackernews/hackernews-app/Cargo.toml
- leptos_reactive/src/resource.rs
- leptos_reactive/src/runtime.rs
This PR allows for the creation of unserializable "client" resources as discussed in #34. The motivating example from that issue can now be rewritten using a resource:
```rust
use leptos::*;
use nokhwa::{js_camera::JSCameraConstraintsBuilder, JSCamera};
use std::{cell::RefCell, fmt::Debug, rc::Rc};
#[derive(Clone)]
struct Camera(Rc<RefCell<JSCamera>>);
impl Debug for Camera {
fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
f.debug_tuple("Camera")
.field(&self.0.borrow().id())
.finish()
}
}
async fn get_camera(_: ()) -> Option<Camera> {
let constraints = JSCameraConstraintsBuilder::new().build();
let camera = JSCamera::new(constraints).await;
camera.ok().map(|c| Camera(Rc::new(RefCell::new(c))))
}
#[component]
pub fn UserWebcam(cx: scope) -> Element {
let camera = …
```
> Unserializable resources

- examples/counters-stable/src/main.rs
- examples/counters/src/lib.rs
- leptos_core/src/for_component.rs
- leptos_core/src/map.rs
- leptos_reactive/src/memo.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/signal.rs
- router/src/components/routes.rs
- router/src/data/action.rs
- router/src/history/location.rs
- router/src/hooks.rs
As mentioned in #36, this removes every `Clone` bound that didn't seem necessary. The main notes are:
- Types held in a Signal no longer need to be Clone
- The output type of a Resource's future no longer needs to be Clone, though the bounds for the source type are unchanged
- A `Resource::with()` method was added, with similar behavior to `Signal::with()` to allow access without cloning
- Memo output types do not need to be Clone
- To accommodate this, Memo now takes `impl FnMut(Option<&T>) -> T` instead of `impl FnMut(Option<T>) -> T` which is a breaking change, albeit a minor one
This still needs some documentation updates which I'll hopefully get to tomorrow. I'll probably also drop the webcam component that spawned this PR and #35 in as an example unless you object. Tested with all …
> Remove clone bounds

- leptos_dom/src/operations.rs
- leptos_macro/Cargo.toml
- leptos_macro/src/view.rs
Avoid manual delegation for all the DOM events that don't bubble by default. (This is technically too conservative, as one or two of these only don't bubble on certain elements, but it's simpler than passing in the element name and only a very small deopt in those cases.)
> Fix `focus`, `blur`, and other non-bubbling events

- leptos_dom/src/operations.rs
- leptos_dom/src/render.rs
- leptos_macro/src/view.rs
I think I've nailed this one down, mostly by removing old rendering code that was doing a wrong-headed kind of check that had failed to fix an early bug (oops) and by restoring something in the view macro that I'd been reasoning about a little incorrectly.
I definitely want to manually test the various examples to see if this causes issues, in addition to letting the CI run.
> Fix the out-of-order component/element rendering in #53.

- leptos/src/lib.rs
It looked a bit confusing that there were 3 `serde` feature flags and all of them were defaults.
> Amend docs on feature flags

- examples/counter/src/lib.rs
- leptos_macro/Cargo.toml
- leptos_macro/src/lib.rs
- leptos_macro/src/props.rs
- leptos_macro/src/view.rs
This includes a breaking change that will remove the `on-`/`class-`/`attr-`/`prop-` prefixes and just keep `on:`/`class:`/`attr:`/`prop:`, but with an upgraded `view` macro that lets you use custom event, class, and attribute names with dashes: so `on:my-event` will work now
> Update to `syn-rsx` 0.9

- leptos_dom/src/render_to_string.rs
Also fixes the order of resource and `<Suspense/>` fragment streaming so that suspense fragments that resolve while some resources are still pending can send their HTML.
> Make `render_to_stream()` return a `Stream` that is `Send`

- leptos_reactive/src/lib.rs
- leptos_reactive/src/memo.rs
- leptos_reactive/src/signal.rs
- leptos_reactive/src/signal_wrappers.rs
Per issue #84, provides a simple way to specify that a type can be any reactive signal type (`Signal<T>`) or either a signal or unchanging value (`MaybeSignal<T>`). 
This should be useful for creating better APIs for functions and components rather than `fn my_fn(arg1: impl Fn() -> T)`
> Provide `Signal<T>` and `MaybeSignal<T>` wrapper types.

- examples/counter-isomorphic/src/main.rs
- examples/todo-app-sqlite/src/main.rs
- examples/todo-app-sqlite/src/todo.rs
- leptos_macro/src/server.rs
- leptos_macro/src/view.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/scope.rs
- leptos_server/src/action.rs
- leptos_server/src/lib.rs
- leptos_server/src/multi_action.rs
This can be used to inject server-only dependencies like `HttpRequest` and `HttpResponse`. and access them from the server function.
This allows you to do things like access and set cookies in a way that doesn't couple Leptos to any particular server framework or its types.
> Allow accessing `Scope` from server functions

- examples/counters-stable/src/main.rs
- examples/counters/src/lib.rs
The counters and counters-stable examples didn't assign the correct ids when clicking the "Add 1000 Counters" button if there were already counters added, which meant clicking the "x" to remove them would remove the wrong counter.
> Assign correct ids in `add_many_counters`

- examples/parent-child/src/lib.rs
- examples/todomvc/src/lib.rs
- leptos_dom/Cargo.toml
- leptos_dom/src/operations.rs
- leptos_dom/src/render_to_string.rs
- leptos_macro/Cargo.toml
- leptos_macro/src/lib.rs
- leptos_macro/src/view.rs
- router/src/components/form.rs
Hi, I tried to implement #93. I borrowed the code of event types from Yew.
This works fine for me in my test code:
```rust
use leptos::*;
use web_sys::{Event, MouseEvent, DragEvent};
pub fn simple_counter(cx: Scope) -> web_sys::Element {
let (value, set_value) = create_signal(cx, 0);
view! { cx,
<div>
<button on:click=move |ev| {set_value(0); warn!("{}", ev.x())}>"Clear"</button>
<button on:something=move |_| set_value.update(|value| *value -= 1)>"-1"</button>
<span on:drag=move |ev| {warn!("{}", ev.x())} >"Value: " {move || value().to_string()} "!"</span>
<button on:click=move |_| set_value.update(|value| *value += 1)>"+1"</button>
</div>
}
}
```
> Add typed event handlers

- examples/router/src/lib.rs
- router/src/components/outlet.rs
- router/src/components/route.rs
- router/src/components/routes.rs
For the moment, this seems to be work to limit the number of `<Outlet/>` rerenders to 2, rather than the linearly or exponentially increasing number of rerenders.
I'll work a little more on getting that down to 1 where it should be.
> Fix issue #115

- examples/counter-isomorphic/Cargo.toml
- examples/hackernews-axum/Cargo.toml
- examples/hackernews/Cargo.toml
- examples/router/Cargo.toml
- examples/todo-app-cbor/Cargo.toml
- examples/todo-app-sqlite/Cargo.toml
The path dependencies go one step too high, meaning that they include the name of the repo. This won't compile since I named the repo *gbj_leptos*. This PR fixes it.
> Fix path deps' going one level too high

- examples/counter-isomorphic/README.md
- examples/counter/README.md
- examples/counters-stable/README.md
- examples/counters/README.md
- examples/fetch/README.md
- examples/gtk/README.md
- examples/hackernews-axum/README.md
- examples/hackernews/README.md
- examples/parent-child/README.md
- examples/router/README.md
- examples/todo-app-cbor/README.md
- examples/todo-app-sqlite-axum/README.md
- examples/todo-app-sqlite-axum/src/main.rs
- examples/todo-app-sqlite/README.md
- examples/todomvc/README.md
- examples/view-tests/README.md
- leptos/src/lib.rs
I added and corrected READMEs for all the examples in the repo. Hopefully that should make things a bit easier
> Add READMEs to all examples and fix typo in todo-app-axum

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
For the hard-coded html in the integrations:
- Added a missing _wasm path_ param to init.
- Added preloading of wasm and js.
@benwis look ok to you?
> Integration html updates

- examples/tailwind/README.md
Hi,
Thanks for this project !
In example/tailwind, readme says `-o ./style/output.scss`, so I guess this is the one we should look at.
Otherwise:
```
╰─>$ cargo leptos watch
Error: at `/home/nim/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-leptos-0.0.9/src/main.rs@104:58`
Caused by:
no css/sass/scss file found at: "style/output.css"
> Fix example tailwind

- examples/counter/src/lib.rs
trying out `leptos` for the first time, I noticed a warning in this example, which pointed to what appears to be a bug:
```
warning: unused variable: `initial_value`
--> examples/counter/src/lib.rs:11:33
|
11 | pub fn SimpleCounter(cx: Scope, initial_value: i32, step: i32) -> web_sys::Element {
|                                 ^^^^^^^^^^^^^ help: try ignoring the field: `initial_value: _`
|
= note: `#[warn(unused_variables)]` on by default
```
I think this resolves the problem
> fix warning, set initial value of counter

- docs/COMMON_BUGS.md
```rust
let (b, set_a) = create_signal(cx, false); // should be set_b
```
> Update COMMON_BUGS.md to fix typo

- examples/counter-isomorphic/src/counters.rs
- router/src/components/form.rs
- router/src/components/link.rs
I'm investigating using this framework, but prefer to use stable Rust, so just a couple of fixes to get the `counter-isomorphic` example building when enabling the `stable` feature.
Tested by enabling stable in the [counter isomorphic deps](https://gist.github.com/snapbug/49e0ad2512511e2ef86c85d9ea761a37), and building. Checked functionality remains correct for all the methods shown in both Safari and Chrome.
Note: I don't know that editing the example is necessarily a completely desireable fix, given the separation of `counter` and `counters-stable`, and I also noted in router/src/components/link.rs that there is a cfg_if separation of csr or hydrate and not, whereas components/form.rs also has a stable/not cfg_if.
> Fix build errors in `counter-isomorphic` when using `stable`

- examples/counter-isomorphic/src/counters.rs
- examples/todo-app-sqlite-axum/src/todo.rs
- examples/todo-app-sqlite/src/todo.rs
- leptos_reactive/src/lib.rs
- leptos_reactive/src/signal_wrappers_read.rs
- leptos_reactive/src/signal_wrappers_write.rs
- leptos_reactive/src/stored_value.rs
- leptos_server/src/action.rs
- leptos_server/src/multi_action.rs
- router/src/components/form.rs
This PR allows you to store values in the reactive system, in exchange for non-reactive references that are `Copy` and `'static`. This means that any value can have the same `move`-ability and easy DX as the signal types, without triggering reactive updates.
This also migrates the `Signal` and `SignalSetter` wrapper types and the `Action` and `MultiAction` types so that they are backed by `StoredValue`s, which means that all of the framework's primitive types are `Copy`.
> `store_value`

- leptos_dom/src/html.rs
- leptos_dom/src/html/math.rs
- leptos_dom/src/html/svg.rs
Make sure all tag names are uppercased, which they're not for elements created with `document.createElementNS()`
> Closes #212

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
Inspired by your video and Remix's `redirect()`, I've added some helper functions to ResponseParts/ResponseOptions, and a handy `redirect()` function for easy redirection in server functions.
So this code
```rust
let response =
use_context::<ResponseOptions>(cx).expect("to have leptos_actix::ResponseOptions provided");
let mut response_parts = ResponseParts::default();
let mut headers = HeaderMap::new();
headers.insert(
SET_COOKIE,
HeaderValue::from_str(&format!("darkmode={prefers_dark}; Path=/"))
.expect("to create header value"),
);
response_parts.headers = headers;
std::thread::sleep(std::time::Duration::from_millis(250));
response.overwrite(response_parts).await;
```
could be this now:
```rust
let mut response = use_context::<ResponseOptions>(cx).expect("to have …
```
> Add a redirect() function and some helpful utility functions for ResponseParts and ResponseOptions

- router/src/lib.rs
- router/src/matching/mod.rs
- router/tests/expand_optionals.rs
- router/tests/join_paths.rs
- router/tests/matcher.rs
- router/tests/resolve_path.rs
At some point in late August/early September I moved the router directory, and accidentally lost the tests.
Is it sad that I'm only now getting around to finding them in git and putting them back in? Yes.
Do they still pass? Also yes.
> Add all the missing `router` tests

- .github/workflows/test.yml
I was looking into the test failures.
I see out of memory errors.
I have seem similar errors in a unrelated project, and the solution was to bump the major version of actions/checkout to 3
This may or may not be the problem here ....
> Bump actions/checkout to version@3

- leptos_dom/src/components/each.rs
Minor Tidy which reduces  compiler warnings when running 
```
Cargo doc
```
> #254 Minor: In docs, Rename EachKey to Each.

- examples/hackernews/src/lib.rs
- leptos_dom/src/lib.rs
- meta/Cargo.toml
- meta/src/lib.rs
- meta/src/link.rs
- meta/src/meta_tags.rs
- meta/src/script.rs
- meta/src/style.rs
- meta/src/stylesheet.rs
This PR refactors some of the internals of the `leptos_meta` package to use the new builder approach, and provides new `<Link/>`, `<Style/>`, and `<Script/>` components. (It also refactors `<Stylesheet/>` to use `<Link/>`, which is fun.)
All of these correctly load and unload when you navigate to/from nested routes.
> Additional meta tags — closes issue #158

- leptos_reactive/src/signal_wrappers_read.rs
- leptos_reactive/src/signal_wrappers_write.rs
I'm not sure what name to give the `IntoSignalSetter` method...I thought that `.mapped_signal_setter()` might be appropriate because we already mapped a signal in the closure, and now just need to convert it to the right type. Lmk if you don't like it!
> added `IntoSignal` and `IntoSignalSetter` helper traits

- integrations/axum/src/lib.rs
Here is a link to the clippy rule
https://rust-lang.github.io/rust-clippy/master/index.html#single_match
it is just cosmetic, a readability issue, found in two places.
> Removed clippy::single_match issue.

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- leptos_config/src/lib.rs
- leptos_dom/src/html.rs
- leptos_dom/src/logging.rs
- leptos_macro/src/props.rs
- leptos_macro/src/server.rs
- leptos_reactive/src/effect.rs
- router/src/history/params.rs
Here is link the clippy discussion
https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
lots of changes of the form
```
-        _ => format!("{}/{}", site_root, pkg_path),
+        _ => format!("{site_root}/{pkg_path}"),
```
To me this is a very minor readability change... 
The real advantage is that things  I feel strongly about are often lost in the noise of a large list.
When a more pressing problem occurs ... I want to see it.
> Minor: Clippy format!() all variables now inlined.

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
```
cargo clippy
```
Clippy suggest that these .clone() calls are not needed.
I am not making any performance assertions -  that these calls are on a 'hot' path or anything,
just suggesting doing less mem-copies is always good.
> Clippy: Removed stray calls to .clone().

- Cargo.toml
- integrations/actix/Cargo.toml
- integrations/axum/Cargo.toml
- leptos/Cargo.toml
- leptos_dom/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_reactive/Cargo.toml
- leptos_server/Cargo.toml
- meta/Cargo.toml
- router/Cargo.toml
Using workspace-level defined version and [dependencies](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-workspacedependencies-table) in order to make sure that the versions match and for reducing the work needed for creating a release.
The `main` branch doesn't compile, so I have not been able to test it.
> Workspace features

- leptos_macro/src/props.rs
This is a minor chippy warning 
Here is the link to the clippy issue page.
https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrowed_reference
> Clippy: Minor needless_borrowed_reference.

- examples/router/Cargo.toml
- meta/Cargo.toml
- router/Cargo.toml
Fixes an issue in which `leptos_meta` and `leptos_router` tried to erroneously use browser APIs on the server side, possibly after recent changes to workspace structure.
> Adjust default features for `meta` and `router`

- integrations/axum/src/lib.rs
- leptos_dom/src/components.rs
Sorry for the noise, 
It seems with all these minor changes we have changed the way chippy perceives the code-base
(Earlier today I found only 2 places where .clone() was called without reason.)
Now under iteration I see a  few more places, so this is round two.
> Removing clone call where possible(round2).

- examples/hackernews/src/main.rs
- examples/hackernews/src/routes/stories.rs
- examples/hackernews/src/routes/story.rs
- leptos_macro/src/props.rs
Previously I  have been sweeping up errors by running cargo clippy from the root directory.
Today I ran  "cargo clippy" from examples/hackernews.
The feature flags in this example change the build environment
running  "cargo clippy" here picks up a few more issues.
I WAS trying to fix issues class-by-class, but in this PR there are previously visited rules : -
Redundant clone issues.
clippy::uninlined_format_args
I hope that explains why some of these rules are re-appearing
Here is the clippy warning for a new ambiguous namespace issue found in the view macro
```
warning: `leptos_router` (lib) generated 3 warnings (run `cargo clippy --fix --lib -p leptos_router` to apply 3 suggestions)
Checking hackernews v0.1.0 (/home/martin/build/leptos/examples/hackernews)
warning: The view macro is …
```
> examples/hackernews - Cargo clippy fixes.

- examples/hackernews_axum/src/routes/stories.rs
- examples/hackernews_axum/src/routes/story.rs
This is similar to recent fixes related to examples/hackernews
examples/hackernews_axum changes the build flags in a way that is distinct and so exposed different clippy warning 
in short 
1) A couple of .clone() call are removed
2) more inline formatting.
3) namespace disambiguation  <html::a class="page-link">
> Minor: Clippy fixes related to hackernew_axum.

- examples/counter_isomorphic/Cargo.toml
- examples/hackernews/Cargo.toml
This is very minor ... a mix of version number for simple_logger were being used.
> simple_logger use version 4.0.0 everywhere.

- examples/hackernews/src/routes/stories.rs
- examples/hackernews_axum/src/routes/stories.rs
- integrations/axum/src/lib.rs
- leptos_dom/examples/test-bench/src/main.rs
- leptos_dom/src/html.rs
- leptos_macro/src/view.rs
This was double-inserting the query params, meaning they were not being parsed at all, causing a hydration mismatch.
> Correct Axum query handling

- examples/hackernews/src/routes/stories.rs
- examples/hackernews_axum/src/routes/stories.rs
- leptos_dom/examples/test-bench/src/main.rs
- leptos_dom/src/html.rs
- leptos_macro/src/view.rs
(instead of the too-annoying compile-time warning)
> Use a runtime warning about SVG `<a/>`

- integrations/actix/src/lib.rs
So basically I provide a way to resolve data before calling the app. This is how it looks when using it:
```rust
App::new().leptos_preloaded_data_routes(
leptos_options.clone(),
routes.to_owned(),
data_populate,
|cx, (data, theme)| view! { cx, <App theme data /> },
)
})
async fn data_populate(req: HttpRequest) -> Result<(JsonResponse, Theme), actix_web::Error> {
....
}
```
In the end, I made it as a new LeptosRoutes function, because like this it doesn't break backward compatibility. 
I will also need to refactor the integrations to support custom Actix Guards (my root path has a wildcard which means it needs to use a guard for Accept=text/html in order to not be used for things like favicon requests. 
Once the second refactoring is done, then we could discuss implementing any breaking …
> Pre resolved data

- leptos_macro/src/server.rs
The PR #144 left in a single extra `'/'` which was from the `format!` macro and was not properly converted to `'-'` because the replace call was changed. 
This PR updates the `format!` macro while on Windows to match everything else emitted from `span.source_file().path().to_string_lossy()` so the `replace()` properly cleans up everything.
> Update Generated API URL on Windows Attempt #2

- .github/workflows/test.yml
[`rust-cache`](https://github.com/Swatinem/rust-cache) can make CI faster. It caches `~/.cargo` and `./target`, disables incremental compilation and does some other things.
ref: https://matklad.github.io/2021/09/04/fast-rust-builds.html
> Use rust-cache in CI

- leptos_config/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_server/Cargo.toml
- router/Cargo.toml
This fixes 317
https://crates.io/crates/leptos_router
is bare ...  we are missing a link the the root README.md
> Minor: For each sub crate the landing page should be the root README.md.

- leptos_config/Cargo.toml
- leptos_macro/Cargo.toml
This is really minor.
typed-builder is used in 4 sub crates, it looks like there is a small oversight.
3 crates use 
```
typed-builder = "0.11"
```
1 crate 
```
typed-builder = "0.10"
```
"One of these kids is doing his own thing."
> typed-builder inconsistent version.

- README.md
- examples/counter_isomorphic/README.md
- examples/hackernews/README.md
- examples/hackernews_axum/README.md
- examples/tailwind/README.md
- examples/todo_app_sqlite/README.md
- examples/todo_app_sqlite_axum/README.md
Why:
- didn't know when reading the documentation if I had to serve the app myself or if it was listening on a port
What was done:
- Explain to open browser on localhost:3000 after leptos watch
> doc: add link for leptos watch

- benchmarks/src/ssr.rs
- benchmarks/src/todomvc/leptos.rs
- benchmarks/src/todomvc/mod.rs
- examples/todomvc/src/lib.rs
- leptos/tests/ssr.rs
- leptos_dom/src/hydration.rs
- leptos_dom/src/ssr.rs
- leptos_macro/src/lib.rs
- leptos_macro/src/view.rs
This reimplements the fast path for server-side rendering HTML elements by compiling static parts into an HTML string. I've tested it against the examples in the repo but it could definitely use more testing.
It's probably not as optimized as it could be. In particular, I think the need to insert so many hydration IDs on what are actually static elements slows it down significantly. This is something we should be able to address in the future.
> Reenable optimizations for SSR using the `view!` macro

- router/Cargo.toml
- router/src/history/location.rs
- router/src/history/params.rs
- router/src/history/url.rs
- router/tests/matcher.rs
- router/tests/query_params.rs
There is a behavior difference when we get search params (QueryString) right now between the SSR and Hydrate. Not only this, but both cases are sometimes just wrong. For example, if you have any parameter with a '+' encoded into the data it will be converted to a space in SSR. And it seems that Hydrate, can't handle any special character.
So here I am using the crate URL to parse the URL and get the query pairs and convert it to our ParamsMap. I am not sure why we are avoiding using this crate in Hydrate. If there is a good reason we might think of another way.
> Fix query params behaviour difference between SSR and Hydrate

- .gitignore
- leptos/tests/ssr.rs
- leptos_macro/Cargo.toml
- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
Couldn't find any guides for external contributor PRs, so I'm winging this a bit. 
- Allow `snake_case` functions to be used for components
- Add a unit test
- Update docs for `#[component]` macro (very minor change)
Added a little function which uses the `convert_case` crate to check whether `item.sig.ident` is `snake_case`, and if so it converts the `ident` to `PascalCase` (referred to as `camelCase` in the docs, but I don't think the distinction matters too much because most people refer to it as that anyway) which is later used to generate the `Component` and `ComponentProps` structs.
```rs
use convert_case::{Case::{Snake, Pascal}, Casing};
// . . .
fn convert_from_snake_case(name: &Ident) -> Ident {
let name_str = name.to_string();
if !name_str.is_case(Snake) {
name.clone()
} else { …
```
> Allow snake case components

- leptos/src/suspense.rs
- leptos_dom/src/components/errors.rs
- router/src/components/route.rs
- router/src/components/router.rs
There have been lots of improvements recently
Clippy is very good at spotting redundant .clone() calls, which I think are always good to removed, without spending the time to see if they are on a hot code path or not.
Might as well fix some reported .to_string() while I see them.
> Clippy fixes: redundant clone and .to_string() issues.

- leptos_reactive/Cargo.toml
> leptos_reactive base64 bump version to 0.21.

- examples/hackernews_axum/src/handlers.rs
- examples/todo_app_sqlite_axum/Cargo.toml
- examples/todo_app_sqlite_axum/src/main.rs
- examples/todo_app_sqlite_axum/src/todo.rs
- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- leptos_dom/src/ssr.rs
This closes #238 by adding `handle_server_fns_with_context()` and `render_app_to_stream_with_context()` functions to leptos_actix and leptos_axum. This lets you write your own handlers with whatever extractors you desire, and pass them in.
Here's an example for Axum:
```rust
//Define a handler to test extractor with state
async fn custom_handler(Path(id): Path<String>, Extension(options): Extension<Arc<LeptosOptions>>, req: Request<AxumBody>) -> Response{
let handler = leptos_axum::render_app_to_stream_with_context((*options).clone(),
move |cx| {
provide_context(cx, id.clone());
},
|cx| view! { cx, <TodoApp/> }
);
handler(req).await.into_response()
}
```
> Add methods to take Actix/Axum Extractors/Route Info/Stuff and pass it to Leptos

- router/Cargo.toml
- router/src/history/url.rs
Motivation: `percent-encoding` is from the Servo team and part of the `url` crate.
> Replace urlencoding with percent-encoding

- leptos_reactive/src/scope.rs
- router/src/components/outlet.rs
- router/src/components/route.rs
- router/src/components/routes.rs
This makes changes to the router so that the reactive scopes created in nested routes are children of the scope of the previously-matched route, not the root scope. This closes #370 by ensuring that each nested route has access to contexts provided by its parent (or grandparent), not only in the root route.
> Fix context in outlets

- integrations/axum/src/lib.rs
this avoids cloning the strings around, they can just be reused
> (micro optimization) cloning is not needed here

- leptos_server/src/action.rs
- router/src/components/form.rs
This one is a little tricky. Technically it is fixing a bug in `ActionForm` that led to it not resetting the action's `input` signal, which led to a discrepancy in behavior between `Action` and `ActionForm`. `Action.input()` should only be `Some(_)` if it is pending, and `None` if it is not pending, but `ActionForm` doesn't reset it.
So while this is a bugfix to bring `ActionForm` into alignment with the documented and expected behavior, it may also break some applications that were built on the buggy behavior... including my `example-darkmode` video! (Although it also explains the bug I encounter in that video around 49:24 — as I had built my implementation on top of the `ActionForm` bug, so could not figure out why the manual version with `Action` didn't work the same way.)
> fix: Align `<ActionForm/>` behavior with `Action`

- leptos_dom/src/html.rs
- leptos_dom/src/hydration.rs
- leptos_dom/src/macro_helpers/into_attribute.rs
- leptos_dom/src/macro_helpers/into_class.rs
- leptos_dom/src/macro_helpers/into_property.rs
This PR moves some client-side rendering and/or hydration code out of generic functions into concrete functions, allowing some small-but-respectable WASM binary size wins: about 5% for `todomvc` and about 2.5% for `hackernews` (more of which consists of serde/HTTP request code than in `todomvc`).
> Reduce WASM binary sizes by 3-5%

- meta/src/body.rs
- meta/src/html.rs
Clears warnings found by running
```cargo doc```
Markup not escaping HTML or BODY tokens could lead to "code injection" security problems.
> Escape <HTML> and <BODY> tokens in documentation markup.

- leptos/tests/ssr.rs
- leptos_macro/src/view.rs
> fix: correct types for top-level `<option>` and `<use>` in SSR `view` macro

- integrations/actix/Cargo.toml
- integrations/actix/src/lib.rs
- integrations/axum/Cargo.toml
- integrations/axum/src/lib.rs
Basically we're making ResponseOptions functions synchronous so that they can be called from either server functions or a non async component. parking_lot's RwLock is nice because it doesn't panic
> Switch RwLock to parking_lot so they are no longer async

- examples/errors_axum/src/error_template.rs
- examples/errors_axum/src/fallback.rs
- examples/errors_axum/src/landing.rs
- examples/errors_axum/src/main.rs
- leptos_macro/Cargo.toml
- leptos_macro/src/view.rs
Includes correctly escaping HTML-unsafe characters in the `view` macro
> Fix some small issues in `axum_errors` example

- leptos_macro/src/component.rs
Currently, if you use `#[component(transparent)]` on a component, and the `cx` has any other name besides `cx`, we get an error. This fixes this.
> fixes cx not found on components marked with #[component(transparent)]

- examples/errors_axum/README.md
- examples/errors_axum/src/error_template.rs
- examples/errors_axum/src/fallback.rs
- examples/errors_axum/src/landing.rs
- examples/errors_axum/src/main.rs
- examples/todo_app_sqlite_axum/src/error_template.rs
- examples/todo_app_sqlite_axum/src/fallback.rs
- examples/todo_app_sqlite_axum/src/main.rs
- examples/todo_app_sqlite_axum/src/todo.rs
- leptos_macro/src/component.rs
* Added a button to errors_axum example to generate a 500 error with a \<Form\>
* Correct README.md on errors_axum example
* Ran clippy on errors_axum and todo_app_sqlite_axum examples
```
cargo clippy --no-deps --features="csr"
cargo clippy --no-deps --features="ssr"
cargo clippy --no-deps --features="hydrate"
```
* Changed a few cfg_if blocks to help rust_analyzer code completion
* Added "http://" to log so the page can be directly opened from the terminal when server starts
> Several Minor Updates on Examples

- leptos/Cargo.toml
- leptos/src/show.rs
It should now render correctly when toggling between conditions multiple times, but sitll without rerendering on every change.
Closes issue #434.
> fix: correct behavior of `<Show/>` 

- leptos_config/src/lib.rs
Not sure if this is wanted or needed, was reading through the code to get a better understanding of how leptos works under the hood and saw some duplication. Figured I'd edit it and put up a PR. :) I'm happy to change it however folks want / delete the PR if it's not needed or wanted!
Some nice things:
- Only one implementation
- Unifies error messages
- Easier to see what's different between the usages
> Dedup from_str implementations for Env

- integrations/axum/Cargo.toml
there was a version number error in Cargo.toml which caused leptos_axum to depend on a separate older version of tokio
> use latest tokio in leptos_axum

- examples/todo_app_sqlite_axum/Cargo.toml
Thank you for Leptos!
Just a tiny update of the dependency path to Leptos from the `examples/todo-app-sqlite-axum` so that all of the examples build successfully
> fix: update leptos dependencies paths to the workspace

- leptos_config/src/lib.rs
> Clippy: "{input} is not a supported environment."

- leptos_macro/src/server.rs
Is this something worth doing? I came across wanting this while writing a little app to get more familiar with leptos. It means that all params to `#[server]` functions need to implement `Debug` but they already must implement `Serialize` and `Deserialize` so I imagine that's fine? In any case, feel free to close if not wanted / needed!
The specific use where I came across this was something like:
```rust
let pending_todos = move || {
submissions
.get()
.filter(|submission| submission.pending().get())
.into_iter()
.map(|submission| {
view! {cx,
// Inspect the whole struct not just one field
<li class="pending">{move || format!("{:?}", submission.input.get()) }</li>
}
})
.collect::<Vec<_>>()
};
```
> Derive debug for params struct in server macro

- examples/hackernews/src/routes/nav.rs
- examples/router/src/lib.rs
- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- router/Cargo.toml
- router/src/components/mod.rs
- router/src/components/redirect.rs
This creates a `<Redirect/>` component in the router that does two things
- when rendered on the server, sets appropriate headers to redirect to the given path
- when rendered on the client, uses client-side navigation to navigate
This can be mounted at a particular route in the `<Route/>` tree (see the `router` example), or can be rendered inline in a component.
> feature: add isomorphic `<Redirect/>` component (closes #412)

- leptos_macro/src/component.rs
Doesn't fix #465 but improves it in showing an error on invalid usage.
> error on non meta input for prop attribute

- examples/counter_isomorphic/src/main.rs
- examples/errors_axum/src/main.rs
- examples/hackernews/src/main.rs
- examples/hackernews_axum/src/main.rs
- examples/tailwind/src/main.rs
- examples/todo_app_sqlite/src/main.rs
- examples/todo_app_sqlite_axum/src/main.rs
- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- leptos_config/src/lib.rs
Should fix #446, by changing leptos internal options to site_addr
> Convert site_address to site_addr

- leptos_reactive/src/signal_wrappers_read.rs
Once again I'm not sure if there are any unforeseen consequences of doing this, just something I ran into while writing some code.
Enables not having to call `.to_string()` on a `&str` passed as a `MaybeSignal` like this:
```rust
<A class="navbar-brand" href="/">"link text"</A>
```
instead of this:
```rust
<A class="navbar-brand".to_string() href="/">"link text"</A>
```
> impl From<&str> for MaybeSignal<String>

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
The integrations initially sent I added the `<Html/>` component I merged the first two chunks in the HTML stream, leading to a bugged implementation that waited for the first `<Suspense/>` fragment to resolve instead of waiting for the point immediately before that. This fixes HTTP streaming behavior.
> fix: correct out-of-order streaming behavior (closes #473)

- leptos/src/lib.rs
- leptos_dom/src/macro_helpers/into_attribute.rs
- router/src/components/form.rs
- router/src/components/link.rs
- router/src/lib.rs
Made a few changes to `IntoAttribute` to make it usable as `Box<dyn IntoAttribute>` to support styling similar to native tags.
Before the `<A>` tag took a `MaybeSignal<String>` so you needed to do: 
```rust
view!{cx,
<A href="home" class="my-class".to_string()>
<A href="home" class=Signal::derive(cx, move || "my-class".to_string())>
}
```
Now you can do:
```rust
view!{cx,
<A href="home" class="my-class">
<A href="home" class=move || "my-class">
}
```
And it also works for `Form`, `ActionForm` and `MultiActionForm`
I tried really hard to implement this using generics, but it does not seem possible. The type of the generic parameter needs to be inferred even if its value is `None` because it needs to know what `Option::<T>::None` it is.
> Better styling for router related components

- examples/counters/src/lib.rs
- examples/counters_stable/src/main.rs
- examples/errors_axum/src/error_template.rs
- examples/hackernews/src/routes/stories.rs
- examples/hackernews/src/routes/story.rs
- examples/hackernews_axum/src/error_template.rs
- examples/hackernews_axum/src/routes/stories.rs
- examples/hackernews_axum/src/routes/story.rs
- examples/todo_app_sqlite_axum/src/error_template.rs
- examples/todomvc/src/lib.rs
- leptos/src/for_loop.rs
- leptos_dom/examples/test-bench/src/main.rs
- leptos_dom/src/components/each.rs
At present, because the `each_fn` doesn’t take a Scope as one of its arguments, each `EachItem` is rendered with the scope of the `Each` itself. This means that if there are dynamic children for example the `create_effect` will be created on the scope of the `Each`, not the `EachItem`, so it will be disposed eventually but not when the row is destroyed. This means as you create and destroy rows you keep allocating more and more signals.
> change: add `Scope` to view function in `<For/>` to avoid memory "leak"

- leptos_macro/src/lib.rs
- leptos_macro/src/view.rs
Render literal string as class in view macro correctly. This is currently allowed but produces incorrect html.
this code:
```rust
// Notice that "scope-class" doesn't have braces around it `{ ... }`
view!{cx, class="scope-class", ...}
```
Pre this PR:
Notice there's an extra attribute `scope-class""=""`.
This is because the quotes in `"scope-class"` get rendered and the browser turns that into its own attribute.
Post this PR:
The class renders correctly.
As a side note, the `Header` and `Banner` component that are inside of the `scope-class` scope don't have the `scope-class` applied. I don't know if this is intentional because they are components, but there it is.
This PR also includes updated error messaging if a user tries to use a class but forgets the trailing comma.
Pre this PR it …
> Allow literal string as class in view macro

- examples/router/src/lib.rs
- examples/router/src/main.rs
- leptos_reactive/src/scope.rs
- router/src/components/outlet.rs
- router/src/components/routes.rs
This addresses #498. It also involved cleaning up the `<Routes/>` code significantly, in a way that I think was *very* sorely needed and that makes me more comfortable with what's going on there now.
> fix: proper disposal of nested route scopes

- integrations/axum/src/lib.rs
The motivation is to allow users to remove additional boilerplate of ensuring that there is a ResponseOptions present before calling leptos_axum::redirect().
ResponseOptions do not exist during startup of the server when leptos_axum::generate_route_list() is called.
During the route building phase the Response does not need to be updated since it does not exist and the function can return immediately without a panic.
> In Axum Integration Remove unwrap() from redirect function

- leptos_dom/src/components/errors.rs
> leptos_dom erros.rs remove<E>() does not need to be generic.

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
Identify the CSS to reload from the href, which is already sent to the browser in the WebSocket message, instead of using the CSS `id`. 
This opens the possibility to have more than one CSS file that is hot-reloaded by `cargo-leptos`. I plan on using that for the Tailwind implementation.
This is backwards compatible with previous `cargo-leptos` versions.
@benwis Ok for you? I have to admit that I didn't test it with an Axum setup as I don't have one easily available. Would appreciate it if you could test it!
@gbj I would be really good to include this in release 0.2.0.
> Identify CSS to reload from the href

- examples/errors_axum/src/error_template.rs
- examples/fetch/index.html
- examples/fetch/src/lib.rs
- examples/hackernews_axum/src/error_template.rs
- examples/todo_app_sqlite_axum/src/error_template.rs
- leptos/src/error_boundary.rs
- leptos_dom/src/components/errors.rs
- leptos_reactive/src/resource.rs
I've been thinking about how to limit the API surface of `Errors` so we aren't committed to any particular internal implementation. I'm hoping to achieve the following with this PR:
- avoid the abstraction leak of exposing the fact that hydration keys are used as the keys in a map here
- avoid committing to backing this with a `HashMap` forever without being able to switch to another data structure
- implement `IntoIter` so you can just do this
```rust
for error in errors.get() {
// ...
}
```
- get over the slightly-awkward API of `errors.get().0` and friends
@benwis I'd like you to review this because a) it's your creation originally and b) without a doubt you're using this in more places than anyone else. Remember it's a lot easier for us to *add* additional methods in the future (not a …
> change: tweak API of `Errors` and implement `IntoIter`

- leptos_dom/src/events.rs
- leptos_dom/src/lib.rs
- leptos_dom/src/macro_helpers/into_attribute.rs
- leptos_dom/src/macro_helpers/into_class.rs
- leptos_macro/Cargo.toml
- leptos_macro/src/lib.rs
- leptos_macro/src/template.rs
- leptos_macro/src/view.rs
In particular circumstances (specifically, reusing an identical template a large number of times) the `<template>`-cloning approach of Leptos `0.0.x` had performance advantages over the more-flexible, more-reliable `0.1.x` renderer. This begins to reintroduce a constrained version of that approach by adapting the `0.0.x` `view` macro, for CSR only, for single elements only.
> feature: reintroduce limited template-node cloning w/ `template` macro

- examples/hackernews_axum/index.html
```bash
2023-02-18T15:49:42.957124Z ERROR ❌ error
error from HTML pipeline
Caused by:
0: error getting canonical path for "/leptos/examples/hackernews_axum/./static/style.css"
1: No such file or directory (os error 2)
```
> fix(examples): hackernews_axum styles href

- leptos/src/suspense.rs
> fix: more work on hydration IDs with `<Suspense/>`

- examples/counter_isomorphic/src/counters.rs
- examples/fetch/src/lib.rs
- examples/hackernews/src/routes/stories.rs
- examples/hackernews/src/routes/story.rs
- examples/hackernews/src/routes/users.rs
- examples/hackernews_axum/src/routes/stories.rs
- examples/hackernews_axum/src/routes/story.rs
- examples/hackernews_axum/src/routes/users.rs
- examples/router/src/lib.rs
- examples/ssr_modes/src/app.rs
- examples/todo_app_sqlite/src/todo.rs
- examples/todo_app_sqlite_axum/src/todo.rs
- leptos/src/suspense.rs
- leptos/src/transition.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/scope.rs
- router/src/lib.rs
Calling `Resource::read()` or `Resource::with()` crawls up the `Scope` tree, looking for the nearest `<Suspense/>` component, if any. This is used for streaming resource and suspense data from the server to the client during initial load, which is a significant optimization over waiting to start loading data until Wasm has loaded on the client.
Previously, a `Scope` was given to the `Resource` when it was created, and it carried this `Scope` around with it. Unfortunately, this meant that a `Resource` created in a "higher" scope couldn't be read correctly under a "lower" `<Suspense/>`. For example, if you created a resource in the root of your application, reading it under a `<Suspense/>` in one of your routes would not correctly register with the suspense, so would not properly stream. …
> change: pass `Scope` into `Resource::read()` and `Resource::with()`

- examples/parent_child/src/lib.rs
I thought I'd added this back into the example but apparently only did it in CodeSandbox.
> docs: add example of `<ButtonC on:click/>` syntax

- meta/src/html.rs
allows you to set class on the Html component.
do not like line 95, but is was done to fix a compile error, not sure how to resolve it
> feature: add class option to Html component

- meta/src/link.rs
Fixes [this issue](https://github.com/leptos-rs/leptos/issues/572).
> Make meta link as output correct attribute html

- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
- leptos_macro/src/params.rs
- leptos_macro/src/server.rs
- leptos_macro/src/template.rs
- leptos_macro/src/view.rs
I noticed that the `view` macro panic's on incorrect input. This can be a problem for language servers and semantically it's not really the correct thing to do.
I tried to minimize codepath's that are able to panic and replace panic's with `abort` where applicable.
Related: #227
> Macro `panic` hygiene

- examples/login_with_token_csr_only/Cargo.toml
- examples/login_with_token_csr_only/README.md
- examples/login_with_token_csr_only/api-boundary/Cargo.toml
- examples/login_with_token_csr_only/api-boundary/src/lib.rs
- examples/login_with_token_csr_only/client/Cargo.toml
- examples/login_with_token_csr_only/client/Trunk.toml
- examples/login_with_token_csr_only/client/index.html
- examples/login_with_token_csr_only/client/src/api.rs
- examples/login_with_token_csr_only/client/src/components/credentials.rs
- examples/login_with_token_csr_only/client/src/components/mod.rs
- examples/login_with_token_csr_only/client/src/components/navbar.rs
- examples/login_with_token_csr_only/client/src/lib.rs
- examples/login_with_token_csr_only/client/src/main.rs
- examples/login_with_token_csr_only/client/src/pages/home.rs
- examples/login_with_token_csr_only/client/src/pages/login.rs
- examples/login_with_token_csr_only/client/src/pages/mod.rs
- examples/login_with_token_csr_only/client/src/pages/register.rs
- examples/login_with_token_csr_only/server/Cargo.toml
- examples/login_with_token_csr_only/server/src/adapters.rs
- examples/login_with_token_csr_only/server/src/application.rs
- examples/login_with_token_csr_only/server/src/main.rs
Here is an example that demonstrates how you can use leptos for SPAs that use some kind of a API token (e.g. JWT).
**Motivation**:
I am considering porting an existing web application whose server/API cannot be changed and SSR is not needed initially. 
To get a sense of what an example looks like beyond a counter example, I chose this scenario.
Since I'm new to FRP, I'm interested in any feedback that could make the code cleaner.
> Add example: Login with API token (CSR only)

- router/src/matching/resolve_path.rs
- router/tests/resolve_path.rs
While reading this code to get a better understanding of it for possibly helping with the changes identified in #517 i came across a few things that looked like they could be cleaned up a little. There should be no functional changes in here, just code changes with the goal of simplifying some code, and removing the split between `ssr` and `not(ssr)` where possible.  Happy to change any of this or close the PR if it's not wanted / needed!
I also had a question I put as a line comment.
Also happy to add tests if there something you wanna make sure hasn't changed or whatever!
> Some cleanups in router/matching/resolve_paths

- examples/counter/Cargo.toml
- examples/counter/tests/mod.rs
a had to make some small tweaks to let the counter test example compile and pass.
I am not sure if web-sys is really needed, but it is used with websys::HtmlElement in the test.
please have a look at it.
> make counter test compile

- leptos_server/src/action.rs
- leptos_server/src/multi_action.rs
This PR changes when the value signal is set during `Action::dispatch()` and `MultiAction::dispatch()`. This aligns the behavior of `Action::dispatch()` with `<ActionForm/>`, which already sets the value signal before resetting the input signal ([see form.rs](https://github.com/leptos-rs/leptos/blob/ceb7bd398df73ba3bb0059467a06a42299484283/router/src/components/form.rs#L238)).
Before there was a brief moment, after the future resolves, where the state of input and value were the same as before the dispatch call.
> In `Action::dispatch()` set new value before resetting input signal

- leptos/src/transition.rs
- router/src/matching/resolve_path.rs
Just a couple of clippy fixes, only one is worth highlighting
all I have to say is when I draw out the equivalent logic elements this makes sense to me.
```
warning: this boolean expression can be simplified
--> leptos/src/transition.rs:122:24
|
122 |                       if (has_local_only && child_runs.get() > 0)
|  ________________________^
123 | |                         || !has_local_only
| |__________________________________________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#nonminimal_bool
= note: `#[warn(clippy::nonminimal_bool)]` on by default
```
> Minor: Clippy - Simplified conditional logic in transition.rs.

- leptos_dom/src/events/typed.rs
references used:
- https://developer.mozilla.org/en-US/docs/Web/API/
- web archives of the above before jul 11th 2022, relevant: https://github.com/mdn/content/issues/19590
> fix: added missing attributes of events that don't bubble

- router/src/components/router.rs
Previously, the console warning message tells user to add `feature = ["csr"]`. However, it's incorrect. This change rectifies the instruction to be adding `features = ["csr"]`.
> docs: fix instruction typos

- examples/errors_axum/Cargo.toml
- examples/hackernews_axum/Cargo.toml
- examples/login_with_token_csr_only/server/Cargo.toml
- examples/session_auth_axum/Cargo.toml
- examples/ssr_modes_axum/Cargo.toml
- examples/todo_app_sqlite_axum/Cargo.toml
This is as result of looking at cargo outdated 
As the code base currently  stands there is a  inconsistent policy in the stating of of version number of tower-http
in many places the full MAJOR.MINOR.PATCH is used.
in one place it stated only as MAJOR.MINOR .. 
The MAJOR.MINOR option  relies on the goodness of the crate below to not break anything with a PATCH update.
As I updated the version number I changed/unified the policy to MAJOR.MINOR only, If any reviewer objects I will unify  the patch to the  MAJOR.MINOR.PATCH pattern
There are lots of tabulation changes, but I think that is as result of my IDE picking up on the recently introduced 
rustfmt.toml file.
> Bump tower-http upto 0.4.

- router/src/components/form.rs
this is very minor ... I saw this while reading the code... might as well fix as go along.
> Minor: form component Removed unused variables.

- leptos_reactive/Cargo.toml
- leptos_reactive/src/serialization.rs
Working on clearing the output of 'Cargo outdated'.
> bump bytecheck to 0.7, remove deprecated simdutf8_std.

- leptos/Cargo.toml
- leptos_config/Cargo.toml
- leptos_macro/Cargo.toml
- meta/Cargo.toml
Despite being recently bumped, this is showing up again in the output from 
Cargo outdated.
> Bumped typed-builder up to 0.14.

- docs/book/src/14_create_effect.md
- docs/book/src/15_global_state.md
- docs/book/src/async/10_resources.md
- docs/book/src/async/11_suspense.md
- docs/book/src/async/13_actions.md
- docs/book/src/interlude_functions.md
- docs/book/src/testing.md
- docs/book/src/view/01_basic_component.md
- docs/book/src/view/06_control_flow.md
- docs/book/src/view/08_parent_child.md
- docs/book/src/view/09_component_children.md
- I converted all tabs to 4 spaces since some code examples were using a mix of both, which was making them display strangely on GitHub when I had my GitHub setting for "Tab size preference" set to something other than 4.
- I noticed that "rerun" and "re-run" were both used a lot, so I converted them all to "rerun" for consistency.
- In one of the test examples, it seemed like the intention was to calculate the number of remaining todos, but the variable was named "maximum", and it was actually calculating the number of completed todos, so I changed the code and the variable name to "num_remaining", and also used the variable name "num_remaining" in the other parts of that test example since I thought that made more sense, but if you would prefer that it be the shorter "remaining" instead …
> Typo fixes and other small changes to the docs

- leptos_reactive/src/signal_wrappers_read.rs
Clippy's way of saying this is : -
warning: using `clone` on type `Signal<T>` which implements the `Copy` trait
--> leptos_reactive/src/signal_wrappers_read.rs:523:52
|
523 |             Self::Dynamic(signal) => Self::Dynamic(signal.clone()),
|                                                    ^^^^^^^^^^^^^^ help: try dereferencing it: `*signal`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy
= note: `#[warn(clippy::clone_on_copy)]` on by default
> Clippy: signal_wrappers_read, was using .clone() when copy is available.

- examples/counter_isomorphic/Cargo.toml
- examples/errors_axum/Cargo.toml
- examples/hackernews/Cargo.toml
- examples/hackernews_axum/Cargo.toml
- examples/session_auth_axum/Cargo.toml
- examples/ssr_modes/Cargo.toml
- examples/ssr_modes_axum/Cargo.toml
- examples/todo_app_sqlite_axum/Cargo.toml
- examples/todo_app_sqlite_viz/Cargo.toml
- integrations/axum/Cargo.toml
- integrations/utils/Cargo.toml
- integrations/viz/Cargo.toml
- leptos_dom/examples/hydration-test/Cargo.toml
- leptos_dom/examples/test-bench/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_server/Cargo.toml
- meta/Cargo.toml
- router/Cargo.toml
- server_fn/Cargo.toml
- server_fn/server_fn_macro_default/Cargo.toml
- server_fn_macro/Cargo.toml
There are a lot of unused dependencies in the repo at this point, especially in examples. This applies `cargo machete` to remove them systematically. See #657.
> chore: apply `cargo machete` systematically

- leptos_reactive/src/runtime.rs
Missed a debug assertions config, might want to add a CI check for release build
> Fixed building in release (`cfg(not(debug_assertions))`)

- examples/router/src/lib.rs
- leptos_reactive/Cargo.toml
- leptos_reactive/src/runtime.rs
This one is... a little difficult to describe but very important. Switching to using an `IndexSet` rather than a `HashSet` ensures that the iteration order of both sources and dependencies in the reactive graph is always the same. This means that reactive nodes (memos) are updated in the same order on every update, which is important to maintaining efficient dynamic dependency arrays  Taken together with the laziness of memos, it has the effect of closing #339 by ensuring (I hope) that route params are not updated for an old route after navigation, etc.
> feat: maintain order of sources and dependencies

- leptos_dom/src/html.rs
- meta/src/link.rs
- meta/src/meta_tags.rs
- meta/src/script.rs
- meta/src/style.rs
Closes issue #576.
Various tags created by `leptos_meta` under a `<Suspense/>` would give hydration errors in streaming rendering because they were not found in the `<head>`. These warnings are not real—the framework simply creates the tags and makes sure they are injected into the head properly—so this PR suppresses them to avoid confusion with actual mismatches/bugs.
> fix: suppress spurious hydration warnings for tags in `leptos_meta`

- examples/counter_isomorphic/src/lib.rs
- examples/counters/src/main.rs
- examples/counters_stable/src/main.rs
- examples/errors_axum/src/lib.rs
- examples/fetch/src/main.rs
- examples/hackernews_axum/src/main.rs
- examples/router/src/main.rs
- examples/session_auth_axum/src/lib.rs
- examples/tailwind/src/lib.rs
- examples/todo_app_sqlite_axum/src/lib.rs
- examples/todo_app_sqlite_viz/src/lib.rs
- examples/todomvc/src/main.rs
I noticed that in a lot of the examples, `console_error_panic_hook::set_once()` was being called twice:
```
console_error_panic_hook::set_once();
_ = console_log::init_with_level(log::Level::Debug);
console_error_panic_hook::set_once();
```
so I removed the first one since most of the other examples were using this pattern:
```
_ = console_log::init_with_level(log::Level::Debug);
console_error_panic_hook::set_once();
```
Lef me know if you would prefer that I instead delete the second one, so that the order would be like this:
```
console_error_panic_hook::set_once();
_ = console_log::init_with_level(log::Level::Debug);
```
Also, I noticed that the [examples/tailwind/src/lib.rs](https://github.com/leptos-rs/leptos/compare/main...elliotwaite:leptos:fix-duplicate-panic-hook-calls?expand=1#di …
> examples: remove duplicate `console_error_panic_hook::set_once()` calls

- leptos_macro/src/view.rs
The following basic component is failing to compile on the current version of Leptos `v0.2.3`:
```
error[E0425]: cannot find value `cx` in this scope
```
```rust
use leptos::*;
#[component]
pub fn Button (scope: Scope) -> impl IntoView {
view!(scope, <button>"Click"</button>)
}
```
> `view!` macro not compiling with a non-default scope name

- leptos_dom/src/lib.rs
- leptos_dom/src/ssr_in_order.rs
- leptos_reactive/src/runtime.rs
As usual less .clone() calls
Just to signal things to come, there are two warnings which I am keeping behind, because I am going to suggest a change is approach which needs a different kind of review.
Here is the warning which I will cover in a upcomming PR
```
warning: unused `std::result::Result` that must be used
--> leptos_dom/src/ssr_in_order.rs:145:5
|
145 |     tx.unbounded_send(std::mem::take(&mut buffer));
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: this `Result` may be an `Err` variant, which should be handled
```
> Clippy: less .clone() calls, simpler pointer passing.

- leptos_server/src/action.rs
- leptos_server/src/multi_action.rs
-        Box::pin(async move { fut.await }) as Pin<Box<dyn Future<Output = O>>>
+        Box::pin(fut) as Pin<Box<dyn Future<Output = O>>>
My reading of this is the simplification: - 
The type coercion into the final concrete type only relies "Can I make what I have  into a 'Pin<Box<dyn Future<Output = O>>>'
> Minor: Simplifiy Box::Pin() call.

- examples/counter/Cargo.toml
- examples/counter_isomorphic/Cargo.toml
- examples/counter_without_macros/Cargo.toml
- examples/counters/Cargo.toml
- examples/counters_stable/Cargo.toml
- examples/error_boundary/Cargo.toml
- examples/errors_axum/Cargo.toml
- examples/fetch/Cargo.toml
- examples/hackernews/Cargo.toml
- examples/hackernews_axum/Cargo.toml
- examples/login_with_token_csr_only/client/Cargo.toml
- examples/parent_child/Cargo.toml
- examples/router/Cargo.toml
- examples/session_auth_axum/Cargo.toml
- examples/ssr_modes/Cargo.toml
- examples/ssr_modes_axum/Cargo.toml
- examples/tailwind/Cargo.toml
- examples/tailwind_csr_trunk/Cargo.toml
- examples/todo_app_sqlite/Cargo.toml
- examples/todo_app_sqlite_axum/Cargo.toml
- examples/todo_app_sqlite_viz/Cargo.toml
- examples/todomvc/Cargo.toml
- leptos_dom/examples/view-tests/Cargo.toml
The crate [console_log](https://github.com/iamcodemaker/console_log) has re-released the version 0.2.2 as 1.0.0 without changes (see [release](https://github.com/iamcodemaker/console_log/releases/tag/1.0.0) and [full changelog](https://github.com/iamcodemaker/console_log/compare/0.2.2...1.0.0)).
> chore: Upgrade `console_log` dependency to stable

- router/src/components/form.rs
Solution based on previous solution in #727. @gbj's PR included a manually inserted `?` when a leading `?` is present automatically in `Url.search`.
Context in Discord topic: https://discordapp.com/channels/1031524867910148188/1088151782766694490/1088151782766694490
> fix: include query params in navigation when `<ActionForm>` response redirects.

- examples/counter_isomorphic/src/counters.rs
This is a trivial fix for what I think is a bug in the counter_isomorphic example.  Whenever you visit the Multi-User counter, and then click away to one of the other counters.  The EventSource is closed `on_cleanup`, however an `EventSourceSubscription` seems to be sent after the source is closed, with a value of Err.
[Kooha-2023-03-22-22-34-54.webm](https://user-images.githubusercontent.com/364615/227088506-a4b06829-c87d-4f12-a24b-9022d838a61e.webm)
This PR simply matches the Result and takes the happy path in the Ok branch.  In the Err branch, I had to create and return a useless string, which makes me think there's probably a more idiomatic Leptos way to handle this kind of thing.  Any suggestions?  Thanks!
> avoid panic in counter_isomorphic Multi-User counter

- leptos_reactive/Cargo.toml
Just a minor change. 
PS by way of discussion when I look at bumping 
syn   1.0.109  ->   2.0.8 
it not possible at the moment, there is a messy sub dependency issue 
syn-rsx is moving more slowly that syn. -- in needs to internal starting using syn 2.x before we can increment to syn2.x
> leptos-reactive: Bumped serde-lite from 0.3 to 0.4.

- leptos/src/lib.rs
There was a typo in the section of the docs that pointed towards the hackernews example, so I fixed it by add the word "application."
> Fix typo in docs.

- docs/COMMON_BUGS.md
Due to no rust edition being present in a workspac's Cargo.toml, non
WASM compatible code can end up being built for a WASM target.
This commit documents this error and how to resolve it.
> Document cargo workspace feature resolver footgun

- leptos_reactive/src/memo.rs
> fix: correct typecast on `Memo::get_untracked` (closes issue #754)

- examples/counter_without_macros/src/lib.rs
- examples/counter_without_macros/src/main.rs
The `counter_without_macros` example was generated originally by expanding the `component` and `view` macros. Both of these generates code that's kind of ugly and overkill if you're not using any of the macros, but the ugliness is usually just hidden behind the prettiness of the macro DX so it's fine.
I've gone through, simplified it to look more like human-written code, and added some comments to explain aspects of the builder pattern.
> examples: improve `counter_without_macros`

- leptos_macro/Cargo.toml
- leptos_macro/src/component.rs
- leptos_macro/tests/ui.rs
- leptos_macro/tests/ui/component_absolute.rs
- leptos_macro/tests/ui/component_absolute.stderr
This  improves the behaviour / hygiene of the `component` macro, allowing for the following type of leptos component declarations, not requiring `use leptos::*` to be in scope.
```
#[::leptos::component]
pub fn MyComponent(cx: ::leptos::Scope) -> impl ::leptos::IntoView {
::leptos::view! { cx,
"ok"
}
}
```
Closes: https://github.com/leptos-rs/leptos/issues/747
> Allow component decl without `use leptos::*` in scope

- leptos_dom/src/ssr.rs
Because resources are serialized as a JSON string within a `<script>` tag, it turned out that any instance of the string `"</string>"` within a resource's value causes issues: in its infinite wisdom, the browser reads this as the end of the inline `<script>` with a syntax error for an unclosed string rather than continuing on until the end of the string and matching `</script>`. This causes all sorts of junk to appear at the end of the document.
This simply escapes the `<` character to identical JS Unicode, which prevents the issue. It imposes an `O(n)` string replacement cost on every resource so is probably not ideal. (I also cleaned up accidentally duplicating the serialized resource string, so this is a net performance win over the current state of things but a deopt over the ideal.)
> fix: escape `</script>` and other HTML tags in serialized resources

- examples/login_with_token_csr_only/client/Trunk.toml
When testing this example on Windows OS the initial value of ```0.0.0.0:3000``` for the IP did not work.
> Updated proxy settings to work on all OS

- router/src/components/route.rs
As discussed on Discord with @gbj it might be a good idea to introduce some sort of a ```ProtectedRoute``` that evaluates a condition and either redirects the user, or exposes a Route.
I am unsure if the condition is called correctly in its current form.
The overarching idea was taken from:  https://www.robinwieruch.de/react-router-private-routes/
> feat: Added ProtectedRoute component to route file

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- integrations/utils/src/lib.rs
- integrations/viz/src/lib.rs
- meta/src/lib.rs
This allows, specifically, for JS import maps, which must occur before any module loading begins (which we do right away so we can start loading WASM).
This addresses #694.
> change: insert `<head>` metadata tags at the beginning of the `<head>`

- meta/src/additional_attributes.rs
- meta/src/body.rs
- meta/src/html.rs
- meta/src/lib.rs
Adds a additional `attributes` property to the Html component so one can add several arbitrary attributes to the document's `<html>` element.
> Add arbitrary attributes to Html meta tag

- leptos_dom/src/ssr.rs
- leptos_dom/src/ssr_in_order.rs
- leptos_reactive/src/hydration.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/scope.rs
- leptos_reactive/src/suspense.rs
This PR addresses #617 and makes streaming server rendering more granular by creating "blocking resources." If you read a blocking resource under a `<Suspense/>` component, it prevents the server from returning *any* HTML until that particular `<Suspense/>` has resolved.
This is very useful in cases in which you need to wait for a particular resource to resolve before sending any HTML response. Imagine, for example, that you have a blog. To know whether a blog post exists you need to do an async read from a database. You want to send a 404 status code if the post doesn't exist. This means you need to wait for the database read to load before sending any part of the response. Currently, you can opt into `SsrMode::Async`, but that waits for *everything* on the page to load before rendering …
> Blocking resources

- server_fn/server_fn_macro_default/Cargo.toml
Fixes server function support on stable by forwarding the stable flag to the server_fn_macro crate in the default macro implementation.
> Fix server functions default macro on stable

- leptos_config/Cargo.toml
This removes an unused outdated dependency from `leptos_config`.
It was tripping up my `cargo deny` as it was pulling in a very old `bytes` and `futures 0.1` version that I blacklisted.
I found one function that I think it was intended to be used in, as said function is async despite not using any await.
> Remove unused fs dependency from leptos_config

- server_fn_macro/src/lib.rs
An unused bit of code in the server functions macro causes it to fail when non-copy types are set as the server context. This works for Leptos because scope is clone, but for other libraries like Dioxus this can cause issues.
> Fix server functions with non-copy server contexts

- server_fn_macro/src/lib.rs
When running cargo clippy on server functions that use `cx: Scope` it has an unused variable error.
It appears that the logic for adding an `#[allow(unused)]` notation is inverted.
> fix: unused warning on cx in server functions

- meta/src/body.rs
- meta/src/html.rs
- meta/src/lib.rs
This was documented in the crate docs, but fails silently at runtime. So adding a debug-mode warning about it should avoid issues like #796 in the future and make it easier for people to understand what's going on.
> docs: warn if you are using `leptos_meta` without features

- leptos_dom/Cargo.toml
- leptos_dom/src/events.rs
- leptos_dom/src/events/typed.rs
- leptos_dom/src/html.rs
- leptos_dom/src/lib.rs
I found myself needing to set options for events. I chose between putting it in the `Custom` event or creating a new `on_with_options` in `HtmlElement`. With arguments for and against both, I chose the event to avoid the combinatory explosion of optional parameters.
Comments are welcome.
> feat: Add ability to include options to event listeners

- leptos_reactive/src/runtime.rs
This also shrinks the size of signals and `Scope` by 8 bytes. 
Before:
```
print-type-size type: `signal::WriteSignal<usize>`: 24 bytes, alignment: 8 bytes
print-type-size     field `.ty`: 0 bytes
print-type-size     field `.runtime`: 8 bytes
print-type-size     field `.id`: 8 bytes
print-type-size     field `.defined_at`: 8 bytes
```
After:
```
print-type-size type: `signal::WriteSignal<usize>`: 16 bytes, alignment: 8 bytes
print-type-size     field `.runtime`: 0 bytes
print-type-size     field `.ty`: 0 bytes
print-type-size     field `.id`: 8 bytes
print-type-size     field `.defined_at`: 8 bytes
```
Then without `debug_assertions` it'll drop to 8 bytes for a single Signal.
> Reduce size of RuntimeId when slotmap is not used

- examples/session_auth_axum/src/main.rs
- examples/todo_app_sqlite_viz/src/todo.rs
- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- integrations/viz/src/lib.rs
- leptos_macro/src/lib.rs
- leptos_server/src/lib.rs
- server_fn/src/lib.rs
- server_fn_macro/src/lib.rs
Per popular request, I added the ability for server fns to be submitted via GET requests, with their args included in a query string! The encoding "GetJSON" and "GetCBOR" will do that, and return the response either via JSON or CBOR.
Let me know if I broke something, because I probably did. I modified the axum integration to make this work, but not the Actix one yet, and there's plenty of docs that still need to be updated.
Closes issue #788
> Add the ability for server fns to be submitted via GET requests

- leptos_reactive/Cargo.toml
- leptos_reactive/src/node.rs
- leptos_reactive/src/runtime.rs
Looking for places to remove memory allocations. Found this intermediate buffer and removed it.
I also marked `Runtime::mark` as `#[inline(always)]`. Due to opt-level s and z aggressively _avoiding_ inlining, such a hot function as `mark` would likely incur significant overhead to call in the loops.
Might even be worth looking into rerunning the js benchmarks after this.
> Optimize Runtime::mark_dirty

- README.md
I assume the leptos guide is the same as the book?
> remove `Leptos guide` link

- .github/workflows/check-stable.yml
- .github/workflows/check.yml
- .github/workflows/test.yml
- Makefile.toml
- leptos_dom/src/helpers.rs
- leptos_server/src/lib.rs
- router/src/components/redirect.rs
Enabling on all except for checking examples to start. I'll fix those and add it as a follow up.
Fixes #795
> chore: deny warnings on github actions

- docs/book/src/view/08_parent_child.md
The `Parent-Child Communication` segment of the Leptos book contains a broken URL to the `MaybeSignal` enum...!
https://leptos-rs.github.io/leptos/view/08_parent_child.html#parent-child-communication
This PR address the issue...!
P/S - Great work, btw...! <3
> [Fix] Correct broken `MaybeSignal` link

- leptos_reactive/src/context.rs
- leptos_reactive/src/diagnostics.rs
- leptos_reactive/src/effect.rs
- leptos_reactive/src/lib.rs
- leptos_reactive/src/memo.rs
- leptos_reactive/src/node.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/scope.rs
- leptos_reactive/src/selector.rs
- leptos_reactive/src/serialization.rs
- leptos_reactive/src/signal.rs
- leptos_reactive/src/signal_wrappers_read.rs
- leptos_reactive/src/signal_wrappers_write.rs
- leptos_reactive/src/slice.rs
- leptos_reactive/src/spawn.rs
- leptos_reactive/src/spawn_microtask.rs
- leptos_reactive/src/stored_value.rs
- leptos_reactive/src/suspense.rs
- leptos_reactive/src/trigger.rs
I would like to introduce the `Trigger` primitive to use in place of `RwSignal<()>`, simply to avoid unnecessary allocations and overhead in cases where many hundreds or thousands of them may be present.
`Rc<RefCell<dyn Any>>` will allocate 8-16 bytes (32-bit/64-bit) on the Rust heap even if the value stored is a unit type, while `Option<Rc<Refcell<dyn Any>>` will not allocate if `None`, and thanks to null-pointer optimization of `Option` will not increase the size of `ReactiveNode` at all. It also avoids the overhead of regular signal functionality. 
If not used by an application, this only adds about 200 bytes to the compiled WASM.
TODO:
Which I'll likely get to tomorrow. Submitting this as a draft for early feedback. 
My later plan is to use triggers inside a reactive Store structure …
> [WIP] Trigger prototype

- router/src/history/params.rs
The method `ParamsMap.to_query_string()` currently appends a `&` character at the end of query strings when they have one param or more, which is very ugly, specially to share URLs copy- pasting them.
> fix: Strip `&` from the end of params queries

- docs/book/src/async/11_suspense.md
- change the order in the match statement to avoid unreachable_pattern
by the way: the book is a great resource to learn about leptos, much appreciated!
> fix: match statement in leptos book

- README.md
This makes it easier to play around with Leptos without changing global settings.
> docs: Add per-project toolchain override readme

- examples/router/src/lib.rs
- examples/router/style.css
- router/src/components/outlet.rs
- router/src/components/routes.rs
`<AnimatedOutlet/>` and `<AnimatedRoutes/>` both insert a `<div>`, to which they apply the animation classes providing. This can interrupt existing styling, making it harder to style your app. This PR adds a `class` attribute to both components, which allows you to add some base classes that will be included under any animation state, making it possible to style the route outlet itself.
> feat: add non-animation base classes to `<AnimatedOutlet/>` and `<AnimatedRoutes/>`

- server_fn_macro/src/lib.rs
Following up on #857 
I tried the suggested `option_env!(...).unwrap_or(env!(...))`, but that runs into an error within the `concatcp` macro ([note: erroneous constant used](https://gist.github.com/snapbug/6c24a18d7c8998f93e76bc0d8d023a3a)). I tried to get multiple alternatives within the generated code to work, but all ran into this, or very similar variants of it.
I thought that the build context of `server_fn_macro` would probably be the same as that of the library being built, meaning the env that exists there probably exists when the lib using `#[server...]` is being built.
So, take advantage of that to decide which env var to use when building the library.
Results from cargo expand on counter isomorphic file:
Override env not set:
`cargo expand --bin counter_isomorphic …
> Use override key, if available, for server function calling

- leptos_dom/src/ssr_in_order.rs
I got some console.warn `element with id 0-0-4-2-2-2-7 not found, ignoring it for hydration` and page render error.
This error occurred when:
* SSR mode
* Route ssr=InOrder/Async
* create_resource() communicate with server
* <For /> component.
* cargo leptos build **--release**
I modify `examples/ssr_modes` to trigger this bug, here is <https://github.com/hjin-me/leptos/commit/0a22aef3649a798df461eaea7a5dc0b5f71e2524>
`cargo leptos watch` works fine, but `cargo leptos build **--release**` not.
I try to fix this bug in this merge.
Thanks.
> fix: <For/> rendering error in SSR InOrder/Async Mode

- examples/counter_without_macros/Cargo.toml
- examples/counter_without_macros/tests/web.rs
This improves the test by extracting distinct scenarios. 
It also demonstrates how you can:
- Remount the counter
- Frame tests from the user's point of view
- Query elements by exact text
Run `cargo make test-flow` to verify.
> Split counter without macros web test

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- integrations/viz/src/lib.rs
Closes issue #862 and a memory leak with potential security implications, which could be triggered by intentionally submitting bad inputs to a server function.
> fix: dispose of scope when server fns return error

- README.md
While the project offers a [Matrix][matrix] bridge, it is nowhere shown. One would need to join the [Discord][discord] server and search through it to find it.
To make it easier to join through [Matrix][matrix], add a badge in the project `README.md`.
[matrix]: https://matrix.org/
[discord]: https://discord.com/
Fixes: #893
> chore(readme): add link to Matrix bridge

- integrations/axum/Cargo.toml
- integrations/axum/src/lib.rs
This fixes #890 where leptos_axum is using the nightly only `OnceLock`, switching to use the `once_cell` dependency for now as per gbj.
> Fixes #890 that was using OnceLock, which is nightly only, by adding the once_cell crate as a dependency.

- leptos_reactive/src/resource.rs
Occasionally it's useful to have a resource that loads initially and then can be mutated subsequently, e.g., you load a list of blog posts from a database and then, on updating them, use the resource as a locally-cached version rather than refetching. This adds that ability.
> feat: add ability to mutate resources

- router/Cargo.toml
- router/src/components/routes.rs
- router/src/matching/mod.rs
The current `<Routes/>` implementation calculates the possible route branches on each request. But because every application should only have one `<Routes/>` component, and because the routing structure of the application should not change at runtime, this is less efficient than it could be. This PR stores the route branches in a thread-local static variable, so that they are only calculated once per server thread, rather than once per request, which should make requests faster.
This also removes a couple places in which the tree of branches was being cloned unnecessarily.
> perf: improve router performance on server by calculating route branches once

- leptos_dom/src/node_ref.rs
Avoids getting messages of unused reactivity.
When working with simple event handlers the use of NodeRef::get() triggers a diagnostic due to inner RwSignal that gets it `get` called. For this cases the simple get_untracked avoids this diagnostic message.
> Added get_untracked for node_ref.

- Makefile.toml
- examples/Makefile.toml
- examples/counter_without_macros/Makefile.toml
This makes it easier to run checks and tests for all examples. 
It also covers the `cargo make` part of  #210.
The Solution:
- Makes the examples directory a workspace
- Adds task flows that support lint, unit, and web testing
- Makes web testing optional
- Demonstrates calling from the leptos workspace
Run `cargo make test-examples` in the root to verify.
The `counters` example is excluded from the members until the test compile errors are fixed.
> Use cargo make to run tests for examples

- router/Cargo.toml
This eliminates cargo warning:
```
dependency (cached) specified without providing a local path, Git repository, or version to use. This will be considered an error in future versions
```
> chore: specify dependency version for cached

- Makefile.toml
- examples/todo_app_sqlite_axum/src/errors.rs
- examples/todo_app_sqlite_axum/src/todo.rs
- integrations/utils/src/lib.rs
- leptos_config/src/lib.rs
- leptos_config/src/tests.rs
- leptos_config/tests/config.rs
Tweaked the get_configuration function and the checks to make LEPTOS_OUTPUT_NAME required for compilation, but not with the compiled binary.
> Remove need for LEPTOS_OUTPUT_NAME env var after compilation

- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
The link-region could be done differently as well, but the main point is to not link to std's `Into` but the actual type in question.
> Link to actual type instead of Into trait for component properties

- leptos_macro/src/component.rs
I use `#[warn(missing_docs)]` to spot missing docs. But children don't need
documentation in many cases.
An alternative would be to allow passing-through a `#[allow(missing_docs)]` put
on the parameter, which is currently only supported for doc attributes.
> feat: add allow missing_docs to `children` field

- server_fn/server_fn_macro_default/src/lib.rs
I was looking into how I could use the Get (for caching) and found out that it was missing documentation for the `server` macro for those encodings. This PR add that documentation. Of course the user must register the leptos_axum::handle_server_fns for `get`.
> Adds the GetCbor and GetJson to server macro documentation.

- integrations/actix/src/lib.rs
Using Actix and Axum extractors in server functions is a frequently-requested feature and has been a pain point for users so far. This is somewhat easier to tackle with Actix than with Axum, but I suspect we can find a similar solution there. 
This function essentially lets you use Actix extractors directly in your server functions, with a similar syntax to the one that's familiar from Actix route handlers:
```rust
use serde::Deserialize;
#[derive(Deserialize)]
struct Search {
q: String,
}
#[server(ExtractoServerFn, "/api")]
pub async fn extractor_server_fn(cx: Scope) -> Result<String, ServerFnError> {
use actix_web::web;
extract(
cx,
|(data, search): (web::Data<String>, web::Query<Search>)| {
format!(
"data = {} and search = {}",
data.into_inner().to_string(),
search.q
)
},
)
.await
} …
```
> feat: add Actix `extract` helper

- examples/counter_without_macros/Cargo.toml
- examples/counter_without_macros/Makefile.toml
- examples/counter_without_macros/src/lib.rs
- examples/counter_without_macros/tests/business.rs
This demonstrates extracting and testing business logic.
Run `cargo make test-all` from the `examples/counter_without_macros` directory
You can also run `cargo make test-examples` from the `leptos/examples` directory.
> Test business logic for counter_without_macros

- leptos_macro/src/component.rs
This PR implements the `IntoView` trait for props generated from the `#[component]` macro. This is a **MASSIVELY HUGE** DX improvement for the builder pattern, because it allows the following usage:
```rust
#[component]
fn Comp(cx: Scope, prop_1: String, prop_2: usize) -> impl IntoView {}
fn example(cx: Scope) -> impl IntoView {
CompProps::builder()
.prop_1("hello!")
.prop_2(7)
.build()
}
```
> impl `IntoView` for component props

- leptos_dom/src/components.rs
- leptos_dom/src/components/fragment.rs
- leptos_dom/src/lib.rs
This implementation chooses to use `View::from(Fragment/ComponentRepr)` inside of their `IntoView` implementations.
Alternatively those could maybe be replaced by a generic: `impl<T: Into<View>> IntoView for T`, but I'm not sure if this would run into any issues with conflicting trait implementations, and I didn't know how the `#[instrument]` attributes would need to be placed.
fixes #941
> impl FromIterator for View

- Makefile.toml
- leptos_macro/example/Cargo.toml
- leptos_macro/example/src/lib.rs
- leptos_macro/src/component.rs
The current implementation mangled doc comments containing escapes.
> fix: escapes in doc comments on component properties

- router/src/components/routes.rs
- router/src/matching/mod.rs
Using a Vec<Branch> was breaking hosting multiple SPAs (on different paths) inside the same server.
I'm not sure if not allowing that is intended behaviour or not, but this patch seems to make it work.
> fix: use a HashMap on Branches::initialize

- leptos_macro/src/lib.rs
- leptos_server/src/lib.rs
- router/Cargo.toml
- router/src/components/form.rs
- server_fn/Cargo.toml
- server_fn/server_fn_macro_default/src/lib.rs
- server_fn/src/lib.rs
`serde_html_form` is a fork of `serde_urlencoded` that supports additional features that won't be supported by `urlencoded`.
The motivating example I have is an `ActionForm` with `create_server_action` where I want multiple fields to be combined into a single `Vec` argument to the `serverfn`, allowing for varying numbers of arguments. (Think: a todo list that you can select multiple items to mark done/delete in one action).
Typically this would be done with non-standard (from what I can tell) additions/encoding in www-form-urlencoded, `"field[]=1&field[]=2"` or `"field=1&field=2"`. The non-standard-ness is why it's not going to be added to urlencoded (https://github.com/nox/serde_urlencoded/issues/6 / https://github.com/nox/serde_urlencoded/issues/75).
The fork has already been adopted by …
> Replace `serde_urlencoded` with `serde_html_form` to support cross-input vec serverfn

- examples/cargo-make/common.toml
- examples/counter/src/lib.rs
- examples/counter/src/main.rs
- examples/counter/tests/web.rs
This cleans up the lint issues in the `counter` example.
Verification:
- Run `cargo make check-style` from the `examples/counter` directory
- Run `cargo make verify-examples` from the `leptos` root directory (`counter` passes but other examples fail)
> Fix the lint issues in the counter example

- examples/counter_isomorphic/Makefile.toml
- examples/counter_isomorphic/src/counters.rs
- examples/counter_isomorphic/src/lib.rs
- examples/counter_isomorphic/src/main.rs
This cleans up the lint issues in the `counter_isomorphic` example.
Verification:
- Run cargo make check-style from the examples/counter_isomorphic directory
- Run cargo make verify-examples from the leptos root directory (counter_isomorphic passes but other examples fail)
- Run `cargo leptos watch` from the leptos root directory and test manually
> Fix lint issues in counter_isomorphic example

- leptos_macro/src/lib.rs
- leptos_server/src/lib.rs
- router/Cargo.toml
- router/src/components/form.rs
- server_fn/Cargo.toml
- server_fn/server_fn_macro_default/src/lib.rs
- server_fn/src/lib.rs
- server_fn_macro/src/lib.rs
`serde_urlencoded` doesn't accept nested structs. (Makes sense: URL encoding is flat.) But server function arguments are already built into a struct, so they can be serialized. (Makes sense: otherwise how would you send named arguments?) But this means you can't send a struct as a server function argument: Sad panda.
~~I don't know if this will actually work so simply but there is a `#[serde(flatten)]` attribute that should allow this to be possible.~~
`#[serde(flatten)]` doesn't help without additional proc-macro work (because it can only be applied to structs, not primitives) but using `serde_qs` will solve the problem.
> feat: allow structs in server function arguments

- leptos/src/lib.rs
- leptos_dom/src/lib.rs
- leptos_dom/src/ssr.rs
- leptos_dom/src/ssr_in_order.rs
Compile errors for incompatible feature flag sets cause issues with tools that assume there's no such thing — which is best practice in terms of feature flags, so fair enough. This shifts to runtime warnings in some obvious places if you've goofed up.
> docs: switch from compile errors to runtime warnings for incompatible feature flags

- examples/counters/src/lib.rs
This cleans up the lint issues in the `counters` example.
Verification:
- Run `cargo make check-style` from the `examples/counters` directory
- Run `cargo make verify-example`s from the leptos root directory (`counters` passes but other examples fail)
> fix: lint issues in `counters` example

- examples/errors_axum/Makefile.toml
- examples/errors_axum/src/landing.rs
- examples/errors_axum/src/lib.rs
- examples/errors_axum/src/main.rs
This cleans up the lint issues in the `erros_axum` example.
Verification:
_From the **examples/erros_axum** directory..._
- Run `cargo leptos watch` and test manually
> fix: lint issues in `erros_axum` example

- examples/fetch/Makefile.toml
- examples/fetch/src/lib.rs
This cleans up the lint issues in the `fetch` example.
Verification:
_From the **examples/fetch** directory..._
- Run `trunk serve --open` and test manually
> fix: lint issues in `fetch` example

- examples/login_with_token_csr_only/Makefile.toml
- examples/login_with_token_csr_only/api-boundary/Makefile.toml
- examples/login_with_token_csr_only/client/Makefile.toml
- examples/login_with_token_csr_only/client/src/api.rs
- examples/login_with_token_csr_only/client/src/components/credentials.rs
- examples/login_with_token_csr_only/client/src/components/navbar.rs
- examples/login_with_token_csr_only/client/src/lib.rs
- examples/login_with_token_csr_only/client/src/main.rs
- examples/login_with_token_csr_only/client/src/pages/home.rs
- examples/login_with_token_csr_only/client/src/pages/login.rs
- examples/login_with_token_csr_only/client/src/pages/register.rs
- examples/login_with_token_csr_only/server/Makefile.toml
- examples/login_with_token_csr_only/server/src/adapters.rs
- examples/login_with_token_csr_only/server/src/main.rs
This cleans up the lint issues in the `login_with_token_csr_only` example.
Verification:
- Run `cargo make check-style` from the **examples/login_with_token_csr_only** directory
- Run `cargo make check-style` from the **examples/login_with_token_csr_only/api-boundary** directory
- Run `cargo make check-style` from the **examples/login_with_token_csr_only/client** directory
- Run `cargo make check-style` from the **examples/login_with_token_csr_only/server** directory
> fix: lint issues in `login_with_token_csr_only` example

- examples/router/Makefile.toml
- examples/router/src/lib.rs
This cleans up the lint issues in the `router` example.
Verification:
_From the **examples/router** directory..._
> fix: lint issues in `router` example

- examples/todo_app_sqlite/Makefile.toml
- examples/todo_app_sqlite/src/lib.rs
- examples/todo_app_sqlite/src/main.rs
- examples/todo_app_sqlite/src/todo.rs
This cleans up the lint issues in the `todo_app_sqlite` example.
Verification:
_From the **examples/todo_app_sqlite** directory..._
> fix: lint issues in `todo_app_sqlite` example

- examples/todo_app_sqlite_axum/Makefile.toml
- examples/todo_app_sqlite_axum/src/lib.rs
- examples/todo_app_sqlite_axum/src/main.rs
- examples/todo_app_sqlite_axum/src/todo.rs
This cleans up the lint issues in the `todo_app_sqlite_axum` example.
Verification:
_From the **examples/todo_app_sqlite_axum** directory..._
> fix: lint issues in `todo_app_sqlite_axum` example

- examples/todo_app_sqlite_viz/Makefile.toml
- examples/todo_app_sqlite_viz/src/lib.rs
- examples/todo_app_sqlite_viz/src/main.rs
- examples/todo_app_sqlite_viz/src/todo.rs
This cleans up the lint issues in the `todo_app_sqlite_viz` example.
Verification:
_From the **examples/todo_app_sqlite_viz** directory..._
> fix: lint issues in `todo_app_sqlite_viz` example

- examples/todomvc/Makefile.toml
- examples/todomvc/src/lib.rs
- examples/todomvc/src/storage.rs
This cleans up the lint issues in the `todomvc` example.
Verification:
_From the **examples/todomvc** directory..._
> fix: lint issues in `todomvc` example

- leptos/src/suspense.rs
This problem should ultimately be solved by #918. It's the same kind of issue as the earlier one with `<Show/>` not being disposed, but this was leading to runaway exponential rendering in `<Suspense/>` children. In theory #967 should have solved this in a better way, but I simply found that the finickiness of the DOM when doing things like moving document fragments around made it almost impossible to do without glitches. I've spent about 15 hours over the last two weeks on this and finally been defeated for now, I think.
I've tested this against each of the 3 memory leaks identified in #834 and found that none of them are still open on this branch, i.e., each example renders without a measurable increase in memory usage (or, in the case of the hackernews example itself, a small increase …
> fix: properly dispose of `<Suspense/>` scopes (closes #834)

- examples/cargo-make/common.toml
- examples/counter_isomorphic/src/main.rs
- examples/errors_axum/src/fallback.rs
- examples/hackernews/src/main.rs
- examples/hackernews_axum/src/api.rs
- examples/hackernews_axum/src/main.rs
- examples/session_auth_axum/src/fallback.rs
- examples/session_auth_axum/src/main.rs
- examples/session_auth_axum/src/todo.rs
- examples/ssr_modes/Makefile.toml
- examples/ssr_modes/src/main.rs
- examples/ssr_modes_axum/Makefile.toml
- examples/ssr_modes_axum/src/fallback.rs
- examples/ssr_modes_axum/src/main.rs
- examples/tailwind/Makefile.toml
- examples/tailwind/src/main.rs
- examples/todo_app_sqlite_axum/src/fallback.rs
- examples/todo_app_sqlite_axum/src/main.rs
- examples/todo_app_sqlite_viz/src/fallback.rs
- examples/todo_app_sqlite_viz/src/main.rs
This improves linting and cleans up related issues. The recent switch from compile errors to runtime warnings for incompatible feature flags made it possible to use the --all-features with clippy.
Verification:
- Run `cargo make verify-examples` from **leptos** root directory
- Manually test web applications
- `counter_isomorphic`
- `errors_axum`
- `hackernews`
- `hackernews_axum`
- `session_auth_axum`
- `ssr_modes`
- `ssr_modes_axum`
- `tailwind`
- `todo_app_sqlite_axum`
- `todo_app_sqlite_viz`
> test: lint examples with --all-features

- leptos_reactive/src/resource.rs
- leptos_reactive/src/selector.rs
- router/src/hooks.rs
Remove unneccesary `std::fmt::Debug` trait bounds on some functions.
> Relax Debug trait bounds

- docs/book/src/15_global_state.md
The MDBook UI doesn't work on the Global State Management page:
https://leptos-rs.github.io/leptos/15_global_state.html
This turned out to be because the iframe tag for the codesandbox embed wasn't closed.
This fixes it.
> book: close iframe tag on global state management page

- docs/book/src/view/02_dynamic_attributes.md
Adjust the intro in the Dynamic Attributes page to include the recent `dynamic style` feature. Also reorder a little given the order of the page body that follows.
> docs: adjust Dynamic Attributes page

- docs/book/src/ssr/21_cargo_leptos.md
the link to cargo-leptos' README erroneously pointed to a source file of the hackernews example, this PR fixes that.
> book: fix link to cargo-leptos README

- router/src/history/mod.rs
This could be a bit more verbose for people wanting to write their own integration with the router.
I copied the examples from how `ServerIntegration` is used [here](https://github.com/leptos-rs/leptos/blob/72414b7945dee81c37833b44b54285a36393dfc8/router/src/extract_routes.rs#LL61C51-L61C51).
probably should have opened an issue first before opening this, but alas. Likely an obvious thing for someone familiar with web, but more docs on finer details can be appreciated by newer people.
> docs: add examples for manual server integration

- Makefile.toml
- examples/Makefile.toml
- examples/cargo-make/common.toml
This reduces the storage space costs of running `cargo make verify-examples`.
`verify-examples` will now clean up cargo and trunk files as it goes along.
Verification:
- Run `cargo make verify-examples` and see target and dist folders are not present in examples.
> Clean up examples after verification

- router/Cargo.toml
- router/src/components/form.rs
> fix: corrects error-deserialization behavior of `ActionForm` (closes #1024)

- leptos/src/suspense.rs
- leptos/src/transition.rs
I'm so happy about this, as it took me a lot of messing around and turned out to be quite simple! Nota bene: if you ever find yourself needing to clone a `Fragment` and use it somewhere else, know that it doesn't work very well to clone a `Fragment` before you turn it into a `View`, but it *does* work very well to clone a `Fragment` and move it after you turn it into a `View`.
We can probably improve that but for now, this fixes the issue.
> fix: flicking `<Transition/>` in release mode (closes #960)

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- leptos/src/lib.rs
- leptos_dom/src/helpers.rs
- leptos_dom/src/html.rs
- leptos_dom/src/node_ref.rs
- leptos_reactive/src/signal.rs
- leptos_reactive/src/stored_value.rs
This removes the following deprecated APIs:
- Actix: `render_preloaded_data_app` and `.leptos_preloaded_data_routes()` (use `SsrMode::Async` with `<Suspense/>` instead)
- Axum: `generate_request_parts` (use `generate_request_and_parts` instead)
- `window_event_listener` is now the typed version (briefly `window_event_listener_with_precast`), and `window_event_listener_untyped` is the old `window_event_listener`
- `set_interval` no longer returns a handle (use `set_interval_with_handle` instead)
- `HtmlElement::from_html()` (mostly internal and related to SSR optimizations; if you were using this for some weird reason, use `HtmlElement::from_chunks()`) 
- `NodeRef::new(cx)` (use `create_node_ref(cx)`)
- `update_returning` etc. (use `try_update`)
- `StoredValue::get()`, `with()`, `set()`, …
> change: remove APIs that had been marked deprecated

- examples/tailwind_csr_trunk/Trunk.toml
The current example only works if there is already a created CSS file but on the first run it fails.
This patch should fix is.
> examples: fix trunk config to run tailwind at the right time

- examples/errors_axum/Cargo.toml
- examples/errors_axum/src/fallback.rs
- examples/errors_axum/src/main.rs
- examples/hackernews_axum/src/fallback.rs
- examples/hackernews_axum/src/main.rs
- examples/session_auth_axum/src/fallback.rs
- examples/session_auth_axum/src/main.rs
- examples/ssr_modes_axum/src/fallback.rs
- examples/ssr_modes_axum/src/main.rs
- examples/todo_app_sqlite_axum/src/fallback.rs
- examples/todo_app_sqlite_axum/src/main.rs
- integrations/axum/src/lib.rs
In axum, `State` provides compile-time type safety that `Extension` does not (https://github.com/tokio-rs/axum/discussions/1830).
When using `with_state` the axum router becomes `Router<_your state_>` rather than `Router`, meaning that `LeptosRoutes` is not `impl`'d for it. Update the default impl to work with a stateful router, provided the state can provide the options.
The addition of the `LeptosOptionProvider` trait allows the impl to be generic on any custom state struct, as long as it can provide the options. I added an impl for `LeptosOptions` itself, so all the examples continue to work when updated to with_state.
The `session_auth_axum` might be a good candidate to illustrate integration with a custom state, as it also uses other `Extension` layers, I'd be happy to do this 🙂
> Migrate axum integration to use `with_state` over `layer(Extension`

- integrations/actix/Cargo.toml
- integrations/actix/src/lib.rs
- router/src/components/form.rs
As a consequence, any extractor that needs to consume the Payload (like MultipartForm) should now work on server fns.
> fix: multipart forms on server fns

- examples/cargo-make/common.toml
- examples/todomvc/src/lib.rs
This resolves style errors in the `todomvc` example. It also ensures all examples respect the project format standards.
Verification:
- Run `cargo make check-style` from the **examples/todomvc** directory.
- Run `cargo make verify-examples` from the **leptos** root directory.
> fix: `todomvc` example style errors

- server_fn_macro/src/lib.rs
Add an option to specify the full server fn paths, so that one could define an API for external consumption with Leptos server Fns. Should close #1061
> Specify Server Fn Paths

- examples/cargo-make/cargo-leptos-web-test.toml
- examples/cargo-make/common.toml
This automates e2e setup for `cargo-leptos-web-test`s.
Verification:
From the **examples/tailwind** directory...
- Run `cargo make clean-all`
- Run `cargo make web-test`
> test: setup e2e automatically for tailwind example

- Cargo.toml
- leptos_hot_reload/Cargo.toml
- leptos_hot_reload/src/lib.rs
- leptos_hot_reload/src/node.rs
- leptos_hot_reload/src/parsing.rs
- leptos_macro/Cargo.toml
- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
- leptos_macro/src/slot.rs
- leptos_macro/src/template.rs
- leptos_macro/src/view.rs
- leptos_macro/tests/ui/component.stderr
- leptos_macro/tests/ui/component_absolute.stderr
- router/src/components/link.rs
- server_fn/Cargo.toml
- server_fn/server_fn_macro_default/Cargo.toml
- server_fn_macro/Cargo.toml
Hi.
Original author of syn-rsx is absent for a while.
I tried to reach him through the e-mail but have no luck with that.
I have created a fork of https://github.com/rs-tml/rstml 
With aim to better IDE support.
Fork contain few refactors which breaks the API, but during refactor all types became to be self-describing (every type contain all tokens that was parsed), which, i hope, will reduce future breaking changes.
In this PR i move from syn-rsx to rstml fork.
Which also bump minimum syn version to 2.0 (it was already in dependencies before)
1. Add support of unquoted text support.
2. Introduce recovery of parser after invalid closing tags, unclosed tags or invalid expression ( can be checked by semantic syntax highlight)
3. Simplified Node::Text ( no expressions, or other literals …
> Rsx parser with recovery after errors, and unquoted text

- examples/hackernews/src/lib.rs
- leptos_dom/src/components/dyn_child.rs
- leptos_reactive/src/lib.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/suspense.rs
- router/src/components/mod.rs
- router/src/components/outlet.rs
- router/src/components/progress.rs
- router/src/components/router.rs
- router/src/components/routes.rs
#994 describes the behavior used by many (but not all) frameworks: if you navigate to a new page in the client (after hydration or with client-side rendering) and async resources must be loaded to render it, rather than navigating immediately and showing a "Loading..." fallback, hold the current page until the resources have loaded.
I'm open to suggestions on how to opt into this. For the moment, I've done it by adding an optional `set_is_routing` prop to the `<Router/>` component that just takes a `WriteSignal<bool>` or similar.
```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
let (is_routing, set_is_routing) = create_signal(cx, false);
view! { cx,
<Router set_is_routing>
```
In my opinion this is kind of clever because it requires the user to provide some kind of indicator …
> feat: add "async routing" feature

- leptos_dom/src/components/each.rs
A release-mode optimization removed the closing comment when not needed, for `<For/>` rows that consisted of a single element. Unfortunately it didn't apply the same thing to omit the opening comment in debug mode, but also didn't append that opening comment to the DOM, leading to some broken logic (see #955, #1075, #1076)
> fix: debug-mode bugs in `<For/>` (closes #955, #1075, #1076)

- integrations/actix/src/lib.rs
Ignoring any header with a `None` key means that we can't set multiple cookies (for example).
The correct behaviour seems to be reusing the last non-None key from what I saw in the docs.
> fix: duplicate headers (like Set-Cookie) on the actix integration

- examples/todo_app_sqlite_axum/src/todo.rs
- integrations/axum/src/lib.rs
Typically, Axum extractors are called in an "access phase" at the beginning of processing a request, conceptually at the "root" of the application tree, before any rendering begins. Leptos is built in the other direction, allowing you to fetch data granularly closer to the "leaves" of the application, in individual components calling individual server functions. Because the Axum request can't be cloned, this has been awkward to handle and has necessitated special handler functions that then pass data down the context tree.
This PR introduces an `extract` function that can be called instead directly in a server function. `extract` takes a `Scope` (...of course) and a handler function that is very similar to an Axum handler, i.e., an async function that takes some number of extractors. …
> feat: add Axum `extract()` function

- docs/book/src/router/18_params_and_queries.md
Fix the signature for generic params in the ch18 of the docs, from `Memo<Result<T>, _>` to `Memo<Result<T, _>>`.
Thanks!
> docs: fix generic type

- examples/ssr_modes_axum/src/app.rs
> examples: fix suspense scope in `ssr_modes_axum`

- integrations/axum/src/lib.rs
- leptos_dom/src/ssr.rs
- leptos_dom/src/ssr_in_order.rs
- router/src/extract_routes.rs
The SSR and Axum integration were disposing of the reactive runtime slightly too early, which meant that reading context, using actions (with stored values), etc. could cause panics (see #1097). 
To do
> fix: dispose of runtime when stream is actually finished (closes #1097)

- examples/cargo-make/cargo-leptos-web-test.toml
- examples/cargo-make/common.toml
This **PR** addresses #1112, in order to support `ci` testing of examples.
_Verification:_
- [Remove playwright browsers](https://playwright.dev/docs/browsers#managing-browser-binaries)
- From the **examples/tailwind** directory
- Run `cargo make clean-node_modules`
- Run `cargo make web-test`
> build(examples): auto install playwright browsers (#1112)

- ARCHITECTURE.md
- CONTRIBUTING.md
I'm going to consider this one a way to finally close #59. It adds a `CONTRIBUTING.md` doc with some guidelines for contributors, as well as a high-level `ARCHITECTURE.md` with some thoughts on the overall structure.
I added issue templates finally in #1128.
We're at 118 contributors so far, so I don't think anyone's been too inhibited by the lack of these docs. But I think they're very good for the long term, and it's always good to have things written down in a document that were previously just in my head or in other, scattered posts.
> chore: add guide for contributors

- leptos_reactive/src/spawn_microtask.rs
this pr use js_sys Reflect to remove snippets/inline0.js file, which can simplify the deployment of leptos apps.
> work around for remove inline0.js

- leptos/src/suspense_component.rs
The renderer has some difficulty correctly unmounting nested fragments inside a dynamic child if you clone and reuse them. `<Suspense/>` was wrapping everything in an additional fragment from one of my early attempts to solve persistent hydration issues, but this turns out to be unnecessary, and seems to me to fix both these issues.
> fix: remove nested fragments from Suspense (closes #1094 and #960)

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
This closes a secondary issue raised in #1118, during which I realized that `leptos_meta` tags were not interacting correctly with blocking resources, i.e., the metadata for the `<head>` was being extracted before the blocking resources had actually resolved.
> fix: wait for blocking fragments to resolve  before pulling metadata (closes #1118)

- integrations/actix/src/lib.rs
- leptos_hot_reload/src/node.rs
- leptos_hot_reload/src/parsing.rs
- leptos_reactive/benches/fan_out.rs
- leptos_reactive/benches/narrow_down.rs
- leptos_reactive/src/suspense.rs
- router/src/components/outlet.rs
Lots of minor changes 
Only one thing worth talking about is the removal of a .clone() call.
As with the recent release of  rust 1.7 : cargo clippy has added a few new rules.
> Ran cargo clippy --fix.

- leptos_macro/src/view.rs
> feat: variable bindings on components and slots

- leptos_reactive/src/spawn_microtask.rs
In Function::call0 in js_sys is the same as calling a function without arguments, the only accept argument is a context object used to capture/pass "ambient" data. The method that we want to use to replace the inline javascript is Function::call1.
> fix queue_microtask

- examples/README.md
- examples/hackernews/src/lib.rs
- examples/hackernews_axum/src/lib.rs
- examples/router/src/lib.rs
- examples/ssr_modes/src/app.rs
- examples/ssr_modes_axum/src/app.rs
- leptos/Cargo.toml
- leptos/src/await_.rs
- leptos/src/lib.rs
- leptos_macro/example/src/lib.rs
- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
- leptos_macro/src/view.rs
- leptos_reactive/src/context.rs
Currently, all components are transformed into a function with two arguments: a `Scope` and a `Props` type. Constructing a `Props` type allows us to use named props in the `view` macro without support for named function arguments in Rust, which is great. However, it also means that components that take no props are still implemented as functions of two arguments (a `Scope` and an empty `Props` type).
This PR addresses a significant component of #766 by rewriting prop-less components into a function that only takes a `Scope`, while still allowing them to be used in the `view` macro. This enables a very useful shortcut for passing them into any component prop that takes something like `Fn(Scope) -> impl IntoView`.
For example, you can now create routes like this:
```rust
view! { cx,
<Route …
```
> feat: pass components with no props directly into the view as a function that takes only `Scope`

- leptos/src/suspense_component.rs
- leptos/src/transition.rs
Currently `<Suspense/>` and `<Transition/>` rerender their children each time they resolve. This is bad for rendering efficiency and causes issues like this https://github.com/leptos-rs/leptos/issues/398#issuecomment-1581144454, in which creating and reading resource inside a `<Suspense/>` immediately creates an infinite loop.
The changes in #1135 should make it possible to clone `<Suspense/>` instead of rerendering. We already move people toward reading resources reactively inside `<Suspense/>`, so that should continue to work.
TODO
> feat: clone <Suspense/> children instead of calling again (closes #398) 

- leptos_reactive/Cargo.toml
- leptos_reactive/src/runtime.rs
https://github.com/joshua-maros/ouroboros/issues/88 suggests `self_cell` in place of `ouroboros`. These things can be tricky. The iterator-based algorithm itself is still good.
> Replace ouroboros with self_cell

- Cargo.toml
This patch just clears the warnings listed below and ensures we get the benefits of a better package manger function.
```console
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
> Since rust 1.70 - the warnings about have gotten more particular.

- docs/book/src/server/25_server_functions.md
- leptos_macro/src/lib.rs
- leptos_server/src/lib.rs
This is intended to address both #952 and #1159 by adding additional explanations of why server functions suport the particular encodings they do, and not the `PUT` or `DELETE` methods or JSON encoding.
By default, the server function call is a `POST` request that serializes the arguments as URL-encoded form data in the body of the request. But here are a few other methods supported. Optionally, we can provide another argument to the `#[server]` macro to specify an alternate encoding:
```rust
#[server(AddTodo, "/api", "Url")]
#[server(AddTodo, "/api", "GetJson")]
#[server(AddTodo, "/api", "Cbor")]
#[server(AddTodo, "/api", "GetCbor")]
```
The four options use different combinations of HTTP verbs and encoding methods:
| Name              | Method | Request     | Response |
| …
> docs: clarify available server fn encodings

- leptos_reactive/Cargo.toml
Sorry for mirco PR's 
There are lots of packages marked as outdated.
I want to deal with them individually - So when problems occurs we can run git blame / git revert and know exactly what being changed.
This maybe the first of many PRs
> chore: criterion was outdated version 0.4.0 becomes 0.5.1.

- router/Cargo.toml
A small issue, but I find clearing these imperfections periodically is preferable, Otherwise splurging and fixing many before issuing a release is a headache ...  really subtle errors can creep in if one say fixes 10 in one go.
These things really need time to breathe.
> Chore: router -- cached is outdated was 0.43.0 is now 0.44.0.

- docs/book/src/async/13_actions.md
Used different names for add_todo server fn vs add_todo action as using the same name can cause confusion to newcomers to the framework.
On the first readthrough, seeing the same name being used for both action and the server function tripped me up a little.
> [documentation] Renamed function names in 13-actions chapter of book to reduce confusion

- leptos_hot_reload/src/parsing.rs
- leptos_macro/src/view.rs
- leptos_server/src/lib.rs
- server_fn/src/default.rs
- server_fn/src/lib.rs
The change in indentation makes the PR hard to review
so I will discuss the change in conversational language
Two "if"'s checks were merged into one "if"
this
-        if let Some(expr) = node.value() {
-            if let syn::Expr::Tuple(tuple) = expr {
becomes
+        if let Some(Tuple(tuple)) = node.value() {
> Removed clippy warnings - merged "if"s

- leptos_dom/examples/test-bench/src/main.rs
- leptos_dom/src/components/each.rs
This PR fixes more edge cases with `apply_diff` by reordering steps and simplifying `unpack_moves`.
> Reorder `<For />` `apply_diff` steps

- docs/book/src/appendix_binary_size.md
Fixes #1199 
`leptos_meta` fails to build under the following conditions:
1, using nightly
2, having `leptos_meta` as a dependency
3, using `rust-toolchain.toml` set to a nightly channel
4, following the advice on rebuilding std to remove panic info in section [Appendix: Optimizing WASM Binary Size](https://leptos-rs.github.io/leptos/appendix_binary_size.html#appendix-optimizing-wasm-binary-size)
This addition to docs aims to make it clear on how to fix this build error, should it arise.
If you'd like edits/changes/clarifications in the doc, let me know.
Thanks!
> Fix #1199 - Docs: Add note on how to fix failing builds which rebuild-std

- examples/Makefile.toml
READY TO REVIEW
Make it easy to update the `CARGO_MAKE_CRATE_WORKSPACE_MEMBERS` variable.
**Verification**
- Run `cargo make gen-members` from the **examples** directory.
> build(examples): generate workspace members variable

- leptos_dom/src/components/dyn_child.rs
`leptos_dom::DynChild` seems to have been re-mounting the child on the second run, no matter what, even if the child was identical. This causes no visible issues, unless you're using animations, in which case they restart. This was discovered in the `leptos_router::Outlet` component, where the first navigation would cause a re-mount, restarting animations.
I'm not sure this solution is correct, but I can't imagine how it could be incorrect—all it does is check whether the current child and the new child are the same, in which case I can't imagine why it would need to be mounted again.
> fix: don't re-mount identical child in `DynChild`

- CONTRIBUTING.md
- docs/book/src/interlude_projecting_children.md
- docs/book/src/metadata.md
- docs/book/src/reactivity/working_with_signals.md
- docs/book/src/view/01_basic_component.md
- docs/book/src/view/03_components.md
Just a few errors I spotted while I was reading thru the book. I hope to contribute more substantially in the future. 😉
> docs: a few grammar fixes, removal of ref to ComponentProps

- leptos/src/suspense_component.rs
- leptos/tests/test_examples/suspense-tests/Cargo.toml
- leptos/tests/test_examples/suspense-tests/src/app.rs
- leptos_dom/src/hydration.rs
- leptos_dom/src/ssr.rs
- leptos_dom/src/ssr_in_order.rs
- leptos_reactive/src/lib.rs
Currently, nested `<Suspense/>` (or `<Transition/>`) components that read from resources created at the top level are fine. However, creating a new resource inside the body rendered by the `<Suspense/>` causes issues (see #1156) because the stream does not wait for the newly-pending fragment to resolve. 
This PR should resolve that, allowing for nested data loading. While this is an antipattern (all resources should be hoisted out to a higher level instead to allow them to load in parallel) it's sometimes necessary—some resources just really do depend on the previous resource—and in any case it's a bug it to be broken without warning, I think.
> fix: nested Suspense/Transition with cascading resources

- leptos_server/src/action.rs
- router/src/components/form.rs
This adds an internal version counter to ensure that actions do not resolve to `pending: false` if there are multiple dispatches still in flight. It also properly translates errors encountered during `<ActionForm/>` POST requests into `ServerFnError::Request`.
Closes #1205.
> feat: improved error handling and version tracking for pending actions/`<ActionForm/>` (closes #1205)

- examples/fetch/src/lib.rs
- examples/session_auth_axum/src/auth.rs
- examples/session_auth_axum/src/todo.rs
- examples/todo_app_sqlite/src/todo.rs
- examples/todo_app_sqlite_axum/src/todo.rs
- examples/todo_app_sqlite_viz/src/todo.rs
- leptos/src/lib.rs
- leptos_dom/Cargo.toml
- leptos_dom/src/components/errors.rs
- leptos_server/src/lib.rs
- router/src/components/form.rs
- server_fn/src/error.rs
- server_fn/src/lib.rs
The `Result<T>` type provided by a library like `anyhow` is extremely useful for converting errors of different types into a single type using the `?` operator:
```rust
async fn fetch_cats(count: CatCount) -> Result<Vec<String>> {
if count > 0 {
// make the request
let res = reqwasm::http::Request::get(&format!(
"https://api.thecatapi.com/v1/images/search?limit={count}",
))
.send()
.await?
// convert it to JSON
.json::<Vec<Cat>>()
.await?
// extract the URL field for each cat
.into_iter()
.take(count)
.map(|cat| cat.url)
.collect::<Vec<_>>();
Ok(res)
} else {
Err(CatError::NonZeroCats.into())
}
}
```
However, `anyhow::Result` can't be directly rendered into the `view` of a Leptos component, because `anyhow::Error` doesn't implement `std::error::Error`. (In fact, it can't, because it …
> feat: add an `anyhow`-like `Result` type for easier error handling

- examples/counters_stable/e2e/playwright.config.ts
- examples/counters_stable/e2e/tests/add_1k_counters.spec.ts
- examples/counters_stable/e2e/tests/counters_page.ts
Fix #1240
The solution is to wait before clicking a button.
**Two Strategies**
1. Wait before each click attempt (used by most buttons)
2. Synchronize navigation and the wait for a button (used only by Add 1000 Counters button)
All buttons except the **Add 1000 Counters** button use strategy **1**. It is not clear why this is a requirement. Switching strategies breaks the test!?
> fix(counters_stable): intermittent closed target errors (#1240)

- leptos_macro/src/view.rs
As mentioned in [Discord](https://discord.com/channels/1031524867910148188/1031524868883218474/1123256306384502784), attributes prefixed with `prop:` are ignored with SSR in the `view` macro, though this can cause unused variable warnings. This was already fixed with event listeners, but props was never handled to remove warnings.
This PR simply adds `_ = #expr` to remove any unused variable warnings.
> chore: remove unused variable warnings with ssr props

- leptos_config/src/lib.rs
Current `get_config_from_str` and `get_configuration` will return an error when used in workspace environment.
This PR attempts to add support for root Cargo.toml in workspace environment.
Since it will always search for `[package.metadata.leptos]` first it shouldn't break existing examples (I have not really check each one of them).
Feel free to close this PR if you think there's a better alternative than just a slapping a fallback.
> Add fallback support for workspace in get_config_from_str

- leptos_dom/src/components/each.rs
We were using the `once_cell` in several places, and the newly-stabilized `std::once_cell::OnceCell` in one. It makes sense to use the same thing everywhere. 1.70 is still quite recent so for now I'm just using `once_cell` everywhere to avoid the MSRV issue for some users.
> fix: use `once_cell::OnceCell` rather than `std::OnceCell`

- examples/counter_isomorphic/Cargo.toml
- examples/counter_isomorphic/src/counters.rs
- examples/counter_isomorphic/src/main.rs
- examples/hackernews/src/main.rs
- examples/ssr_modes/src/app.rs
- examples/ssr_modes/src/main.rs
- examples/todo_app_sqlite/src/main.rs
- examples/todo_app_sqlite/src/todo.rs
This adds 404-page support to the Actix examples, making it easier to understand how to combine `/*catchall` routes with proper static-file service on Actix, bringing these examples up to parity with the Axum ones with their error route. See also https://github.com/leptos-rs/start/commit/dc3015aa974400f84377ccb6fb8aeeb2596577a6
This should close #1031.
> examples: add 404 support in Actix examples (closes #1031)

- docs/book/src/view/07_errors.md
- examples/error_boundary/src/lib.rs
type="number" prevents user from typing letters (at least in Chrome)
Nice lib!
> fixed example for error handling

- examples/tailwind/README.md
This adds instructions for adding tailwind plugins such as DaisyUI to the tailwind example. Someone besides me may find it useful.
> Adding instructions to add a tailwind plugin to examples.

- docs/book/src/view/08_parent_child.md
Removed extra `<F>` from 
```
#[component]
pub fn ButtonC<F>(cx: Scope) -> impl IntoView {
view! { cx,
<button>"Toggle"</button>
}
}
```
> fixed typo in parent-child doc

- leptos_dom/examples/test-bench/src/main.rs
- leptos_dom/src/components/each.rs
Hi! While reading through the code behind this guy: https://github.com/leptos-rs/leptos/issues/1289 I noticed that the `diff` makes some assumptions / calculations that may not be correct. In the example provided, if you type `C` then `a` notice the bottom two items `Cocos` and `Christmas` are out of order. This is with `add`s and `remove`s alone, no `move`s necessary. If you check the console you can see the data in the correct order. This results in not only a visual inconsistency but a panic on what i think is trying to reach an incorrect index. I think this PR as it stands solves that issue, and potentially any others with panicing / proper arrangement, but is of course not optimized. I don't have the time to finish this right now but wanted to leave it up in case it helps anyone else …
> Rework diff functionality for Each component

- leptos_dom/src/lib.rs
This addresses issues like #1248 by warning you if you create a `View` that is unused. This can create confusing issues, e.g., a stray semicolon causes you to return `()` instead of your intended `View` from a function, showing nothing. It can also cause hydration issues (the hydration system assumes that if something is created on the client, it exists in the HTML.)
> docs: must use `View`

- router/Cargo.toml
- router/src/matching/expand_optionals.rs
Uses `thread_local` `Lazy` for storing regex instances to avoid parsing the same regex multiple times on the client.
> feat: use lazy thread local for regex

- examples/counters_stable/Cargo.toml
- examples/counters_stable/e2e/tests/add_1k_counters.spec.ts
- examples/counters_stable/e2e/tests/add_counter.spec.ts
- examples/counters_stable/e2e/tests/decrement_count.spec.ts
- examples/counters_stable/e2e/tests/enter_count.spec.ts
- examples/counters_stable/e2e/tests/increment_count.spec.ts
- examples/counters_stable/e2e/tests/remove_counter.spec.ts
- examples/counters_stable/src/lib.rs
- examples/counters_stable/tests/web/add_1k_counters.rs
- examples/counters_stable/tests/web/add_counter.rs
- examples/counters_stable/tests/web/decrement_counter.rs
- examples/counters_stable/tests/web/enter_count.rs
- examples/counters_stable/tests/web/fixtures/counters_page.rs
- examples/counters_stable/tests/web/increment_counter.rs
- examples/counters_stable/tests/web/main.rs
- examples/counters_stable/tests/web/remove_counter.rs
Supports #210
Add wasm tests for Enter Count feature.
This PR covers 100% of e2e test scenarios.
_Thank you @gbj. The handler change from `on:input` to `on:input:undelegated` enabled the input to work as expected._
> test(counters_stable/wasm): enter count

- leptos_dom/src/lib.rs
- leptos_dom/src/ssr.rs
- leptos_dom/src/ssr_in_order.rs
Hi,
thanks for your work on Leptos.
I noticed these warnings while working on my project. Since `csr` is no longer a default feature as of 0.4.0, I figured the warnings should be updated.
> update warnings to remove mention of csr as a default feature

- leptos_config/src/lib.rs
In order to facilitate its usage in other structs, which might derive various traits, such as `serde::Serialize` or `PartialEq`, implement them for the `leptos_config::Env` enum.
> feat(config): implement common traits for Env

- leptos_dom/Cargo.toml
- leptos_hot_reload/Cargo.toml
- leptos_reactive/Cargo.toml
- meta/Cargo.toml
Not sure if y'all are interested but indexmap had a major version release a couple weeks ago:
https://github.com/bluss/indexmap/blob/master/RELEASES.md
Notably it includes a version bump of its underlying hashmap library hashbrown:
https://github.com/rust-lang/hashbrown/blob/master/CHANGELOG.md
Also notably it now requires rust 1.64 or later where as the previously specified highest version of 1.9.2 required rust 1.56.1 or later.
Just a little housekeeping PR, I'm not trying to advocate for anything. Feel free to delete this PR if it's not needed/wanted.
> Bump indexmap to version 2

- leptos_dom/Cargo.toml
- leptos_dom/src/events.rs
The current event delegation code causes an infinite loop if you have an input with the name `host`. This is because forms are given properties for their inputs, such that `form.host` now refers to the input, not to a theoretical `host` property that existed on the form previously.
```rust
#[component]
fn App(cx: Scope) -> impl IntoView {
let on_submit = |ev: SubmitEvent| {
ev.prevent_default();
log!("submit");
};
view! { cx,
<form on:submit=on_submit>
<input name="host"/>
<button>"Submit"</button>
</form>
}
}
```
Checking `host` is necessary to handle event delegation across shadow DOM roots. However, the order of these checks was also reversed so that this (less common) case was listed rather than the more common `parentNode` case.
> fix: event delegation issue with `<input name="host">`

- router/src/history/mod.rs
The router is intended to scroll to the top of the page on navigation unless `NavigateOptions.scroll` is set to `false`, or the `noscroll` attribute is set on an `<a>` element. Unfortunately the logic for checking this was slightly messed up, so it was not actually being done. This PR should fix that. 
It will appear as if it's a breaking change in the router's behavior but this is what sometimes happens when you fix a long-standing bug. If you have any questions about the changed behavior, feel free to let me know, but it should behave as above: the default behavior should be to scroll to the top of the window on navigation, and you must opt in to maintain the current scroll position.
> fix: routing logic to scroll to top was broken

- integrations/utils/src/lib.rs
> fix: check `LEPTOS_OUTPUT_NAME` correctly at compile time (closes #1337)

- leptos_reactive/src/resource.rs
This was responsible for the annoying-but-seemingly-innocuous `[Signal::update] You're trying to update a Signal<usize> that has already been disposed of.` warnings that would fire if, e.g., you defined a resource in the root of your app, read it under `<Suspense/>` somewhere, and navigated away, and then the resource updated again. Resources were not being properly instructed that they should unsubscribe the suspense counter that tracked how many resources under it were loading, so they tried to notify a suspense that no longer existed.
> fix: un-register `<Suspense/>` from resource reads when `<Suspense/>` is unmounted

- Makefile.toml
- cargo-make/main.toml
- integrations/actix/Makefile.toml
- integrations/axum/Makefile.toml
- integrations/utils/Makefile.toml
- integrations/viz/Makefile.toml
- leptos/Makefile.toml
- leptos_config/Makefile.toml
- leptos_dom/Makefile.toml
- leptos_hot_reload/Makefile.toml
- leptos_macro/Makefile.toml
- leptos_macro/src/view.rs
- leptos_reactive/Makefile.toml
- leptos_server/Makefile.toml
- meta/Makefile.toml
- router/Makefile.toml
- server_fn/Makefile.toml
- server_fn/server_fn_macro_default/Makefile.toml
- server_fn_macro/Makefile.toml
Add the ability to run `ci` checks and tests from either the workspace root or a member directory.
- Support test driven development workflow
- Enable crate level `ci` workflows
- Move common tasks to the `cargo-make/main.toml`
- Extend all workspace members from `cargo-make/main.toml`
- Move project specific tasks to `leptos`
- Move project specific tasks to `leptos_macro`
- Replace `check-all-release` with `check-release`
> build: run tasks from workpace or member directory

- examples/todo_app_sqlite/src/todo.rs
- examples/todo_app_sqlite_axum/src/todo.rs
- examples/todo_app_sqlite_viz/src/todo.rs
Rather than using cfg_if to re-define structs with and without sqlx::FromRow, we can use cfg_attr to conditionally derive sqlx::FromRow. This simplifies the sqlite todo examples.
> use cfg_attr for conditional derives

- Cargo.toml
- leptos_reactive/src/resource.rs
- leptos_reactive/src/signal.rs
- meta/Cargo.toml
- router/Cargo.toml
This is basically always a case of "we navigated away from the page but there's no way to cancel the resource load." The warnings were confusing and annoying and gave the impression that something was broken that was not.
I've now
- added `defined_at` markers to this warning
- removed it for `try_set` and `try_update`, on the theory that you don't need a warning when you explicitly say something's fallible and it fails
- used  `try_update` for resource internals, so that these would not warn
> docs: don't warn when a resource resolves after its scope has been disposed

- integrations/utils/src/lib.rs
> fix: duplicated meta content during async rendering

- leptos/src/error_boundary.rs
> fix: hydration-key conflicts between `<ErrorBoundary/>` children and fallback

- .github/workflows/ci.yml
- leptos/Makefile.toml
Only run the **CI** workflow when a file in a workspace member directory changes.
This will speed up checks for non-source changes.
> ci(ci): only run on source change

- .github/workflows/check-examples.yml
- leptos/Makefile.toml
Only run the **Check Examples** workflow when a file in a workspace member directory changes.
This will speed up checks for changes that do not affect the examples.
> ci(check-examples): only run on source change

- leptos/src/transition.rs
- leptos_dom/src/hydration.rs
Currently there's a bug with `<Transition/>`: if you are in hydrate mode, on first page load it correctly shows the fallback, then subsequently whatever the previous children were. However, on subsequent navigations it never shows the fallback, because it incorrectly assumes that the children have been streamed down from the server as if it were first page load. This should fix that issue.
> fix: correctly show fallback for Transition on first load even if not hydrating

- docs/book/src/testing.md
The current link here `404`s - this just fixes the link in the book markdown
> fix: update link to example code in book testing page

- docs/book/src/15_global_state.md
- docs/book/src/async/10_resources.md
- docs/book/src/async/11_suspense.md
- docs/book/src/async/12_transition.md
- docs/book/src/async/13_actions.md
- docs/book/src/reactivity/14_create_effect.md
- docs/book/src/router/17_nested_routing.md
- docs/book/src/router/18_params_and_queries.md
- docs/book/src/router/19_a.md
- docs/book/src/router/20_form.md
- docs/book/src/view/01_basic_component.md
- docs/book/src/view/02_dynamic_attributes.md
- docs/book/src/view/03_components.md
- docs/book/src/view/04_iteration.md
- docs/book/src/view/05_forms.md
- docs/book/src/view/06_control_flow.md
- docs/book/src/view/07_errors.md
- docs/book/src/view/08_parent_child.md
- docs/book/src/view/09_component_children.md
I experience sporradic unavailability with the code sandbox MicroVM embed that we're using in the book. It's very nice when it works, but I was getting an error where I couldn't read the examples at all. This drops the text of all MicroVM examples into the book itself behind a `<preview>` so that readers can still view the source even if CodeSandbox is wonky.
> doc: previews to backup CodeSandbox

- leptos_hot_reload/src/patch.js
I believe this will fix [the bug I reported previously](https://github.com/leptos-rs/leptos/issues/1355). If nothing else, to the best of my abilities I am now unable to reproduce the bug.
TL;DR: 
In one of the instances where you created a tree walker, you instantiated it with a filter. The filter was however incorrect. It returned a boolean true/false, where the spec states it needs to be one of 3 enum values, `NodeFilter.FILTER_{ACCEPT,REJECT,SKIP}`.
The first commit, which I am happy to remove if you want me to(!), is a reformatting pass of the patch javascript file. It had a mix of indentation styles and tabs and spaces.
> Hot reload bug-fix

- leptos/Cargo.toml
- leptos_dom/Cargo.toml
- leptos_dom/src/hydration.rs
- leptos_dom/src/lib.rs
`leptos_dom`, unlike the other packages, doesn't currently separate `csr` and `hydrate` but merges them into one `web` feature. This splits them apart, simply for the purpose of disabling some of the hydration code. This saves several kilobytes of WASM binary size in `csr` mode.
> perf: exclude hydration code in CSR mode

- integrations/axum/src/lib.rs
- leptos_reactive/src/runtime.rs
Reactive runtimes are stored a slotmap inside a thread-local variable. Because the reactive is `!Send` (see #832 for details and considerations), this is necessary. However, it means that the runtime needs to be created and disposed from the same thread. While we are required by the fact that the runtime is `!Send` to pin the responses to the current thread, unfortunately the way that the current implementation is written meant that `runtime.dispose()` was called outside that pinned block, meaning that in almost every case it did *not* actually find the relevant runtime by its ID in the map of reactive runtimes, because it was looking in the thread-local on the wrong thread.
This PR fixes that issue, closing a per-request memory leak in the Axum integration.
It also unwraps the attempt to …
> fix: memory leak in `leptos_axum`

- examples/todo_app_sqlite_axum/src/todo.rs
This slipped in as a demo of the ability to handle `POST` requests during rendering, but I accidentally committed it. It has the potential to create confusion by doing an unenhanced full-reload. (See #1391) I'm just removing it to match the `todo_app_sqlite` example.
> examples: remove random `<form>`

- leptos_reactive/src/resource.rs
Implements `SignalDispose` for resources, meaning you can call `resource.dispose()` to dispose of it before its reactive scope has been disposed. This can be useful for things like caching, in cases in which you want to dispose of a resource independently of the rest of the UI.
> feat: implement `Resource::dispose()`

- cargo-make/lint.toml
- cargo-make/main.toml
- integrations/utils/src/lib.rs
- leptos_config/src/lib.rs
- leptos_dom/src/helpers.rs
- leptos_dom/src/lib.rs
- leptos_reactive/src/lib.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/scope.rs
- leptos_reactive/src/serialization.rs
- leptos_server/src/lib.rs
- leptos_server/src/multi_action.rs
- router/src/lib.rs
- router/src/matching/expand_optionals.rs
Add clippy to the `lint` task.
- Support conditional compilation with `cargo hack`
- Fix most violations
- Defer resolution of [incorrect clone implementation](https://rust-lang.github.io/rust-clippy/master/index.html#/incorrect_) errors
- Add clippy to `ci` flow
- I did not find a way to pass clippy options with `cargo hack`
_See [Clippy Lints](https://rust-lang.github.io/rust-clippy/master/index.html) for rule details._
> ci: lint with clippy

- docs/book/src/router/16_routes.md
- docs/book/src/router/17_nested_routing.md
- docs/book/src/router/18_params_and_queries.md
- docs/book/src/router/19_a.md
- docs/book/src/router/20_form.md
- docs/book/src/ssr/23_ssr_modes.md
- examples/errors_axum/src/landing.rs
- examples/session_auth_axum/src/todo.rs
- examples/todo_app_sqlite_axum/src/todo.rs
- examples/todo_app_sqlite_viz/src/todo.rs
- leptos/tests/test_examples/suspense-tests/src/app.rs
- router/src/lib.rs
#1144 made it possible to change this
```
<Route path="" view=|cx| view! { <HomePage/> }/>
```
to this
```
<Route path="" view=HomePage/>
```
This makes this change in the examples and docs to reflect this newly-available syntax.
> docs/examples: use shorthand form for `<Route/>` views when possible

- leptos_macro/src/view.rs
> fix: `RawText`/unquoted text nodes in SSR (closes #1384)

- leptos_macro/src/view.rs
> fix: closing element names wrong for `svg::`, `math::`, and `use_` (closes #1403)

- leptos_macro/src/view.rs
> fix: `<use_/>` as typed top-level element in view

- examples/Makefile.toml
READY
Add the `test-info` task to report the test runners for each example that run during `ci`.
Make it easy to find out:
- Which examples have `ci` tests?
- How many types of tests do examples use?
- Where can I find an example of a specific test runner?
The `test-info` task has two modes. The default only includes examples that run tests during `ci`. You can also pass any argument to include all examples in the report.
- Run `cargo make test-info` from the **examples** directory
- See a report similar to the following...
```console
[cargo-make] INFO - Running Task: test-info
CI test runners by example...
counter -C-W
counters -W
counters_stable -W-P
counter_without_macros -R-W
js-framework-benchmark -W
router -P
tailwind -L
Test Runners: C = Cargo Test, L = Cargo Leptos Test, P = …
```
> build(examples): make it easy to see which examples do what kind of testing

- leptos_dom/src/lib.rs
- leptos_dom/src/node_ref.rs
- leptos_reactive/src/lib.rs
- leptos_reactive/src/memo.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/signal_wrappers_read.rs
- leptos_reactive/src/signal_wrappers_write.rs
- leptos_reactive/src/stored_value.rs
- leptos_server/src/action.rs
- leptos_server/src/lib.rs
- leptos_server/src/multi_action.rs
This is a good lint! Ensures correctness, catches one issue (the `tracing` instrumentation can't be added to a `Clone` that is also `Copy`), and encourages removing a bunch of redundant lines of code in a way I hadn't thought of previously.
Closes #1401.
> chore: resolve clippy `incorrect_clone_impl_on_copy_type` (closes #1401)

- leptos_hot_reload/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_macro/src/lib.rs
- leptos_macro/src/view.rs
It's marked as feature, since in rstml v0.11.0 i added support of numbers in dash seperated attributes
https://github.com/leptos-rs/leptos/issues/73
https://github.com/rs-tml/rstml/issues/9
Currently during parse it follows SGML rule:
ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").
https://www.w3.org/TR/html4/types.html#type-cdata
So special symbols are still forbidden in attribute names.
> Feat: Update rstml to v0.11.0

- leptos_reactive/src/signal.rs
* Remove "either" because it didn't make sense in the sentence
* Change "cause cause" to "not cause"
> Fix warning message about updating a signal after it has been disposed

- Makefile.toml
- examples/cargo-make/compile.toml
- examples/cargo-make/main.toml
- examples/counter/Makefile.toml
- examples/counter_isomorphic/Makefile.toml
- examples/counter_without_macros/Makefile.toml
- examples/counters/Makefile.toml
- examples/counters_stable/Makefile.toml
- examples/error_boundary/Makefile.toml
- examples/errors_axum/Makefile.toml
- examples/fetch/Makefile.toml
- examples/hackernews/Makefile.toml
- examples/hackernews_axum/Makefile.toml
- examples/js-framework-benchmark/Makefile.toml
- examples/leptos-tailwind-axum/Makefile.toml
- examples/login_with_token_csr_only/Makefile.toml
- examples/parent_child/Makefile.toml
- examples/router/Makefile.toml
- examples/session_auth_axum/Makefile.toml
- examples/slots/Makefile.toml
- examples/ssr_modes/Makefile.toml
- examples/ssr_modes_axum/Makefile.toml
- examples/tailwind/Makefile.toml
- examples/tailwind_csr_trunk/Makefile.toml
- examples/timer/Makefile.toml
- examples/todo_app_sqlite/Makefile.toml
- examples/todo_app_sqlite_axum/Makefile.toml
- examples/todo_app_sqlite_viz/Makefile.toml
- examples/todomvc/Makefile.toml
Reduce task duplication
Supports (#210)
- Move duplicate `check` and `build` tasks to a common file
- Add project level tasks with automated cleanup to simplify local testing
> build(examples): pull up compile tasks

- router/src/components/form.rs
This already works for `a` tags,
https://github.com/leptos-rs/leptos/blob/daeb47e72e7e0e384fa33db7af2df88da21ace68/router/src/components/router.rs#L418
but unless I missed something there was no equivalent for forms.
> feat: add `noscroll` attribute to `Form`, `ActionForm`

- leptos/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_server/Cargo.toml
- server_fn_macro/Cargo.toml
- server_fn_macro/src/lib.rs
The current server-function implementation includes `#[cfg(feature = "ssr")]` in its codegen, which means that it actually checks an `ssr` feature in your application code, not whether an `ssr` feature is enabled for `server_fn_macro` itself. This means that your application is forced to use `ssr` as a feature name and not, for example, `server`. 
This PR instead checks the feature when the proc-macro runs, rather than emitting it into the generated code, which means that it will check which features are enabled on `server_fn_macro`, not in your application. This means you can name your features whatever you want — say `server` and `client` instead of Leptos's go-to `ssr` and `hydrate` — and it will work.
I've tested this by running the `todo_app_sqlite` example as is against the new …
> feat: allow feature-name flexibility when using server functions

- leptos_dom/src/components/each.rs
The calculation being used at line 398 was correct for release mode, and both unnecessary and incorrect for debug mode, where we have an explicit opening marker.
This should re-close #1168.
> fix: incorrect opening node for `<Each/>` in debug mode (closes #1168)

- leptos_reactive/src/runtime.rs
Fix to resolve an issue where items in leptos_reactive::store_value references were lost before on_cleanup was run.
> cleanups must be called before properties are disposed

- leptos_dom/src/lib.rs
- leptos_reactive/src/signal_wrappers_read.rs
This adds a `MaybeProp` type, which is essentially a wrapper for `Option<MaybeSignal<Option<T>>>` with a nicer API.
This allows you to define optional props that 
1) may or may not be provided
2) if provided, may be a plain value or a signal
3) if a signal type, may or may not have a value (i.e., are a `Signal<Option<T>>`)
> Implementing `From<_>` for a plain `Signal<T>` type here is possible, but depends on the changes in `0.5.0`, so I'll add it for that release.
```rust
#[component]
pub fn App(cx: Scope) -> impl IntoView {
let (count, set_count) = create_signal(cx, 5);
view! { cx,
<TakesMaybeProp/>
<TakesMaybeProp maybe=42/>
<TakesMaybeProp maybe=Signal::derive(cx, move || Some(count.get()))/>
}
}
#[component]
pub fn TakesMaybeProp(cx: Scope, #[prop(optional, into)] maybe: …
```
> feat: add `MaybeProp` type

- examples/Makefile.toml
Fix #1446
- Refactor to do less work (_now runs in a 1/5 of the time_)
- Rename `test-info` task as `test-runner-report`
- Report the RS Tests as Cargo Tests (_no need to separate them_)
- Add instructions to show all examples
1. Run `cargo make test-runner-task` from the `examples` directory
2. See a report similar to the following...
```rust
Test Runner Report
Pass the option "all" to show all the examples
animated_show -C
counter -W
counters -C-W
counters_stable -C-W-P
counter_without_macros -C-W
js-framework-benchmark -C-W
router -P
tailwind -L
todo_app_sqlite -C
Runners: C = Cargo Test, L = Cargo Leptos Test, P = Playwright Test, W = WASM Test
```
> perf(examples): speed up the test-info report (#1446)

- examples/session_auth_axum/src/main.rs
- examples/session_auth_axum/src/state.rs
- integrations/axum/src/lib.rs
Created render_route() and render_route_with_context() so that people can use custom handlers and SsrModes together in the Axum integration
> Add render_route functions to respect SsrMode on routes when using custom handlers

- leptos/src/animated_show.rs
This is a very tiny bugfix for the `AnimatedShow` component.
When you use the `AnimatedShow` component together with `AnimatedRoutes`, you could create a panic in the `on_cleanup` function. If you start a hide animation with the `AnimatedShow` and then start a route change on the client side at the same time before the hide animation was finished, you could end up in a situation where the context is already disposed for the `on_cleanup` inside the `AnimatedShow` while the route switching animation is still running, which throws a panic in the browsers console.
> fix: `AnimatedShow` - possible panic on cleanup

- leptos_dom/src/components/dyn_child.rs
fix #1456
In release mode, the `DynChild` (like many elements) uses the opening node of its child as its opening node. It also has a "previous text" optimization which, if you're replacing a text node with a new text node, reuses the previous node and sets its data, rather than replacing it with the new node. This is slightly but measurably faster.
However, while it was reusing the previous text node for what was mounted in the DOM, it was still passing the new text node in as the text-node part of the new child. This meant that, if the first child of a DynChild was a text node, if it was edited and then removed it would actually end up moving *both* text nodes back into the `DocumentFragment` and subsequently into the DOM.
This should fix that issue.
> fix: properly replace text nodes in DynChild (closes #1456)

- leptos_macro/src/view.rs
This removes a section of the view macro whose purpose was to add syntax highlighting and IDE hints for component closing tags in debug mode by associating the closing tag ident with the component function.
Doing this in a way that correctly inferred types, however, required duplicating the entire component constructor.
In view trees with many nested components, this led to a massive explosion in compile times.
It may be possible to do this correctly some other way, but I think other changes in the commit that caused this (namely, changes that made it possible to call no-prop components as no-argument functions) make it more difficult.
Closes #1283.
> fix: compile-time regression for deeply-nested component trees

- leptos_dom/src/ssr.rs
- leptos_dom/src/ssr_in_order.rs
See comment on #1475: `move || some_script.get()` was inadvertently not being escaped, allowing script injection.
> fix: correctly escape HTML in DynChild text nodes

- integrations/utils/src/lib.rs
- leptos_dom/src/ssr.rs
The javascript scopes are altering global variables. This creates an issue with the "open" and "close" methods of the javascript window object. This PR simply changes the var declarations to let, which utilize sane scoping rules.
> Fix js scoping

- leptos_reactive/Cargo.toml
There is a slight problem with rkyv dependency. Leptos Reactive seems to request copy feature here: 
https://github.com/leptos-rs/leptos/blob/2f860b37bd1e76ef9ced15ce1d99e2055c1c426b/leptos_reactive/Cargo.toml#L20
The copy feature requires nightly therefore making it impossible to use stable Leptos with `rkyv`:
https://github.com/rkyv/rkyv/blob/bf39dbc3a61783774fc7e1d47b8bf75db2581be7/rkyv/src/lib.rs#L117
This PR makes `rkyv` `copy` feature only available on nightly.
> rkyv `copy` feature is now only enabled if nightly feature is enabled

- leptos_dom/src/ssr.rs
- leptos_dom/src/ssr_in_order.rs
Rendering an empty string to HTML currently renders it as ``, i.e., an empty string. This is fine but makes it impossible to hydrate, because `` in HTML doesn't become an empty text node in the DOM; it simply doesn't exist. 
This PR instead renders it as ` `, i.e., a string with a single space. Because it will be wrapped in comments in debug mode (and has an extra comment inserted before it in release mode to separate it from other surrounding text nodes), this should not display but can be hydrated correctly.
This may cause layout issues but only in cases where whitespace is preformatted.
This should fix the panics described in #1382.
> fix: render empty dynamic text node in HTML as ` ` (closes #1382)

- router/src/hooks.rs
Previously, the query signal was local to the route it was created in, so when its value was updated, the URL path was reset to the original, which is odd behavior. Now the URL won't be reset.
> Fix behavior of `create_query_signal`

- examples/cargo-make/cargo-leptos.toml
- examples/todo_app_sqlite/Makefile.toml
- examples/todo_app_sqlite_axum/Cargo.toml
- examples/todo_app_sqlite_axum/Makefile.toml
- examples/todo_app_sqlite_axum/README.md
- examples/todo_app_sqlite_axum/e2e/Cargo.toml
- examples/todo_app_sqlite_axum/e2e/Makefile.toml
- examples/todo_app_sqlite_axum/e2e/README.md
- examples/todo_app_sqlite_axum/e2e/features/add_todo.feature
- examples/todo_app_sqlite_axum/e2e/features/delete_todo.feature
- examples/todo_app_sqlite_axum/e2e/features/open_app.feature
- examples/todo_app_sqlite_axum/e2e/tests/fixtures/action.rs
- examples/todo_app_sqlite_axum/e2e/tests/fixtures/check.rs
- examples/todo_app_sqlite_axum/e2e/tests/fixtures/find.rs
- examples/todo_app_sqlite_axum/e2e/tests/fixtures/mod.rs
- examples/todo_app_sqlite_axum/e2e/tests/fixtures/world/action_steps.rs
- examples/todo_app_sqlite_axum/e2e/tests/fixtures/world/check_steps.rs
- examples/todo_app_sqlite_axum/e2e/tests/fixtures/world/mod.rs
- examples/todo_app_sqlite_axum/e2e/tests/manage_todos.rs
- examples/todo_app_sqlite_axum/src/lib.rs
- examples/todo_app_sqlite_axum/src/main.rs
Demonstrate e2e testing with Rust using executable requirements.
- Pull up `cargo-leptos` tasks to `cargo-make`
- Introduce e2e tests from `todo_app_sqlite`
- Change log level to Error
Closes #1514 
Supports #210
> test(todo_app_sqlite_axum): add e2e tests (#1514)

- examples/hackernews/src/api.rs
- examples/hackernews_axum/src/api.rs
Hi :wave:,
while reading examples online, I saw this piece of code. Shouldn't the on_cleanup register be before we wait to fully fetch the API ?
If this is a real issue, I can see if this error has been reproduced in others examples and add a commit to finish this PR.
Thanks
> on_cleanup misorder? in fetch examples

- docs/book/src/view/06_control_flow.md
Small tweak to highlight `<Show/>` doesn't just work one way.
> Documentation update for <Show/> 

- docs/book/src/01_introduction.md
Prevent that contributors need to search
which of several git repositories of the Leptos project contains the source of what they are feeling to need changing.
> Tell where the source is

- leptos_dom/Cargo.toml
- leptos_dom/src/macro_helpers/mod.rs
- leptos_dom/src/macro_helpers/tracing_property.rs
- leptos_macro/src/component.rs
Use for tracing component property.
Returns a json value when the property is serializable.  If serialization is not possible, the reason for the failure is returned.
> tracing component property

- .github/workflows/publish-book.yml
The intention here is to make it easier for me to merge a large breaking change (like 0.5) into main even if it's not ready to be released yet; at present the docs always reflect the current state of the main branch, but if there are significant enough discrepancies between that and the latest released version, this is confusing.
An alternative would be to deploy multiple versions of the book corresponding to different versions of the library. That's also possible but seems like more than I need for now.
I will probably revert this once 0.5 is actually released, so that merging PRs to the book republishes it as is currently the case.
> build(docs): only publish on new version tags

- leptos_macro/src/view/client_builder.rs
- leptos_macro/src/view/server_template.rs
- leptos_macro/src/view/slot_helper.rs
This PR removes the requirement for `S: Clone` for when rendering a list of slots `S`.
It is currently required because the `view!` macro is building an array of `S`, then calling `to_vec()` (which obviously requires `S: Clone`). This can be a problem when the slot contains `ChildrenFn` (i.e. `Box<dyn Fn(Scope) -> Fragment`), as this type does not implement `Clone`.
This PR removes this requirement by using the `vec!` macro directly instead.
Take this code for example:
```rust
use leptos::{component, mount_to_body, slot, view, ChildrenFn, CollectView, IntoView, Scope};
#[slot]
pub struct MenuItems {
pub menu_item: Vec<MenuItem>,
}
#[slot]
pub struct MenuItem {
pub children: ChildrenFn,
}
#[component]
pub fn Menu(cx: Scope, menu_items: MenuItems) -> impl IntoView {
view! {
cx,
<ul>
{ …
```
> Remove Clone requirement for slots in Vec

- leptos_dom/src/macro_helpers/tracing_property.rs
The level that prop tracing was set at is too high, causing logs to be emitted for all component props during server rendering in a confusing way.
> fix: INFO is too high a level for this prop tracing

- leptos_dom/src/events.rs
- leptos_dom/src/helpers.rs
- leptos_reactive/src/diagnostics.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/runtime.rs
This warning is already suppressed in event listeners anyway. This suppresses for resource refetches in general, in case they are called in async blocks like an action or `spawn_local`. `.refetch()` re-loads the resource, which makes some reactive calls, but this shouldn't be reactive in any case.
> fix: suppress warning about non-reactivity when calling `.refetch()` (occurs in e.g., async blocks in actions)

- leptos_reactive/src/effect.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/suspense.rs
As discussed at #1563, I think it's nice addition for `leptos_reactive`, because `scope` is no longer existed, and there is no way to early dispose an effect.
> support effect dispose

- leptos_macro/src/server.rs
Fixes server functions with fourth argument by removing additional trailing comma.
> fix: fourth argument to server functions

- leptos_reactive/src/memo.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/signal.rs
- leptos_reactive/src/signal_wrappers_read.rs
- leptos_reactive/src/signal_wrappers_write.rs
- leptos_reactive/src/trigger.rs
I initially began this as part of #1577, before realizing that that had a trait conflict with `Fn()` in any case and needed to use the concrete types instead. It was not possible to do something like
```rust
impl<T, U> IntoAttribute for T where
T: SignalGet<U>,
U: IntoAttribute { /* */ }
```
because the compiler says `U` is unused. I guess because it's only used as the generic of the constraint on `T`. 
This led me down a (short) path re: the difference between generics on traits and associated types. I *think* it's probably correct for these to be associated types rather than generics, because there truly only is one value, and it's provided by the implementor of the trait, not the caller: i.e., any `T: SignalGet` will always have some `T::Value` which is the value it returns. It doesn't …
> feat: signal traits should take associated types instead of generics

- leptos/src/lib.rs
- leptos_dom/src/events/typed.rs
- leptos_dom/src/lib.rs
Hello,
apart from fixing missing reexport I noticed two things:
1. Many struct structs and enums are missing Debug impl
2. There isn't a straightforward way to bundle events with handlers into collection
Is there a reason for not adding Debug? And if not, can I sprinkle in few `#[derive(Debug)]`s?
And as for what I mean by 2, I would like to create some collection to hold different event listeners to be used later:
```rust
#[slot]
pub struct Input {
#[prop(default = "text".into())]
itype: TextProp,
// Event listeners with different types, like input and click
listeners: Vec<EventListener>
}
#[component]
pub fn FancyForm(cx: Scope, input: Vec<Input>) -> impl IntoView {
// Attach event listeners to inputs
}
```
However, only way to use EventListener with different types (as far as I know) …
> Convenient event handling with slots

- integrations/utils/src/lib.rs
- leptos_config/src/lib.rs
- leptos_config/src/tests.rs
- leptos_config/tests/config.rs
Currently we have to access the site served by `cargo leptos watch [--hot-reload]` via localhost, as the websocket connection on the client is tied to the server configuration.
This PR updates the client-side websocket connection to use window.location.protocol/hostname and an additional optional configuration reload_external_port to allow more control over how the client connects to the server. 
This allows us to access via IP other than 127.0.0.1/localhost or a domain via reverse proxy (that can be wss)
> Update autoreload websocket connection to work outside of localhost

- examples/Makefile.toml
- examples/cargo-make/clean.toml
Closes #1598
- Add `tr` alias for `test-runner-report` for convenience
- Add Cucumber Test Runner Report to make it easy to find cucumber tests
- Clean cargo targets recursively to include cucumber `e2e` directories. These test-only directories are not included as workspace members intentionally.
> chore(examples): improve cucumber support #1598

- leptos_macro/src/params.rs
I got a `clippy` warning `clippy::redundant_closure_for_method_calls` on the code generated by the `Params` derive macro. This is the fix suggested by `clippy`, which fixes the issue.
> fix(macro/params): clippy warning

- server_fn/src/lib.rs
Handle all error codes 401-499 in addition to the 400 and 500-599 that were already handled.
In addition, handle them all in the same way and improve the error message.
The idea came about when trying to handle authentication in an axum layer
by setting the 401 status code.
In this situation the client side still tried to parse the body as if this was a
success case and failed with a deserialization error message.
> Improve server function client side error handling

- router/src/components/form.rs
When a server function redirects using `leptos_actix::redirect` or `leptos_axum::redirect` the result of that redirect will be a page not JSON, but the `ActionForm` `on_response` still attempts to parse it as JSON. This change just adds a guard to not attempt to parse the body of a redirected response.
This should address the error part of #1600
> Don't try to parse as JSON the result from a server function redirect

- docs/book/src/server/25_server_functions.md
- leptos_macro/src/lib.rs
- adds explainer in the `leptos_macros/src/lib.rs` for the requirement that server functions should have unique paths even for different HTTP methods.
- adds a new section in the book chapter on server functions explaining the 4th argument with a more relaxed language than the docs
- Since we have already a section on the 3rd argument and now a section on the 4th, why not add a section also for the 2nd argument? Hence, this was added as well.
Closes #1606.
> fix: add docs on #[server] functions

- examples/Makefile.toml
Show which examples use [Fantoccini WebDriver](https://github.com/jonhoo/fantoccini).
1. Run `cargo make test-runner-report` or  `cargo make test-runner-report all` from the **examples** directory
2. See that the report shows examples that use Fantoccini WebDriver
Closes #1615
> doc(examples): add fantoccini to test-runner-report (#1615)

- docs/book/src/view/02_dynamic_attributes.md
I love these docs .. they are well work the read...
This is just a minor thing that broke my concentration 
The double use of the word "**per**" in a sentence made no sense to me 
It read like the units of acceleration meters per second per second...
> docs: Derived signals - Clarified derived signals 

- docs/book/src/deployment.md
It seems like the generated server binary was renamed from `leptos_website` to `leptos_start` at some point.
This PR reflects this change in the example `Dockerfile` under the deployments section in the leptos book.
> doc(book,deployment): update reference to binary in dockerfile

- leptos/src/for_loop.rs
`move | counter: Counter| {...}` -> `move |counter: Counter| {...}`
> docs: remove extra space

- docs/book/src/async/11_suspense.md
I believe the variable should be named `once` not `a`, as only `once` is used in the view macro below.
> docs(book): fix wrong variable name

- leptos_dom/src/callback.rs
- leptos_dom/src/lib.rs
This is a proposal to include callbacks in leptos 5.0.
It is heavily inspired by leptonic, see [here](https://github.com/lpotthast/leptonic/blob/f8a270ae5512561a92f5deca057f7999940de11b/leptonic/src/callback.rs
)
It has 2 main goals: 
- creating a stable way to design components that need special interactivity given as a prop. Currently, there are multiple approaches to write the same code, a problem framework like Yew don't have, thank's to callbacks.
- removing any boxed closure from the perspective of the user: if it works like a function, the user should be able to write a function.
> Callback proposal

- integrations/utils/src/lib.rs
- leptos_config/src/lib.rs
- leptos_config/src/tests.rs
1. Allows the PROD selection for LEPTOS_ENV, previously it was locked to DEV at all times.
2. Adds a new configuration: LEPTOS_RELOAD_WS_PROTOCOL which must be either `ws` or `wss`.
- cargo-leptos can only perform hot-reloading over non-secure websockets so `ws` is used by default, but this option allows `wss` to be selected when the site is behind a reverse https proxy. The default of `ws` is also useful when your server binary supports https without a reverse proxy.
3. Updates the tests to verify that LEPTOS_ENV: PROD and LEPTOS_RELOAD_WS_PROTOCOL: WSS can be selected if set in the environment variables.
> Configuration for Hot-Reloading Websocket Protocol and enable ENV PROD selection

- leptos_dom/src/html.rs
- leptos_macro/src/view/client_builder.rs
- leptos_macro/src/view/server_template.rs
As discussed in Discord, here's a simple PR for some basic spread attributes support for items implementing `IntoIterator<Item= (&'static str, Attribute)>`.
Essentially, you can do the following:
```rs
let attrs = ["value", 1.into_attribute()];
view! { <input {..attrs} /> }
```
and it'll spread the attributes from the iterator into the component as if they were applied normally.
I've tested it and it seems to work correctly, this is my first PR to leptos as well so no idea if I did any of this correctly but please let me know. :)
> feat: implement simple spread attributes

- leptos/src/suspense_component.rs
- leptos/src/transition.rs
- leptos_reactive/src/suspense.rs
- router/src/components/outlet.rs
- router/src/components/routes.rs
Digging into issue #1629 I found that the switch between children and fallback is being re-triggered every time the Suspense count changes, not only when it switches between loading and readiness. This is a problem if multiple resources are read. I think I've fixed this by just memoizing that check.
> fix: memoize Suspense readiness to avoid rerendering children/fallback

- leptos_macro/src/view/component_builder.rs
Adds support for passing generics straight into components using native support in rstml, should close #1176.
> feat: add component generics

- docs/book/src/02_getting_started.md
- docs/book/src/15_global_state.md
- docs/book/src/appendix_reactive_graph.md
- docs/book/src/interlude_projecting_children.md
- docs/book/src/reactivity/14_create_effect.md
- docs/book/src/server/25_server_functions.md
- docs/book/src/server/27_response.md
- docs/book/src/testing.md
- docs/book/src/view/03_components.md
- docs/book/src/view/08_parent_child.md
- docs/book/src/view/09_component_children.md
Cleaned up whitespace issues with examples in the book. Also added some missing brackets to a function.
I also noticed that `<input type=` messes up the rendering of the examples since type is a rust keyword. I thought of two ways to fix this but both have drawbacks. Adding a zero width space to `type` fixes the issue but would obviously cause problems if someone copy and pastes the code. Another option would be simply removing cases of `type="text"` as this is the default anyway, however this wouldn't fix the issues with `type="checkbox"` or `type="submit"`.
I think that the `type="number"` in the Error Handling section examples should be removed since it prevents typing letters so it makes it more awkward to test the error handling shown off in that section.
> docs: cleanup

- leptos_reactive/src/resource.rs
This should close #1640, in which the resource version was checked both to determine whether to set the value and whether to decrement the Suspense count, but the Suspense count was incremented in every case. i.e., if a resource refetches multiple times before loading, the version check prevents a race condition by ensuring that only the resolved result of the most-recently-fired async call is used. However, this was causing Suspense to hang indefinitely on its loading state, as it would never decrement the count.
This fixes this bug by decrementing the count in every situation, just as the count is incremented in every situation, no matter the result of the version check; but it only updates the value if the version check passes.
> fix: versioned resources never decrement Suspense (closes #1640)

- examples/counter_without_macros/src/lib.rs
- leptos_reactive/src/effect.rs
- leptos_reactive/src/memo.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/selector.rs
- leptos_reactive/src/signal.rs
- leptos_reactive/src/stored_value.rs
This library has traditionally had a style that's more idiomatic/familiar to JS devs coming from React or Solid than to typical Rust:
```rust
let (count, set_count) = create_signal(cx, 0);
let double_count = create_memo(cx, move |_| count() * 2);
```
as opposed to
```rust
let count = RwSignal::new(0);
let double_count = Memo::new(move |_| count() * 2);
```
Historically this has been for three reasons
1. `create_signal`'s tuple return doesn't lend itself well to a `::new()` style; it's not returning a struct, after all.
2. The addition of a `cx` variable has made `::new()` seem odd.
3. I largely ported it from SolidJS and its idioms, which are all that classless JS `createSignal()` and `useSomething()` style.
But there are some real advantages to using structs with associated functions and …
> feat: start adding some Rustier interfaces for reactive types

- leptos_macro/src/view/mod.rs
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__client_template__custom_event.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__client_template__full_span__custom_event.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__csr__custom_event.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__csr__full_span__custom_event.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__ssr__custom_event.snap
- leptos_macro/src/view/snapshots/leptos_macro__view__tests__ssr__full_span__custom_event.snap
- leptos_macro/src/view/tests.rs
**This PR fixes the following bug**
I was using events on components like in the chapter [Parent-Child Communication](https://leptos-rs.github.io/leptos/view/08_parent_child.html#3-use-an-event-listener) of the book:
```rust
<ButtonC on:click=move |_| set_toggled.update(|value| *value = !*value)/>
```
But I was using custom events like this:
```rust
<Modal header="Hello, World!" id="test-modal" on:hidden.bs.modal=|_: Event| log!("modal closed")>
"This is a test message."
</Modal>
```
Which resulted into a compiler error on `0.5.0-beta2` and also on commit 4a43983f4ed4472d8c34f51a069d4f2c5b4a40e0:
rustc 1.74.0-nightly (4e78abb43 2023-08-28)
```
error[E0423]: expected value, found struct `leptos::leptos_dom::ev::Custom`
```
This is because the macro was generating
```rust
.on( …
```
> fix: custom events on components

- router/src/components/link.rs
With this chage, the two path fragments are compared by their components, not just as strings.
This should fix  #1655.
I'm note sure if this covers each and every corner case though.
> fix: compare path components to detect active link in router

- .github/workflows/run-cargo-make-task.yml
- router/Cargo.toml
Saw a few outdated package while reading the code
-cached = { version = "0.44.0", optional = true }
+cached = { version = "0.45.0", optional = true }
-lru = { version = "0.10", optional = true }
+lru = { version = "0.11", optional = true }
NB gloo_net needs updating but that would take bigger refactoring as the raw response is now private.
> Router version bump

- leptos/src/children.rs
- leptos/src/lib.rs
- leptos/src/show.rs
- leptos/src/suspense_component.rs
- leptos/src/transition.rs
- leptos_macro/src/view/component_builder.rs
- leptos_macro/src/view/slot_helper.rs
Currently components only accept `Box` backed children, it makes sense for `Children` and `ChildrenFnMut` but makes working with `ChildrenFn` difficult as it can't be cloned, so the solution most user would take is to put it in a `Rc` but it introduce more code and unecessary allocations.
This PR change `ChildrenFn` to be `Rc` backed, so component taking `ChildrenFn` as an argument can now clone it directly with minimal cost.
> `Rc` backed `ChildrenFn`

- examples/login_with_token_csr_only/Cargo.toml
tiny fix, seen while running the examples
> chore: Removed resolver link warning.

- leptos/Cargo.toml
These lint warnings.
> warning: /home/martin/build/leptos/leptos/Cargo.toml: dependency (serde) specified without providing a local path, Git repository, version, or workspace dependency to use. This will be considered an error in future versions
> warning: /home/martin/build/leptos/leptos/Cargo.toml: dependency (serde_json) specified without providing a local path, Git repository, version, or workspace dependency to use. This will be considered an error in future versions
> Chore: Remove ambiguity surrounding version numbers.

- integrations/axum/src/lib.rs
I seem to have missed a step while rebasing the 0.5 branch, and lost the `extract_with_state` work from the Axum integration, presumably by not noticing that removing `Scope` from the `extract` arguments created a merge conflict and just choosing the new one.
Here it is again.
> fix: restore deleted `extract_with_state` function

- leptos_reactive/src/memo.rs
warning: Rust code block is empty
--> leptos_reactive/src/memo.rs:209:9
|
209 |     /// ```
|         ^^^
|
= note: `#[warn(rustdoc::invalid_rust_codeblocks)]` on by default
help: mark blocks that do not contain Rust code as text
|
209 |     /// ```text
|            ++++
> Chore: cleared "cargo doc" issue.

- docs/book/src/ssr/24_hydration_bugs.md
- examples/todomvc/src/lib.rs
- leptos_dom/src/components/dyn_child.rs
- leptos_dom/src/components/each.rs
- leptos_dom/src/html.rs
- leptos_dom/src/node_ref.rs
- leptos_reactive/src/effect.rs
Currently, effects created with `create_effect` run 
1) only in the browser
2) immediately
This means that simple code like this fails silently
```rust
#[component]
let input = create_node_ref::<html::Input>();
create_effect(move |_| {
if let Some(input) = input.get() {
logging::log!("focusing");
input.focus();
}
});
view! {
<input node_ref=input/>
}
}
```
This logs `focusing` but does not actually focus the `<input>` because it has not yet been mounted to the DOM. The sequence of events goes:
1. `create_node_ref`: NodeRef is created
2. `create_effect`: creates the effect, and runs once immediately to register its dependencies
3. `<input node_ref=input/>`: creates an `HtmlInputElement` and loads it into the `NodeRef`
4. loading the `NodeRef` triggers the …
> Feedback Wanted  — change: run effects after a tick

- docs/book/src/reactivity/working_with_signals.md
- leptos_reactive/src/lib.rs
- leptos_reactive/src/macros.rs
PR for #1682 
I wasn't able to run the doctests due to some errors with the `nix` crate - if you could run them and lmk of any changes needed that would be great. Not really sure how they are supposed to be set up, I copied some sections from the `view!` macro docs. 
Also the doc links to `StoredValue::with_value` and `update_value` aren't working for me (can't click it in VSC), but rustdoc doesn't give any warnings for it.
> with! macros

- leptos_dom/src/lib.rs
While moving to `v0.5.0-rc1` for one of my project I realised I made a mistake with #1669, there is a `IntoView` impl for `Fn() -> impl IntoView` but it does not affect `Rc<dyn Fn() -> impl IntoView>`, so `ChildrenFn` does not impl `IntoView` anymore.
```rust
// works
let children: Children = ...;
view! { <b>{children}</b> };
// works
let children_mut: ChildrenFnMut = ...;
view! { <b>{children}</b> };
// fail
let children_fn: ChildrenFn = ...;
view! { <b>{children}</b> };
// need to call it to make it work:
view! { <b>{children()}</b>
```
This PR add a `IntoView` impl for `Rc<dyn Fn() -> impl IntoView>`
> fix: impl `IntoView` for `Rc<dyn Fn() -> impl IntoView>`

- leptos_dom/src/html.rs
- leptos_dom/src/math.rs
- leptos_dom/src/svg.rs
Closes #1699 
As it's not possible to implement this as a blanket implementation, at least, not as it's currently implemented, I added some codegen to the macros to make this work.
> impl `From<HtmlElement<El>> for HtmlElement<AnyElement>`

- leptos_dom/src/callback.rs
Great to see, that this is now part of Leptos :). This PR mainly adds manual Clone and Debug implementations.
The manual `Clone` impl removes the `Clone` type  bounds on the generic `In` and `Out` types. All callback types can be cloned by simply cloning the inner `Rc`. The generic types are not important here.
The Debug impls are debatable, as they are not strictly needed. But I would say it's good practice to supply users with a Debug impl for ALL custom types a library provides, as this is somewhat expected. (The ability to derive Debug on your types without problems.) If not provided, users would always need to add custom `Debug` impls for all structs in which they want to store some `Callback` type and have a Debug impl on that struct. 
Also adds a missing `pub` modifier to construct …
> Callbacks: Manual Clone and Debug impl; Visibility fix

- examples/cargo-make/client-process.toml
- examples/cargo-make/server-process.toml
- examples/login_with_token_csr_only/README.md
Do not run trunk in a separate process.
From the **examples/login_with_token_csr_only** directory...
1. Run `cargo make status` (Terminal 1) - Output reports client and server are not running
2. Run `cargo make start` (Terminal 1) 
3. Run `cargo make status` (Terminal 2) - Output reports client and server are up
4. Execute CTRL+C (Terminal 1)
5. Run `cargo make status` (Terminal 2) - Output reports client is not running and server is up
6. Run `cargo make stop` (Terminal 2)
7. Run `cargo make status` (Terminal 2) - Output reports client and server are not running
1. Run `cargo make status` (Terminal 1) - Output reports client and server are not running
2. Run `cargo make start` (Terminal 1) 
3. Run `cargo make status` (Terminal 2) - Output reports client and server are up …
> fix(examples/build): do not require stop to end trunk

- leptos_reactive/src/macros.rs
adds an optional `move` for the `with!` and associated macros.
e.g. `with!(move |thing| thing + other_captured_thing)` would expand to `thing.with(move |thing| thing + other_captured_thing)`
> feat: support `move` on `with!` macros

- leptos_reactive/src/resource.rs
> fix: correctly register `Resource::with()` (closes #1711)

- leptos/src/animated_show.rs
- leptos_reactive/src/memo.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/signal.rs
- leptos_reactive/src/signal_wrappers_read.rs
- router/src/components/outlet.rs
- router/src/components/progress.rs
- router/src/components/routes.rs
In a number of places, the reactive system was using `create_effect`. Now that `create_effect` is defined as a user-created effect that runs on the next tick, this is wrong and it caused #1709 because of a discrepancy between resources and local resources, where local resources used `create_effect`. 
This also changes several places in the router to use `create_render_effect` (matches old behavior of `create_effect`) in case they were generating similar issues.
> fix: replace uses of `create_effect` internally with `create_isomorphic_effect` (closes #1709)

- leptos_hot_reload/src/parsing.rs
- leptos_macro/src/view/ide_helper.rs
Simply put, this allows you to do `<module::Component />` on top of the existing `<div />` and `<Component />` style syntaxes.
> feat: Allow component names to be paths

- docs/book/src/metadata.md
- leptos/src/additional_attributes.rs
- meta/src/body.rs
- meta/src/html.rs
- router/src/components/form.rs
This PR takes advantage of the `attr:` syntax introduced by #1628 to make it more ergonomic to add arbitrary attributes to the `leptos_meta` components `Body` and `Html`. It also deprecates `AdditionalAttributes`, which is basically a worse form of this pattern IMO.
```rust
#[component]
provide_meta_context();
let value = RwSignal::new(0);
view! {
<Body
attr:class="foo"
attr:id=value
/>
<Html lang="he"
attr:data-theme="dark"
attr:data-foo={move || if value() % 2 == 0 { "bar" } else { "baz" }}
/>
<button on:click=move |_| value.update(|n| *n += 1)>"+1"</button>
}
}
```
> feat: use `attr:` syntax rather than `AdditionalAttributes`

- examples/cargo-make/client-process.toml
- examples/cargo-make/playwright-trunk-test.toml
- examples/error_boundary/README.md
Closes  #1738
- Run CI (examples/error_boundary)
> fix(examples/error_boundary): ci error

- leptos/src/suspense_component.rs
- leptos/src/transition.rs
- leptos_reactive/src/lib.rs
- leptos_reactive/src/runtime.rs
#1753 broke Suspense loading in hydration mode on subsequent navigations. This PR reverts its changes, while addressing the issue about CSS animations raised in #1742 and caused by rendering the Suspense children twice initially.
> Fix Suspense issues on subsequent navigations

- server_fn_macro/src/lib.rs
This allows form submission with checkbox inputs to work.
For example:
let doit = create_server_action::<DoItSFn>();
<ActionForm action=doit>
<input type="checkbox" name="is_good" value="true"/>
<input type="submit"/>
</ActionForm>
#[server(DoItSFn, "/api")]
pub async fn doit(#[server(default)] is_good: bool) -> Result<(), ServerFnError> {}
If is_good is absent in the request to the server API,
`Default::default()` is used instead.
This is the approach suggested by https://github.com/leptos-rs/leptos/pull/1745#issuecomment-1724680903
> Support default values for annotated server_fn arguments

- docs/book/src/ssr/23_ssr_modes.md
- leptos_reactive/src/resource.rs
- router/src/render_mode.rs
Meant to address users making the same mistake as
https://github.com/leptos-rs/leptos/issues/1119
> Better document the interaction of SsrModes with blocking resources

- leptos_dom/src/lib.rs
- leptos_dom/src/ssr.rs
- leptos_reactive/src/oco.rs
- meta/src/link.rs
- meta/src/script.rs
- meta/src/style.rs
- router/src/hooks.rs
- Make `Clone` impl generic.
- Add `clone_inplace` method that accept `&mut self` to clone and replace the original value inplace with `Oco::Counted` in case if was `Oco::Owned`
> Reimplement `Oco` cloning

- leptos_macro/src/component.rs
Use [expand](https://github.com/dtolnay/cargo-expand) to show result
```shell
$ cd router
$ cargo expand ::components::redirect
```
```rust
///Props for the [`Redirect`] component.
///
/// Redirects the user to a new URL, whether on the client side or on the server
/// side. If rendered on the server, this sets a `302` status code and sets a `Location`
/// header. If rendered in the browser, it uses client-side navigation to redirect.
/// In either case, it resolves the route relative to the current route. (To use
/// an absolute path, prefix it with `/`).
/// **Note**: Support for server-side redirects is provided by the server framework
/// integrations ([`leptos_actix`], [`leptos_axum`], and [`leptos_viz`]). If you’re not using one of those
/// integrations, you should manually provide …
```
> chore(leptos_marco): enhancement of document generation

- flake.nix
Now, the nix flakes declares a shell with `cargo-make` and `trunk`
> Add tooling for nix flakes

- Cargo.toml
- docs/book/src/01_introduction.md
- docs/book/src/02_getting_started.md
- leptos_reactive/src/resource.rs
- meta/Cargo.toml
- router/Cargo.toml
This is one of those changes that is somewhere between a "fix" and a "breaking change." Local resources were intended to run only in the browser, but in fact were running on both the server and in the browser, but without being serialized/shared between the two. This aligns them with the document behavior of only running in the browser. 
(Does this fix #1775?)
> change: only run `create_local_resource` in the browser

- benchmarks/src/todomvc/leptos.rs
- docs/book/src/router/17_nested_routing.md
- examples/counters/src/lib.rs
- examples/counters_stable/src/lib.rs
- examples/errors_axum/src/error_template.rs
- examples/hackernews/src/routes/stories.rs
- examples/hackernews/src/routes/story.rs
- examples/hackernews_axum/src/error_template.rs
- examples/hackernews_axum/src/routes/stories.rs
- examples/hackernews_axum/src/routes/story.rs
- examples/hackernews_islands_axum/src/error_template.rs
- examples/hackernews_islands_axum/src/routes/stories.rs
- examples/hackernews_js_fetch/src/error_template.rs
- examples/hackernews_js_fetch/src/routes/stories.rs
- examples/hackernews_js_fetch/src/routes/story.rs
- examples/js-framework-benchmark/src/lib.rs
- examples/session_auth_axum/src/error_template.rs
- examples/todo_app_sqlite_axum/src/error_template.rs
- examples/todo_app_sqlite_viz/src/error_template.rs
- examples/todomvc/src/lib.rs
- leptos/src/for_loop.rs
This PR would change the name of the view function argument to `For` from `view` to `children`. This allows it to written inline using the `bind:` syntax to specify the name of the argument.
```rust
let (data, set_data) = create_signal(vec![0, 1, 2]);
view! {
<For
each=data
key=|n| *n
// stores the item in each row in a variable named `data`
let:data
>
<p>{data}</p>
</For>
}
```
is the same as
```rust
let (data, set_data) = create_signal(vec![0, 1, 2]);
view! {
<For
each=data
key=|n| *n
children=|data| view! { <p>{data}</p> }
/>
}
```
which replaces
```rust
let (data, set_data) = create_signal(vec![0, 1, 2]);
view! {
<For
each=data
key=|n| *n
view=|data| view! { <p>{data}</p> }
/>
}
```
The intention here is to make it easier to write views by reducing the number of times you need to …
> change: enable inline children for `For` by switching to `children` and `bind:`

- leptos_config/Cargo.toml
Only `toml` format is required in `leptos_config`, disable default features to avoid pulling in lots of dependencies for unneeded formats like json, yaml and etc.
> feat(leptos_config): only enable `toml` feature for the `config` dependency

- leptos_reactive/Cargo.toml
- leptos_reactive/src/lib.rs
- leptos_reactive/src/runtime.rs
This PR serves to extend the current `leptos_runtime` API surface to allow for running futures within an `Owner` scope context.
> Scoped Futures

- leptos_macro/src/component.rs
- leptos_macro/src/lib.rs
- leptos_macro/src/server.rs
- leptos_macro/tests/ui/component.stderr
This change fixes #1781. Please do try it out. You might have to restart rust-analyzer for it to "rebuild" the macros.
There is a caveat.
The situation is a bit more tricky than I initially thought, because the macros (at least the client macro) actually uses non-standard Rust syntax: Function parameter documentation comments (and potentially more, I'm not sure). Here's what happens:
1. The macro is fed the token stream with my extraneous `let`
2. The macro realizes that the syntax is broken and returns the token stream as is
3. The Rust compiler and rust-analyzer get token stream _with_ function parameter doc comments, and then complain
This is not a problem with valid syntax, as the behavior there is unchanged. However, it might confuse users, and they might remove the doc comments …
> fix: improve rust-analyzer auto-completion

- leptos_macro/Cargo.toml
-attribute-derive = { version = "0.6", features = ["syn-full"] }
+attribute-derive = { version = "0.8", features = ["syn-full"] }
-itertools = "0.10"
+itertools = "0.11"
cargo outdated reports a long list of issues. but I am only focusing on a small sub-section
Going over them on a case by case basis is tricky as for legacy reasons not all should be fixed.
We still need periodic nudges in the right direction, 
as if we let every thing get stale, the problem festers into a unsolvable mess.
> chore: leptos_marco: Bumped outdated crates

- integrations/axum/src/lib.rs
This sets the Content Type header for all non serverfn responses. Firefox will complain and show a Content Encoding error if you try to view page source without it. Plus it's good practive
> Set Content-Type header for all Responses to text/html;charset="utf-8"

- leptos_reactive/src/suspense.rs
At some point in the distant past, I added a delay here, probably as a hacky workaround for some other failing I can no longer remember.
It causes an issue if you have multiple resources loading in the same `Suspense`, and one of them is immediately loaded without any further delay.
In the near future, I'm sure removing this will surface some other bug, but I can't find it now!
> fix: broken `Suspense` when a resource loads immediately (closes #1805)

- meta/src/lib.rs
`generate_head_metadata_separated` adds a set of angle brackets around the body tag as shown here https://github.com/leptos-rs/leptos/blob/2d634364a9a4087b64389e9cd54ecc337151aaeb/meta/src/lib.rs#L308-L308 That means `generate_head_metadata` introduces an extra set of angle brackets by interpolating that value like so `<{body}>`. This PR removes the extra set of angle brackets.
> Remove extra angle brackets in generate_head_metadata

- leptos/src/lib.rs
The current `#[cfg]` condition for the `template!` aliased as `view!` is not the negation of the condition for the real `template!`.
This causes an error when the compilation target is not `wasm32` but the `template_macro` feature is enabled, which happens with rust-analyzer in a workspace for example.
The fix is just to use the negation of condition for the real `template!`.
> Fix template! cfg condition

- leptos/src/lib.rs
- leptos/src/show.rs
- leptos/src/suspense_component.rs
- leptos/src/transition.rs
- leptos/src/view_fn.rs
> made show fallback optional
