- leptos_dom/src/render.rs
- leptos_macro/src/view.rs
> Fix issues with mixing blocks and elements

- router/src/components/router.rs
This should address issue #65.
> Fix immediate redirect panic

- examples/router/Cargo.toml
- examples/router/src/lib.rs
- examples/view-tests/src/main.rs
- leptos_core/src/suspense.rs
- leptos_macro/src/view.rs
- router/Cargo.toml
Per issue #77 
There are a few issues that have cropped up w.r.t. the ordering of children within elements recently. This is trying to systematically fix some of those issues.
> Fix rendering issues, including in router example

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- leptos/tests/ssr.rs
- leptos_core/src/map.rs
- leptos_core/src/suspense.rs
- leptos_dom/src/mount.rs
- leptos_dom/src/render_to_string.rs
- leptos_macro/src/lib.rs
- leptos_reactive/src/context.rs
- leptos_reactive/src/effect.rs
- leptos_reactive/src/lib.rs
- leptos_reactive/src/memo.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/scope.rs
- leptos_reactive/src/selector.rs
- leptos_reactive/src/signal.rs
- leptos_reactive/src/signal_wrappers.rs
- leptos_reactive/tests/effect.rs
- leptos_reactive/tests/memo.rs
- leptos_reactive/tests/signal.rs
- leptos_reactive/tests/untracked.rs
- leptos_server/src/action.rs
- leptos_server/src/lib.rs
- leptos_server/src/multi_action.rs
- meta/src/lib.rs
- router/src/history/mod.rs
Fixes issue #103.
I did manually test most of the examples and this seems to just work? It's possible I'm introducing some kind of subtle bug here having to do with streaming resources to multiple different clients (in which case I'm going to feel pretty dumb) but I really don't think so.
> Thread local runtimes

- examples/todo-app-sqlite/src/todo.rs
- leptos_reactive/src/resource.rs
> Fix issue in which server-side resource are called 3x

- integrations/axum/src/lib.rs
- leptos_macro/src/server.rs
- leptos_macro/src/server.rs server_macro_impl
- integrations/axum/src/lib.rs handle_server_fns
> update functions for Windows file directories

- leptos/Cargo.toml
- leptos/build.rs
- leptos_core/Cargo.toml
- leptos_core/build.rs
- leptos_dom/Cargo.toml
- leptos_dom/build.rs
- leptos_macro/Cargo.toml
- leptos_macro/build.rs
- leptos_reactive/Cargo.toml
- leptos_reactive/build.rs
> Automatically enable the `stable` feature if you're on `stable` Rust

- leptos_config/src/lib.rs
KDL likes dashes, and I did not know that
> Replace _ with - for KDL files

- leptos_reactive/src/effect.rs
- leptos_reactive/src/memo.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/signal.rs
> Relax the `Debug` trait bounds on various types in `leptos_reactive`

- README.md
I haven't used nightly much and at first couldn't get examples to run.  
I found helpful notes in the tailwind example README, and thought they
would be good to include in the main README for other newcomers.
> info about how to set up nightly -> README

- leptos_macro/src/component.rs
> fixed components only rendering `<() />` on release

- leptos_dom/src/lib.rs
> fixes compiler recursion limit on `View::on`

- leptos_dom/examples/test-bench/Cargo.toml
- leptos_dom/examples/test-bench/src/main.rs
- leptos_reactive/Cargo.toml
- leptos_reactive/src/effect.rs
- leptos_reactive/src/lib.rs
- leptos_reactive/src/memo.rs
- leptos_reactive/src/resource.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/signal.rs
- leptos_reactive/src/signal_wrappers_read.rs
- leptos_reactive/src/signal_wrappers_write.rs
Adds instrumenting for the `tracing` crate to most of the reactive system.
> Adding `tracing` to `leptos_reactive`

- leptos_dom/Cargo.toml
- leptos_dom/src/helpers.rs
- leptos_dom/src/html.rs
Uses a combination of async goodness and `request_animation_frame` to efficiently poll to check if the element is a child of `<body />`
> added `HtmlElement::on_mount`

- leptos_dom/src/lib.rs
Related to #253 Getting cargo docs to compile
> #254 Minor: Unbalanced tags.

- leptos_macro/src/view.rs
I was swept out all the issues related to this clippy rule
https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
> Minor: Removed Clippy::needless_borrrow issues.

- leptos_macro/src/component.rs
> fix component macro lifetime parsing

- leptos_macro/src/component.rs
> default prop values in prop macro

- integrations/actix/Cargo.toml
- integrations/axum/Cargo.toml
- leptos/Cargo.toml
- leptos/src/for_loop.rs
- leptos_dom/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_reactive/Cargo.toml
- leptos_server/Cargo.toml
- meta/Cargo.toml
- router/Cargo.toml
This is a minor comment 
In my IDE .. I have a count of errors in the toolbar.
The error count registers invalid lines in toml files.
As a double check I dumped the root Cargo.toml files in a validator 
https://www.toml-lint.com/
So all my changes are of the form 
```
-leptos.workspace = true
+leptos = { workspace = true }
```
As I see things - This does not uncover any bugs, the original intend of the code in being interpreted without problem.
So it is just a DX thing for me - When I am making changes to the code I always have to ignore a these errors.
> Minor: "leptos.workspace = true" is invalid.

- README.md
Congrats on 0.1.0!
This is just a tiny fix for a problem I ran across while exploring the docs.
> Fix link to counters_stable in README

- README.md
- docs/book/src/01_introduction.md
- docs/book/src/02_getting_started.md
- docs/book/src/03_building_ui.md
- examples/tailwind/README.md
- integrations/actix/Cargo.toml
- integrations/axum/Cargo.toml
- leptos/src/lib.rs
- leptos_dom/Cargo.toml
- leptos_macro/Cargo.toml
- meta/src/lib.rs
- meta/src/meta_tags.rs
- Should point to counters (plural)
- Search https://github.com/gbj/ and replace with https://github.com/leptos-rs/
> Doc fix + search & replace url

- leptos/src/suspense.rs
- leptos_dom/src/html.rs
- leptos_dom/src/ssr.rs
- leptos_macro/src/view.rs
> Death to suspense hydration mismatches

- leptos/tests/ssr.rs
- leptos_dom/Cargo.toml
- leptos_dom/src/hydration.rs
- leptos_dom/src/lib.rs
- leptos_dom/src/ssr.rs
- meta/src/lib.rs
> Use comments instead of element markers for hydration

- integrations/axum/src/lib.rs
Include relative path and query string for Axum
> Path and Query for Axum

- examples/router/src/lib.rs
- router/src/components/link.rs
> Add programmatic navigation in router example

- leptos/src/suspense.rs
- leptos_dom/src/components.rs
- leptos_dom/src/lib.rs
- leptos_dom/src/ssr.rs
This should avoid both hydration issues and the styling issues introduced by using a `<leptos-suspense>` element.
> Change `<Suspense/>` to a specialized type that uses comments for SSR

- leptos_dom/src/components/errors.rs
I want to pass Errors from outside render_app_to_stream(), and for that it needs to be Sync. So I changed it from Rc to Arc.
> Make Errors Sync

- leptos_dom/src/html.rs
> added `hgroup` element

- docs/book/project/ch02_getting_started/Cargo.toml
- docs/book/project/ch02_getting_started/src/main.rs
- docs/book/project/ch03_building_ui/Cargo.toml
- docs/book/project/ch03_building_ui/src/main.rs
- docs/book/project/ch04_reactivity/Cargo.toml
Recently a large number of doc issue were fixed...
When I run
```cargo outdated```
I see some outdated packages were being used in the doc area. So this is a minor tidy
> doc/book updated leptos version.

- leptos/src/error_boundary.rs
- leptos/src/lib.rs
- leptos/src/show.rs
- router/src/components/form.rs
- router/src/components/link.rs
- router/src/components/route.rs
- router/src/components/router.rs
- router/src/components/routes.rs
> Add `Children` type alias

- leptos_dom/src/macro_helpers/into_attribute.rs
- leptos_macro/src/view.rs
> Fix boolean attributes in `view` macro fast-path SSR

- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- meta/src/body.rs
- meta/src/html.rs
- meta/src/lib.rs
- meta/src/title.rs
This closes #376 by allowing you to edit a limited set of attributes on the `<html>` and `<body>` elements from within your application.
> Add `<Html/>` and `<Body/>` components in `leptos_meta`

- leptos/Cargo.toml
- leptos_config/Cargo.toml
- leptos_macro/Cargo.toml
- meta/Cargo.toml
typed-builder is undergoing rapid development .. 
I just want to keep in sync... I prefer tens of minor bumps, rather than an afternoon muttering under my breath "fixing all the things".
> Minor: Bump typed-builder from 0.11 to 0.12.

- leptos_reactive/src/stored_value.rs
Hi there, this PR adds support of `update_returning` to `StoredValue` bringing API to parity with `RwSignal`.
> Implemented update_returning for StoredValue

- leptos_macro/src/view.rs
> Fix top-level SVG elements in SSR

- leptos_macro/Cargo.toml
> leptos_macro: Machete - Removed unused deps.

- router/Cargo.toml
```
-itertools = "0.10"
-bincode = "1"
```
> router: Machete - Removed unused deps.

- leptos_macro/src/view.rs
> fix: don't override element event listeners with component event listeners

- leptos_macro/src/server.rs
> fix: `cargo doc` in projects using `#[server]`

- leptos/src/suspense.rs
Minor: Just noticed as I was crawling the code..must as well fix as I go.
> Suspense: removed unused .clone() call.

- leptos_dom/src/hydration.rs
- leptos_dom/src/lib.rs
- leptos_macro/src/lib.rs
- leptos_reactive/src/signal.rs
Just a few typos I found while reading around and a tiny code cleanup.
> Typos and a small cleanup

- leptos_dom/src/hydration.rs
> Fix typo in hydration.rs

- examples/counter/Cargo.toml
- examples/counter/tests/mod.rs
Incorrect framework referenced, threw me off.
> Update example readme

- docs/book/src/02_getting_started.md
> cx typo in 02_getting_started.md

- docs/book/src/view/05_forms.md
Code in the example already updated by someone
> use create_node_ref instead of NodeRef::new

- docs/book/src/view/03_components.md
Compiler reports error
F may not live long enough
Issue #608.
> fix compilation error, Issue #608

- docs/book/src/view/07_errors.md
code is from already updated example
> updated error handling code in book

- leptos_macro/Cargo.toml
- leptos_macro/src/component.rs
- leptos_macro/src/params.rs
- leptos_macro/src/template.rs
- leptos_macro/tests/component.rs
- leptos_macro/tests/ui.rs
- leptos_macro/tests/ui/component.rs
- leptos_macro/tests/ui/component.stderr
- Improved error messages
- Added testing for component macro
fixes: #465
> feat: support expr for #[prop(default=...)]

- docs/book/src/view/04_iteration.md
Little change on 3.4 Iteration page to see codesanbox window
> docs: Update 04_iteration.md

- leptos/Cargo.toml
- leptos_config/Cargo.toml
- leptos_macro/Cargo.toml
- meta/Cargo.toml
> bump typed-builder to version 0.13.

- leptos_reactive/Cargo.toml
> Bump serde-wasm-bindgen to 0.5.

- leptos_server/Cargo.toml
> Cargo machete: Strip down leptos_server.

- docs/book/src/view/03_components.md
fix spelling error for document
> fix spelling error for document

- leptos_macro/Cargo.toml
"Say hello, wave goodbye" to leptos_server.
> cargo machete: leptos_macro - Removed unused crates.

- leptos_reactive/src/signal_wrappers_read.rs
Hello, first PR here!
I implemented Copy & Clone for MaybesSignal<T> so that the api has better parity with Signal<T>. 
Are there any additional steps I should make here, e.g. updating a changelog?
> Copy & Clone for MaybeSignal<T>

- .github/workflows/check-examples.yml
- .github/workflows/check-stable.yml
- .github/workflows/check.yml
- .github/workflows/fmt.yml
- .github/workflows/test.yml
- Cargo.toml
- Makefile.toml
- examples/counter_without_macros/Makefile.toml
- leptos_macro/Cargo.toml
- leptos_server/Cargo.toml
- meta/Cargo.toml
- router/Cargo.toml
- server_fn/Cargo.toml
- server_fn/server_fn_macro_default/Cargo.toml
- server_fn_macro/Cargo.toml
- server_fn_macro/src/lib.rs
The new server function macro setup didn't quite pass the `stable` flag through as it needed to (see #669). This fixes the issue and adds some `stable` tests to help prevent regressions.
> fix broken stable support

- leptos_dom/src/lib.rs
These traits are already implemented through blanket with `nightly`.
> Added `IntoView` for `ReadSignal` and `RwSignal` in the `stable` feature.

- leptos_dom/src/html.rs
- leptos_dom/src/lib.rs
- leptos_dom/src/ssr.rs
- leptos_dom/src/ssr_in_order.rs
- leptos_macro/src/view.rs
> fix: hydration errors with `<Suspense/>` inside components in SSR mode

- leptos_dom/src/helpers.rs
> feat: add `set_interval_with_handle` and deprecate `set_interval`

- leptos_reactive/src/memo.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/signal.rs
> feat: allow manual signal disposal before the scope is disposed

- docs/book/src/view/02_dynamic_attributes.md
The modulo operator is less of a head-scratcher for folks coming through here. The bitwise & is equally correct (clearly) but is likely to cause confusion if folks don't immediately see what's going on.
> Used modulo rather than bitwise & for is_odd check.

- leptos_dom/src/html.rs
I added two methods to `HtmlElement`.
- `is_mounted` which returns true if the element is currently in the DOM
- - `dyn_classes` which takes any signal that yields iterable elements of class names which will dynamically add/remove the classes on the element as the signal changes
> Add `is_mounted` and `dyn_classes`

- docs/COMMON_BUGS.md
- docs/book/src/15_global_state.md
- docs/book/src/async/12_transition.md
- docs/book/src/router/README.md
- examples/errors_axum/src/landing.rs
- integrations/actix/src/lib.rs
- integrations/axum/src/lib.rs
- integrations/utils/src/lib.rs
- integrations/viz/src/lib.rs
- leptos/src/suspense.rs
- leptos_dom/src/html.rs
- leptos_reactive/src/scope.rs
- router/tests/query_params.rs
- server_fn_macro/src/lib.rs
Just fixing a few typos in the docs ✌🏻
> Fix a few typos

- meta/src/meta_tags.rs
This seems easier than I expected. Closes issue #758
> Add property field to Meta tag

- leptos_reactive/src/runtime.rs
Removes a (potentially unused) clone from `Runtime::update` and shrinks what memory/operations are needed in `update_if_necessary`
> Optimize memory usage of update methods

- integrations/actix/Cargo.toml
- integrations/actix/src/lib.rs
- integrations/axum/Cargo.toml
- integrations/axum/src/lib.rs
- integrations/viz/Cargo.toml
- integrations/viz/src/lib.rs
- leptos_server/src/lib.rs
- server_fn/src/lib.rs
> fix: correctly pass server fn errors to client

- docs/book/src/view/03_components.md
- examples/counter/src/main.rs
- examples/counters/src/main.rs
- leptos/src/lib.rs
- leptos_macro/src/component.rs
- leptos_macro/src/view.rs
- leptos_reactive/benches/deep_update.rs
- leptos_reactive/benches/fan_out.rs
- leptos_reactive/benches/narrow_down.rs
- meta/src/stylesheet.rs
- router/src/components/route.rs
Huge shout-out to @Lej77 for showing the way to do this in issue #746.
> feat: make `__Props` imports unnecessary (closes #746)

- leptos_reactive/src/memo.rs
- leptos_reactive/src/scope.rs
> Fix leaked memo nodes

- leptos_macro/src/view.rs
> docs: emit error when trying to combine global class and dynamic class in a bugged way

- leptos/src/additional_attributes.rs
- leptos/src/lib.rs
- leptos/src/text_prop.rs
- meta/src/body.rs
- meta/src/html.rs
- meta/src/lib.rs
- meta/src/title.rs
- router/src/components/form.rs
> feat: add ability to set `node_ref` and pass additional attributes to `<Form/>` and friends

- docs/book/src/ssr/21_life_cycle.md
Fixed typo in the SSR life cycle docs
> Fixed typo in life cycle docs

- examples/fetch/Cargo.toml
- examples/fetch/src/lib.rs
> examples: fix error handling in fetch example

- examples/session_auth_axum/flake.lock
update nix flakes lock files to fix once_cell doesn't compile.
> [fix] updated nix flakes lock files on session auth axum examples

- leptos_macro/src/view.rs
This treats some static primitive values passed as element children (specifically strings, integers, floats, and chars) as `&'static str`, rather than converting them to `String`, saving a single allocation. Minor but worth ten minutes' work.
See issue #883.
> perf: tiny optimization on primitive child values

- router/Cargo.toml
- router/src/history/params.rs
This should solve issue #892.
It just adds the derive macros for ParamsMap, and uses the feature serde_impl from LienarMap,
> This should solve ParamsMap / LinearMap serde serialization and deserialization #892

- examples/router/style.css
- router/src/components/outlet.rs
- router/src/components/router.rs
- router/src/components/routes.rs
- router/src/history/location.rs
- router/src/history/mod.rs
- router/src/history/state.rs
- router/src/hooks.rs
> fix some issues with animated routing

- leptos_macro/src/view.rs
> fix: allow nested slots

- server_fn/src/lib.rs
Fix a tiny error, that still sent me in the wrong direction while debugging.
> Fix ServerFnError::Serialization error string

- examples/todo_app_sqlite/src/todo.rs
- examples/todo_app_sqlite_axum/src/todo.rs
- examples/todo_app_sqlite_viz/src/todo.rs
> examples: better practice for view types in todos

- docs/book/src/ssr/24_hydration_bugs.md
- docs/book/src/view/04_iteration.md
- docs/book/src/view/07_errors.md
- docs/book/src/view/09_component_children.md
- examples/counters/tests/web.rs
- examples/error_boundary/src/lib.rs
- examples/fetch/src/lib.rs
- examples/router/src/lib.rs
- examples/session_auth_axum/src/todo.rs
- examples/ssr_modes/src/app.rs
- examples/ssr_modes_axum/src/app.rs
- examples/todo_app_sqlite/src/todo.rs
- examples/todo_app_sqlite_axum/src/todo.rs
- examples/todo_app_sqlite_viz/src/todo.rs
- leptos/src/lib.rs
- leptos/src/suspense.rs
- leptos/src/transition.rs
- leptos_dom/src/lib.rs
I updated all applicable examples (maybe too aggressively).
fixes #953
> feat: add collect_view(cx)

- Cargo.toml
- meta/Cargo.toml
- router/Cargo.toml
I'm going to start screwing around with the feature sets on main soon. To keep people from getting mad at me, I'm putting up some `0.3.0` prereleases :smile:
> `v0.3.0-alpha`

- leptos_dom/src/html.rs
One possible route to closing #963.
> feat: add builder syntax for optional event listener

- examples/session_auth_axum/Makefile.toml
- examples/session_auth_axum/src/auth.rs
- examples/session_auth_axum/src/errors.rs
- examples/session_auth_axum/src/todo.rs
This cleans up the lint issues in the `session_auth_axum` example.
Verification:
_From the **examples/session_auth_axum** directory..._
> fix: lint issues in `session_auth_axum` example

- leptos_reactive/src/signal.rs
Following [discord question](https://discord.com/channels/1031524867910148188/1049869221636620300/1104043773194928163)
> [docs] Reduce firmness of overlapping signal warning

- docs/book/src/view/02_dynamic_attributes.md
- leptos/src/lib.rs
- leptos_dom/Cargo.toml
- leptos_dom/src/html.rs
- leptos_dom/src/macro_helpers/into_style.rs
- leptos_dom/src/macro_helpers/mod.rs
- leptos_macro/src/lib.rs
- leptos_macro/src/view.rs
> feat: add `style:` to view

- examples/tailwind_csr_trunk/README.md
- examples/tailwind_csr_trunk/Trunk.toml
- examples/tailwind_csr_trunk/style/output.css
**Proposed**
This demonstrates how the tailwind build process can be automated with a Trunk hook.
The hook will run whenever a build is triggered by`trunk build` or `trunk serve`.
> build tailwind CSS with trunk

- integrations/actix/src/lib.rs
> fix: typo in actix extract documentation

- leptos_reactive/src/trigger.rs
Simple commit to add PartialEq, Eq and Debug derive traits to Trigger.
> Added Debug, PartialEq and Eq derives to trigger.

- leptos_reactive/src/memo.rs
- leptos_reactive/src/signal.rs
- leptos_reactive/src/signal_wrappers_read.rs
- leptos_reactive/src/stored_value.rs
Since it was marked as a good first issue, I gave this a shot. Let me know if there's any problems with it.
> feat: manually implement Debug, PartialEq, Eq and Hash for reactive types

- router/src/hooks.rs
added a hint for a common error when using use_navigate
> Docs edit:   added a hint for a common error when using use_navigate

- examples/errors_axum/src/fallback.rs
- examples/errors_axum/src/main.rs
- examples/hackernews_axum/src/fallback.rs
- examples/hackernews_axum/src/main.rs
- examples/session_auth_axum/Cargo.toml
- examples/session_auth_axum/src/fallback.rs
- examples/session_auth_axum/src/lib.rs
- examples/session_auth_axum/src/main.rs
- examples/session_auth_axum/src/state.rs
- examples/ssr_modes_axum/src/fallback.rs
- examples/ssr_modes_axum/src/main.rs
- examples/todo_app_sqlite_axum/src/fallback.rs
- examples/todo_app_sqlite_axum/src/main.rs
- examples/todo_app_sqlite_viz/src/fallback.rs
- examples/todo_app_sqlite_viz/src/main.rs
- integrations/axum/src/lib.rs
Basically the goal is to remove the LeptosProvider trait and use Axum's inbuilt SubStates with FromRef. Should close #1079
> Remove LeptosProvider trait and use Axum SubStates

- examples/session_auth_axum/Cargo.toml
- examples/session_auth_axum/src/auth.rs
- examples/session_auth_axum/src/main.rs
This should update axum_database_sessions and axum_sessions_auth in the example directory to use the latest versions.
> updated axum_database_sessions to axum_session.

- examples/fetch/src/lib.rs
I was keen to try out the fetch example, and was confused by what it was showing me initially. This version is a lot of fun, individual details are in the commit messages.
> Improve fetch example

- leptos_dom/src/events/typed.rs
Please see https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollend_event
> added scrollend event

- examples/counters/tests/web.rs
- examples/errors_axum/src/main.rs
- examples/ssr_modes_axum/src/fallback.rs
- examples/ssr_modes_axum/src/main.rs
- examples/timer/Makefile.toml
- examples/timer/src/lib.rs
This fixes #1113.
- From **examples/counters** run `cargo make web-test`
- From **examples/errors_axum** run `cargo make check-style`
- From **examples/ssr_modes_axum** run `cargo make check-style`
- From **examples/timer** run `cargo make check-style`
- Run `cargo make verify-examples` from the **leptos** root.
> fix(examples): verification errors (#1113)

- leptos_reactive/src/resource.rs
- leptos_reactive/src/spawn_microtask.rs
- leptos_reactive/tests/resource.rs
Closes #1124
I've also added a unit test that tests for this issue but it doesn't run correctly because of some microtask issue I don't fully understand.
> Replace preempted with version in Resource

- integrations/actix/src/lib.rs
I want to reduce the number of calls to .collect()
The code below shows the variable "routes" and the  first .iterator -> .map() ->  .collect() code pattern .
Later on in the code the "collect()'ed"  routes are then converted by a .into_iter() call 
and fed into next .map() call 
The whole thing can be simplified by daisy-chaining the two .map()  calls.
Another way of thinking about this is  'This change signals to the compiler, don't spool the intermediate values of "routes" to memory 
before proceeding'
```rust 
routes = routes
.into_iter()
.map(|listing| {
let path = listing.path();
if path.is_empty() {
return RouteListing::new(
"/".to_string(),
listing.mode(),
listing.methods(),
);
}
RouteListing::new(listing.path(), listing.mode(), listing.methods())
})
.collect();
```
> actix: Removed calls to .collect() and .into_ier()

- docs/book/src/reactivity/14_create_effect.md
- docs/book/src/reactivity/working_with_signals.md
> Fix grammar in signals doc.

- .github/workflows/run-example-task.yml
- .github/workflows/verify-all-examples.yml
Add missing OS browser dependencies needed by Playwright.
> fix(examples/tailwind): host system is missing dependencies to run browsers

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- leptos_reactive/src/memo.rs
- leptos_reactive/tests/memo.rs
Closes https://github.com/leptos-rs/leptos/issues/1212
> fix: memo with_untracked

- server_fn/src/error.rs
This allows returning it in a memo.
> feat: implement PartialEq on ServerFnError

- leptos/src/suspense_component.rs
- leptos_dom/src/ssr.rs
A few .clone() calls  removed.
> Minor: Ran cargo clippy --fix and reviewed changes.

- leptos_reactive/src/lib.rs
- leptos_reactive/src/runtime.rs
- leptos_reactive/src/scope.rs
- leptos_reactive/src/watch.rs
- leptos_reactive/tests/watch.rs
Fixes #1177
Should I also add sth to the book?
> Added watch

- leptos_dom/src/macro_helpers/into_class.rs
> fix: issue with class hydration not removing classes correctly

- integrations/axum/src/lib.rs
Pr following up from discord discussion.
> leptos axum extract with state

- leptos/Cargo.toml
- leptos/src/lib.rs
- leptos_server/Cargo.toml
- server_fn/Cargo.toml
> fix: `server_fn` `rustls` feature shouldn't pull in `default-tls`

- integrations/actix/Cargo.toml
- integrations/actix/src/lib.rs
- integrations/axum/Cargo.toml
- integrations/axum/src/lib.rs
- integrations/utils/src/lib.rs
- integrations/viz/Cargo.toml
- integrations/viz/src/lib.rs
- leptos/Cargo.toml
- leptos/src/lib.rs
- leptos_dom/Cargo.toml
- leptos_dom/src/lib.rs
- leptos_dom/src/nonce.rs
- leptos_dom/src/ssr.rs
- leptos_dom/src/ssr_in_order.rs
- meta/src/link.rs
- meta/src/script.rs
- meta/src/style.rs
> feat: add support for adding CSP nonces

- leptos_reactive/src/stored_value.rs
Fixes a panic that would occur while trying to access a `StoredValue` inside a different `StoredValue::update_value()` (or set).
> fix: release lock on stored values during update/set

- ARCHITECTURE.md
- docs/book/src/reactivity/interlude_functions.md
A few improvements I made while going through the docs. Keep up the good work, folks!
> Doc proof-reading

- integrations/utils/src/lib.rs
Small adjustments seen while reading the code.
> Minor: Removed call to .into(), plus minor touch to docs.

- docs/book/src/15_global_state.md
> Proofreading 15_global_state.md

- docs/book/src/router/16_routes.md
> Proofreading 16_routes.md

- docs/book/src/view/09_component_children.md
Enjoying the book! Found what I believe to be a typo.
> fix typo for WrapsChildren

- CONTRIBUTING.md
hat tip to @sebadob for these notes on running the CI locally
> docs: CONTRIBUTING.md with helpful info re: CI

- docs/book/src/server/25_server_functions.md
- docs/book/src/server/26_extractors.md
- docs/book/src/ssr/23_ssr_modes.md
Fixed grammar, added the section anchor links
> Docs proofreading and fixing the links

- leptos_macro/src/view.rs
Since these are all static lists of things, theoretically it should be faster to sort them and then use a binary search rather than `.find` or sequential pattern matches. Binary search should be around O(log n) and find should be around O(n).
> Binary search dom stuff

- leptos_reactive/src/spawn.rs
> (doc)expand spawn_local documentation

- leptos_macro/example/src/lib.rs
- leptos_macro/src/component.rs
> feat: allow `mut` in component props and suppress "needless lifetime" warning (closes #1458)

- leptos_dom/src/hydration.rs
This is just a minor nudge, seen whilst reading the code.
'128' make not sense to me until I spent a few minutes googling.
Elsewhere in the code the   https://developer.mozilla.org/ website is used a golden reference for explaining HTML document concepts.
> Document the magic number 128 as FILTER_SHOW_COMMENT.

- server_fn/src/error.rs
Fixed warning  seen whilst running 
```bash
Cargo doc
```
> Minor: doclink to Error needed FQDN.

- leptos/tests/test_examples/suspense-tests/src/app.rs
Add closing tags to several `Route`s.
Fix #1517
> fix(suspense-tests): build errors (#1517)

- .github/workflows/check-stable.yml
> perf(check-stable): only run workflow on leptos source change (#1541)

- .github/workflows/check-examples.yml
- .github/workflows/check-stable.yml
- .github/workflows/ci.yml
- .github/workflows/get-examples-matrix.yml
- .github/workflows/get-leptos-changed.yml
- .github/workflows/verify-all-examples.yml
- leptos/Makefile.toml
Supports #1543
- Extract `get-leptos-changed` to reduce duplication
- Extract `get-examples-matrix` to reduce duplication
- Rename jobs and steps to improve readability
- Simulated leptos source change
- Check Examples passed
- Check Stable passed
- CI checks were properly triggered but failed for a reason not related to the refactoring
> refactor(workflows): extract calls

- .github/workflows/check-examples.yml
- .github/workflows/check-stable.yml
- .github/workflows/ci-changed-examples.yml
- .github/workflows/ci.yml
- .github/workflows/run-cargo-make-task.yml
- .github/workflows/verify-all-examples.yml
- leptos/Makefile.toml
Closes #1543
- Introduce `toolchain` input to `run-cargo-make-task`
- Refactor `check-stable` to use matrix
> refactor(check-stable): use matrix (#1543)

- .github/workflows/run-cargo-make-task.yml
- examples/tailwind/README.md
Closes #1607
- Use `playwright install` to keep the browser dependencies up to date, automatically.
> fix(ci): add new webkit dependency (#1607)

- docs/book/src/reactivity/working_with_signals.md
> docs: fix typo

- leptos_dom/src/helpers.rs
> hide `get_property`

- leptos_dom/src/macro_helpers/into_attribute.rs
- leptos_dom/src/macro_helpers/into_class.rs
- leptos_dom/src/macro_helpers/into_property.rs
- leptos_dom/src/macro_helpers/into_style.rs
> Into thing boxed

- leptos_reactive/src/signal_wrappers_read.rs
- leptos_reactive/src/signal_wrappers_write.rs
- leptos_reactive/src/slice.rs
> Rename into signal traits

- .github/workflows/run-cargo-make-task.yml
> Chore: Bump to actions/checkout@v4

- integrations/actix/src/lib.rs
the Actix integration provides the `leptos_routes` method for the App type, but when you need to configure the App with a ServiceConfig (such as when trying to integrate Actix with Shuttle.rs), the `leptos_routes` method is not available. This PR fixes that.
> impled LeptosRoutes for &mut ServiceConfig in integrations/actix

- .github/workflows/get-example-changed.yml
- .github/workflows/get-examples-matrix.yml
- examples/Makefile.toml
- leptos/Makefile.toml
> fix: exclude markdown files from examples lists

- leptos_macro/src/component.rs
> fix: document `#[prop(default = ...)]` as in Optional Props (closes #1710)

- integrations/axum/src/lib.rs
> fix: relax bounds on `LeptosRoutes`

- benchmarks/Cargo.toml
- benchmarks/src/lib.rs
- benchmarks/src/reactive.rs
- benchmarks/src/ssr.rs
- benchmarks/src/todomvc/mod.rs
> fix: broken benchmarks (closes #1736)

- docs/book/src/async/11_suspense.md
- leptos/src/await_.rs
- leptos_macro/src/view/component_builder.rs
- leptos_macro/src/view/slot_helper.rs
This is an implementation of #1767, for reference.
> change: use `let:` instead of `bind:`

- leptos_reactive/src/lib.rs
- leptos_reactive/src/signal_wrappers_read.rs
This will close #1722, if it works.
> feat: implement `From<Fn() -> T>` for `Signal<T>`

- docs/book/src/interlude_styling.md
> "#two" was being hidden. Added another # to unhide

- router/src/components/outlet.rs
> fix: hydration ID clash with Suspense > Outlet > Suspense (closes #1863)

- meta/src/link.rs
- meta/src/meta_tags.rs
- meta/src/script.rs
- meta/src/style.rs
- meta/src/stylesheet.rs
Ability to add custom attributes on head elements.
> Custom attributes on head tags

- router/src/components/link.rs
> feat(router): Add the target attribute to the A component

- docs/book/src/view/08_parent_child.md
- examples/counters/rust-toolchain.toml
- examples/login_with_token_csr_only/client/src/components/navbar.rs
- examples/login_with_token_csr_only/client/src/lib.rs
- examples/login_with_token_csr_only/client/src/pages/login.rs
- examples/parent_child/rust-toolchain.toml
- examples/parent_child/src/lib.rs
- leptos_reactive/Cargo.toml
- leptos_reactive/src/callback.rs
Also reduced code duplication in Callback implementation.
> docs: added Callback to documentation and examples.

- .github/workflows/get-changed-examples-matrix.yml
- .github/workflows/get-example-changed.yml
- .github/workflows/get-leptos-changed.yml
I looked at the associated migration guide... and I think this should work.
I can't test locally, so I will jump on this if it fails.
> Minor: bumped tj-actions/changed-files to @39.

- router/src/components/link.rs
This allows to add arbitrary attributes to the anchor component.
This closes #1927
> Allow arbitrary attributes for anchor component

- leptos_reactive/src/signal_wrappers_read.rs
> impl `Default` for `TextProp`

- docs/book/src/reactivity/14_create_effect.md
- docs/book/src/reactivity/working_with_signals.md
> Use new with macro in book pages, update formatting for create effect page

- CONTRIBUTING.md
- meta/src/body.rs
The changes are minor and self-explanatory. Thanks for creating and maintaining Leptos!
> Minor documentation corrections

- examples/session_auth_axum/.env
- examples/session_auth_axum/src/error_template.rs
- examples/session_auth_axum/src/todo.rs
I've always hated the get_todos function and I wanted to change it badly. Added a .env file containing the db url for sqlx-cli, and cleaned up with leptosfmt.
> example session-auth-axum: Minor changes for ergonomics

- flake.lock
- flake.nix
the last time this was updated is a long time ago and also it now supports nix on OSX :)
> add nix-darwin support, update flake

- leptos_dom/src/lib.rs
> fix: let `mount_to_body` accept `FnOnce` closures (closes #2115)

- leptos_macro/tests/server.rs
- leptos_macro/tests/ui/server.stderr
- server_fn/Cargo.toml
- server_fn_macro/src/lib.rs
I have no clue if I'm doing the right thing
> Fixed tests for `server_fn`

- leptos/Cargo.toml
- leptos_reactive/Cargo.toml
- server_fn/Cargo.toml
- server_fn/src/codec/json.rs
- server_fn/src/codec/mod.rs
- server_fn/src/codec/serde_lite.rs
- server_fn/src/lib.rs
- server_fn_macro/src/lib.rs
Does this suffice? Do we need anything else?
This seems too simple to be it. There's gotta be more to it
> Added serde-lite implementation

- examples/server_fns_axum/Cargo.toml
- examples/server_fns_axum/src/app.rs
https://github.com/leptos-rs/leptos/assets/286622/1bd01e4a-3a6c-44a2-9774-84dcc5f70a27
> example: file upload with streaming progress bar

- leptos_dom/src/html.rs
I kept tripping up on this and for some reason it was hard to wrap my head around so I added a "beginner's tip" to explain the transparent nature of HtmlElement<El>. I think tips like this in docs will go a long way in on boarding new community members! Thanks in advance!
> Adding a Beginner's Tip to HtmlElement<El>

- examples/counter_isomorphic/Cargo.toml
- examples/error_boundary/README.md
- examples/errors_axum/Cargo.toml
- examples/hackernews/Cargo.toml
- examples/hackernews_axum/Cargo.toml
- examples/hackernews_islands_axum/Cargo.toml
- examples/hackernews_js_fetch/Cargo.toml
- examples/server_fns_axum/Cargo.toml
- examples/session_auth_axum/Cargo.toml
- examples/session_auth_axum/src/auth.rs
- examples/slots/src/lib.rs
- examples/sso_auth_axum/Cargo.toml
- examples/sso_auth_axum/src/auth.rs
- examples/tailwind_actix/Cargo.toml
- examples/tailwind_axum/README.md
- examples/tailwind_csr/Cargo.toml
- examples/todo_app_sqlite/Cargo.toml
- examples/todo_app_sqlite_axum/Cargo.toml
- examples/todo_app_sqlite_csr/Cargo.toml
> docs: typos in examples

- router/src/components/form.rs
> fix: add key/value pair from submit button when parsing form event

- examples/counter_isomorphic/src/counters.rs
- server_fn_macro/src/lib.rs
A good lesson in my own fallibility, and the importance of fixing CI before merging anything, or being super careful with manual testing.
A couple PRs with issues got through during our CI issues. Now that they are fixed it is clearer what they were. This should fix them.
> Fix remaining CI issues

- .github/workflows/get-changed-examples-matrix.yml
- examples/counter/tests/web.rs
Resolves #2287
- Specify the example directories glob pattern for `tj-actions/changed-files@v41` correctly
> fix(ci): empty directory vector error

- examples/session_auth_axum/Cargo.toml
- examples/session_auth_axum/src/main.rs
Fix for https://github.com/leptos-rs/leptos/issues/2309
> session_auth_axum compiles and works again

- examples/README.md
- examples/cargo-make/scripts/web-report.sh
- Fix typo
- Clarify readme step
> docs(examples): update docs

- examples/tailwind_axum/package-lock.json
- examples/tailwind_axum/src/app.rs
In #2291 I updated the output name but didn't fix the name of the CSS file.
Closes #2322.
> examples: fix CSS file name in `tailwind_axum`

- .github/workflows/get-changed-examples-matrix.yml
- .github/workflows/run-cargo-make-task.yml
- examples/cargo-make/client-process.toml
- examples/cargo-make/deno-build.toml
- examples/cargo-make/scripts/web-report.sh
- examples/cargo-make/server-process.toml
- examples/cargo-make/webdriver.toml
- examples/gtk/Makefile.toml
- examples/hackernews_js_fetch/Makefile.toml
- examples/todo_app_sqlite/e2e/tests/app_suite.rs
> ci(examples): build hackernews_js_fetch with deno 

- examples/server_fns_axum/migrations/20221118172000_create_todo_table.sql
- server_fn/src/lib.rs
Added missing link for #[server] macro
> Added missing link for #[server] macro

- .github/workflows/run-cargo-make-task.yml
- leptos/tests/ssr.rs
> fix(ci): trunk command not found

- leptos_dom/Cargo.toml
- leptos_reactive/Cargo.toml
> Bumped base64 to 0.22.

- leptos_dom/src/lib.rs
As discussed on discord, this should allow on events to work with `<For />` components and dynamic signal based children. 
Tested with: 
```rust
#[component]
pub fn Wrapper(children: Children) -> impl IntoView {
children().into_view().on(leptos::ev::mouseenter, move |_| {
leptos::logging::log!("mouseenter");
})
}
<Wrapper>{move || view! { <div>BBBBBB</div> }}</Wrapper>
<Wrapper>
<For each=move || vec![1, 2, 3] key=move |v| format!("{}", v) let:v>
<div>{v}</div>
</For>
</Wrapper>
```
> View::on support for CoreComponent::{DynChild, Each}

- .github/workflows/ci-semver.yml
- leptos/tests/ssr.rs
> chore(ci): run semver checks on push

- examples/counter_url_query/Cargo.toml
- examples/counter_url_query/rust-toolchain.toml
- examples/counter_url_query/src/lib.rs
Addressing: #2481 
> New code contains only _stable_ features
`cargo +stable build`
> ex: counter_url_query; to stable

- router/Cargo.toml
> Minor: Bumped serde_qs to 0.13.

- router/src/components/form.rs
> Add id to ActionForm and MultiActionForm

- .github/workflows/run-cargo-make-task.yml
> Minor: Bumped trunk-action to 0.5.

- router/src/hooks.rs
Addresses https://github.com/leptos-rs/leptos/issues/2513
> Add 'create_query_signal_with_options' to leptos_router

- projects/README.md
The Index gives a high level overview of the projects
> Added an Index to Project README

- leptos/src/lib.rs
- leptos_macro/src/component.rs
> fix: extract dyn_bindings impl into DynBindings trait

- reactive_graph/src/signal/arc_read.rs
- reactive_graph/src/signal/arc_write.rs
- reactive_graph/src/signal/rw.rs
> Implement Default trait for signals with a parameter that also implements Default

- leptos_config/tests/config.rs
- leptos_macro/src/view/component_builder.rs
- reactive_graph/src/signal/rw.rs
- router/src/components.rs
- router/src/form.rs
This PR will help the formatter and CI work by addressing formatting issues.
> leptos 0.7: Making CI and `rustfmt` work as usual

- leptos_dom/src/macro_helpers/into_style.rs
> add impl IntoStyle for Style

- reactive_graph/src/effect/effect.rs
- reactive_graph/tests/watch.rs
Needed so Leptos-Use can continue to port to 0.7
https://github.com/Synphonyte/leptos-use/issues/140
> Implemented Effect::watch

- tachys/src/html/event.rs
The last missing piece for Synphonyte/leptos-use#140 is a custom event type. This PR reintroduces [Custom](https://github.com/leptos-rs/leptos/blob/d50012f8d4e7bc70853debb89ee40c450a01cc5c/leptos_dom/src/events/typed.rs#L55-L61), with some tweaks to `EventDescriptor`.
Since `Custom` now needs to be `Send + Sync`, it needs to wrap its `options` field with `SendWrapper` in some way. To preserve the previous signature, its `options` field _could_ be `SendWrapper<Option<web_sys::AddEventListenerOptions>>`. However, I'm a little concerned that could lead to more situations where a `SendWrapper` is invalidly constructed.
The alternative approach that I took, `Option<SendWrapper<web_sys::AddEventListenerOptions>>`, does not require a `SendWrapper` construction until the moment its inner JS data …
> Reintroduce custom events

- leptos/src/for_loop.rs
- tachys/src/view/keyed.rs
#2695
Implement the functionality described in https://github.com/leptos-rs/leptos/issues/2043 issue.
Please feel free to rename the component name.
> feat: adds ForEnumerate component

- Cargo.toml
- any_error/Cargo.toml
- any_spawner/Cargo.toml
- const_str_slice_concat/Cargo.toml
- either_of/Cargo.toml
- hydration_context/Cargo.toml
- integrations/actix/Cargo.toml
- integrations/axum/Cargo.toml
- integrations/utils/Cargo.toml
- leptos/Cargo.toml
- leptos_config/Cargo.toml
- leptos_dom/Cargo.toml
- leptos_hot_reload/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_server/Cargo.toml
- meta/Cargo.toml
- next_tuple/Cargo.toml
- oco/Cargo.toml
- or_poisoned/Cargo.toml
- reactive_graph/Cargo.toml
- reactive_stores/Cargo.toml
- reactive_stores_macro/Cargo.toml
- router/Cargo.toml
- router_macro/Cargo.toml
- server_fn/Cargo.toml
- server_fn/server_fn_macro_default/Cargo.toml
- server_fn_macro/Cargo.toml
- tachys/Cargo.toml
make all crates use the same edition as the workspace
> workspace edition

- reactive_graph/src/signal.rs
> feat: provide deprecated `create_rw_signal`

- reactive_graph/src/computed.rs
> feat: provide deprecated `create_memo`

- examples/counter/Cargo.toml
- examples/counter_url_query/Cargo.toml
- examples/counter_without_macros/Cargo.toml
- examples/counters/Cargo.toml
- examples/directives/Cargo.toml
- examples/directives/src/lib.rs
- examples/hackernews/Cargo.toml
- examples/hackernews_axum/Cargo.toml
- examples/hackernews_islands_axum/Cargo.toml
- examples/hackernews_js_fetch/Cargo.toml
- examples/parent_child/Cargo.toml
- examples/portal/Cargo.toml
- examples/server_fns_axum/Cargo.toml
- examples/stores/Cargo.toml
- examples/timer/Cargo.toml
- examples/todomvc/Cargo.toml
- leptos/Cargo.toml
- leptos_dom/Cargo.toml
- meta/Cargo.toml
- reactive_graph/Cargo.toml
- router/Cargo.toml
- server_fn/Cargo.toml
- server_fn/src/request/browser.rs
- tachys/Cargo.toml
This needs to be merged first before #2827 to make CI work.
> fix: fix `web-sys` warnings in `server_fn`

- leptos_macro/src/lib.rs
- leptos_macro/src/memo.rs
- leptos_macro/tests/memo.rs
- leptos_macro/tests/memo/red.rs
- leptos_macro/tests/memo/red.stderr
> feat: add `memo!` macro (closes #2708)

- leptos_macro/src/component.rs
Currently, when you mark a component as deprecated, the meta attribute is propagated to the dummy model, when it should be propagated to the "real" model.
To check the behaviour, you can just mark as `#[deprecated]` the `SimpleCounter` component of the `counter` example and run `trunk serve`:
```rust
#[deprecated="Hello"]
#[component]
pub fn SimpleCounter( ... )
```
Before:
```
warning: use of deprecated function `__SimpleCounter`: Hello
--> src/lib.rs:8:8
|
8 | pub fn SimpleCounter(
|        ^^^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
```
After:
```
warning: use of deprecated function `counter::SimpleCounter`: Hello
--> src/main.rs:1:14
|
1 | use counter::SimpleCounter;
|              ^^^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: use of deprecated …
```
> fix: `#[component]` unknown attributes propagation

- router/src/link.rs
> added ToHref impl for Rc<str>

- leptos_server/src/resource.rs
I am not sure if this will work for closing out one of the todos in #2771, but I figured I would take a stab at it at least. Let me know if I need to change anything.
> feat: add Resouce::map and Resouce::and_then

- leptos/src/callback.rs
This allows the following:
```rust
let cb0: Callback<()> = (|| {}).into();  // No more parameter necessary
let cb1: Callback<(i32,)> = (|x| {}).into();
let cb2: Callback<(i32, String)> = (|x, s| {}).into();
let cb3: Callback<(i32, String, f32)> = (|x, s, f| {}).into();
```
Please note the lack of tuple parentheses in the closure paremeters. 
This makes it nicer to provide callbacks as params to components.
The only downside is that inside a component, when you run a callback with only one parameter, it requires a tuple. The same goes for specifying the type of a callback with one parameter as you can see above (`cb1: Callback<(i32,)>`).
```rust
cb0.run(());                             // same as before
cb1.run((42,));                          // this requires a tuple now
cb2.run((42, …
```
> DX: Variadic `From` for `Callback`implemented variadic from for callbacks

- leptos_macro/src/view/mod.rs
Currently only supports `attr:aria_label`, not `attr:aria-label`.
> fix: compile attr:aria-* syntax

- leptos_hot_reload/Cargo.toml
- leptos_hot_reload/src/parsing.rs
- leptos_macro/Cargo.toml
- leptos_macro/src/lib.rs
- leptos_macro/src/view/component_builder.rs
- leptos_macro/src/view/mod.rs
- leptos_macro/src/view/slot_helper.rs
This is #2769 but without erroring, and therefore without requiring the breaking syntax change.
It was easier for me to cherry-pick the first commit from @blorbb's PR in a new branch than to undo the syntax changes in the examples and docs, so I'm opening it as a new PR here!
> update to rstml and improve recoverability in attributes

- server_fn_macro/src/lib.rs
> Allow for documentation and other attributes to fields in server fn

- reactive_stores_macro/src/lib.rs
The feature has already been implemented in https://github.com/leptos-rs/leptos/pull/2958 for `more-stores` branch, but it got lost. Assuming it wasn't intentional, I've restored it here.
> feat(#2946): add #[store(skip)] for #[derive(Store)]

- leptos_macro/src/component.rs
Currently with the "hydrate" feature this code
```rust
#[island]
pub fn Test(#[prop(optional)] _test: Option<bool>) -> impl IntoView {}
```
produce this error:
```
error[E0308]: mismatched types
--> src\app.rs:6:31
|
6 | pub fn Test(#[prop(optional)] _test: Option<bool>) -> impl IntoView {}
|                               ^^^^^
|                               |
|                               expected `bool`, found `Option<bool>`
|                               arguments to this method are incorrect
|
= note: expected type `bool`
found enum `std::option::Option<bool>`
note: method defined here
--> src\app.rs:6:31
|
6 | pub fn Test(#[prop(optional)] _test: Option<bool>) -> impl IntoView {}
|                               ^^^^^-------------
help: consider using `Option::expect` to unwrap …
```
> Fix an error with optionnal props for islands

- leptos_macro/src/component.rs
> Fix optional props with islands

- examples/stores/src/lib.rs
- reactive_stores/src/keyed.rs
- reactive_stores/src/lib.rs
- reactive_stores/src/patch.rs
- reactive_stores/src/store_field.rs
- reactive_stores/src/subfield.rs
Some edge cases on reactive stores, and using an example of patching — providing a new value but only notifying changed fields.
> Stores patching

- leptos/src/hydration/island_script.js
The hydration errors while trying to write a warning about island hydration problems, which is rather inconvenient…
> Fix island hydration warning message

- reactive_stores/src/iter.rs
- reactive_stores/src/keyed.rs
This PR implements DoubleEndedIterator for two structs: StoreFieldKeyedIter and StoreFieldIter
> Double-ended-iterator-for-stores

- reactive_graph/src/actions/action.rs
Found this bug while checking whether fixes related to #2652 had been backported successfully. We need to track dispatches separately from version, where dispatches = how many times it's been dispatched, and version = committed final values. We want to commit any value that was the result of the last-dispatched action, whether or not earlier calls had resolved yet when it fired.
```rust
#[component]
let action: Action<i32, i32> = Action::new_unsync(|v: &i32| {
let v = *v;
async move {
gloo_timers::future::sleep(std::time::Duration::from_secs(4)).await;
v + 1
}
});
spawn_local(async move {
action.dispatch(10);
gloo_timers::future::sleep(std::time::Duration::from_secs(1)).await;
action.dispatch(41);
gloo_timers::future::sleep(std::time::Duration::from_secs(1)) …
```
> fix: inconsistencies in check for latest version in actions

- reactive_graph/src/wrappers.rs
- tachys/src/html/class.rs
To make `view!{<div class={Option<impl IntoClass>} />}` work and an extra `Signal` impl.
> impl IntoClass for Option<impl IntoClass>

- any_spawner/src/lib.rs
> Correctly support futures-executor

- integrations/axum/src/lib.rs
This PR mirrors leptos-rs/start-axum#38 for the now-incorporated file serving for the axum integration.
As noted in leptos-rs/start-axum#41, `ServeDir` can produce odd behavior when all headers are passed along, so this PR passes only `accept-encoding`.
Closes #3130.
> feat: allow axum to serve precompressed files

- leptos/src/lib.rs
Thought it made sense to add the Fragment type to the prelude, please let me know if it doesnt
> add tachys::view::fragment::Fragment to prelude

- examples/islands_router/public/routing.js
> islands_router example: Support browsers without startViewTransition

- router/src/static_routes.rs
This includes a unit test that will be red until #3228 is merged
> Add tests for converting path segments into paths

- .github/workflows/autofix.yml
- tachys/src/view/mod.rs
Related: https://github.com/leptos-rs/leptos/pull/3235#issuecomment-2471376458
> fix: run `autofix.ci` on pull requests only

- README.md
Feel free to merge this when we release 0.7. I'm just keeping this open for now so that I don't forget :p
> Remove pre-release message

- .github/workflows/ci-semver.yml
Related: https://github.com/leptos-rs/leptos/pull/3376
> fix(ci): add missing glib for semver checks

- reactive_graph/src/traits.rs
- reactive_stores/src/lib.rs
- reactive_stores/src/store_field.rs
- reactive_stores/src/subfield.rs
There were missing `#[track_caller]` on a number of trait method definitions and impls. All I could find and that was relevant to my case were added.
> Add missing `#[track_caller]`s

- tachys/src/html/class.rs
This simply makes it easier to use custom classes. In my hobby project I have use a lot of `Cow<'static, str>` props/signals since my attribute values are mostly static and sometimes dynamic. Being able to use them directly would be a nice DX win.
I also thought about making the implementation more generic, for example over T: AsRef<str>, but that would change the associated types and be a breaking change it would also conflict with the `Option` impl due to the orphan rules.
Maybe there is something to be done with Borrow or Deref in a future release?
> Tachy class: impl IntoClass for Cow<'_, str>

- Cargo.lock
- leptos_macro/Cargo.toml
- leptos_macro/src/params.rs
- leptos_macro/tests/params.rs
Handles raw identifier e.g. `r#type` in Params macro
Fixes https://github.com/leptos-rs/leptos/issues/3521
> feat: allow raw identifiers in Params derive macro

- integrations/axum/src/lib.rs
like in leptos_routes_with_context func
> add file_and_error_handler_with_context

- reactive_stores/src/option.rs
- reactive_stores/src/patch.rs
Adding implementation of `PatchField` (in `reactive_stores`) for `Option<T>`.
> Implement PatchField for Option

- projects/bevy3d_ui/Cargo.toml
- projects/bevy3d_ui/src/demos/bevydemo1/scene.rs
-bevy = "0.14.1"
+bevy = "0.15.2"
<https://bevyengine.org/learn/migration-guides/0-14-to-0-15/>
--- This is PR part 2 (Part 1 can be found here  #3596 )
Also there are a few things about the project that clippy report but I want to
generate micro PR that fix a tight set of issues that make reverting easy.
So there will be part 3...
> projects/bevy3d_ui: Bevy migration

- leptos/src/lib.rs
- tachys/src/html/element/mod.rs
- tachys/src/lib.rs
- tachys/src/view/any_view.rs
- tachys/src/view/iterators.rs
As iterated on in #3598. 
I've left out the changes from #3583, they'll be pulled in from main and anything not explicitly related to this to keep simple.
> Internally erase html elements

- leptos/src/callback.rs
- leptos_server/src/shared.rs
- reactive_stores_macro/src/lib.rs
Addressing the failed CI on updating to newest nightly in #3674:
https://github.com/leptos-rs/leptos/actions/runs/13683036838/job/38259849573?pr=3674
With two more clippy fixes.
> fix: enum stack size

- .github/workflows/ci-semver.yml
- .github/workflows/ci.yml
- examples/spread/rust-toolchain.toml
- leptos_macro/Makefile.toml
- scripts/update_nightly.sh
The script needs to be run from the root directory.
```bash
cd leptos
./scripts/update_nightly.sh
./scripts/update_nightly.sh 2025-03-05
```
> fix: semver and feature handy script for update nightly

- reactive_graph/src/effect/immediate.rs
- reactive_graph/tests/effect_immediate.rs
> `ImmediateEffect` follow up

- reactive_graph/src/owner.rs
- reactive_graph/src/owner/arena.rs
- reactive_graph/src/owner/arena_item.rs
- reactive_graph/src/owner/storage.rs
> Various issues related to setting signals and context in cleanups

- leptos_server/src/local_resource.rs
`ArcLocalResource` doesn't use the `new_mock` variant in `ssr` like `LocalResource`, which breaks it before this fix.
> ArcLocalResource fix (0.8)

- either_of/src/lib.rs
In response to [issue 3709](https://github.com/leptos-rs/leptos/issues/3709).
> Make trailing comma optional for either macro

- leptos_config/src/lib.rs
> Make docs match reality

- reactive_graph/src/wrappers.rs
Seems to be accidentally forgotten
> derive_local for ArcSignal<T, LocalStorage>

- examples/cargo-make/wasm-test.toml
- examples/portal/Cargo.toml
- examples/portal/Makefile.toml
- examples/portal/src/lib.rs
- examples/portal/tests/web.rs
> fix: portal example

- reactive_stores/src/keyed.rs
- reactive_stores/src/option.rs
- reactive_stores/src/subfield.rs
These fix some issues created by #3799 (thanks to sabify's note in #3802): One due to my accidental deletion of a line of code, and one due to the need to update a test to actually reflect correct behavior.
> Store test fixes

- Cargo.lock
- Cargo.toml
- any_spawner/Cargo.toml
- hydration_context/Cargo.toml
- leptos/Cargo.toml
- leptos_config/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_server/Cargo.toml
- oco/Cargo.toml
- reactive_graph/Cargo.toml
- reactive_stores_macro/Cargo.toml
- router/Cargo.toml
- server_fn/Cargo.toml
- server_fn_macro/Cargo.toml
I noticed the list of outliers was getting large...
> chore: ran cargo outdated.

- examples/websocket/e2e/tests/fixtures/action.rs
- examples/websocket/e2e/tests/fixtures/find.rs
- examples/websocket/e2e/tests/fixtures/world/action_steps.rs
- examples/websocket/e2e/tests/fixtures/world/check_steps.rs
do not check the label immediately
> fix(examples): websocket tests fail (occasionally) second attemp

- .github/workflows/autofix.yml
- .github/workflows/run-cargo-make-task.yml
- Cargo.lock
- reactive_graph/src/owner/context.rs
- server_fn/Cargo.toml
- server_fn/build.rs
- server_fn/tests/invalid/empty_return.stderr
- server_fn/tests/invalid/not_result.stderr
- server_fn/tests/server_macro.rs
Please check out https://github.com/rust-lang/rust-clippy/issues/14722.
> fix(CI): prevent regreession from nightly clippy in autofix

- .github/workflows/run-cargo-make-task.yml
> feat: check the `counter_isomorphic` release build with the leptos_debuginfo

- reactive_stores/src/lib.rs
StoredValue also has these implemented and does the same thing (i.e. comparing the inner `ArenaItem` directly).
> reactive_stores: implement PartialEq and Eq for Store

- leptos/src/hydration/reload_script.js
This should theoretically fix #3927 . I have tested that the style updating still works, however I have not tested that there's no more issues with it (as that is fairly difficult to find out). However, from the code I'm pretty confident that this should completely eliminate the issue.
> Fix cargo-leptos stylesheet caching (#3927)

- Cargo.lock
- Cargo.toml
- any_error/Cargo.toml
- any_spawner/Cargo.toml
- either_of/Cargo.toml
- hydration_context/Cargo.toml
- integrations/actix/Cargo.toml
- integrations/axum/Cargo.toml
- integrations/utils/Cargo.toml
- leptos/Cargo.toml
- leptos_config/Cargo.toml
- leptos_dom/Cargo.toml
- leptos_hot_reload/Cargo.toml
- leptos_macro/Cargo.toml
- leptos_server/Cargo.toml
- meta/Cargo.toml
- oco/Cargo.toml
- reactive_graph/Cargo.toml
- reactive_stores/Cargo.toml
- reactive_stores_macro/Cargo.toml
- router/Cargo.toml
- router_macro/Cargo.toml
- server_fn/Cargo.toml
- server_fn/server_fn_macro_default/Cargo.toml
- server_fn_macro/Cargo.toml
- tachys/Cargo.toml
This has been done with [`cargo-easy-dep`](https://crates.io/crates/cargo-easy-dep).
> chore: unify all deps with min occurrences of 2

- const_str_slice_concat/src/lib.rs
- examples/fetch/src/main.rs
- examples/suspense_tests/src/instrumented.rs
- integrations/axum/src/lib.rs
- leptos/src/children.rs
- leptos/src/form.rs
- leptos/src/portal.rs
- leptos_server/src/local_resource.rs
- reactive_graph/src/computed/async_derived/async_derived.rs
- reactive_graph/src/computed/inner.rs
- reactive_graph/src/computed/memo.rs
- reactive_graph/src/owner.rs
- reactive_graph/src/send_wrapper_ext.rs
- reactive_graph/src/signal/mapped.rs
- reactive_graph/src/traits.rs
- reactive_stores/README.md
- reactive_stores/src/option.rs
- router/src/link.rs
- server_fn/tests/server_macro.rs
- tachys/src/html/attribute/custom.rs
- tachys/src/view/mod.rs
Miscellaneous typo fixes in comments.
> Fix spelling typos.

- Cargo.lock
- examples/suspense_tests/e2e/features/check_instrumented_issue_3719.feature
- examples/suspense_tests/src/instrumented.rs
- leptos/Cargo.toml
- leptos/tests/pr_4061.rs
Additional discussion under #4062 (closed prematurely due to an accident 😅).
> Tests for #4061

- tachys/src/html/class.rs
- tachys/src/reactive_graph/class.rs
> Fix updates to static class names

- README.md
I think we're in a place where we don't have to deter users from using Leptos in production. Thoughts?
> We're kinda prod-ready

- examples/axum_js_ssr/Cargo.toml
- examples/errors_axum/Cargo.toml
- examples/fetch/Cargo.toml
- examples/regression/Cargo.toml
- examples/server_fns_axum/Cargo.toml
- examples/ssr_modes/Cargo.toml
- examples/ssr_modes_axum/Cargo.toml
- examples/static_routing/Cargo.toml
- examples/tailwind_axum/Cargo.toml
- examples/todo_app_sqlite/Cargo.toml
- examples/todo_app_sqlite_axum/Cargo.toml
- examples/todo_app_sqlite_csr/Cargo.toml
- examples/websocket/Cargo.toml
Making a small extremely narrowly focued issue, there are lots of other outdated crates in the examples... 
This is quixotic - but my way of contributing to open source...is what I do to my own projects 
I do the projects I love/ rely on
> chore: examples - bumped version numbers for sqlx and this error.

- reactive_stores_macro/src/lib.rs
This is new PR so it sits on top of `0.8.5` codebase
> Fixes #4163: Derive `Patch` for a struct with generic arguments
